Repository elastic/ml-cpp, pull requests merged in 2018-11, with the labels that each got.

#294 [ML] Fix cause of multimodal prior error
  docs/CHANGELOG.asciidoc
  lib/maths/CGammaRateConjugate.cc
  lib/maths/CMultimodalPrior.cc
  lib/maths/COneOfNPrior.cc
  lib/maths/unittest/CMultimodalPriorTest.cc
Labels: :ml, >bug, review, v6.5.0, v6.6.0, v7.0.0

#296 [6.6][ML] Fix cause of multimodal prior error (#294)
  docs/CHANGELOG.asciidoc
  lib/maths/CGammaRateConjugate.cc
  lib/maths/CMultimodalPrior.cc
  lib/maths/COneOfNPrior.cc
  lib/maths/unittest/CMultimodalPriorTest.cc
Labels: :ml, >backport, >bug, v6.5.0, v6.6.0, v7.0.0

#295 [6.5][ML] Fix cause of multimodal prior error (#294)
  docs/CHANGELOG.asciidoc
  lib/maths/CGammaRateConjugate.cc
  lib/maths/CMultimodalPrior.cc
  lib/maths/COneOfNPrior.cc
  lib/maths/unittest/CMultimodalPriorTest.cc
Labels: :ml, >backport, >bug, v6.5.0, v6.6.0, v7.0.0

#298 [FEATURE][ML] Introduce data_frame_analyzer process
  bin/Makefile
  bin/controller/Main.cc
  bin/data_frame_analyzer/.objs/.gitignore
  bin/data_frame_analyzer/CCmdLineParser.cc
  bin/data_frame_analyzer/CCmdLineParser.h
  bin/data_frame_analyzer/Main.cc
  bin/data_frame_analyzer/Makefile
  include/api/CDataFrameAnalyzer.h
  lib/api/CDataFrameAnalyzer.cc
  lib/api/Makefile.first
Labels: :ml

#300 [ML] Preserve test report if unit tests fail inside Docker
  dev-tools/docker/docker_entrypoint.sh
  dev-tools/docker_test.sh
Labels: :ml, >build, >non-issue, v6.6.0, v7.0.0

#301 [ML][6.6] Preserve test report if unit tests fail inside Docker
  dev-tools/docker/docker_entrypoint.sh
  dev-tools/docker_test.sh
Labels: >backport, >non-issue, v6.6.0

#297 [FEATURE][ML] Overhaul integration of Eigen vector and matrix types with maths library
  include/maths/CAnnotatedVector.h
  include/maths/CBasicStatistics.h
  include/maths/CLassoLogisticRegression.h
  include/maths/CLinearAlgebraEigen.h
  include/maths/CLinearAlgebraFwd.h
  include/maths/CLinearAlgebraShims.h
  include/maths/CMultivariateNormalConjugate.h
  include/maths/CRandomProjectionClusterer.h
  include/maths/CRegressionDetail.h
  include/maths/CTypeTraits.h
  lib/maths/CInformationCriteria.cc
  lib/maths/CLassoLogisticRegression.cc
  lib/maths/CLinearAlgebraTools.cc
  lib/maths/CPca.cc
  lib/maths/CSampling.cc
  lib/maths/unittest/CLassoLogisticRegressionTest.cc
  lib/maths/unittest/CLinearAlgebraTest.cc
  lib/maths/unittest/CPcaTest.cc
Labels: :ml, >feature, review

#308 [FEATURE][ML] Deletes some prototype code which is no longer needed
  bin/Makefile
  bin/cluster/.objs/.gitignore
  bin/cluster/CCmdLineParser.cc
  bin/cluster/CCmdLineParser.h
  bin/cluster/Main.cc
  bin/cluster/Makefile
  bin/cluster/example_params_file.txt
  include/api/CClusterer.h
  include/api/CClustererOutputWriter.h
  lib/api/CClusterer.cc
  lib/api/CClustererOutputWriter.cc
  lib/api/Makefile.first
Labels: :ml

#309 [ML] Update Windows icon to match new product logos
  mk/ml.ico
Labels: :ml, >non-issue, review, v6.5.1, v6.6.0, v7.0.0

#310 [ML][6.6] Update Windows icon to match new product logos
  mk/ml.ico
Labels: >backport, >non-issue, v6.6.0

#312 [ML] Deemphasizing X-Pack
  CONTRIBUTING.md
  README.md
  bin/autodetect/Main.cc
  bin/categorize/Main.cc
  include/api/CForecastRunner.h
  lib/api/CForecastRunner.cc
  mk/make_rc_defines.sh
Labels: :ml, >non-issue, review, v6.5.1, v6.6.0, v7.0.0

#313 [ML][6.6] Deemphasizing X-Pack
  CONTRIBUTING.md
  README.md
  bin/autodetect/Main.cc
  bin/categorize/Main.cc
  include/api/CForecastRunner.h
  lib/api/CForecastRunner.cc
  mk/make_rc_defines.sh
Labels: >backport, >non-issue, v6.6.0

#311 [ML][6.5] Update Windows icon to match new product logos
  mk/ml.ico
Labels: >backport, >non-issue, v6.5.1

#314 [ML][6.5] Deemphasizing X-Pack
  CONTRIBUTING.md
  README.md
  bin/autodetect/Main.cc
  bin/categorize/Main.cc
  include/api/CForecastRunner.h
  lib/api/CForecastRunner.cc
  mk/make_rc_defines.sh
Labels: >backport, >non-issue, v6.5.1

#318 [ML] Remove out-of-phase buckets feature
  bin/autodetect/CCmdLineParser.cc
  bin/autodetect/CCmdLineParser.h
  bin/autodetect/Main.cc
  include/api/CAnomalyJob.h
  include/model/CAnomalyDetectorModel.h
  include/model/CAnomalyDetectorModelConfig.h
  include/model/CBucketGatherer.h
  include/model/CCountingModel.h
  include/model/CCountingModelFactory.h
  include/model/CDataGatherer.h
  include/model/CEventRateBucketGatherer.h
  include/model/CEventRateModelFactory.h
  include/model/CEventRatePopulationModelFactory.h
  include/model/CHierarchicalResults.h
  include/model/CIndividualModel.h
  include/model/CMetricBucketGatherer.h
  include/model/CMetricModelFactory.h
  include/model/CMetricPopulationModelFactory.h
  include/model/CModelFactory.h
  include/model/CModelParams.h
  include/model/CModelPlotData.h
  include/model/CPopulationModel.h
  include/model/CResultsQueue.h
  lib/api/CAnomalyJob.cc
  lib/api/dump_state/Main.cc
  lib/api/unittest/CAnomalyJobLimitTest.cc
  lib/api/unittest/CAnomalyJobTest.cc
  lib/api/unittest/CAnomalyJobTest.h
  lib/api/unittest/CMultiFileDataAdderTest.cc
  lib/api/unittest/CRestorePreviousStateTest.cc
  lib/api/unittest/CSingleStreamDataAdderTest.cc
  lib/api/unittest/CStringStoreTest.cc
  lib/model/CAnomalyDetector.cc
  lib/model/CAnomalyDetectorModelConfig.cc
  lib/model/CCountingModel.cc
  lib/model/CCountingModelFactory.cc
  lib/model/CDataGatherer.cc
  lib/model/CEventRateModel.cc
  lib/model/CEventRateModelFactory.cc
  lib/model/CEventRatePopulationModelFactory.cc
  lib/model/CHierarchicalResults.cc
  lib/model/CIndividualModel.cc
  lib/model/CMetricModel.cc
  lib/model/CMetricModelFactory.cc
  lib/model/CMetricPopulationModelFactory.cc
  lib/model/CModelParams.cc
  lib/model/CModelPlotData.cc
  lib/model/CPopulationModel.cc
  lib/model/CResultsQueue.cc
  lib/model/Makefile
  lib/model/unittest/CEventRateDataGathererTest.cc
  lib/model/unittest/Mocks.cc
  lib/model/unittest/Mocks.h
Labels: :ml, >refactoring, review, v6.6.0, v7.0.0

#317 [FEATURE][ML] Outliers for memory mapped vectors
  include/maths/CBasicStatistics.h
  include/maths/CKdTree.h
  include/maths/CLinearAlgebraEigen.h
  include/maths/CLinearAlgebraShims.h
  include/maths/CLocalOutlierFactors.h
  lib/maths/unittest/CLocalOutlierFactorsTest.cc
  lib/model/unittest/CEventRateModelTest.cc
Labels: :ml, >feature, review

#319 [FEATURE][ML] Outliers for data frames
  include/core/CDataFrame.h
  include/core/CDataFrameRowSlice.h
  include/maths/CLocalOutlierFactors.h
  lib/core/CDataFrame.cc
  lib/core/CDataFrameRowSlice.cc
  lib/core/unittest/CDataFrameTest.cc
  lib/core/unittest/CDataFrameTest.h
  lib/maths/CLocalOutlierFactors.cc
  lib/maths/Makefile
Labels: :ml, >feature, review

#320 [FEATURE][ML] Create data frame analysis spec from config file
  bin/data_frame_analyzer/CCmdLineParser.cc
  bin/data_frame_analyzer/Main.cc
Labels: :ml
