Repository elastic/ml-cpp, pull requests merged in 2018-09, with the labels that each got.

#195 [ML] Improvements to address QA regressions associated with multi-bucket
  include/maths/CModel.h
  include/maths/CTimeSeriesMultibucketFeatures.h
  lib/maths/CModel.cc
  lib/maths/CTimeSeriesModel.cc
  lib/maths/unittest/CTimeSeriesMultibucketFeaturesTest.cc
  lib/model/CEventRatePopulationModel.cc
  lib/model/CMetricPopulationModel.cc
  lib/model/unittest/CEventRateAnomalyDetectorTest.cc
  lib/model/unittest/CMetricAnomalyDetectorTest.cc
Labels: >enhancement, >non-issue, affects-results, v6.5.0, v7.0.0

#194 [ML] Add notice stating how to obtain the Eigen source code
  3rd_party/licenses/eigen-NOTICE.txt
Labels: :ml, >non-issue, v6.4.1, v6.5.0, v7.0.0

#199 [6.4][ML] Add notice stating how to obtain the Eigen source code
  3rd_party/licenses/eigen-NOTICE.txt
Labels: >backport, >non-issue, v6.4.1

#200 [6.5][ML] Add notice stating how to obtain the Eigen source code
  3rd_party/licenses/eigen-NOTICE.txt
Labels: >backport, >non-issue, v6.5.0

#196 [ML] Improvements to address QA regressions associated with multi-bucket
  include/maths/CModel.h
  include/maths/CTimeSeriesMultibucketFeatures.h
  lib/maths/CModel.cc
  lib/maths/CTimeSeriesModel.cc
  lib/maths/unittest/CTimeSeriesMultibucketFeaturesTest.cc
  lib/model/CEventRatePopulationModel.cc
  lib/model/CMetricPopulationModel.cc
  lib/model/unittest/CEventRateAnomalyDetectorTest.cc
  lib/model/unittest/CMetricAnomalyDetectorTest.cc
Labels: >backport, >non-issue, v6.5.0

#182 [ML] Partition-wise max-scores
  docs/CHANGELOG.asciidoc
  include/api/CResultNormalizer.h
  include/maths/CBasicStatistics.h
  include/model/CAnomalyScore.h
  include/model/CHierarchicalResultsNormalizer.h
  lib/api/CResultNormalizer.cc
  lib/api/unittest/CResultNormalizerTest.cc
  lib/api/unittest/CResultNormalizerTest.h
  lib/api/unittest/testfiles/new_normalizerInput.csv
  lib/api/unittest/testfiles/new_quantilesState.json
  lib/api/unittest/testfiles/normalizerInput.csv
  lib/model/CAnomalyScore.cc
  lib/model/CHierarchicalResultsNormalizer.cc
  lib/model/unittest/CAnomalyScoreTest.cc
  lib/model/unittest/CAnomalyScoreTest.h
  lib/model/unittest/CHierarchicalResultsTest.cc
Labels: :ml, affects-results, review, v6.5.0, v7.0.0

#202 [6.5][ML] Partition-wise max-scores (#182)
  docs/CHANGELOG.asciidoc
  include/api/CResultNormalizer.h
  include/maths/CBasicStatistics.h
  include/model/CAnomalyScore.h
  include/model/CHierarchicalResultsNormalizer.h
  lib/api/CResultNormalizer.cc
  lib/api/unittest/CResultNormalizerTest.cc
  lib/api/unittest/CResultNormalizerTest.h
  lib/api/unittest/testfiles/new_normalizerInput.csv
  lib/api/unittest/testfiles/new_quantilesState.json
  lib/api/unittest/testfiles/normalizerInput.csv
  lib/model/CAnomalyScore.cc
  lib/model/CHierarchicalResultsNormalizer.cc
  lib/model/unittest/CAnomalyScoreTest.cc
  lib/model/unittest/CAnomalyScoreTest.h
  lib/model/unittest/CHierarchicalResultsTest.cc
Labels: :ml, >backport, >feature, affects-results, review, v6.5.0

#203 [ML] Optimization to quantile persistence
  lib/api/CAnomalyJob.cc
Labels: :ml, >non-issue, review, v6.5.0, v7.0.0

#205 [ML] Optimization to quantile persistence (#203)
  lib/api/CAnomalyJob.cc
Labels: :ml, >non-issue, v6.5.0, v7.0.0

#207 [ML] Trap case triggering "Bad density value..." log errors whilst forecasting
  docs/CHANGELOG.asciidoc
  include/maths/CNaiveBayes.h
  lib/maths/CNaiveBayes.cc
  lib/maths/unittest/CNaiveBayesTest.cc
  lib/maths/unittest/CNaiveBayesTest.h
Labels: :ml, >bug, review, v6.5.0, v7.0.0

#209 [6.5][ML] Trap case triggering "Bad density value..." log errors whilst forecasting
  docs/CHANGELOG.asciidoc
  include/maths/CNaiveBayes.h
  lib/maths/CNaiveBayes.cc
  lib/maths/unittest/CNaiveBayesTest.cc
  lib/maths/unittest/CNaiveBayesTest.h
Labels: >backport, v6.5.0

#211 [ML] Rework per partition analysis so it doesn't maintain one maximum score for each member of a population
  include/api/CAnomalyJob.h
  include/api/CResultNormalizer.h
  include/model/CAnomalyScore.h
  include/model/CHierarchicalResultsLevelSet.h
  include/model/CHierarchicalResultsNormalizer.h
  lib/api/CAnomalyJob.cc
  lib/api/CResultNormalizer.cc
  lib/api/unittest/CResultNormalizerTest.cc
  lib/api/unittest/testfiles/new_quantilesState.json
  lib/model/CAnomalyScore.cc
  lib/model/CHierarchicalResultsAggregator.cc
  lib/model/CHierarchicalResultsNormalizer.cc
  lib/model/unittest/CAnomalyScoreTest.cc
  lib/model/unittest/CHierarchicalResultsLevelSetTest.cc
  lib/model/unittest/CHierarchicalResultsTest.cc
Labels: >bug, >non-issue, affects-results, v6.5.0, v7.0.0

#213 [ML] Add mechanism to remove "stale" normaliser maximum scores
  include/model/CAnomalyScore.h
  lib/api/unittest/testfiles/new_quantilesState.json
  lib/model/CAnomalyScore.cc
  lib/model/unittest/CAnomalyScoreTest.cc
Labels: >bug, >non-issue, affects-results, v6.5.0, v7.0.0

#215 [6.5][ML] Rework per partition normalisation so it doesn't maintain one maximum score for each member of a population
  include/api/CAnomalyJob.h
  include/api/CResultNormalizer.h
  include/model/CAnomalyScore.h
  include/model/CHierarchicalResultsLevelSet.h
  include/model/CHierarchicalResultsNormalizer.h
  lib/api/CAnomalyJob.cc
  lib/api/CResultNormalizer.cc
  lib/api/unittest/CResultNormalizerTest.cc
  lib/api/unittest/testfiles/new_quantilesState.json
  lib/model/CAnomalyScore.cc
  lib/model/CHierarchicalResultsAggregator.cc
  lib/model/CHierarchicalResultsNormalizer.cc
  lib/model/unittest/CAnomalyScoreTest.cc
  lib/model/unittest/CHierarchicalResultsLevelSetTest.cc
  lib/model/unittest/CHierarchicalResultsTest.cc
Labels: >backport, >non-issue, v6.5.0

#216 [6.5][ML] Add mechanism to remove "stale" normaliser maximum scores (#213)
  include/model/CAnomalyScore.h
  lib/api/unittest/testfiles/new_quantilesState.json
  lib/model/CAnomalyScore.cc
  lib/model/unittest/CAnomalyScoreTest.cc
Labels: >backport, >non-issue, v6.5.0

#218 [ML] Improve initialisation of the residual model after detecting new decomposition component
  docs/CHANGELOG.asciidoc
  include/maths/CExpandingWindow.h
  include/maths/CTimeSeriesDecomposition.h
  include/maths/CTimeSeriesDecompositionDetail.h
  include/maths/CTimeSeriesDecompositionInterface.h
  include/maths/CTimeSeriesDecompositionStub.h
  include/maths/CTimeSeriesModel.h
  lib/maths/CExpandingWindow.cc
  lib/maths/CTimeSeriesDecomposition.cc
  lib/maths/CTimeSeriesDecompositionDetail.cc
  lib/maths/CTimeSeriesDecompositionStub.cc
  lib/maths/CTimeSeriesModel.cc
  lib/maths/unittest/CTimeSeriesModelTest.cc
Labels: :ml, >enhancement, affects-results, review, v6.5.0, v7.0.0

#221 [ML] Add tzdata to required OS packages in setup instructions
  build-setup/linux.md
Labels: :ml, >non-issue, v7.0.0
