Repository elastic/ml-cpp, pull requests merged in 2018-12, with the labels that each got.

#325 [ML] Upgrade Gradle to v5.0
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  upload.gradle
Labels: :ml, >build, >non-issue, v6.6.0, v7.0.0

#326 [ML][6.6] Upgrade Gradle to v5.0
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  upload.gradle
Labels: >backport, >non-issue, v6.6.0

#323 [FEATURE][ML] Wire in creation of data frame and control messages to data_frame_analyzer
  bin/data_frame_analyzer/Main.cc
  bin/data_frame_analyzer/Makefile
  include/api/CDataFrameAnalysisSpecification.h
  include/api/CDataFrameAnalyzer.h
  lib/api/CDataFrameAnalysisSpecification.cc
  lib/api/CDataFrameAnalyzer.cc
Labels: :ml, >feature

#327 [ML] Correct query times for model plot and forecast
  docs/CHANGELOG.asciidoc
  include/api/CForecastRunner.h
  include/model/CForecastDataSink.h
  lib/api/CForecastRunner.cc
  lib/model/CForecastDataSink.cc
  lib/model/CModelDetailsView.cc
Labels: :ml, >bug, v6.5.3, v6.6.0, v7.0.0

#328 [ML] Correct query times for model plot and forecast
  docs/CHANGELOG.asciidoc
  include/api/CForecastRunner.h
  include/model/CForecastDataSink.h
  lib/api/CForecastRunner.cc
  lib/model/CForecastDataSink.cc
  lib/model/CModelDetailsView.cc
Labels: >backport, v6.6.0

#329 [ML] Correct query times for model plot and forecast (#327)
  docs/CHANGELOG.asciidoc
  include/api/CForecastRunner.h
  include/model/CForecastDataSink.h
  lib/api/CForecastRunner.cc
  lib/model/CForecastDataSink.cc
  lib/model/CModelDetailsView.cc
Labels: >backport, v6.5.3

#330 Revert "[ML] Correct query times for model plot and forecast"
  docs/CHANGELOG.asciidoc
  include/api/CForecastRunner.h
  include/model/CForecastDataSink.h
  lib/api/CForecastRunner.cc
  lib/model/CForecastDataSink.cc
  lib/model/CModelDetailsView.cc
Labels: :ml, >non-issue, blocker, v6.5.3

#331 [FEATURE][ML] Prepare data frame analytics results writing
  bin/data_frame_analyzer/Main.cc
  include/api/CDataFrameAnalyzer.h
  lib/api/CDataFrameAnalyzer.cc
  lib/core/CJsonOutputStreamWrapper.cc
Labels: :ml

#332 [ML] Write out forecasts predictions at "bucket time" rather than the actual times they are made in the time buckets
  lib/model/CForecastDataSink.cc
Labels: :ml, >non-issue, review, v6.5.4, v6.6.0, v7.0.0

#333 [ML] Write out forecasts predictions at "bucket time" rather than the actual times they are made in the time buckets
  lib/model/CForecastDataSink.cc
Labels: >backport, >non-issue, v6.6.0

#334 [FEATURE][ML] Wire outlier detection into the data_frame_analyzer command
  bin/data_frame_analyzer/Main.cc
  include/api/CDataFrameAnalysisRunner.h
  include/api/CDataFrameAnalysisSpecification.h
  include/api/CDataFrameAnalyzer.h
  include/api/CDataFrameOutliersRunner.h
  include/core/CDataFrame.h
  include/core/CRapidJsonConcurrentLineWriter.h
  include/core/CRapidJsonLineWriter.h
  include/core/CRapidJsonWriterBase.h
  include/core/CStaticThreadPool.h
  lib/api/CDataFrameAnalysisSpecification.cc
  lib/api/CDataFrameAnalyzer.cc
  lib/api/CDataFrameOutliersRunner.cc
  lib/api/unittest/CDataFrameAnalysisSpecificationTest.cc
  lib/api/unittest/CDataFrameAnalyzerTest.cc
  lib/api/unittest/CDataFrameAnalyzerTest.h
  lib/api/unittest/Main.cc
  lib/api/unittest/Makefile
  lib/core/CDataFrame.cc
  lib/core/CStaticThreadPool.cc
  lib/core/unittest/CDataFrameTest.cc
  lib/maths/CLocalOutlierFactors.cc
Labels: :ml, >feature, review

#335 [ML] Fix for CPoissonMeanConjugate sampling error.
  docs/CHANGELOG.asciidoc
  lib/maths/CPoissonMeanConjugate.cc
  lib/maths/unittest/CPoissonMeanConjugateTest.cc
  lib/maths/unittest/CPoissonMeanConjugateTest.h
  lib/maths/unittest/testfiles/log4cxx.properties
  lib/maths/unittest/testfiles/testLogErrorsLog4cxx.properties
Labels: :ml, >bug, review, v6.6.0, v7.0.0

#338 [6.6][ML] Fix for CPoissonMeanConjugate sampling error. (#335)
  docs/CHANGELOG.asciidoc
  lib/maths/CPoissonMeanConjugate.cc
  lib/maths/unittest/CPoissonMeanConjugateTest.cc
  lib/maths/unittest/CPoissonMeanConjugateTest.h
  lib/maths/unittest/testfiles/log4cxx.properties
  lib/maths/unittest/testfiles/testLogErrorsLog4cxx.properties
Labels: :ml, >backport, v6.6.0

#339 [6.5][ML] Correct query times for model plot and forecast
  docs/CHANGELOG.asciidoc
  include/api/CForecastRunner.h
  include/model/CForecastDataSink.h
  lib/api/CForecastRunner.cc
  lib/model/CForecastDataSink.cc
  lib/model/CModelDetailsView.cc
Labels: >backport, v6.5.4

#341 [6.5][ML] Write out forecasts predictions at "bucket time" rather than the actual times they are made in the time buckets
  lib/model/CForecastDataSink.cc
Labels: >backport, >non-issue, v6.5.4

#340 [FEATURE][ML] Shallow copy memory mapped vector and matrix types
  include/core/CDataFrame.h
  include/core/CDataFrameRowSlice.h
  include/maths/CLinearAlgebraEigen.h
  lib/api/CDataFrameAnalyzer.cc
  lib/core/CDataFrame.cc
  lib/core/CDataFrameRowSlice.cc
  lib/maths/CLocalOutlierFactors.cc
Labels: :ml, >bug, review

#343 [FEATURE][ML] Fix possible deadlock in thread pool shutdown
  include/core/CConcurrentQueue.h
  include/core/CStaticThreadPool.h
  lib/core/CStaticThreadPool.cc
  lib/core/unittest/CStaticThreadPoolTest.cc
  lib/core/unittest/CStaticThreadPoolTest.h
Labels: :ml, >bug, review

#336 [FEATURE][ML] Migrate data frame background write to storage to use thread pool
  include/core/CDataFrame.h
  include/core/Concurrency.h
  lib/core/CDataFrame.cc
  lib/core/unittest/CStaticThreadPoolTest.cc
Labels: :ml, >enhancement, review

#346 [DOCS] Edits 6.5.4 release notes entries
  docs/CHANGELOG.asciidoc
Labels: >non-issue, v6.5.4

#348 [ML] Bumped version to 6.7.0
  doxygen/cplusplus.Doxyfile
  gradle.properties
Labels: :ml, >non-issue, v6.7.0
