Repository elastic/ml-cpp, pull requests merged in 2018-10, with the labels that each got.

#223 [6.5][ML] Improve initialisation of the residual model after detecting new decomposition components
  docs/CHANGELOG.asciidoc
  include/maths/CExpandingWindow.h
  include/maths/CTimeSeriesDecomposition.h
  include/maths/CTimeSeriesDecompositionDetail.h
  include/maths/CTimeSeriesDecompositionInterface.h
  include/maths/CTimeSeriesDecompositionStub.h
  include/maths/CTimeSeriesModel.h
  lib/maths/CExpandingWindow.cc
  lib/maths/CTimeSeriesDecomposition.cc
  lib/maths/CTimeSeriesDecompositionDetail.cc
  lib/maths/CTimeSeriesDecompositionStub.cc
  lib/maths/CTimeSeriesModel.cc
  lib/maths/unittest/CTimeSeriesModelTest.cc
Labels: >backport, v6.5.0

#225 [ML] Add -headerpad_max_install_names to macOS linker args
  build-setup/macos.md
  dev-tools/docker/build_macosx_build_image.sh
  dev-tools/docker/macosx_builder/Dockerfile
  dev-tools/docker/macosx_image/Dockerfile
  docs/CHANGELOG.asciidoc
  mk/linux_crosscompile_macosx.mk
  mk/macosx.mk
Labels: :ml, >build, review, v6.4.3, v6.5.0, v7.0.0

#226 [ML][6.5] Add -headerpad_max_install_names to macOS linker args
  build-setup/macos.md
  dev-tools/docker/build_macosx_build_image.sh
  dev-tools/docker/macosx_builder/Dockerfile
  dev-tools/docker/macosx_image/Dockerfile
  docs/CHANGELOG.asciidoc
  mk/linux_crosscompile_macosx.mk
  mk/macosx.mk
Labels: >backport, v6.5.0

#227 [ML][6.4] Add -headerpad_max_install_names to macOS linker args
  build-setup/macos.md
  dev-tools/docker/build_macosx_build_image.sh
  dev-tools/docker/macosx_builder/Dockerfile
  dev-tools/docker/macosx_image/Dockerfile
  docs/CHANGELOG.asciidoc
  mk/linux_crosscompile_macosx.mk
  mk/macosx.mk
Labels: >backport, v6.4.3

#219 [ML] Fix incorrectly missing anomaly influences for empty buckets
  docs/CHANGELOG.asciidoc
  include/model/CBucketGatherer.h
  include/model/CEventRateBucketGatherer.h
  include/model/CMetricBucketGatherer.h
  lib/model/CBucketGatherer.cc
  lib/model/CEventRateBucketGatherer.cc
  lib/model/CMetricBucketGatherer.cc
  lib/model/unittest/CEventRateDataGathererTest.cc
  lib/model/unittest/CEventRateModelTest.cc
Labels: >bug, affects-results, review, v6.5.0, v7.0.0

#228 [6.5][ML] Fix incorrectly missing anomaly influences for empty buckets
  docs/CHANGELOG.asciidoc
  include/model/CBucketGatherer.h
  include/model/CEventRateBucketGatherer.h
  include/model/CMetricBucketGatherer.h
  lib/model/CBucketGatherer.cc
  lib/model/CEventRateBucketGatherer.cc
  lib/model/CMetricBucketGatherer.cc
  lib/model/unittest/CEventRateDataGathererTest.cc
  lib/model/unittest/CEventRateModelTest.cc
Labels: >backport, v6.5.0

#198 [ML] Improve time series decomposition in the presence of change points
  docs/CHANGELOG.asciidoc
  include/maths/CPeriodicityHypothesisTests.h
  include/maths/CRegression.h
  include/maths/CTimeSeriesDecomposition.h
  include/maths/CTimeSeriesDecompositionDetail.h
  include/maths/CTimeSeriesDecompositionInterface.h
  include/maths/CTimeSeriesSegmentation.h
  lib/maths/CPeriodicityHypothesisTests.cc
  lib/maths/CTimeSeriesChangeDetector.cc
  lib/maths/CTimeSeriesDecomposition.cc
  lib/maths/CTimeSeriesDecompositionDetail.cc
  lib/maths/CTimeSeriesSegmentation.cc
  lib/maths/Makefile
  lib/maths/unittest/CForecastTest.cc
  lib/maths/unittest/CPeriodicityHypothesisTestsTest.cc
  lib/maths/unittest/CPeriodicityHypothesisTestsTest.h
  lib/maths/unittest/CTimeSeriesChangeDetectorTest.cc
  lib/maths/unittest/CTimeSeriesDecompositionTest.cc
  lib/maths/unittest/CTimeSeriesModelTest.cc
  lib/maths/unittest/CTimeSeriesSegmentationTest.cc
  lib/maths/unittest/CTimeSeriesSegmentationTest.h
  lib/maths/unittest/Main.cc
  lib/maths/unittest/Makefile
  lib/model/unittest/CEventRateAnomalyDetectorTest.cc
  lib/model/unittest/CMetricPopulationDataGathererTest.cc
Labels: :ml, >enhancement, affects-results, review, v6.5.0, v7.0.0

#231 [6.5][ML] Improve time series decomposition in the presence of change points
  docs/CHANGELOG.asciidoc
  include/maths/CPeriodicityHypothesisTests.h
  include/maths/CRegression.h
  include/maths/CTimeSeriesDecomposition.h
  include/maths/CTimeSeriesDecompositionDetail.h
  include/maths/CTimeSeriesDecompositionInterface.h
  include/maths/CTimeSeriesSegmentation.h
  lib/maths/CPeriodicityHypothesisTests.cc
  lib/maths/CTimeSeriesChangeDetector.cc
  lib/maths/CTimeSeriesDecomposition.cc
  lib/maths/CTimeSeriesDecompositionDetail.cc
  lib/maths/CTimeSeriesSegmentation.cc
  lib/maths/Makefile
  lib/maths/unittest/CForecastTest.cc
  lib/maths/unittest/CPeriodicityHypothesisTestsTest.cc
  lib/maths/unittest/CPeriodicityHypothesisTestsTest.h
  lib/maths/unittest/CTimeSeriesChangeDetectorTest.cc
  lib/maths/unittest/CTimeSeriesDecompositionTest.cc
  lib/maths/unittest/CTimeSeriesModelTest.cc
  lib/maths/unittest/CTimeSeriesSegmentationTest.cc
  lib/maths/unittest/CTimeSeriesSegmentationTest.h
  lib/maths/unittest/Main.cc
  lib/maths/unittest/Makefile
  lib/model/unittest/CEventRateAnomalyDetectorTest.cc
  lib/model/unittest/CMetricPopulationDataGathererTest.cc
Labels: >backport, v6.5.0

#232 [ML] Improve robustness to very low variance data
  include/maths/CPeriodicityHypothesisTests.h
  lib/maths/CPeriodicityHypothesisTests.cc
  lib/maths/CTimeSeriesDecompositionDetail.cc
Labels: :ml, >bug, >non-issue, affects-results, review, v7.0.0

#233 [ML] Add support for PR CI builds
  dev-tools/ci
  dev-tools/ci.bat
Labels: :ml, >build, >non-issue, review, v6.4.3, v6.5.0, v7.0.0

#234 [ML][6.5] Add support for PR CI builds
  dev-tools/ci
  dev-tools/ci.bat
Labels: >backport, >non-issue, v6.5.0

#235 [ML][6.4] Add support for PR CI builds
  dev-tools/ci
  dev-tools/ci.bat
Labels: >backport, >non-issue, v6.4.3

#237 [ci] Add a couple of `jenkins-ci` helper scripts for Linux and Widnows testing.
  dev-tools/jenkins_ci.ps1
  dev-tools/jenkins_ci.sh
Labels: :ml, >build, >non-issue, v6.4.3, v6.5.0, v7.0.0

#238 [ci] Mark 'jenkins_ci.sh' as executable
  dev-tools/jenkins_ci.sh
Labels: :ml, >build, >non-issue, v6.4.3, v6.5.0, v7.0.0

#239 [6.5][ML] Add multi_bucket_impact label to anomalies
  docs/CHANGELOG.asciidoc
  include/api/CHierarchicalResultsWriter.h
  include/maths/CModel.h
  include/model/CAnnotatedProbability.h
  include/model/CAnnotatedProbabilityBuilder.h
  include/model/CAnomalyDetectorModelConfig.h
  include/model/CProbabilityAndInfluenceCalculator.h
  lib/api/CHierarchicalResultsWriter.cc
  lib/api/CJsonOutputWriter.cc
  lib/api/unittest/CJsonOutputWriterTest.cc
  lib/maths/CModel.cc
  lib/maths/CTimeSeriesModel.cc
  lib/model/CAnnotatedProbabilityBuilder.cc
  lib/model/CAnomalyDetectorModelConfig.cc
  lib/model/CEventRateModel.cc
  lib/model/CMetricModel.cc
  lib/model/CProbabilityAndInfluenceCalculator.cc
  lib/model/unittest/CEventRateModelTest.cc
  lib/model/unittest/CEventRateModelTest.h
Labels: :ml, >backport, v6.5.0, v7.0.0

#241 [ML] Bug-fix for multi_bucket_impact
  lib/model/CAnnotatedProbability.cc
Labels: :ml, >bug, >non-issue, review, v6.5.0, v7.0.0

#242 [6.5][ML] Bug-fix for multi_bucket_impact (#241)
  lib/model/CAnnotatedProbability.cc
Labels: :ml, >backport, >bug, >non-issue, v6.5.0, v7.0.0

#245 [ci][6.4] Add `jenkins-ci` helper scripts for Linux and Windows CI
  dev-tools/jenkins_ci.ps1
  dev-tools/jenkins_ci.sh
Labels: >backport, >non-issue, v6.4.3

#236 [ML] Fix handling of snapshot flag in CI builds
  dev-tools/ci
  dev-tools/ci.bat
Labels: :ml, >build, >non-issue, review, v6.4.3, v6.5.0, v7.0.0

#246 [ML][6.5] Fix handling of snapshot flag in CI builds
  dev-tools/ci
  dev-tools/ci.bat
Labels: >backport, >non-issue, v6.5.0

#247 [ML][6.4] Fix handling of snapshot flag in CI builds
  dev-tools/ci
  dev-tools/ci.bat
Labels: >backport, >non-issue, v6.4.3

#250 [ML] Consolidate CI scripts
  dev-tools/ci
  dev-tools/ci.bat
  dev-tools/download_windows_deps.ps1
  dev-tools/jenkins_ci.ps1
  dev-tools/jenkins_ci.sh
Labels: :ml, >build, >non-issue, review, v6.4.3, v6.5.0, v7.0.0

#253 [ML][6.4] Consolidate CI scripts
  dev-tools/ci
  dev-tools/ci.bat
  dev-tools/download_windows_deps.ps1
  dev-tools/jenkins_ci.ps1
  dev-tools/jenkins_ci.sh
Labels: >backport, >non-issue, v6.4.3

#254 [ML] Upgrade to Gradle 4.10
  gradle/wrapper/gradle-wrapper.properties
Labels: :ml, >build, >non-issue, review, v6.5.0, v7.0.0

#255 [ML][6.5] Upgrade to Gradle 4.10
  gradle/wrapper/gradle-wrapper.properties
Labels: >backport, >non-issue, v6.5.0

#243 [ML] hard_limit memory error fix
  docs/CHANGELOG.asciidoc
  include/model/CResourceMonitor.h
  lib/api/unittest/CAnomalyJobLimitTest.cc
  lib/model/CResourceMonitor.cc
Labels: :ml, >bug, v6.5.0, v7.0.0

#229 [ML-Dataframe][FEATURE] A dense data frame
  include/core/CConcurrentQueue.h
  include/core/CDataAdder.h
  include/core/CDataFrame.h
  include/core/CDataFrameRowSlice.h
  lib/core/CCompressOStream.cc
  lib/core/CDataFrame.cc
  lib/core/CDataFrameRowSlice.cc
  lib/core/Makefile
  lib/core/unittest/CDataFrameTest.cc
  lib/core/unittest/CDataFrameTest.h
  lib/core/unittest/Main.cc
  lib/core/unittest/Makefile
Labels: :ml, >feature, review

#256 [6.5][ML] hard_limit memory error fix (#243)
  docs/CHANGELOG.asciidoc
  include/model/CResourceMonitor.h
  lib/api/unittest/CAnomalyJobLimitTest.cc
  lib/model/CResourceMonitor.cc
Labels: :ml, >backport, >bug, v6.5.0, v7.0.0

#257 [ML] Round multi_bucket_impact to 2dp
  lib/model/CProbabilityAndInfluenceCalculator.cc
Labels: :ml, >non-issue, review, v6.5.0, v7.0.0

#259 [6.5][ML] Round multi_bucket_impact to 2dp (#257)
  lib/model/CProbabilityAndInfluenceCalculator.cc
Labels: :ml, >backport, >non-issue, v6.5.0, v7.0.0

#258 [6.4][ML] hard_limit memory error fix (#243)
  docs/CHANGELOG.asciidoc
  include/model/CResourceMonitor.h
  lib/api/unittest/CAnomalyJobLimitTest.cc
  lib/model/CResourceMonitor.cc
Labels: :ml, >backport, v6.4.3, v6.5.0, v7.0.0

#222 [ML] Skip model update in anomaly model
  docs/CHANGELOG.asciidoc
  include/maths/CModel.h
  lib/maths/CModel.cc
  lib/maths/CTimeSeriesModel.cc
  lib/maths/unittest/CTimeSeriesModelTest.cc
  lib/maths/unittest/CTimeSeriesModelTest.h
  lib/model/CEventRateModel.cc
  lib/model/CEventRatePopulationModel.cc
  lib/model/CMetricModel.cc
  lib/model/CMetricPopulationModel.cc
Labels: :ml, >bug, v6.4.3, v6.5.0, v7.0.0

#262 [6.5][ML] Account for step discontinuities when reinitialising the residual model after a detecting a change or new decomposition components
  include/maths/CTimeSeriesDecomposition.h
  include/maths/CTimeSeriesDecompositionDetail.h
  include/maths/CTimeSeriesDecompositionInterface.h
  include/maths/CTimeSeriesDecompositionStub.h
  include/maths/CTimeSeriesModel.h
  lib/maths/CTimeSeriesDecomposition.cc
  lib/maths/CTimeSeriesDecompositionDetail.cc
  lib/maths/CTimeSeriesDecompositionStub.cc
  lib/maths/CTimeSeriesModel.cc
  lib/maths/unittest/CTimeSeriesModelTest.cc
Labels: >backport, >non-issue, v6.5.0

#263 [ML] Add Boost Test to build environment
  build-setup/linux.md
  build-setup/macos.md
  build-setup/windows.md
  dev-tools/docker/build_linux-musl_build_image.sh
  dev-tools/docker/build_linux_build_image.sh
  dev-tools/docker/build_linux_test_image.sh
  dev-tools/docker/build_macosx_build_image.sh
  dev-tools/docker/linux-musl_image/Dockerfile
  dev-tools/docker/linux_builder/Dockerfile
  dev-tools/docker/linux_image/Dockerfile
  dev-tools/docker/linux_test_image/Dockerfile
  dev-tools/docker/linux_tester/Dockerfile
  dev-tools/docker/macosx_builder/Dockerfile
  dev-tools/docker/macosx_image/Dockerfile
  dev-tools/download_windows_deps.ps1
  dev-tools/vagrant/linux/provision.sh
Labels: :ml, >build, >non-issue, review, v6.5.0

#265 [ML] Improvements to model robustness to outliers
  docs/CHANGELOG.asciidoc
  include/maths/CTimeSeriesChangeDetector.h
  include/maths/CTimeSeriesDecomposition.h
  lib/maths/CTimeSeriesChangeDetector.cc
  lib/maths/CTimeSeriesDecomposition.cc
  lib/maths/CTimeSeriesDecompositionDetail.cc
  lib/maths/CTimeSeriesModel.cc
  lib/maths/unittest/CTimeSeriesChangeDetectorTest.cc
  lib/maths/unittest/CTimeSeriesModelTest.cc
  lib/model/CAnomalyDetectorModelConfig.cc
Labels: :ml, >enhancement, affects-results, v6.5.0, v7.0.0

#261 [ML] Backport skip model update in anomaly model (#222)
  docs/CHANGELOG.asciidoc
  include/maths/CModel.h
  lib/maths/CModel.cc
  lib/maths/CTimeSeriesModel.cc
  lib/maths/unittest/CTimeSeriesModelTest.cc
  lib/maths/unittest/CTimeSeriesModelTest.h
  lib/model/CEventRateModel.cc
  lib/model/CEventRatePopulationModel.cc
  lib/model/CMetricModel.cc
  lib/model/CMetricPopulationModel.cc
Labels: >backport, review, v6.4.3

#270 [ML] Manually do what dissociate flag does in build script
  dev-tools/jenkins_ci.sh
Labels: :ml, >build, >non-issue, v6.4.3, v6.5.0, v7.0.0

#272 [ML] Do isnan check when computing significance
  docs/CHANGELOG.asciidoc
  lib/maths/CStatisticalTests.cc
Labels: :ml, >bug, review, v6.5.0, v7.0.0

#275 [6.5][ML] Do isnan check when computing significance (#272)
  docs/CHANGELOG.asciidoc
  lib/maths/CStatisticalTests.cc
Labels: :ml, >bug, v6.5.0, v7.0.0

#277 [ML][6.6] Change Mac compiler version in build setup docs
  build-setup/macos.md
Labels: >backport, >non-issue, v6.6.0

#278 [ML][6.6] Call CTestTmpDir::tmpDir() before installing syscall filter
  lib/seccomp/unittest/CSystemCallFilterTest.cc
Labels: >backport, >non-issue, v6.6.0

#279 [ML][6.5] Call CTestTmpDir::tmpDir() before installing syscall filter
  lib/seccomp/unittest/CSystemCallFilterTest.cc
Labels: >backport, >non-issue, v6.5.0

#280 [ML] Fix underlying cause of "Failed to compute significance Error in function boost::math::cdf(fisher_f_distribution..." log error
  lib/maths/CStatisticalTests.cc
  lib/maths/CTimeSeriesSegmentation.cc
Labels: >bug, >non-issue, affects-results, v6.5.0, v6.6.0, v7.0.0

#281 [6.6][ML] Fix underlying cause of "Failed to compute significance Error in function boost::math::cdf(fisher_f_distribution..." log error
  lib/maths/CStatisticalTests.cc
  lib/maths/CTimeSeriesSegmentation.cc
Labels: >backport, >non-issue, v6.6.0

#282 [ML] Fix underlying cause of "Failed to compute significance Error in function boost::math::cdf(fisher_f_distribution..." log error
  lib/maths/CStatisticalTests.cc
  lib/maths/CTimeSeriesSegmentation.cc
Labels: >backport, >non-issue, v6.5.0

#291 [ML][6.4] Switch Docker registry to docker.elastic.co
  dev-tools/docker/build_check_style_image.sh
  dev-tools/docker/build_linux-musl_build_image.sh
  dev-tools/docker/build_linux_build_image.sh
  dev-tools/docker/build_linux_test_image.sh
  dev-tools/docker/build_macosx_build_image.sh
  dev-tools/docker/linux-musl_builder/Dockerfile
  dev-tools/docker/linux_builder/Dockerfile
  dev-tools/docker/linux_test_image/Dockerfile
  dev-tools/docker/linux_tester/Dockerfile
  dev-tools/docker/macosx_builder/Dockerfile
  dev-tools/docker/style_checker/Dockerfile
Labels: >backport, >non-issue, v6.4.3

#287 [ML] Prevent trend detection during a change in a time series creating a poorly reinitialised model
  docs/CHANGELOG.asciidoc
  include/maths/CTimeSeriesDecomposition.h
  include/maths/CTimeSeriesDecompositionDetail.h
  include/maths/CTimeSeriesDecompositionInterface.h
  include/maths/CTimeSeriesDecompositionStub.h
  lib/maths/CTimeSeriesDecomposition.cc
  lib/maths/CTimeSeriesDecompositionDetail.cc
  lib/maths/CTimeSeriesDecompositionStub.cc
  lib/maths/CTimeSeriesModel.cc
Labels: :ml, >bug, affects-results, review, v6.5.0, v6.6.0, v7.0.0

#290 [ML][6.5] Switch Docker registry to docker.elastic.co
  dev-tools/docker/build_check_style_image.sh
  dev-tools/docker/build_linux-musl_build_image.sh
  dev-tools/docker/build_linux_build_image.sh
  dev-tools/docker/build_linux_test_image.sh
  dev-tools/docker/build_macosx_build_image.sh
  dev-tools/docker/linux-musl_builder/Dockerfile
  dev-tools/docker/linux_builder/Dockerfile
  dev-tools/docker/linux_test_image/Dockerfile
  dev-tools/docker/linux_tester/Dockerfile
  dev-tools/docker/macosx_builder/Dockerfile
  dev-tools/docker/style_checker/Dockerfile
Labels: >backport, >non-issue, v6.5.0

#289 [ML][6.6] Switch Docker registry to docker.elastic.co
  dev-tools/docker/build_check_style_image.sh
  dev-tools/docker/build_linux-musl_build_image.sh
  dev-tools/docker/build_linux_build_image.sh
  dev-tools/docker/build_linux_test_image.sh
  dev-tools/docker/build_macosx_build_image.sh
  dev-tools/docker/linux-musl_builder/Dockerfile
  dev-tools/docker/linux_builder/Dockerfile
  dev-tools/docker/linux_test_image/Dockerfile
  dev-tools/docker/linux_tester/Dockerfile
  dev-tools/docker/macosx_builder/Dockerfile
  dev-tools/docker/style_checker/Dockerfile
Labels: >backport, >non-issue, v6.6.0

#292 [6.6][ML] Prevent trend detection during a change in a time series creating a poorly reinitialised model
  docs/CHANGELOG.asciidoc
  include/maths/CTimeSeriesDecomposition.h
  include/maths/CTimeSeriesDecompositionDetail.h
  include/maths/CTimeSeriesDecompositionInterface.h
  include/maths/CTimeSeriesDecompositionStub.h
  lib/maths/CTimeSeriesDecomposition.cc
  lib/maths/CTimeSeriesDecompositionDetail.cc
  lib/maths/CTimeSeriesDecompositionStub.cc
  lib/maths/CTimeSeriesModel.cc
Labels: >backport, v6.6.0

#293 [6.5][ML] Prevent trend detection during a change in a time series creating a poorly reinitialised model
  docs/CHANGELOG.asciidoc
  include/maths/CTimeSeriesDecomposition.h
  include/maths/CTimeSeriesDecompositionDetail.h
  include/maths/CTimeSeriesDecompositionInterface.h
  include/maths/CTimeSeriesDecompositionStub.h
  lib/maths/CTimeSeriesDecomposition.cc
  lib/maths/CTimeSeriesDecompositionDetail.cc
  lib/maths/CTimeSeriesDecompositionStub.cc
  lib/maths/CTimeSeriesModel.cc
Labels: >backport, v6.5.0
