Repository elastic/ml-cpp, pull requests merged in 2018-07, with the labels that each got.

#125 [6.4][ML] Improve the accuracy of model memory control
  docs/CHANGELOG.asciidoc
  include/api/CAnomalyJob.h
  include/api/CForecastRunner.h
  include/model/CAnomalyDetector.h
  include/model/CDataGatherer.h
  include/model/CLimits.h
  include/model/CResourceMonitor.h
  lib/api/CAnomalyJob.cc
  lib/api/unittest/CAnomalyJobLimitTest.cc
  lib/maths/CTimeSeriesDecompositionDetail.cc
  lib/model/CAnomalyDetector.cc
  lib/model/CCountingModelFactory.cc
  lib/model/CDataGatherer.cc
  lib/model/CEventRateModel.cc
  lib/model/CEventRateModelFactory.cc
  lib/model/CEventRatePopulationModelFactory.cc
  lib/model/CIndividualModel.cc
  lib/model/CLimits.cc
  lib/model/CMetricBucketGatherer.cc
  lib/model/CMetricModel.cc
  lib/model/CMetricModelFactory.cc
  lib/model/CMetricPopulationModelFactory.cc
  lib/model/CPopulationModel.cc
  lib/model/CResourceMonitor.cc
  lib/model/CSampleCounts.cc
  lib/model/unittest/CDetectionRuleTest.cc
  lib/model/unittest/CEventRateDataGathererTest.cc
  lib/model/unittest/CEventRatePopulationDataGathererTest.cc
  lib/model/unittest/CHierarchicalResultsTest.cc
  lib/model/unittest/CMetricDataGathererTest.cc
  lib/model/unittest/CMetricPopulationDataGathererTest.cc
  lib/model/unittest/CModelDetailsViewTest.cc
  lib/model/unittest/CResourceLimitTest.cc
  lib/model/unittest/CResourceMonitorTest.cc
  lib/model/unittest/CRuleConditionTest.cc
Labels: >backport, v6.4.0

#137 [6.4][ML] Store calendar periodicity historical error statistics in compressed format
  docs/CHANGELOG.asciidoc
  include/maths/CCalendarCyclicTest.h
  include/maths/CRandomizedPeriodicityTest.h
  include/maths/CTimeSeriesDecompositionDetail.h
  lib/api/unittest/CAnomalyJobLimitTest.cc
  lib/maths/CCalendarCyclicTest.cc
  lib/maths/CRandomizedPeriodicityTest.cc
  lib/maths/Makefile
  lib/maths/unittest/CCalendarCyclicTestTest.cc
  lib/maths/unittest/CCalendarCyclicTestTest.h
  lib/maths/unittest/CRandomizedPeriodicityTestTest.cc
  lib/maths/unittest/CRandomizedPeriodicityTestTest.h
  lib/maths/unittest/CTimeSeriesDecompositionTest.cc
  lib/maths/unittest/CTimeSeriesModelTest.cc
  lib/maths/unittest/CTrendTestsTest.cc
  lib/maths/unittest/Main.cc
  lib/maths/unittest/Makefile
  lib/model/CAnomalyDetector.cc
Labels: >backport, v6.4.0

#138 [6.4][ML] Improve adaption of the modelling of cyclic components to very localised features
  docs/CHANGELOG.asciidoc
  include/maths/CAdaptiveBucketing.h
  include/maths/CBasicStatistics.h
  include/maths/CBasicStatisticsPersist.h
  include/maths/CCalendarComponentAdaptiveBucketing.h
  include/maths/CSeasonalComponent.h
  include/maths/CSeasonalComponentAdaptiveBucketing.h
  include/maths/CTools.h
  include/maths/CTrendComponent.h
  lib/maths/CAdaptiveBucketing.cc
  lib/maths/CCalendarComponentAdaptiveBucketing.cc
  lib/maths/CSeasonalComponent.cc
  lib/maths/CSeasonalComponentAdaptiveBucketing.cc
  lib/maths/CTimeSeriesDecompositionDetail.cc
  lib/maths/CTools.cc
  lib/maths/CTrendComponent.cc
  lib/maths/unittest/CBasicStatisticsTest.cc
  lib/maths/unittest/CForecastTest.cc
  lib/maths/unittest/CSeasonalComponentAdaptiveBucketingTest.cc
  lib/maths/unittest/CTimeSeriesDecompositionTest.cc
Labels: >backport, v6.4.0

#139 [6.4][ML] Fix issues upgrading state leading to possible abort of the autodetect process
  docs/CHANGELOG.asciidoc
  include/core/CStateMachine.h
  lib/core/CStateMachine.cc
  lib/core/unittest/CStateMachineTest.cc
  lib/maths/CTimeSeriesDecompositionDetail.cc
  lib/maths/unittest/CTimeSeriesDecompositionTest.cc
Labels: >backport, v6.4.0

#140 [6.3][ML] Fix issues upgrading state leading to possible abort of the autodetect process
  docs/CHANGELOG.asciidoc
  include/core/CStateMachine.h
  lib/core/CStateMachine.cc
  lib/core/unittest/CStateMachineTest.cc
  lib/maths/CTimeSeriesDecompositionDetail.cc
  lib/maths/unittest/CTimeSeriesDecompositionTest.cc
Labels: >backport, v6.3.2

#143 [ML] Fix bug upgrading state from 5.6 direct to 6.3 causing SIGSEGV on open job
  docs/CHANGELOG.asciidoc
  include/maths/CTimeSeriesDecompositionDetail.h
  lib/maths/CSeasonalComponentAdaptiveBucketing.cc
  lib/maths/CTimeSeriesDecomposition.cc
  lib/maths/CTimeSeriesDecompositionDetail.cc
  lib/maths/unittest/CTimeSeriesDecompositionTest.cc
  lib/maths/unittest/testfiles/CTimeSeriesDecomposition.5.6.seasonal.state.xml
  lib/maths/unittest/testfiles/CTimeSeriesDecomposition.5.6.trend_and_seasonal.state.xml
Labels: :ml, >bug, v6.3.2, v6.4.0, v7.0.0

#144 [6.4][ML] Fix bug upgrading state from 5.6 direct to 6.3 causing SIGSEGV on open job
  docs/CHANGELOG.asciidoc
  include/maths/CTimeSeriesDecompositionDetail.h
  lib/maths/CSeasonalComponentAdaptiveBucketing.cc
  lib/maths/CTimeSeriesDecomposition.cc
  lib/maths/CTimeSeriesDecompositionDetail.cc
  lib/maths/unittest/CTimeSeriesDecompositionTest.cc
  lib/maths/unittest/testfiles/CTimeSeriesDecomposition.5.6.seasonal.state.xml
  lib/maths/unittest/testfiles/CTimeSeriesDecomposition.5.6.trend_and_seasonal.state.xml
Labels: >backport, v6.4.0

#146 [ML] Decrease the memory used by distribution models
  docs/CHANGELOG.asciidoc
  include/maths/CGammaRateConjugate.h
  include/maths/CLogNormalMeanPrecConjugate.h
  include/maths/CNaturalBreaksClassifier.h
  include/maths/CNormalMeanPrecConjugate.h
  include/maths/CPoissonMeanConjugate.h
  include/maths/CXMeansOnline.h
  include/maths/CXMeansOnline1d.h
  include/maths/MathsTypes.h
  lib/maths/CGammaRateConjugate.cc
  lib/maths/CLogNormalMeanPrecConjugate.cc
  lib/maths/CNaturalBreaksClassifier.cc
  lib/maths/CNormalMeanPrecConjugate.cc
  lib/maths/CPoissonMeanConjugate.cc
  lib/maths/CXMeansOnline1d.cc
  lib/maths/unittest/CMultimodalPriorTest.cc
  lib/maths/unittest/CNormalMeanPrecConjugateTest.cc
  lib/maths/unittest/COneOfNPriorTest.cc
  lib/maths/unittest/CPoissonMeanConjugateTest.cc
  lib/maths/unittest/CPriorTest.cc
  lib/maths/unittest/CXMeansOnline1dTest.cc
  lib/model/unittest/CMetricModelTest.cc
Labels: :ml, >enhancement, affects-results, v6.4.0, v7.0.0

#149 [ML] skip calculation of influencer probabilities if no influences specified
  lib/model/CProbabilityAndInfluenceCalculator.cc
Labels: :ml, >non-issue, >refactoring, v6.4.0, v7.0.0

#151 [6.4][ML] skip calculation of influencer probabilities if no influences specified
  lib/model/CProbabilityAndInfluenceCalculator.cc
Labels: >backport, >non-issue, v6.4.0

#150 [ML] Fix influencer count and influence calculation
  docs/CHANGELOG.asciidoc
  lib/model/CMetricPopulationModel.cc
  lib/model/CProbabilityAndInfluenceCalculator.cc
  lib/model/unittest/CMetricPopulationModelTest.cc
Labels: :ml, >bug, affects-results, v6.4.0, v7.0.0

#153 [6.4][ML] Fix influencer count and influence calculation
  docs/CHANGELOG.asciidoc
  lib/model/CMetricPopulationModel.cc
  lib/model/CProbabilityAndInfluenceCalculator.cc
  lib/model/unittest/CMetricPopulationModelTest.cc
Labels: >backport, affects-results, v6.4.0

#152 [ML]improve error message for splitting failure
  include/maths/CAdaptiveBucketing.h
  include/maths/CCalendarComponentAdaptiveBucketing.h
  include/maths/CSeasonalComponentAdaptiveBucketing.h
  lib/maths/CAdaptiveBucketing.cc
  lib/maths/CCalendarComponentAdaptiveBucketing.cc
  lib/maths/CSeasonalComponentAdaptiveBucketing.cc
  lib/maths/unittest/CCalendarComponentAdaptiveBucketingTest.cc
  lib/maths/unittest/CCalendarComponentAdaptiveBucketingTest.h
  lib/maths/unittest/CSeasonalComponentAdaptiveBucketingTest.cc
  lib/maths/unittest/CSeasonalComponentAdaptiveBucketingTest.h
Labels: :ml, >non-issue, >refactoring, review, v6.4.0, v7.0.0

#154 [6.4][ML]improve error message for splitting failure (#152)
  include/maths/CAdaptiveBucketing.h
  include/maths/CCalendarComponentAdaptiveBucketing.h
  include/maths/CSeasonalComponentAdaptiveBucketing.h
  lib/maths/CAdaptiveBucketing.cc
  lib/maths/CCalendarComponentAdaptiveBucketing.cc
  lib/maths/CSeasonalComponentAdaptiveBucketing.cc
  lib/maths/unittest/CCalendarComponentAdaptiveBucketingTest.cc
  lib/maths/unittest/CCalendarComponentAdaptiveBucketingTest.h
  lib/maths/unittest/CSeasonalComponentAdaptiveBucketingTest.cc
  lib/maths/unittest/CSeasonalComponentAdaptiveBucketingTest.h
Labels: >backport, >non-issue, v6.4.0

#148 [ML] Improve model accuracy after detecting a change
  include/maths/CModel.h
  include/maths/CTimeSeriesChangeDetector.h
  include/maths/CTimeSeriesModel.h
  lib/maths/CModel.cc
  lib/maths/CNaiveBayes.cc
  lib/maths/CTimeSeriesChangeDetector.cc
  lib/maths/CTimeSeriesDecomposition.cc
  lib/maths/CTimeSeriesModel.cc
  lib/maths/CXMeansOnline1d.cc
  lib/maths/unittest/CTimeSeriesChangeDetectorTest.cc
  lib/maths/unittest/CToolsTest.cc
  lib/model/CAnomalyDetectorModelConfig.cc
Labels: >enhancement, >non-issue, affects-results, v6.4.0, v7.0.0

#157 [ML] build boost test framework in buildenv
  build-setup/linux.md
  build-setup/macos.md
  build-setup/windows.md
  dev-tools/docker/linux-musl_image/Dockerfile
  dev-tools/docker/linux_image/Dockerfile
  dev-tools/vagrant/linux/provision.sh
Labels: :ml, >build, >non-issue, >test, v7.0.0

#159 [ML] do not clear periodicity test after detecting a changepoint
  include/maths/CTimeSeriesDecompositionDetail.h
  lib/maths/CTimeSeriesDecomposition.cc
  lib/maths/CTimeSeriesDecompositionDetail.cc
  lib/maths/unittest/CTimeSeriesModelTest.cc
Labels: :ml, >non-issue, affects-results, v6.4.0, v7.0.0

#160 [6.4][ML] do not clear periodicity test after detecting a changepoint
  include/maths/CTimeSeriesDecompositionDetail.h
  lib/maths/CTimeSeriesDecomposition.cc
  lib/maths/CTimeSeriesDecompositionDetail.cc
  lib/maths/unittest/CTimeSeriesModelTest.cc
Labels: >backport, >non-issue, affects-results, v6.4.0

#158 [ML] Skip pre-tokenised performance assertion in CI
  lib/api/unittest/CTokenListDataTyperTest.cc
Labels: :ml, >test, review, v6.4.0, v7.0.0

#161 [6.4][ML] Skip pre-tokenised performance assertion in CI
  lib/api/unittest/CTokenListDataTyperTest.cc
Labels: >backport, >test, v6.4.0

#162 [6.4][ML] Decrease the memory used by distribution models (#146)
  docs/CHANGELOG.asciidoc
  include/maths/CGammaRateConjugate.h
  include/maths/CLogNormalMeanPrecConjugate.h
  include/maths/CNaturalBreaksClassifier.h
  include/maths/CNormalMeanPrecConjugate.h
  include/maths/CPoissonMeanConjugate.h
  include/maths/CXMeansOnline.h
  include/maths/CXMeansOnline1d.h
  lib/maths/CGammaRateConjugate.cc
  lib/maths/CLogNormalMeanPrecConjugate.cc
  lib/maths/CNaturalBreaksClassifier.cc
  lib/maths/CNormalMeanPrecConjugate.cc
  lib/maths/CPoissonMeanConjugate.cc
  lib/maths/CXMeansOnline1d.cc
  lib/maths/unittest/CMultimodalPriorTest.cc
  lib/maths/unittest/CNormalMeanPrecConjugateTest.cc
  lib/maths/unittest/COneOfNPriorTest.cc
  lib/maths/unittest/CPoissonMeanConjugateTest.cc
  lib/maths/unittest/CPriorTest.cc
  lib/maths/unittest/CTimeSeriesModelTest.cc
  lib/maths/unittest/CXMeansOnline1dTest.cc
  lib/model/unittest/CMetricModelTest.cc
Labels: >backport, v6.4.0

#164 [6.4][ML] Improve model accuracy after detecting a change
  include/maths/CModel.h
  include/maths/CTimeSeriesChangeDetector.h
  include/maths/CTimeSeriesModel.h
  lib/maths/CModel.cc
  lib/maths/CNaiveBayes.cc
  lib/maths/CTimeSeriesChangeDetector.cc
  lib/maths/CTimeSeriesDecomposition.cc
  lib/maths/CTimeSeriesDecompositionDetail.cc
  lib/maths/CTimeSeriesModel.cc
  lib/maths/CXMeansOnline1d.cc
  lib/maths/unittest/CTimeSeriesChangeDetectorTest.cc
  lib/maths/unittest/CToolsTest.cc
  lib/model/CAnomalyDetectorModelConfig.cc
Labels: >backport, >non-issue, v6.4.0

#163 [ML] Don't use higher resolution for cyclic component models than data bucketing supports
  include/maths/MathsTypes.h
  lib/maths/CAdaptiveBucketing.cc
  lib/maths/unittest/CTimeSeriesDecompositionTest.cc
  lib/maths/unittest/CTimeSeriesModelTest.cc
  lib/maths/unittest/CToolsTest.cc
Labels: :ml, >bug, >non-issue, affects-results, review, v6.4.0, v7.0.0

#165 [ML] Improve times series decomposition after detecting time shifts
  include/maths/CExpandingWindow.h
  include/maths/CTimeSeriesDecompositionDetail.h
  lib/maths/CExpandingWindow.cc
  lib/maths/CTimeSeriesDecomposition.cc
  lib/maths/CTimeSeriesDecompositionDetail.cc
Labels: :ml, >enhancement, >non-issue, affects-results, review, v6.4.0, v7.0.0

#166 [6.4][ML] Don't use higher resolution for cyclic component models than data bucketing supports
  lib/maths/CAdaptiveBucketing.cc
  lib/maths/unittest/CTimeSeriesDecompositionTest.cc
Labels: >backport, >non-issue, v6.4.0

#167 [6.4][ML] Improve times series decomposition after detecting time shifts
  include/maths/CExpandingWindow.h
  include/maths/CTimeSeriesDecompositionDetail.h
  lib/maths/CExpandingWindow.cc
  lib/maths/CTimeSeriesDecomposition.cc
  lib/maths/CTimeSeriesDecompositionDetail.cc
Labels: >backport, >non-issue, v6.4.0

#168 [ML] Bump version to 6.5.0
  doxygen/cplusplus.Doxyfile
  gradle.properties
Labels: >non-issue, v6.5.0

#170 [ML] Fixes potentials for SIGSEGV in multivariate probability calculation
  docs/CHANGELOG.asciidoc
  include/maths/CTimeSeriesModel.h
  lib/maths/CMultimodalPrior.cc
  lib/maths/CMultivariateOneOfNPrior.cc
  lib/maths/CTimeSeriesModel.cc
  lib/model/unittest/CEventRateModelTest.cc
Labels: :ml, >bug, affects-results, review, v6.4.0, v6.5.0, v7.0.0

#172 [6.5][ML] Fixes potentials for SIGSEGV in multivariate probability calculation
  docs/CHANGELOG.asciidoc
  include/maths/CTimeSeriesModel.h
  lib/maths/CMultimodalPrior.cc
  lib/maths/CMultivariateOneOfNPrior.cc
  lib/maths/CTimeSeriesModel.cc
  lib/model/unittest/CEventRateModelTest.cc
Labels: >backport, v6.5.0

#174 [6.4][ML] Fixes potentials for SIGSEGV in multivariate probability calculation
  docs/CHANGELOG.asciidoc
  include/maths/CTimeSeriesModel.h
  lib/maths/CMultimodalPrior.cc
  lib/maths/CMultivariateOneOfNPrior.cc
  lib/maths/CTimeSeriesModel.cc
  lib/model/unittest/CEventRateModelTest.cc
Labels: >backport, v6.4.0

#173 [ML] Pad estimated memory usage in anticipation of multi-bucket analysis
  lib/api/unittest/CAnomalyJobLimitTest.cc
  lib/maths/CTimeSeriesModel.cc
Labels: :ml, >non-issue, v6.4.0
