Repository elastic/ml-cpp, pull requests merged in 2018-06, with the labels that each got.

#116 [ML] Add clock_gettime to Seccomp filter
  lib/seccomp/CSystemCallFilter_Linux.cc
Labels: :ml, >non-issue, review, v6.4.0, v7.0.0

#117 [6.4][ML] Fix deletion forecast overflow (#110)
  lib/api/CForecastRunner.cc
  lib/seccomp/CSystemCallFilter_Linux.cc
  lib/seccomp/unittest/CSystemCallFilterTest.cc
  lib/seccomp/unittest/CSystemCallFilterTest.h
  lib/seccomp/unittest/Makefile
Labels: >backport, >non-issue, v6.4.0

#118 [6.4][ML] Add clock_gettime to seccomp filter (#116)
  lib/seccomp/CSystemCallFilter_Linux.cc
Labels: >backport, >non-issue, v6.4.0

#107 [ML] Trap zero variance in forecast confidence interval calculation causing error to be logged
  docs/CHANGELOG.asciidoc
  lib/maths/CTrendComponent.cc
Labels: :ml, >bug, v6.4.0, v7.0.0

#122 [ML] Improve the accuracy of model memory control
  docs/CHANGELOG.asciidoc
  include/api/CAnomalyJob.h
  include/api/CForecastRunner.h
  include/model/CAnomalyDetector.h
  include/model/CDataGatherer.h
  include/model/CLimits.h
  include/model/CResourceMonitor.h
  lib/api/CAnomalyJob.cc
  lib/api/unittest/CAnomalyJobLimitTest.cc
  lib/maths/CTimeSeriesDecompositionDetail.cc
  lib/model/CAnomalyDetector.cc
  lib/model/CCountingModelFactory.cc
  lib/model/CDataGatherer.cc
  lib/model/CEventRateModel.cc
  lib/model/CEventRateModelFactory.cc
  lib/model/CEventRatePopulationModelFactory.cc
  lib/model/CIndividualModel.cc
  lib/model/CLimits.cc
  lib/model/CMetricBucketGatherer.cc
  lib/model/CMetricModel.cc
  lib/model/CMetricModelFactory.cc
  lib/model/CMetricPopulationModelFactory.cc
  lib/model/CPopulationModel.cc
  lib/model/CResourceMonitor.cc
  lib/model/CSampleCounts.cc
  lib/model/unittest/CDetectionRuleTest.cc
  lib/model/unittest/CEventRateDataGathererTest.cc
  lib/model/unittest/CEventRatePopulationDataGathererTest.cc
  lib/model/unittest/CHierarchicalResultsTest.cc
  lib/model/unittest/CMetricDataGathererTest.cc
  lib/model/unittest/CMetricPopulationDataGathererTest.cc
  lib/model/unittest/CModelDetailsViewTest.cc
  lib/model/unittest/CResourceLimitTest.cc
  lib/model/unittest/CResourceMonitorTest.cc
  lib/model/unittest/CRuleConditionTest.cc
Labels: :ml, >enhancement, affects-results, review, v6.4.0, v7.0.0

#120 [6.4][ML] Trap zero variance in forecast confidence interval calculation causing error to be logged
  docs/CHANGELOG.asciidoc
  lib/maths/CTrendComponent.cc
Labels: >backport, v6.4.0

#123 [ML] Add option to specify output directory to dump_state
  lib/api/dump_state/Main.cc
  lib/api/dump_state/Makefile
Labels: :ml, >non-issue, v6.3.1, v6.4.0, v7.0.0

#129 [6.4][ML] Add option to specify output directory to dump_state (#123)
  lib/api/dump_state/Main.cc
  lib/api/dump_state/Makefile
Labels: >backport, >non-issue, v6.4.0

#130 [6.3][ML] Add option to specify output directory to dump_state (#123)
  lib/api/dump_state/Main.cc
  lib/api/dump_state/Makefile
Labels: >backport, >non-issue, v6.3.1

#126 [ML] Fix #51 - fix lgamma calculation for x-means clustering
  docs/CHANGELOG.asciidoc
  include/maths/CTools.h
  lib/maths/CTools.cc
  lib/maths/CXMeansOnline1d.cc
  lib/maths/unittest/CToolsTest.cc
  lib/maths/unittest/CToolsTest.h
Labels: :ml, >bug, v6.4.0, v7.0.0

#131 [6.4][ML] Fix #51 - fix lgamma calculation for x-means clustering
  docs/CHANGELOG.asciidoc
  include/maths/CTools.h
  lib/maths/CTools.cc
  lib/maths/CXMeansOnline1d.cc
  lib/maths/unittest/CToolsTest.cc
  lib/maths/unittest/CToolsTest.h
Labels: >backport, v6.4.0

#132 [ML] Refactor code to use std::lgamma instead of boost::math::lgamma
  include/core/CRapidJsonWriterBase.h
  include/maths/CMathsFuncs.h
  include/maths/CMultivariateNormalConjugate.h
  include/maths/CTools.h
  lib/maths/CCategoricalTools.cc
  lib/maths/CGammaRateConjugate.cc
  lib/maths/CLogNormalMeanPrecConjugate.cc
  lib/maths/CMathsFuncs.cc
  lib/maths/CMultinomialConjugate.cc
  lib/maths/CNormalMeanPrecConjugate.cc
  lib/maths/CPoissonMeanConjugate.cc
  lib/maths/CRadialBasisFunction.cc
  lib/maths/CStatisticalTests.cc
  lib/maths/CTools.cc
  lib/maths/ProbabilityAggregators.cc
  lib/maths/unittest/CIntegerToolsTest.cc
  lib/maths/unittest/CProbabilityAggregatorsTest.cc
  lib/maths/unittest/CSamplingTest.cc
  lib/maths/unittest/CToolsTest.cc
Labels: :ml, >non-issue, >refactoring, review, v6.4.0, v7.0.0

#133 [6.4][ML] Refactor code to use std::lgamma instead of boost::math::lgamma
  include/core/CRapidJsonWriterBase.h
  include/maths/CMathsFuncs.h
  include/maths/CMultivariateNormalConjugate.h
  include/maths/CTools.h
  lib/maths/CCategoricalTools.cc
  lib/maths/CGammaRateConjugate.cc
  lib/maths/CLogNormalMeanPrecConjugate.cc
  lib/maths/CMathsFuncs.cc
  lib/maths/CMultinomialConjugate.cc
  lib/maths/CNormalMeanPrecConjugate.cc
  lib/maths/CPoissonMeanConjugate.cc
  lib/maths/CRadialBasisFunction.cc
  lib/maths/CStatisticalTests.cc
  lib/maths/CTools.cc
  lib/maths/ProbabilityAggregators.cc
  lib/maths/unittest/CIntegerToolsTest.cc
  lib/maths/unittest/CProbabilityAggregatorsTest.cc
  lib/maths/unittest/CSamplingTest.cc
  lib/maths/unittest/CToolsTest.cc
Labels: >backport, >non-issue, v6.4.0

#127 [ML] Store calendar periodicity historical error statistics in compressed format
  docs/CHANGELOG.asciidoc
  include/maths/CCalendarCyclicTest.h
  include/maths/CRandomizedPeriodicityTest.h
  include/maths/CTimeSeriesDecompositionDetail.h
  lib/api/unittest/CAnomalyJobLimitTest.cc
  lib/maths/CCalendarCyclicTest.cc
  lib/maths/CRandomizedPeriodicityTest.cc
  lib/maths/Makefile
  lib/maths/unittest/CCalendarCyclicTestTest.cc
  lib/maths/unittest/CCalendarCyclicTestTest.h
  lib/maths/unittest/CRandomizedPeriodicityTestTest.cc
  lib/maths/unittest/CRandomizedPeriodicityTestTest.h
  lib/maths/unittest/CTimeSeriesDecompositionTest.cc
  lib/maths/unittest/CTimeSeriesModelTest.cc
  lib/maths/unittest/CTrendTestsTest.cc
  lib/maths/unittest/Main.cc
  lib/maths/unittest/Makefile
  lib/model/CAnomalyDetector.cc
Labels: :ml, >enhancement, affects-results, review, v6.4.0, v7.0.0

#134 [ML] Improve adaption of the modelling of cyclic components to very localised features
  docs/CHANGELOG.asciidoc
  include/maths/CAdaptiveBucketing.h
  include/maths/CBasicStatistics.h
  include/maths/CBasicStatisticsPersist.h
  include/maths/CCalendarComponentAdaptiveBucketing.h
  include/maths/CSeasonalComponent.h
  include/maths/CSeasonalComponentAdaptiveBucketing.h
  include/maths/CTools.h
  include/maths/CTrendComponent.h
  lib/maths/CAdaptiveBucketing.cc
  lib/maths/CCalendarComponentAdaptiveBucketing.cc
  lib/maths/CSeasonalComponent.cc
  lib/maths/CSeasonalComponentAdaptiveBucketing.cc
  lib/maths/CTimeSeriesDecompositionDetail.cc
  lib/maths/CTools.cc
  lib/maths/CTrendComponent.cc
  lib/maths/unittest/CBasicStatisticsTest.cc
  lib/maths/unittest/CForecastTest.cc
  lib/maths/unittest/CSeasonalComponentAdaptiveBucketingTest.cc
  lib/maths/unittest/CTimeSeriesDecompositionTest.cc
Labels: :ml, >enhancement, affects-results, v6.4.0, v7.0.0
