Repository elastic/ml-cpp, pull requests merged in 2019-05, with the labels that each got.

#474 [7.1][ML] Improve residual model selection
  docs/CHANGELOG.asciidoc
  include/maths/COneOfNPrior.h
  include/maths/Constants.h
  lib/api/unittest/CAnomalyJobLimitTest.cc
  lib/maths/CMultivariateOneOfNPrior.cc
  lib/maths/COneOfNPrior.cc
  lib/maths/Constants.cc
  lib/maths/Makefile
  lib/maths/unittest/COneOfNPriorTest.cc
  lib/model/unittest/CEventRateModelTest.cc
  lib/model/unittest/CMetricAnomalyDetectorTest.cc
Labels: :ml, >backport, v7.1.0

#475 [ML] Add some instrumentation of outlier detection
  bin/data_frame_analyzer/Main.cc
  include/api/CDataFrameAnalysisRunner.h
  include/core/CProgramCounters.h
  lib/api/CDataFrameOutliersRunner.cc
  lib/core/unittest/CProgramCountersTest.cc
  lib/core/unittest/CProgramCountersTest.h
  lib/maths/COutliers.cc
Labels: :ml, >non-issue, review, v7.1.0, v8.0.0

#476 [7.1][ML] Add some instrumentation of outlier detection
  bin/data_frame_analyzer/Main.cc
  include/api/CDataFrameAnalysisRunner.h
  include/core/CProgramCounters.h
  lib/api/CDataFrameOutliersRunner.cc
  lib/core/unittest/CProgramCountersTest.cc
  lib/core/unittest/CProgramCountersTest.h
  lib/maths/COutliers.cc
Labels: >backport, >non-issue, v7.1.0

#480 [ML] Stop linking to libcrypt on Linux
  build-setup/linux.md
  dev-tools/docker/build_linux_build_image.sh
  dev-tools/docker/linux_builder/Dockerfile
  dev-tools/docker/linux_image/Dockerfile
  dev-tools/docker/linux_tester/Dockerfile
  dev-tools/vagrant/linux/provision.sh
  docs/CHANGELOG.asciidoc
Labels: :ml, >enhancement, v7.2.0, v8.0.0

#481 [7.2][ML] Stop linking to libcrypt on Linux
  build-setup/linux.md
  dev-tools/docker/build_linux_build_image.sh
  dev-tools/docker/linux_builder/Dockerfile
  dev-tools/docker/linux_image/Dockerfile
  dev-tools/docker/linux_tester/Dockerfile
  dev-tools/vagrant/linux/provision.sh
  docs/CHANGELOG.asciidoc
Labels: >backport, v7.2.0

#482 [7.2][ML] Switch to use temporary test directory for data frame storage in tests
  lib/core/unittest/CDataFrameTest.cc
  lib/maths/unittest/CDataFrameUtilsTest.cc
  lib/maths/unittest/COutliersTest.cc
Labels: >backport, >non-issue, v7.2.0

#483 [ML] Correct outlier peak memory callback and test
  lib/api/CDataFrameOutliersRunner.cc
  lib/api/unittest/CDataFrameAnalyzerTest.cc
Labels: :ml, >bug, >non-issue, review, v7.2.0, v8.0.0

#469 [FEATURE][ML] Compute loss improvement in the training loop
  include/core/CDataFrame.h
  lib/core/CDataFrame.cc
  lib/maths/CBoostedTree.cc
  lib/maths/CDataFrameUtils.cc
  lib/maths/COutliers.cc
  lib/maths/unittest/CBoostedTreeTest.cc
Labels: :ml, >non-issue, review

#484 [ML] Correct outlier peak memory callback and test
  lib/api/CDataFrameOutliersRunner.cc
  lib/api/unittest/CDataFrameAnalyzerTest.cc
Labels: >backport, >non-issue, v7.2.0

#486 [ML] Improve hard_limit audit message
  docs/CHANGELOG.asciidoc
  include/model/CResourceMonitor.h
  lib/api/CModelSizeStatsJsonWriter.cc
  lib/api/unittest/CJsonOutputWriterTest.cc
  lib/api/unittest/CModelSnapshotJsonWriterTest.cc
  lib/model/CResourceMonitor.cc
Labels: :ml, >enhancement, review, v7.2.0, v8.0.0

#485 [FEATURE][ML] Boosted tree improvements plus more unit testing
  include/maths/CBoostedTree.h
  include/maths/CDataFrameRegressionModel.h
  lib/maths/CBoostedTree.cc
  lib/maths/CQuantileSketch.cc
  lib/maths/unittest/CBoostedTreeTest.cc
  lib/maths/unittest/CBoostedTreeTest.h
Labels: :ml, >non-issue, review
