Repository elastic/ml-cpp, pull requests merged in 2019-08, with the labels that each got.

#576 [7.4][ML] Slow test speed ups
  lib/maths/unittest/CBoostedTreeTest.cc
Labels: >backport, >non-issue, v7.4.0

#579 [ML] Fix return type of L-BFGS lambdas
  include/maths/CLbfgs.h
Labels: :ml, >non-issue, v7.4.0, v8.0.0

#567 [ML] Pass dependent variable for regression by name rather than column index
  include/api/CDataFrameAnalysisRunner.h
  include/api/CDataFrameAnalysisSpecification.h
  include/api/CDataFrameBoostedTreeRunner.h
  include/api/CDataFrameOutliersRunner.h
  include/maths/CBoostedTreeFactory.h
  include/maths/CBoostedTreeImpl.h
  lib/api/CDataFrameAnalysisRunner.cc
  lib/api/CDataFrameAnalysisSpecification.cc
  lib/api/CDataFrameAnalyzer.cc
  lib/api/CDataFrameBoostedTreeRunner.cc
  lib/api/CDataFrameOutliersRunner.cc
  lib/api/unittest/CDataFrameAnalysisSpecificationTest.cc
  lib/api/unittest/CDataFrameAnalyzerTest.cc
  lib/api/unittest/CDataFrameMockAnalysisRunner.cc
  lib/api/unittest/CDataFrameMockAnalysisRunner.h
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/unittest/CBoostedTreeTest.cc
Labels: :ml/DataFrameAnalysis, >non-issue, >refactoring, v7.4.0, v8.0.0

#580 [7.x][ML] Fix return type of L-BFGS lambdas
  include/maths/CLbfgs.h
Labels: >backport, >non-issue, v7.4.0

#581 [7.4][ML] Pass dependent variable for regression by name rather than column index
  include/api/CDataFrameAnalysisRunner.h
  include/api/CDataFrameAnalysisSpecification.h
  include/api/CDataFrameBoostedTreeRunner.h
  include/api/CDataFrameOutliersRunner.h
  include/maths/CBoostedTreeFactory.h
  include/maths/CBoostedTreeImpl.h
  lib/api/CDataFrameAnalysisRunner.cc
  lib/api/CDataFrameAnalysisSpecification.cc
  lib/api/CDataFrameAnalyzer.cc
  lib/api/CDataFrameBoostedTreeRunner.cc
  lib/api/CDataFrameOutliersRunner.cc
  lib/api/unittest/CDataFrameAnalysisSpecificationTest.cc
  lib/api/unittest/CDataFrameAnalyzerTest.cc
  lib/api/unittest/CDataFrameMockAnalysisRunner.cc
  lib/api/unittest/CDataFrameMockAnalysisRunner.h
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/unittest/CBoostedTreeTest.cc
Labels: >backport, >non-issue, v7.4.0

#577 [ML] Some corrections to error handling on fail to restore boosted tree training state
  include/core/RestoreMacros.h
  include/core/UnwrapRef.h
  lib/maths/CBayesianOptimisation.cc
  lib/maths/CBoostedTree.cc
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/unittest/CBoostedTreeTest.cc
  lib/maths/unittest/CBoostedTreeTest.h
Labels: :ml/DataFrameAnalysis, >enhancement, >non-issue, v7.4.0, v8.0.0

#585 [ML] Trap the case that no data are sent to data_frame_analyzer explicitly
  lib/api/CDataFrameAnalyzer.cc
  lib/api/unittest/CDataFrameAnalyzerTest.cc
Labels: :ml/DataFrameAnalysis, >enhancement, >non-issue, v7.4.0, v8.0.0

#583 [7.4][ML] Some corrections to error handling on fail to restore boosted tree training state
  include/core/RestoreMacros.h
  include/core/UnwrapRef.h
  lib/maths/CBayesianOptimisation.cc
  lib/maths/CBoostedTree.cc
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/unittest/CBoostedTreeTest.cc
  lib/maths/unittest/CBoostedTreeTest.h
Labels: >backport, >non-issue, v7.4.0

#586 [7.4][ML] Trap the case that no data are sent to data_frame_analyzer explicitly
  lib/api/CDataFrameAnalyzer.cc
  lib/api/unittest/CDataFrameAnalyzerTest.cc
Labels: >backport, >non-issue, v7.4.0

#587 [ML] Allow configuration of prediction column name in data_frame_analyzer
  include/api/CDataFrameBoostedTreeRunner.h
  lib/api/CDataFrameBoostedTreeRunner.cc
  lib/api/unittest/CDataFrameAnalyzerTest.cc
Labels: :ml/DataFrameAnalysis, >non-issue, review, v7.4.0, v8.0.0

#584 Introduce memory usage estimation mode in data_frame_analyzer
  bin/data_frame_analyzer/CCmdLineParser.cc
  bin/data_frame_analyzer/CCmdLineParser.h
  bin/data_frame_analyzer/Main.cc
  include/api/CDataFrameAnalysisRunner.h
  include/api/CDataFrameAnalysisSpecification.h
  include/api/CMemoryUsageEstimationResultJsonWriter.h
  lib/api/CDataFrameAnalysisRunner.cc
  lib/api/CDataFrameAnalysisSpecification.cc
  lib/api/CMemoryUsageEstimationResultJsonWriter.cc
  lib/api/Makefile.first
  lib/api/unittest/CDataFrameAnalysisRunnerTest.cc
  lib/api/unittest/CDataFrameAnalysisRunnerTest.h
  lib/api/unittest/CMemoryUsageEstimationResultJsonWriterTest.cc
  lib/api/unittest/CMemoryUsageEstimationResultJsonWriterTest.h
  lib/api/unittest/Main.cc
  lib/api/unittest/Makefile
Labels: :ml/DataFrameAnalysis, >non-issue, v7.4.0, v8.0.0

#588 [7.x] Introduce memory usage estimation mode in data_frame_analyzer (#584)
  bin/data_frame_analyzer/CCmdLineParser.cc
  bin/data_frame_analyzer/CCmdLineParser.h
  bin/data_frame_analyzer/Main.cc
  include/api/CDataFrameAnalysisRunner.h
  include/api/CDataFrameAnalysisSpecification.h
  include/api/CMemoryUsageEstimationResultJsonWriter.h
  lib/api/CDataFrameAnalysisRunner.cc
  lib/api/CDataFrameAnalysisSpecification.cc
  lib/api/CMemoryUsageEstimationResultJsonWriter.cc
  lib/api/Makefile.first
  lib/api/unittest/CDataFrameAnalysisRunnerTest.cc
  lib/api/unittest/CDataFrameAnalysisRunnerTest.h
  lib/api/unittest/CMemoryUsageEstimationResultJsonWriterTest.cc
  lib/api/unittest/CMemoryUsageEstimationResultJsonWriterTest.h
  lib/api/unittest/Main.cc
  lib/api/unittest/Makefile
Labels: :ml/DataFrameAnalysis, >non-issue, backport, v7.4.0

#589 [7.4][ML] Allow configuration of prediction column name in data_frame_analyzer
  include/api/CDataFrameBoostedTreeRunner.h
  lib/api/CDataFrameBoostedTreeRunner.cc
  lib/api/unittest/CDataFrameAnalyzerTest.cc
Labels: >backport, >non-issue, v7.4.0

#578 [ML] Consider redundancy as well as relevancy when selecting features
  include/maths/CDataFrameCategoryEncoder.h
  include/maths/CDataFrameUtils.h
  lib/core/CDataFrame.cc
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/CDataFrameCategoryEncoder.cc
  lib/maths/CDataFrameUtils.cc
  lib/maths/unittest/CDataFrameCategoryEncoderTest.cc
  lib/maths/unittest/CDataFrameCategoryEncoderTest.h
  lib/maths/unittest/CDataFrameUtilsTest.cc
Labels: :ml/DataFrameAnalysis, >enhancement, >non-issue, review, v7.4.0, v8.0.0

#590 [ML] Make predictions for rows missing the dependent variable value
  include/api/CDataFrameAnalyzer.h
  lib/api/CDataFrameAnalyzer.cc
  lib/api/CDataFrameBoostedTreeRunner.cc
  lib/api/unittest/CDataFrameAnalyzerTest.cc
  lib/api/unittest/CDataFrameAnalyzerTest.h
Labels: :ml/DataFrameAnalysis, >bug, >non-issue, review, v7.4.0, v8.0.0

#592 [7.4][ML] Consider redundancy as well as relevancy when selecting features
  include/maths/CDataFrameCategoryEncoder.h
  include/maths/CDataFrameUtils.h
  lib/core/CDataFrame.cc
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/CDataFrameCategoryEncoder.cc
  lib/maths/CDataFrameUtils.cc
  lib/maths/unittest/CDataFrameCategoryEncoderTest.cc
  lib/maths/unittest/CDataFrameCategoryEncoderTest.h
  lib/maths/unittest/CDataFrameUtilsTest.cc
Labels: >non-issue, backport, v7.4.0

#594 [7.4][ML] Make predictions for rows missing the dependent variable value
  include/api/CDataFrameAnalyzer.h
  lib/api/CDataFrameAnalyzer.cc
  lib/api/CDataFrameBoostedTreeRunner.cc
  lib/api/unittest/CDataFrameAnalyzerTest.cc
  lib/api/unittest/CDataFrameAnalyzerTest.h
Labels: >non-issue, backport, v7.4.0

#591 [ML] Wire category encoding into random forest training
  include/maths/CBoostedTreeFactory.h
  include/maths/CBoostedTreeImpl.h
  include/maths/CChecksum.h
  include/maths/CDataFrameCategoryEncoder.h
  include/maths/CDataFrameUtils.h
  lib/maths/CBoostedTree.cc
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/CChecksum.cc
  lib/maths/CDataFrameCategoryEncoder.cc
  lib/maths/CDataFrameUtils.cc
  lib/maths/Makefile
  lib/maths/unittest/CBoostedTreeTest.cc
  lib/maths/unittest/CBoostedTreeTest.h
  lib/maths/unittest/CDataFrameCategoryEncoderTest.cc
  lib/maths/unittest/CDataFrameCategoryEncoderTest.h
  lib/maths/unittest/CDataFrameUtilsTest.cc
  lib/maths/unittest/CDataFrameUtilsTest.h
Labels: :ml/DataFrameAnalysis, >non-issue, v7.4.0, v8.0.0

#596 [7.4][ML] Wire category encoding into boosted tree training
  include/maths/CBoostedTreeFactory.h
  include/maths/CBoostedTreeImpl.h
  include/maths/CChecksum.h
  include/maths/CDataFrameCategoryEncoder.h
  include/maths/CDataFrameUtils.h
  lib/maths/CBoostedTree.cc
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/CChecksum.cc
  lib/maths/CDataFrameCategoryEncoder.cc
  lib/maths/CDataFrameUtils.cc
  lib/maths/Makefile
  lib/maths/unittest/CBoostedTreeTest.cc
  lib/maths/unittest/CBoostedTreeTest.h
  lib/maths/unittest/CDataFrameCategoryEncoderTest.cc
  lib/maths/unittest/CDataFrameCategoryEncoderTest.h
  lib/maths/unittest/CDataFrameUtilsTest.cc
  lib/maths/unittest/CDataFrameUtilsTest.h
Labels: >non-issue, backport, v7.4.0

#595 [ML] Progress monitoring for regression model training
  include/maths/CBoostedTree.h
  include/maths/CBoostedTreeFactory.h
  include/maths/CDataFrameRegressionModel.h
  lib/api/CDataFrameBoostedTreeRunner.cc
  lib/api/unittest/CDataFrameAnalyzerTest.cc
  lib/maths/CBoostedTree.cc
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/CDataFrameRegressionModel.cc
  lib/maths/unittest/CBoostedTreeTest.cc
  lib/maths/unittest/CBoostedTreeTest.h
Labels: :ml/DataFrameAnalysis, >enhancement, >non-issue, review, v7.4.0, v8.0.0

#599 [7.4][ML] Progress monitoring for regression model training
  include/maths/CBoostedTree.h
  include/maths/CBoostedTreeFactory.h
  include/maths/CDataFrameRegressionModel.h
  lib/api/CDataFrameBoostedTreeRunner.cc
  lib/api/unittest/CDataFrameAnalyzerTest.cc
  lib/maths/CBoostedTree.cc
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/CDataFrameRegressionModel.cc
  lib/maths/unittest/CBoostedTreeTest.cc
  lib/maths/unittest/CBoostedTreeTest.h
Labels: >non-issue, backport, v7.4.0

#602 [ML] Handle unseen categories in encoding
  include/core/CDataFrame.h
  include/maths/CDataFrameCategoryEncoder.h
  lib/api/CDataFrameAnalyzer.cc
  lib/core/CDataFrame.cc
  lib/maths/CDataFrameCategoryEncoder.cc
  lib/maths/unittest/CBoostedTreeTest.cc
  lib/maths/unittest/CDataFrameCategoryEncoderTest.cc
  lib/maths/unittest/CDataFrameCategoryEncoderTest.h
  lib/maths/unittest/CDataFrameUtilsTest.cc
Labels: :ml/DataFrameAnalysis, >bug, >non-issue, review, v7.4.0, v8.0.0

#601 Rename memory usage estimation result fields.
  include/api/CDataFrameAnalysisRunner.h
  include/api/CDataFrameAnalysisSpecification.h
  lib/api/CDataFrameAnalysisRunner.cc
  lib/api/CMemoryUsageEstimationResultJsonWriter.cc
  lib/api/unittest/CDataFrameAnalysisRunnerTest.cc
  lib/api/unittest/CMemoryUsageEstimationResultJsonWriterTest.cc
Labels: :ml, >refactoring, v7.4.0, v8.0.0

#605 [7.x] Rename expected_memory_usage_with_one_partition to expected_memory_without_disk (#601)
  include/api/CDataFrameAnalysisRunner.h
  include/api/CDataFrameAnalysisSpecification.h
  lib/api/CDataFrameAnalysisRunner.cc
  lib/api/CMemoryUsageEstimationResultJsonWriter.cc
  lib/api/unittest/CDataFrameAnalysisRunnerTest.cc
  lib/api/unittest/CMemoryUsageEstimationResultJsonWriterTest.cc
Labels: :ml, >refactoring, backport, v7.4.0

#603 [7.4][ML] Handle unseen categories in encoding
  include/core/CDataFrame.h
  include/maths/CDataFrameCategoryEncoder.h
  lib/api/CDataFrameAnalyzer.cc
  lib/core/CDataFrame.cc
  lib/maths/CDataFrameCategoryEncoder.cc
  lib/maths/unittest/CBoostedTreeTest.cc
  lib/maths/unittest/CDataFrameCategoryEncoderTest.cc
  lib/maths/unittest/CDataFrameCategoryEncoderTest.h
  lib/maths/unittest/CDataFrameUtilsTest.cc
Labels: >non-issue, backport, v7.4.0

#600 [ML] Ignore rows which are missing the target value when mean target encoding
  lib/maths/CDataFrameUtils.cc
  lib/maths/unittest/CDataFrameUtilsTest.cc
  lib/maths/unittest/CDataFrameUtilsTest.h
Labels: :ml/DataFrameAnalysis, >bug, >non-issue, review, v7.4.0, v8.0.0

#598 [ML] Rename outlier detection method values
  docs/CHANGELOG.asciidoc
  lib/api/CDataFrameOutliersRunner.cc
  lib/api/unittest/CDataFrameAnalyzerTest.cc
Labels: :ml, :ml/DataFrameAnalysis, >bug, v7.4.0, v8.0.0

#606 [7.x][ML] Rename outlier detection method values (#598)
  docs/CHANGELOG.asciidoc
  lib/api/CDataFrameOutliersRunner.cc
  lib/api/unittest/CDataFrameAnalyzerTest.cc
Labels: :ml, :ml/DataFrameAnalysis, >bug, backport, v7.4.0

#608 [7.4][ML] Ignore rows which are missing the target value when mean target encoding
  lib/maths/CDataFrameUtils.cc
  lib/maths/unittest/CDataFrameUtilsTest.cc
  lib/maths/unittest/CDataFrameUtilsTest.h
Labels: >non-issue, backport, v7.4.0

#609 [ML] Detect feature data types and refine candidate splits in boosted tree training based on type
  include/maths/CBasicStatistics.h
  include/maths/CBoostedTreeFactory.h
  include/maths/CBoostedTreeImpl.h
  include/maths/CDataFrameUtils.h
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/CDataFrameUtils.cc
  lib/maths/unittest/CBoostedTreeTest.cc
  lib/maths/unittest/CBoostedTreeTest.h
  lib/maths/unittest/CDataFrameUtilsTest.cc
  lib/maths/unittest/CDataFrameUtilsTest.h
Labels: :ml/DataFrameAnalysis, >enhancement, >non-issue, review, v7.4.0, v8.0.0

#612 [ML] Add some missing boosted tree state initialisation
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/unittest/CBoostedTreeTest.cc
Labels: :ml/DataFrameAnalysis, >bug, >non-issue, review, v7.4.0, v8.0.0

#604 [ML] Improve hyperparameter optimisation stability
  include/maths/CBayesianOptimisation.h
  lib/maths/CBayesianOptimisation.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/unittest/CBoostedTreeTest.cc
Labels: :ml/DataFrameAnalysis, >enhancement, >non-issue, review, v7.4.0, v8.0.0

#613 [7.4][ML] Add some missing boosted tree state initialisation
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/unittest/CBoostedTreeTest.cc
Labels: >non-issue, backport, v7.4.0

#610 [7.4][ML] Detect feature data types and refine candidate splits in boosted tree training based on type
  include/maths/CBasicStatistics.h
  include/maths/CBoostedTreeFactory.h
  include/maths/CBoostedTreeImpl.h
  include/maths/CDataFrameUtils.h
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/CDataFrameUtils.cc
  lib/maths/unittest/CBoostedTreeTest.cc
  lib/maths/unittest/CBoostedTreeTest.h
  lib/maths/unittest/CDataFrameUtilsTest.cc
  lib/maths/unittest/CDataFrameUtilsTest.h
Labels: >non-issue, backport, v7.4.0

#615 [7.4][ML] Improve hyperparameter optimisation stability
  include/maths/CBayesianOptimisation.h
  lib/maths/CBayesianOptimisation.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/unittest/CBoostedTreeTest.cc
Labels: >non-issue, backport, v7.4.0

#614 [ML] Check whether the splits will change before recomputing in loop building the regression forest
  include/maths/CBoostedTree.h
  include/maths/CBoostedTreeImpl.h
  lib/api/unittest/CDataFrameAnalyzerTest.cc
  lib/maths/CBoostedTree.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/unittest/CBoostedTreeTest.cc
Labels: :ml/DataFrameAnalysis, >enhancement, >non-issue, review, v7.4.0, v8.0.0

#617 [ML] Tag results which were used for training
  include/maths/CBoostedTree.h
  include/maths/CBoostedTreeImpl.h
  include/maths/CDataFrameRegressionModel.h
  lib/api/CDataFrameBoostedTreeRunner.cc
  lib/api/CDataFrameOutliersRunner.cc
  lib/api/unittest/CDataFrameAnalyzerTest.cc
  lib/maths/CBoostedTree.cc
  lib/maths/CBoostedTreeImpl.cc
Labels: :ml/DataFrameAnalysis, >enhancement, >non-issue, review, v7.4.0, v8.0.0

#618 [7.x][ML] Tag results which were used for training (#617)
  include/maths/CBoostedTree.h
  include/maths/CBoostedTreeImpl.h
  include/maths/CDataFrameRegressionModel.h
  lib/api/CDataFrameBoostedTreeRunner.cc
  lib/api/CDataFrameOutliersRunner.cc
  lib/api/unittest/CDataFrameAnalyzerTest.cc
  lib/maths/CBoostedTree.cc
  lib/maths/CBoostedTreeImpl.cc
Labels: :ml, :ml/DataFrameAnalysis, >enhancement, >non-issue, backport, v7.4.0

#616 [7.4][ML] Check whether the splits will change before recomputing in loop building the regression forest
  include/maths/CBoostedTree.h
  include/maths/CBoostedTreeImpl.h
  lib/api/unittest/CDataFrameAnalyzerTest.cc
  lib/maths/CBoostedTree.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/unittest/CBoostedTreeTest.cc
Labels: >non-issue, backport, v7.4.0

#607 [ML] Instrument the regression code for memory usage and training run time
  bin/data_frame_analyzer/Main.cc
  include/api/CDataFrameBoostedTreeRunner.h
  include/core/CProgramCounters.h
  include/maths/CBayesianOptimisation.h
  include/maths/CBoostedTree.h
  include/maths/CBoostedTreeFactory.h
  include/maths/CBoostedTreeImpl.h
  include/maths/CDataFrameRegressionModel.h
  lib/api/CDataFrameBoostedTreeRunner.cc
  lib/api/CDataFrameOutliersRunner.cc
  lib/api/unittest/CDataFrameAnalyzerTest.cc
  lib/maths/CBayesianOptimisation.cc
  lib/maths/CBoostedTree.cc
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/CDataFrameRegressionModel.cc
  lib/maths/unittest/CBoostedTreeTest.cc
  lib/maths/unittest/CBoostedTreeTest.h
  lib/maths/unittest/COutliersTest.cc
Labels: :ml/DataFrameAnalysis, >enhancement, >non-issue, review, v7.4.0, v8.0.0

#619 [7.4][ML] Instrument the regression code for memory usage and training run time
  bin/data_frame_analyzer/Main.cc
  include/api/CDataFrameBoostedTreeRunner.h
  include/core/CProgramCounters.h
  include/maths/CBayesianOptimisation.h
  include/maths/CBoostedTree.h
  include/maths/CBoostedTreeFactory.h
  include/maths/CBoostedTreeImpl.h
  include/maths/CDataFrameRegressionModel.h
  lib/api/CDataFrameBoostedTreeRunner.cc
  lib/api/CDataFrameOutliersRunner.cc
  lib/api/unittest/CDataFrameAnalyzerTest.cc
  lib/maths/CBayesianOptimisation.cc
  lib/maths/CBoostedTree.cc
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/CDataFrameRegressionModel.cc
  lib/maths/unittest/CBoostedTreeTest.cc
  lib/maths/unittest/CBoostedTreeTest.h
  lib/maths/unittest/COutliersTest.cc
Labels: >non-issue, backport, v7.4.0

#620 [ML] Log stats at info on exit from the data_frame_analyzer command
  bin/data_frame_analyzer/Main.cc
Labels: :ml/DataFrameAnalysis, >non-issue, review, v7.4.0, v8.0.0

#621 [7.4][ML] Log run stats at info on exit
  bin/data_frame_analyzer/Main.cc
Labels: >non-issue, backport, v7.4.0

#626 [ML] Ensure DF analytics reports progress after finishing
  lib/api/CDataFrameAnalyzer.cc
Labels: :ml, :ml/DataFrameAnalysis, >non-issue, v7.4.0, v7.5.0, v8.0.0

#628 [7.4][ML] Ensure DF analytics reports progress after finishing (#626)
  lib/api/CDataFrameAnalyzer.cc
Labels: :ml, :ml/DataFrameAnalysis, >non-issue, backport, v7.4.0

#627 [7.x][ML] Ensure DF analytics reports progress after finishing (#626)
  lib/api/CDataFrameAnalyzer.cc
Labels: :ml, :ml/DataFrameAnalysis, >non-issue, backport, v7.5.0

#622 [ML] Boosted tree training performance improvements
  docs/CHANGELOG.asciidoc
  include/maths/CBoostedTree.h
  include/maths/CBoostedTreeImpl.h
  include/maths/CDataFrameCategoryEncoder.h
  lib/maths/CBoostedTree.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/CDataFrameCategoryEncoder.cc
Labels: :ml/DataFrameAnalysis, >enhancement, review, v7.5.0, v8.0.0
