Repository elastic/ml-cpp, pull requests merged in 2019-11, with the labels that each got.

#802 [6.8][ML] Make the ML native code more ".app"-like on macOS
  3rd_party/3rd_party.sh
  bin/autoconfig/Makefile
  bin/autodetect/Makefile
  bin/categorize/Makefile
  bin/controller/Makefile
  bin/normalize/Makefile
  dev-tools/strip_binaries.sh
  devbin/analyze_test/Makefile
  docs/CHANGELOG.asciidoc
  include/core/CLogger.h
  include/core/CResourceLocator.h
  lib/core/CLogger.cc
  lib/core/CResourceLocator.cc
  lib/core/Makefile
  lib/core/log4cxx.properties
  lib/core/unittest/CResourceLocatorTest.cc
  lib/core/unittest/CResourceLocatorTest.h
  mk/defines.mk
  mk/dynamiclib.mk
  mk/linux.mk
  mk/linux_crosscompile_macosx.mk
  mk/macosx.mk
  mk/make_info_plist.sh
  mk/rules.mk
  mk/staticlib.mk
  mk/stdapp.mk
  mk/stdcpptest.mk
  mk/stddevapp.mk
  mk/windows.mk
  set_env.sh
Labels: backport

#801 [ML] Run ES integration tests on C++ PRs
  dev-tools/jenkins_ci.sh
  dev-tools/run_es_tests.sh
Labels: :ml, >test, v6.8.5, v7.5.0, v7.6.0, v8.0.0

#804 [7.x][ML] Run ES integration tests on C++ PRs
  dev-tools/jenkins_ci.sh
  dev-tools/run_es_tests.sh
Labels: >test, backport

#805 [7.5][ML] Run ES integration tests on C++ PRs
  dev-tools/jenkins_ci.sh
  dev-tools/run_es_tests.sh
Labels: >test, backport

#806 [6.8][ML] Run ES integration tests on C++ PRs
  dev-tools/jenkins_ci.sh
  dev-tools/run_es_tests.sh
Labels: >test, backport

#807 [ML] Move CSV line parser to core library
  bin/data_frame_analyzer/Main.cc
  bin/normalize/Main.cc
  include/api/CBaseTokenListDataTyper.h
  include/api/CCsvInputParser.h
  include/core/CCsvLineParser.h
  lib/api/CCsvInputParser.cc
  lib/api/unittest/CCsvInputParserTest.cc
  lib/api/unittest/CResultNormalizerTest.cc
  lib/core/CCsvLineParser.cc
  lib/core/Makefile
  lib/core/unittest/CCsvLineParserTest.cc
  lib/core/unittest/Makefile
Labels: :ml, >refactoring, v7.6.0, v8.0.0

#808 [7.x][ML] Move CSV line parser to core library
  bin/data_frame_analyzer/Main.cc
  bin/normalize/Main.cc
  include/api/CBaseTokenListDataTyper.h
  include/api/CCsvInputParser.h
  include/core/CCsvLineParser.h
  lib/api/CCsvInputParser.cc
  lib/api/unittest/CCsvInputParserTest.cc
  lib/api/unittest/CResultNormalizerTest.cc
  lib/core/CCsvLineParser.cc
  lib/core/Makefile
  lib/core/unittest/CCsvLineParserTest.cc
  lib/core/unittest/Makefile
Labels: >refactoring, backport

#810 [ML] Move and rename categorization classes
  bin/autodetect/Main.cc
  bin/categorize/Main.cc
  include/api/CFieldDataCategorizer.h
  include/api/CJsonOutputWriter.h
  include/model/CBaseTokenListDataCategorizer.h
  include/model/CCategoryExamplesCollector.h
  include/model/CDataCategorizer.h
  include/model/CTokenListCategory.h
  include/model/CTokenListDataCategorizer.h
  include/model/CTokenListReverseSearchCreator.h
  include/model/CTokenListReverseSearchCreatorIntf.h
  lib/api/CBenchMarker.cc
  lib/api/CDataTyper.cc
  lib/api/CFieldConfig.cc
  lib/api/CFieldDataCategorizer.cc
  lib/api/CJsonOutputWriter.cc
  lib/api/Makefile.first
  lib/api/dump_state/Main.cc
  lib/api/unittest/CBaseTokenListDataTyperTest.cc
  lib/api/unittest/CCsvOutputWriterTest.cc
  lib/api/unittest/CFieldDataCategorizerTest.cc
  lib/api/unittest/CJsonOutputWriterTest.cc
  lib/api/unittest/COutputChainerTest.cc
  lib/api/unittest/CPersistenceManagerTest.cc
  lib/api/unittest/CRestorePreviousStateTest.cc
  lib/api/unittest/CSingleStreamDataAdderTest.cc
  lib/api/unittest/CTokenListDataTyperTest.cc
  lib/api/unittest/Makefile
  lib/model/CBaseTokenListDataCategorizer.cc
  lib/model/CCategoryExamplesCollector.cc
  lib/model/CDataCategorizer.cc
  lib/model/CTokenListCategory.cc
  lib/model/CTokenListReverseSearchCreator.cc
  lib/model/CTokenListReverseSearchCreatorIntf.cc
  lib/model/Makefile
  lib/model/unittest/CBaseTokenListDataCategorizerTest.cc
  lib/model/unittest/CCategoryExamplesCollectorTest.cc
  lib/model/unittest/CEventRateAnomalyDetectorTest.cc
  lib/model/unittest/CMetricAnomalyDetectorTest.cc
  lib/model/unittest/CTokenListDataCategorizerTest.cc
  lib/model/unittest/CTokenListReverseSearchCreatorTest.cc
  lib/model/unittest/Makefile
Labels: :ml, >refactoring, v7.6.0, v8.0.0

#812 [7.x][ML] Move and rename categorization classes
  bin/autodetect/Main.cc
  bin/categorize/Main.cc
  include/api/CFieldDataCategorizer.h
  include/api/CJsonOutputWriter.h
  include/model/CBaseTokenListDataCategorizer.h
  include/model/CCategoryExamplesCollector.h
  include/model/CDataCategorizer.h
  include/model/CTokenListCategory.h
  include/model/CTokenListDataCategorizer.h
  include/model/CTokenListReverseSearchCreator.h
  include/model/CTokenListReverseSearchCreatorIntf.h
  lib/api/CBenchMarker.cc
  lib/api/CDataTyper.cc
  lib/api/CFieldConfig.cc
  lib/api/CFieldDataCategorizer.cc
  lib/api/CJsonOutputWriter.cc
  lib/api/Makefile.first
  lib/api/dump_state/Main.cc
  lib/api/unittest/CBaseTokenListDataTyperTest.cc
  lib/api/unittest/CCsvOutputWriterTest.cc
  lib/api/unittest/CFieldDataCategorizerTest.cc
  lib/api/unittest/CJsonOutputWriterTest.cc
  lib/api/unittest/COutputChainerTest.cc
  lib/api/unittest/CPersistenceManagerTest.cc
  lib/api/unittest/CRestorePreviousStateTest.cc
  lib/api/unittest/CSingleStreamDataAdderTest.cc
  lib/api/unittest/CTokenListDataTyperTest.cc
  lib/api/unittest/Makefile
  lib/model/CBaseTokenListDataCategorizer.cc
  lib/model/CCategoryExamplesCollector.cc
  lib/model/CDataCategorizer.cc
  lib/model/CTokenListCategory.cc
  lib/model/CTokenListReverseSearchCreator.cc
  lib/model/CTokenListReverseSearchCreatorIntf.cc
  lib/model/Makefile
  lib/model/unittest/CBaseTokenListDataCategorizerTest.cc
  lib/model/unittest/CCategoryExamplesCollectorTest.cc
  lib/model/unittest/CEventRateAnomalyDetectorTest.cc
  lib/model/unittest/CMetricAnomalyDetectorTest.cc
  lib/model/unittest/CTokenListDataCategorizerTest.cc
  lib/model/unittest/CTokenListReverseSearchCreatorTest.cc
  lib/model/unittest/Makefile
Labels: >refactoring, backport

#814 [ML] Handle upgrade state to 7.5 to account for sparse count modelling changes
  lib/model/CEventRateModel.cc
  lib/model/CIndividualModel.cc
  lib/model/CMetricModel.cc
Labels: :ml, >non-issue, review, v7.5.0, v7.6.0, v8.0.0

#809 [ML] add geo point formatting string for actual|typical
  docs/CHANGELOG.asciidoc
  lib/api/CJsonOutputWriter.cc
  lib/api/unittest/CJsonOutputWriterTest.cc
Labels: :ml, >enhancement, v7.6.0, v8.0.0

#817 [ML] add geo point formatting string for actual|typical (#809)
  docs/CHANGELOG.asciidoc
  lib/api/CJsonOutputWriter.cc
  lib/api/unittest/CJsonOutputWriterTest.cc
Labels: :ml, >enhancement, backport

#815 [7.6][ML] Handle upgrade state to 7.5 to account for sparse count modelling changes
  lib/model/CEventRateModel.cc
  lib/model/CIndividualModel.cc
  lib/model/CMetricModel.cc
Labels: >non-issue, backport, v7.6.0

#816 [7.5][ML] Handle upgrade state to 7.5 to account for sparse count modelling changes
  lib/model/CEventRateModel.cc
  lib/model/CIndividualModel.cc
  lib/model/CMetricModel.cc
Labels: >non-issue, backport, v7.5.0

#819 [ML] Downgrade verbose test logging to trace
  lib/core/unittest/CMemoryUsageTest.cc
  lib/maths/unittest/CBoundingBoxTest.cc
  lib/maths/unittest/CGammaRateConjugateTest.cc
  lib/maths/unittest/CInformationCriteriaTest.cc
  lib/maths/unittest/CIntegerToolsTest.cc
  lib/maths/unittest/CKMeansTest.cc
  lib/maths/unittest/CKdTreeTest.cc
  lib/maths/unittest/CLogNormalMeanPrecConjugateTest.cc
  lib/maths/unittest/CMixtureDistributionTest.cc
  lib/maths/unittest/CMultimodalPriorTest.cc
  lib/maths/unittest/CNaturalBreaksClassifierTest.cc
  lib/maths/unittest/CNormalMeanPrecConjugateTest.cc
  lib/maths/unittest/COneOfNPriorTest.cc
  lib/maths/unittest/CPoissonMeanConjugateTest.cc
  lib/maths/unittest/CSeasonalComponentTest.cc
  lib/maths/unittest/CTimeSeriesDecompositionTest.cc
  lib/maths/unittest/CToolsTest.cc
  lib/maths/unittest/testfiles/distorted_periodic.csv
  lib/model/unittest/CAnomalyScoreTest.cc
  lib/model/unittest/CHierarchicalResultsTest.cc
  lib/model/unittest/CSampleQueueTest.cc
Labels: :ml, >non-issue, >refactoring, >test, review, v7.6.0, v8.0.0

#823 [7.6][ML] Downgrade verbose test logging to trace
  lib/core/unittest/CMemoryUsageTest.cc
  lib/maths/unittest/CBoundingBoxTest.cc
  lib/maths/unittest/CGammaRateConjugateTest.cc
  lib/maths/unittest/CInformationCriteriaTest.cc
  lib/maths/unittest/CIntegerToolsTest.cc
  lib/maths/unittest/CKMeansTest.cc
  lib/maths/unittest/CKdTreeTest.cc
  lib/maths/unittest/CLogNormalMeanPrecConjugateTest.cc
  lib/maths/unittest/CMixtureDistributionTest.cc
  lib/maths/unittest/CMultimodalPriorTest.cc
  lib/maths/unittest/CNaturalBreaksClassifierTest.cc
  lib/maths/unittest/CNormalMeanPrecConjugateTest.cc
  lib/maths/unittest/COneOfNPriorTest.cc
  lib/maths/unittest/CPoissonMeanConjugateTest.cc
  lib/maths/unittest/CSeasonalComponentTest.cc
  lib/maths/unittest/CTimeSeriesDecompositionTest.cc
  lib/maths/unittest/CToolsTest.cc
  lib/maths/unittest/testfiles/distorted_periodic.csv
  lib/model/unittest/CAnomalyScoreTest.cc
  lib/model/unittest/CHierarchicalResultsTest.cc
  lib/model/unittest/CSampleQueueTest.cc
Labels: >non-issue, backport, v7.6.0

#822 [6.8][ML] Fix restore from checkpoint damaging seasonality modelling for anomaly detection
  docs/CHANGELOG.asciidoc
  include/maths/CSeasonalTime.h
  lib/maths/CSeasonalTime.cc
  lib/maths/unittest/CSeasonalTimeTest.cc
  lib/maths/unittest/CSeasonalTimeTest.h
  lib/maths/unittest/Main.cc
  lib/maths/unittest/Makefile
Labels: backport, review, v6.8.6

#821 [ML] Fix restore from checkpoint damaging seasonality modelling for anomaly detection
  docs/CHANGELOG.asciidoc
  include/maths/CSeasonalTime.h
  lib/maths/CSeasonalTime.cc
  lib/maths/unittest/CSeasonalTimeTest.cc
  lib/maths/unittest/Makefile
Labels: :ml, >bug, v6.8.5, v7.5.0, v7.6.0, v8.0.0

#824 [7.6][ML] Fix restore from checkpoint damaging seasonality modelling for anomaly detection
  docs/CHANGELOG.asciidoc
  include/maths/CSeasonalTime.h
  lib/maths/CSeasonalTime.cc
  lib/maths/unittest/CSeasonalTimeTest.cc
  lib/maths/unittest/Makefile
Labels: backport, v7.6.0

#826 [7.5][ML] Fix restore from checkpoint damaging seasonality modelling for anomaly detection
  docs/CHANGELOG.asciidoc
  include/maths/CSeasonalTime.h
  lib/maths/CSeasonalTime.cc
  lib/maths/unittest/CSeasonalTimeTest.cc
  lib/maths/unittest/CSeasonalTimeTest.h
  lib/maths/unittest/Main.cc
  lib/maths/unittest/Makefile
Labels: backport, v7.5.0

#811 [ML] Stochastic derivatives for tree training
  docs/CHANGELOG.asciidoc
  include/api/CDataFrameTrainBoostedTreeRunner.h
  include/core/CLoopProgress.h
  include/maths/CBoostedTree.h
  include/maths/CBoostedTreeFactory.h
  include/maths/CBoostedTreeImpl.h
  include/maths/CDataFrameRegressionModel.h
  include/maths/CDataFrameUtils.h
  lib/api/CDataFrameTrainBoostedTreeRunner.cc
  lib/api/unittest/CDataFrameAnalysisSpecificationTest.cc
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
  lib/core/CLoopProgress.cc
  lib/maths/CBoostedTree.cc
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/CDataFrameUtils.cc
  lib/maths/unittest/CBoostedTreeTest.cc
  lib/maths/unittest/CDataFrameUtilsTest.cc
Labels: :ml/DataFrameAnalysis, >enhancement, review, v7.6.0, v8.0.0

#828 [ML] Remove CI parallelism hack
  dev-tools/docker/docker_entrypoint.sh
Labels: :ml, >build, >non-issue, v7.5.1, v7.6.0, v8.0.0

#830 [ML] Adjust background interval in persistence test
  lib/api/unittest/CPersistenceManagerTest.cc
Labels: :ml, >test, v7.6.0, v8.0.0

#831 [7.x][ML] Adjust background interval in persistence test
  lib/api/unittest/CPersistenceManagerTest.cc
Labels: >test, backport

#833 [7.5][ML] Remove CI parallelism hack
  dev-tools/docker/docker_entrypoint.sh
Labels: >build, >non-issue, backport

#832 [7.x][ML] Remove CI parallelism hack
  dev-tools/docker/docker_entrypoint.sh
Labels: >build, >non-issue, backport

#799 Remove duplicated code.
  bin/data_frame_analyzer/Main.cc
Labels: :ml, >non-issue, v7.6.0, v8.0.0

#835 [7.x] Remove duplicated code (#799)
  bin/data_frame_analyzer/Main.cc
Labels: :ml, >non-issue, backport

#837 [ML]Documented developing, building and running the `ml-cpp` project
  README.md
  build-setup/macos.md
Labels: :ml, >docs, >non-issue, review, v8.0.0

#818 Emit prediction_probability field alongside prediction field in ml results.
  docs/CHANGELOG.asciidoc
  include/api/CDataFrameTrainBoostedTreeClassifierRunner.h
  lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
  lib/api/unittest/CDataFrameTrainBoostedTreeClassifierRunnerTest.cc
  lib/api/unittest/Makefile
Labels: :ml/DataFrameAnalysis, >enhancement, v7.6.0, v8.0.0

#840 [ML] Remove unary_function/binary_function and old-style binders
  include/api/COutputHandler.h
  include/core/CCompressedDictionary.h
  include/core/CHashing.h
  include/core/CStringCache.h
  include/core/CWordDictionary.h
  include/maths/CBasicStatistics.h
  include/maths/CEqualWithTolerance.h
  include/maths/CMathsFuncs.h
  lib/core/CMemoryUsage.cc
  lib/maths/CGammaRateConjugate.cc
  lib/maths/CKMostCorrelated.cc
  lib/maths/CPrior.cc
  lib/maths/unittest/CIntegrationTest.cc
  lib/maths/unittest/TestUtils.cc
  lib/model/CTokenListCategory.cc
Labels: :ml, >refactoring, v7.6.0, v8.0.0

#839 [ML] Re-added Boost program options to model_extractor Makefile
  devbin/model_extractor/Makefile
Labels: :ml, >non-issue, review, v8.0.0

#841 [7.x][ML] Remove unary_function/binary_function and old-style binders
  include/api/COutputHandler.h
  include/core/CCompressedDictionary.h
  include/core/CHashing.h
  include/core/CStringCache.h
  include/core/CWordDictionary.h
  include/maths/CBasicStatistics.h
  include/maths/CEqualWithTolerance.h
  include/maths/CMathsFuncs.h
  lib/core/CMemoryUsage.cc
  lib/maths/CGammaRateConjugate.cc
  lib/maths/CKMostCorrelated.cc
  lib/maths/CPrior.cc
  lib/maths/unittest/CIntegrationTest.cc
  lib/maths/unittest/TestUtils.cc
  lib/model/CTokenListCategory.cc
Labels: >refactoring, backport

#844 [ML] Use empty base optimization with multiple inheritance
  docs/CHANGELOG.asciidoc
  include/maths/CBasicStatistics.h
  include/maths/CTimeSeriesDecomposition.h
  include/maths/ImportExport.h
  include/maths/ProbabilityAggregators.h
  lib/maths/CBjkstUniqueValues.cc
Labels: :ml, >enhancement, v7.6.0, v8.0.0

#846 [ML] Use empty base optimization with multiple inheritance
  docs/CHANGELOG.asciidoc
  include/maths/CBasicStatistics.h
  include/maths/CTimeSeriesDecomposition.h
  include/maths/ImportExport.h
  include/maths/ProbabilityAggregators.h
  lib/maths/CBjkstUniqueValues.cc
Labels: backport

#847 [ML] Attend to some clang-tidy suggestions
  include/api/CCsvOutputWriter.h
  include/api/CJsonOutputWriter.h
Labels: :ml, >non-issue, >refactoring, review, v7.6.0, v8.0.0

#848 [ML][7.6] Tidied up output writer classes (#847)
  include/api/CCsvOutputWriter.h
  include/api/CJsonOutputWriter.h
Labels: :ml, >non-issue, >refactoring, backport, v7.6.0

#843 [ML] Adjust Eigen linear algebra wrapper constructors
  include/maths/CKdTree.h
  include/maths/CLinearAlgebraEigen.h
Labels: :ml, >refactoring, v7.6.0, v8.0.0

#853 [7.6][ML] Tidy up test analysis specification writing
  include/api/CDataFrameOutliersRunner.h
  include/api/CDataFrameTrainBoostedTreeClassifierRunner.h
  include/api/CDataFrameTrainBoostedTreeRegressionRunner.h
  include/api/CDataFrameTrainBoostedTreeRunner.h
  include/test/CDataFrameAnalysisSpecificationFactory.h
  lib/api/CDataFrameAnalysisSpecificationJsonWriter.cc
  lib/api/CDataFrameOutliersRunner.cc
  lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
  lib/api/CDataFrameTrainBoostedTreeRegressionRunner.cc
  lib/api/CDataFrameTrainBoostedTreeRunner.cc
  lib/api/unittest/CDataFrameAnalysisRunnerTest.cc
  lib/test/CDataFrameAnalysisSpecificationFactory.cc
Labels: >non-issue, backport, v7.6.0

#854 [7.x][ML] Adjust Eigen linear algebra wrapper constructors
  include/maths/CKdTree.h
  include/maths/CLinearAlgebraEigen.h
Labels: >refactoring, backport

#852 [ML] Fix memory errors picked up by Valgrind
  docs/CHANGELOG.asciidoc
  include/api/CCsvOutputWriter.h
  include/api/CJsonOutputWriter.h
  lib/maths/CSignal.cc
Labels: :ml, >bug, review, v7.6.0, v8.0.0

#855 [ML] Add unit test checks for new hyperparameters in supervised learning
  include/api/CDataFrameTrainBoostedTreeRunner.h
  include/maths/CBoostedTree.h
  include/maths/CBoostedTreeHyperparameters.h
  include/maths/CBoostedTreeImpl.h
  lib/api/CDataFrameTrainBoostedTreeRunner.cc
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
  lib/maths/CBoostedTree.cc
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/CBoostedTreeHyperparameters.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/Makefile
Labels: :ml, >bug, >non-issue, review, v7.6.0, v8.0.0

#856 [7.6][ML] Stochastic derivatives for boosted tree training
  docs/CHANGELOG.asciidoc
  include/api/CDataFrameTrainBoostedTreeRunner.h
  include/core/CLoopProgress.h
  include/maths/CBoostedTree.h
  include/maths/CBoostedTreeFactory.h
  include/maths/CBoostedTreeImpl.h
  include/maths/CDataFrameRegressionModel.h
  include/maths/CDataFrameUtils.h
  lib/api/CDataFrameTrainBoostedTreeRunner.cc
  lib/api/unittest/CDataFrameAnalysisSpecificationTest.cc
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
  lib/core/CLoopProgress.cc
  lib/maths/CBoostedTree.cc
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/CDataFrameUtils.cc
  lib/maths/unittest/CBoostedTreeTest.cc
  lib/maths/unittest/CDataFrameUtilsTest.cc
Labels: backport, v7.6.0

#858 [ML][7.6] Fix memory errors picked up by Valgrind (#852)
  docs/CHANGELOG.asciidoc
  include/api/CCsvOutputWriter.h
  include/api/CJsonOutputWriter.h
  lib/maths/CSignal.cc
Labels: :ml, >bug, backport, v7.6.0

#838 [7.x] Emit prediction_probability field alongside prediction field in ml results. (#818)
  docs/CHANGELOG.asciidoc
  include/api/CDataFrameTrainBoostedTreeClassifierRunner.h
  lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
  lib/api/unittest/CDataFrameTrainBoostedTreeClassifierRunnerTest.cc
  lib/api/unittest/Makefile
Labels: :ml/DataFrameAnalysis, >enhancement, backport

#860 [7.6][ML] Add unit test checks for new hyperparameters in supervised learning
  include/api/CDataFrameTrainBoostedTreeRunner.h
  include/maths/CBoostedTree.h
  include/maths/CBoostedTreeHyperparameters.h
  include/maths/CBoostedTreeImpl.h
  lib/api/CDataFrameTrainBoostedTreeRunner.cc
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
  lib/maths/CBoostedTree.cc
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/CBoostedTreeHyperparameters.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/Makefile
Labels: :ml, >non-issue, backport, v7.6.0

#862 [ML] Updates to STYLEGUIDE.md about explicit "if" statements.
  STYLEGUIDE.md
Labels: :ml, >docs, >non-issue, review, v8.0.0

#861 Blacklist a number of prediction field names.
  docs/CHANGELOG.asciidoc
  lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
  lib/api/CDataFrameTrainBoostedTreeRegressionRunner.cc
  lib/api/unittest/CDataFrameTrainBoostedTreeClassifierRunnerTest.cc
  lib/api/unittest/CDataFrameTrainBoostedTreeRegressionRunnerTest.cc
  lib/api/unittest/Makefile
Labels: :ml, >bug, v7.6.0, v8.0.0
