Repository elastic/ml-cpp, pull requests merged in 2019-10, with the labels that each got.

#698 [ML] Depth based regularisation for boosted tree training
  docs/CHANGELOG.asciidoc
  include/maths/CBoostedTree.h
  include/maths/CBoostedTreeFactory.h
  include/maths/CBoostedTreeImpl.h
  include/maths/CDataFrameCategoryEncoder.h
  lib/api/CDataFrameBoostedTreeRunner.cc
  lib/api/unittest/CDataFrameAnalyzerTest.cc
  lib/maths/CBoostedTree.cc
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/CDataFrameCategoryEncoder.cc
  lib/maths/unittest/CBoostedTreeTest.cc
  lib/maths/unittest/CBoostedTreeTest.h
Labels: :ml/DataFrameAnalysis, >enhancement, review, v7.5.0, v8.0.0

#709 [ML] Trap out-of-bounds read initialising boosted tree training
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/unittest/CBoostedTreeTest.cc
  lib/maths/unittest/CBoostedTreeTest.h
Labels: :ml/DataFrameAnalysis, >non-issue, v7.5.0, v8.0.0

#704 [7.4][ML] Make the ML native code more ".app"-like on macOS
  3rd_party/3rd_party.sh
  bin/autoconfig/Makefile
  bin/autodetect/Makefile
  bin/categorize/Makefile
  bin/controller/Makefile
  bin/data_frame_analyzer/Makefile
  bin/normalize/Makefile
  dev-tools/strip_binaries.sh
  devbin/analyze_test/Makefile
  docs/CHANGELOG.asciidoc
  include/core/CLogger.h
  include/core/CResourceLocator.h
  lib/core/CLogger.cc
  lib/core/CResourceLocator.cc
  lib/core/Makefile
  lib/core/log4cxx.properties
  lib/core/unittest/CResourceLocatorTest.cc
  lib/core/unittest/CResourceLocatorTest.h
  mk/defines.mk
  mk/dynamiclib.mk
  mk/linux.mk
  mk/linux_crosscompile_macosx.mk
  mk/macosx.mk
  mk/make_info_plist.sh
  mk/rules.mk
  mk/staticlib.mk
  mk/stdapp.mk
  mk/stdcpptest.mk
  mk/stddevapp.mk
  mk/windows.mk
  set_env.sh
Labels: :ml, backport

#710 [7.5][ML] Depth based regularisation for boosted tree training
  docs/CHANGELOG.asciidoc
  include/maths/CBoostedTree.h
  include/maths/CBoostedTreeFactory.h
  include/maths/CBoostedTreeImpl.h
  include/maths/CDataFrameCategoryEncoder.h
  lib/api/CDataFrameBoostedTreeRunner.cc
  lib/api/unittest/CDataFrameAnalyzerTest.cc
  lib/maths/CBoostedTree.cc
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/CDataFrameCategoryEncoder.cc
  lib/maths/unittest/CBoostedTreeTest.cc
  lib/maths/unittest/CBoostedTreeTest.h
Labels: backport, v7.5.0

#711 [7.5][ML] Trap out-of-bounds read initialising boosted tree training
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/unittest/CBoostedTreeTest.cc
  lib/maths/unittest/CBoostedTreeTest.h
Labels: >non-issue, backport, v7.5.0

#701 Introduce classification analysis runner.
  include/api/CDataFrameAnalysisRunner.h
  include/api/CDataFrameAnalysisSpecification.h
  include/api/CDataFrameAnalyzer.h
  include/api/CDataFrameBoostedTreeRunner.h
  include/api/CDataFrameClassificationRunner.h
  include/api/CDataFrameOutliersRunner.h
  include/api/CDataFrameRegressionRunner.h
  lib/api/CDataFrameAnalysisRunner.cc
  lib/api/CDataFrameAnalysisSpecification.cc
  lib/api/CDataFrameAnalyzer.cc
  lib/api/CDataFrameBoostedTreeRunner.cc
  lib/api/CDataFrameClassificationRunner.cc
  lib/api/CDataFrameOutliersRunner.cc
  lib/api/CDataFrameRegressionRunner.cc
  lib/api/Makefile.first
  lib/api/unittest/CDataFrameAnalysisRunnerTest.cc
  lib/api/unittest/CDataFrameAnalysisRunnerTest.h
  lib/api/unittest/CDataFrameAnalysisSpecificationTest.cc
  lib/api/unittest/CDataFrameAnalyzerTest.cc
  lib/api/unittest/CDataFrameAnalyzerTest.h
  lib/api/unittest/CDataFrameMockAnalysisRunner.cc
  lib/api/unittest/CDataFrameMockAnalysisRunner.h
Labels: :ml/DataFrameAnalysis, >non-issue, v7.5.0, v8.0.0

#714 [7.x] Introduce classification analysis runner. (#701)
  include/api/CDataFrameAnalysisRunner.h
  include/api/CDataFrameAnalysisSpecification.h
  include/api/CDataFrameAnalyzer.h
  include/api/CDataFrameBoostedTreeRunner.h
  include/api/CDataFrameClassificationRunner.h
  include/api/CDataFrameOutliersRunner.h
  include/api/CDataFrameRegressionRunner.h
  lib/api/CDataFrameAnalysisRunner.cc
  lib/api/CDataFrameAnalysisSpecification.cc
  lib/api/CDataFrameAnalyzer.cc
  lib/api/CDataFrameBoostedTreeRunner.cc
  lib/api/CDataFrameClassificationRunner.cc
  lib/api/CDataFrameOutliersRunner.cc
  lib/api/CDataFrameRegressionRunner.cc
  lib/api/Makefile.first
  lib/api/unittest/CDataFrameAnalysisRunnerTest.cc
  lib/api/unittest/CDataFrameAnalysisRunnerTest.h
  lib/api/unittest/CDataFrameAnalysisSpecificationTest.cc
  lib/api/unittest/CDataFrameAnalyzerTest.cc
  lib/api/unittest/CDataFrameAnalyzerTest.h
  lib/api/unittest/CDataFrameMockAnalysisRunner.cc
  lib/api/unittest/CDataFrameMockAnalysisRunner.h
Labels: :ml/DataFrameAnalysis, >non-issue, backport, v7.5.0

#715 [ML] Simplify CLion setup instructions
  build-setup/clion/using_clion.md
  dev-tools/compiledb.sh
  dev-tools/init_compiledb.sh
Labels: :ml, >non-issue, v8.0.0

#717 [ML] Replace std::auto_ptr with std::unique_ptr
  include/core/CContainerPrinter.h
  include/model/CAnomalyDetectorModel.h
  include/model/CCountingModel.h
  include/model/CEventRateModel.h
  include/model/CEventRatePopulationModel.h
  include/model/CMetricModel.h
  include/model/CMetricPopulationModel.h
  lib/core/unittest/CContainerPrinterTest.cc
  lib/model/CAnomalyDetector.cc
  lib/model/CCountingModel.cc
  lib/model/CEventRateModel.cc
  lib/model/CEventRatePopulationModel.cc
  lib/model/CMetricModel.cc
  lib/model/CMetricPopulationModel.cc
  lib/model/unittest/CEventRateModelTest.cc
  lib/model/unittest/CMetricModelTest.cc
  lib/model/unittest/CMetricPopulationModelTest.cc
  lib/model/unittest/Mocks.cc
  lib/model/unittest/Mocks.h
Labels: :ml, >refactoring, v7.5.0, v8.0.0

#718 [7.x][ML] Replace std::auto_ptr with std::unique_ptr
  include/core/CContainerPrinter.h
  include/model/CAnomalyDetectorModel.h
  include/model/CCountingModel.h
  include/model/CEventRateModel.h
  include/model/CEventRatePopulationModel.h
  include/model/CMetricModel.h
  include/model/CMetricPopulationModel.h
  lib/core/unittest/CContainerPrinterTest.cc
  lib/model/CAnomalyDetector.cc
  lib/model/CCountingModel.cc
  lib/model/CEventRateModel.cc
  lib/model/CEventRatePopulationModel.cc
  lib/model/CMetricModel.cc
  lib/model/CMetricPopulationModel.cc
  lib/model/unittest/CEventRateModelTest.cc
  lib/model/unittest/CMetricModelTest.cc
  lib/model/unittest/CMetricPopulationModelTest.cc
  lib/model/unittest/Mocks.cc
  lib/model/unittest/Mocks.h
Labels: >refactoring, backport

#716 [ML] Rename standardize_columns to standardization_enabled
  include/api/CDataFrameOutliersRunner.h
  lib/api/CDataFrameOutliersRunner.cc
Labels: :ml, :ml/DataFrameAnalysis, >non-issue, v7.5.0, v8.0.0

#719 [7.x][ML] Rename standardize_columns to standardization_enabled (#716)
  include/api/CDataFrameOutliersRunner.h
  lib/api/CDataFrameOutliersRunner.cc
Labels: :ml, :ml/DataFrameAnalysis, >non-issue, backport, v7.5.0

#721 [ML] Improvements to sparse count modelling
  docs/CHANGELOG.asciidoc
  include/maths/CModel.h
  include/model/CAnomalyDetectorModelConfig.h
  include/model/CIndividualModel.h
  include/model/CModelParams.h
  include/model/ModelTypes.h
  lib/maths/CModel.cc
  lib/maths/CPeriodicityHypothesisTests.cc
  lib/maths/CTimeSeriesModel.cc
  lib/maths/unittest/CForecastTest.cc
  lib/maths/unittest/CModelTest.cc
  lib/maths/unittest/CPeriodicityHypothesisTestsTest.cc
  lib/maths/unittest/CTimeSeriesModelTest.cc
  lib/model/CAnomalyDetectorModelConfig.cc
  lib/model/CEventRateModel.cc
  lib/model/CEventRatePopulationModel.cc
  lib/model/CIndividualModel.cc
  lib/model/CMetricModel.cc
  lib/model/CMetricPopulationModel.cc
  lib/model/CModelDetailsView.cc
  lib/model/CModelParams.cc
  lib/model/CProbabilityAndInfluenceCalculator.cc
  lib/model/ModelTypes.cc
  lib/model/unittest/CEventRateAnomalyDetectorTest.cc
  lib/model/unittest/CEventRateModelTest.cc
  lib/model/unittest/CModelToolsTest.cc
  lib/model/unittest/CProbabilityAndInfluenceCalculatorTest.cc
Labels: :ml, >enhancement, affects-results, review, v7.5.0, v8.0.0

#722 [7.5][ML] Improvements to sparse count modelling
  docs/CHANGELOG.asciidoc
  include/maths/CModel.h
  include/model/CAnomalyDetectorModelConfig.h
  include/model/CIndividualModel.h
  include/model/CModelParams.h
  include/model/ModelTypes.h
  lib/maths/CModel.cc
  lib/maths/CPeriodicityHypothesisTests.cc
  lib/maths/CTimeSeriesModel.cc
  lib/maths/unittest/CForecastTest.cc
  lib/maths/unittest/CModelTest.cc
  lib/maths/unittest/CPeriodicityHypothesisTestsTest.cc
  lib/maths/unittest/CTimeSeriesModelTest.cc
  lib/model/CAnomalyDetectorModelConfig.cc
  lib/model/CEventRateModel.cc
  lib/model/CEventRatePopulationModel.cc
  lib/model/CIndividualModel.cc
  lib/model/CMetricModel.cc
  lib/model/CMetricPopulationModel.cc
  lib/model/CModelDetailsView.cc
  lib/model/CModelParams.cc
  lib/model/CProbabilityAndInfluenceCalculator.cc
  lib/model/ModelTypes.cc
  lib/model/unittest/CEventRateAnomalyDetectorTest.cc
  lib/model/unittest/CEventRateModelTest.cc
  lib/model/unittest/CModelToolsTest.cc
  lib/model/unittest/CProbabilityAndInfluenceCalculatorTest.cc
Labels: backport, v7.5.0

#713 [ML] Logistic regression loss function for boosted tree training
  docs/CHANGELOG.asciidoc
  include/maths/CBoostedTree.h
  include/maths/CBoostedTreeFactory.h
  include/maths/CBoostedTreeImpl.h
  include/maths/CTools.h
  lib/api/unittest/CDataFrameAnalyzerTest.cc
  lib/api/unittest/CDataFrameAnalyzerTest.h
  lib/maths/CBoostedTree.cc
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/unittest/CBoostedTreeTest.cc
  lib/maths/unittest/CBoostedTreeTest.h
Labels: :ml/DataFrameAnalysis, >enhancement, review, v7.5.0, v8.0.0

#694 [ML][Inference]Format model state compliant to inference JSON schema
  include/api/CBoostedTreeRegressionInferenceModelBuilder.h
  include/api/CDataFrameAnalysisRunner.h
  include/api/CDataFrameAnalysisSpecification.h
  include/api/CDataFrameAnalyzer.h
  include/api/CDataFrameBoostedTreeRunner.h
  include/api/CInferenceModelDefinition.h
  include/core/CRapidJsonLineWriter.h
  include/maths/CBoostedTree.h
  include/maths/CBoostedTreeImpl.h
  include/maths/CDataFrameCategoryEncoder.h
  lib/api/CBoostedTreeRegressionInferenceModelBuilder.cc
  lib/api/CDataFrameAnalysisRunner.cc
  lib/api/CDataFrameAnalysisSpecification.cc
  lib/api/CDataFrameAnalyzer.cc
  lib/api/CDataFrameBoostedTreeRunner.cc
  lib/api/CInferenceModelDefinition.cc
  lib/api/Makefile.first
  lib/api/unittest/CBoostedTreeRegressionInferenceModelBuilderTest.cc
  lib/api/unittest/CBoostedTreeRegressionInferenceModelBuilderTest.h
  lib/api/unittest/CDataFrameAnalyzerTest.cc
  lib/api/unittest/Main.cc
  lib/api/unittest/Makefile
  lib/api/unittest/testfiles/inference_json_schema/definition.schema.combined.json
  lib/maths/CBoostedTree.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/CDataFrameCategoryEncoder.cc
  lib/maths/unittest/CBoostedTreeTest.cc
Labels: :ml, :ml/DataFrameAnalysis, >feature, >non-issue, v7.5.0, v8.0.0

#725 Revert "[ML][Inference]Format model state compliant to inference JSON schema"
  include/api/CBoostedTreeRegressionInferenceModelBuilder.h
  include/api/CDataFrameAnalysisRunner.h
  include/api/CDataFrameAnalysisSpecification.h
  include/api/CDataFrameAnalyzer.h
  include/api/CDataFrameBoostedTreeRunner.h
  include/api/CInferenceModelDefinition.h
  include/core/CRapidJsonLineWriter.h
  include/maths/CBoostedTree.h
  include/maths/CBoostedTreeImpl.h
  include/maths/CDataFrameCategoryEncoder.h
  lib/api/CBoostedTreeRegressionInferenceModelBuilder.cc
  lib/api/CDataFrameAnalysisRunner.cc
  lib/api/CDataFrameAnalysisSpecification.cc
  lib/api/CDataFrameAnalyzer.cc
  lib/api/CDataFrameBoostedTreeRunner.cc
  lib/api/CInferenceModelDefinition.cc
  lib/api/Makefile.first
  lib/api/unittest/CBoostedTreeRegressionInferenceModelBuilderTest.cc
  lib/api/unittest/CBoostedTreeRegressionInferenceModelBuilderTest.h
  lib/api/unittest/CDataFrameAnalyzerTest.cc
  lib/api/unittest/Main.cc
  lib/api/unittest/Makefile
  lib/api/unittest/testfiles/inference_json_schema/definition.schema.combined.json
  lib/maths/CBoostedTree.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/CDataFrameCategoryEncoder.cc
  lib/maths/unittest/CBoostedTreeTest.cc
Labels: >non-issue

#726 [ML] Add state format version for resilience
  lib/maths/CBayesianOptimisation.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/CDataFrameCategoryEncoder.cc
  lib/maths/unittest/CBoostedTreeTest.cc
  lib/maths/unittest/testfiles/error_bayesian_optimisation_state.json
  lib/maths/unittest/testfiles/error_boosted_tree_impl_state.json
  lib/maths/unittest/testfiles/error_no_version_state.json
Labels: :ml, >non-issue, v7.5.0, v8.0.0

#727 [7.5][ML] Add state format version for resilience (#726)
  lib/maths/CBayesianOptimisation.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/CDataFrameCategoryEncoder.cc
  lib/maths/unittest/CBoostedTreeTest.cc
  lib/maths/unittest/testfiles/error_bayesian_optimisation_state.json
  lib/maths/unittest/testfiles/error_boosted_tree_impl_state.json
  lib/maths/unittest/testfiles/error_no_version_state.json
Labels: :ml, >non-issue, backport, v7.5.0

#723 [ML] Wire in binomial logistic regression
  include/api/CDataFrameAnalysisRunner.h
  include/api/CDataFrameAnalysisSpecification.h
  include/api/CDataFrameAnalyzer.h
  include/api/CDataFrameBoostedTreeRunner.h
  include/api/CDataFrameClassificationRunner.h
  include/api/CDataFrameOutliersRunner.h
  include/api/CDataFrameRegressionRunner.h
  include/core/CDataFrame.h
  include/maths/CBoostedTreeFactory.h
  lib/api/CDataFrameAnalysisRunner.cc
  lib/api/CDataFrameAnalysisSpecification.cc
  lib/api/CDataFrameAnalyzer.cc
  lib/api/CDataFrameBoostedTreeRunner.cc
  lib/api/CDataFrameClassificationRunner.cc
  lib/api/CDataFrameOutliersRunner.cc
  lib/api/CDataFrameRegressionRunner.cc
  lib/api/unittest/CDataFrameAnalysisSpecificationTest.cc
  lib/api/unittest/CDataFrameAnalyzerTest.cc
  lib/api/unittest/CDataFrameAnalyzerTest.h
  lib/api/unittest/CDataFrameMockAnalysisRunner.cc
  lib/api/unittest/CDataFrameMockAnalysisRunner.h
  lib/core/CDataFrame.cc
  lib/core/unittest/CDataFrameTest.cc
  lib/maths/CBoostedTree.cc
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/unittest/CBoostedTreeTest.cc
  lib/maths/unittest/CDataFrameCategoryEncoderTest.cc
  lib/maths/unittest/CDataFrameUtilsTest.cc
Labels: :ml/DataFrameAnalysis, >enhancement, >non-issue, review, v7.5.0, v8.0.0

#730 [7.5][ML] Logistic regression loss function for boosted tree training
  docs/CHANGELOG.asciidoc
  include/maths/CBoostedTree.h
  include/maths/CBoostedTreeFactory.h
  include/maths/CBoostedTreeImpl.h
  include/maths/CTools.h
  lib/api/unittest/CDataFrameAnalyzerTest.cc
  lib/api/unittest/CDataFrameAnalyzerTest.h
  lib/maths/CBoostedTree.cc
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/unittest/CBoostedTreeTest.cc
  lib/maths/unittest/CBoostedTreeTest.h
Labels: backport, v7.5.0

#732 [ML] Fix potential problem for boosted tree training initialisation
  docs/CHANGELOG.asciidoc
  lib/maths/CBoostedTreeImpl.cc
Labels: :ml/DataFrameAnalysis, >bug, review, v7.5.0, v8.0.0

#731 [7.5][ML] Wire in binomial logistic regression
  include/api/CDataFrameAnalysisRunner.h
  include/api/CDataFrameAnalysisSpecification.h
  include/api/CDataFrameAnalyzer.h
  include/api/CDataFrameBoostedTreeRunner.h
  include/api/CDataFrameClassificationRunner.h
  include/api/CDataFrameOutliersRunner.h
  include/api/CDataFrameRegressionRunner.h
  include/core/CDataFrame.h
  include/maths/CBoostedTreeFactory.h
  lib/api/CDataFrameAnalysisRunner.cc
  lib/api/CDataFrameAnalysisSpecification.cc
  lib/api/CDataFrameAnalyzer.cc
  lib/api/CDataFrameBoostedTreeRunner.cc
  lib/api/CDataFrameClassificationRunner.cc
  lib/api/CDataFrameOutliersRunner.cc
  lib/api/CDataFrameRegressionRunner.cc
  lib/api/unittest/CDataFrameAnalysisSpecificationTest.cc
  lib/api/unittest/CDataFrameAnalyzerTest.cc
  lib/api/unittest/CDataFrameAnalyzerTest.h
  lib/api/unittest/CDataFrameMockAnalysisRunner.cc
  lib/api/unittest/CDataFrameMockAnalysisRunner.h
  lib/core/CDataFrame.cc
  lib/core/unittest/CDataFrameTest.cc
  lib/maths/CBoostedTree.cc
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/unittest/CBoostedTreeTest.cc
  lib/maths/unittest/CDataFrameCategoryEncoderTest.cc
  lib/maths/unittest/CDataFrameUtilsTest.cc
Labels: >non-issue, backport, v7.5.0

#733 [ML] Add comment for fixing numeric
  lib/maths/CBoostedTreeImpl.cc
Labels: :ml, >non-issue, >refactoring, v7.5.0, v8.0.0

#736 [ML] Improve logistic regression numerics
  include/maths/CBoostedTree.h
  lib/maths/CBoostedTree.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/unittest/CBoostedTreeTest.cc
  lib/maths/unittest/CBoostedTreeTest.h
Labels: :ml/DataFrameAnalysis, >enhancement, >non-issue, review, v7.5.0, v8.0.0

#737 [7.5][ML] Add comment for fixing numeric
  docs/CHANGELOG.asciidoc
  lib/maths/CBoostedTreeImpl.cc
Labels: backport, v7.5.0

#739 [7.5][ML] Improve logistic regression numerics
  include/maths/CBoostedTree.h
  lib/maths/CBoostedTree.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/unittest/CBoostedTreeTest.cc
  lib/maths/unittest/CBoostedTreeTest.h
Labels: >non-issue, backport, v7.5.0

#741 [ML] On disk data frame memory depends on directory name
  lib/core/unittest/CDataFrameTest.cc
Labels: :ml, >test, v7.5.0, v8.0.0

#734 [ML]Merge inference definition
  include/api/CBoostedTreeRegressionInferenceModelBuilder.h
  include/api/CDataFrameAnalysisRunner.h
  include/api/CDataFrameAnalysisSpecification.h
  include/api/CDataFrameAnalyzer.h
  include/api/CDataFrameBoostedTreeRunner.h
  include/api/CInferenceModelDefinition.h
  include/core/CRapidJsonLineWriter.h
  include/maths/CBoostedTree.h
  include/maths/CBoostedTreeImpl.h
  include/maths/CDataFrameCategoryEncoder.h
  lib/api/CBoostedTreeRegressionInferenceModelBuilder.cc
  lib/api/CDataFrameAnalysisRunner.cc
  lib/api/CDataFrameAnalysisSpecification.cc
  lib/api/CDataFrameAnalyzer.cc
  lib/api/CDataFrameBoostedTreeRunner.cc
  lib/api/CInferenceModelDefinition.cc
  lib/api/Makefile.first
  lib/api/unittest/CBoostedTreeRegressionInferenceModelBuilderTest.cc
  lib/api/unittest/CBoostedTreeRegressionInferenceModelBuilderTest.h
  lib/api/unittest/CDataFrameAnalyzerTest.cc
  lib/api/unittest/Main.cc
  lib/api/unittest/Makefile
  lib/api/unittest/testfiles/inference_json_schema/definition.schema.combined.json
  lib/maths/CBoostedTree.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/CDataFrameCategoryEncoder.cc
  lib/maths/unittest/CBoostedTreeTest.cc
Labels: :ml, >non-issue, v8.0.0

#742 [7.x][ML] On disk data frame memory depends on directory name
  lib/core/unittest/CDataFrameTest.cc
Labels: >test, backport

#740 [ML] Snapshot boosted tree training state after final train
  lib/api/unittest/CDataFrameAnalyzerTest.cc
  lib/maths/CBoostedTreeImpl.cc
Labels: :ml/DataFrameAnalysis, >enhancement, >non-issue, v7.5.0, v8.0.0

#744 [7.6][ML] Merge inference definition
  include/api/CBoostedTreeRegressionInferenceModelBuilder.h
  include/api/CDataFrameAnalysisRunner.h
  include/api/CDataFrameAnalysisSpecification.h
  include/api/CDataFrameAnalyzer.h
  include/api/CDataFrameBoostedTreeRunner.h
  include/api/CInferenceModelDefinition.h
  include/core/CRapidJsonLineWriter.h
  include/maths/CBoostedTree.h
  include/maths/CBoostedTreeImpl.h
  include/maths/CDataFrameCategoryEncoder.h
  lib/api/CBoostedTreeRegressionInferenceModelBuilder.cc
  lib/api/CDataFrameAnalysisRunner.cc
  lib/api/CDataFrameAnalysisSpecification.cc
  lib/api/CDataFrameAnalyzer.cc
  lib/api/CDataFrameBoostedTreeRunner.cc
  lib/api/CInferenceModelDefinition.cc
  lib/api/Makefile.first
  lib/api/unittest/CBoostedTreeRegressionInferenceModelBuilderTest.cc
  lib/api/unittest/CBoostedTreeRegressionInferenceModelBuilderTest.h
  lib/api/unittest/CDataFrameAnalyzerTest.cc
  lib/api/unittest/Main.cc
  lib/api/unittest/Makefile
  lib/api/unittest/testfiles/inference_json_schema/definition.schema.combined.json
  lib/maths/CBoostedTree.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/CDataFrameCategoryEncoder.cc
  lib/maths/unittest/CBoostedTreeTest.cc
Labels: :ml, >non-issue, backport, v7.6.0

#748 [ML] Fix categorization bug
  include/api/CBoostedTreeInferenceModelBuilder.h
  include/api/CInferenceModelDefinition.h
  lib/api/CBoostedTreeInferenceModelBuilder.cc
  lib/api/CBoostedTreeRegressionInferenceModelBuilder.cc
  lib/api/CInferenceModelDefinition.cc
  lib/api/unittest/CBoostedTreeInferenceModelBuilderTest.cc
Labels: :ml, >non-issue, review, v7.6.0, v8.0.0

#747 [ML] Fix VS linking problem
  include/api/CInferenceModelDefinition.h
  include/core/CRapidJsonLineWriter.h
  lib/api/CInferenceModelDefinition.cc
Labels: :ml, >non-issue, v7.6.0, v8.0.0

#749 [7.6][ML] Snapshot boosted tree training state after final train
  lib/api/unittest/CDataFrameAnalyzerTest.cc
  lib/maths/CBoostedTreeImpl.cc
Labels: >non-issue, backport, v7.6.0

#750 [7.5][ML] Snapshot boosted tree training state after final train
  lib/api/unittest/CDataFrameAnalyzerTest.cc
  lib/maths/CBoostedTreeImpl.cc
Labels: >non-issue, backport, v7.5.0

#754 [7.6][ML] Generate inference definition for classification NG
  include/api/CBoostedTreeInferenceModelBuilder.h
  include/api/CDataFrameAnalysisSpecification.h
  include/api/CDataFrameBoostedTreeRunner.h
  include/api/CDataFrameClassificationRunner.h
  include/api/CDataFrameRegressionRunner.h
  include/api/CInferenceModelDefinition.h
  lib/api/CBoostedTreeInferenceModelBuilder.cc
  lib/api/CBoostedTreeRegressionInferenceModelBuilder.cc
  lib/api/CDataFrameBoostedTreeRunner.cc
  lib/api/CDataFrameClassificationRunner.cc
  lib/api/CDataFrameRegressionRunner.cc
  lib/api/CInferenceModelDefinition.cc
  lib/api/Makefile.first
  lib/api/unittest/CBoostedTreeInferenceModelBuilderTest.cc
  lib/api/unittest/CBoostedTreeInferenceModelBuilderTest.h
  lib/api/unittest/Main.cc
  lib/api/unittest/Makefile
  lib/api/unittest/testfiles/inference_json_schema/definition.schema.json
Labels: :ml, >non-issue, backport, v7.6.0

#755 [7.6][ML] Fix categorization bug (#748)
  include/api/CBoostedTreeInferenceModelBuilder.h
  include/api/CInferenceModelDefinition.h
  lib/api/CBoostedTreeInferenceModelBuilder.cc
  lib/api/CBoostedTreeRegressionInferenceModelBuilder.cc
  lib/api/CInferenceModelDefinition.cc
  lib/api/unittest/CBoostedTreeInferenceModelBuilderTest.cc
Labels: :ml, >non-issue, backport, v7.6.0

#756 [7.6][ML] Fix VS linking problem
  include/api/CInferenceModelDefinition.h
  include/core/CRapidJsonLineWriter.h
  lib/api/CInferenceModelDefinition.cc
Labels: :ml, >non-issue, backport, v7.6.0

#751 [ML] Better handling of unbalanced class representation in the training data
  bin/data_frame_analyzer/Main.cc
  include/api/CDataFrameBoostedTreeRunner.h
  include/core/CProgramCounters.h
  include/maths/CBoostedTree.h
  include/maths/CBoostedTreeFactory.h
  include/maths/CBoostedTreeImpl.h
  include/maths/CDataFrameCategoryEncoder.h
  include/maths/CDataFrameUtils.h
  include/maths/CSampling.h
  lib/api/CDataFrameBoostedTreeRunner.cc
  lib/api/CDataFrameClassificationRunner.cc
  lib/api/unittest/CBoostedTreeInferenceModelBuilderTest.cc
  lib/api/unittest/CDataFrameAnalyzerTest.cc
  lib/maths/CBoostedTree.cc
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/CDataFrameCategoryEncoder.cc
  lib/maths/CDataFrameUtils.cc
  lib/maths/unittest/CBoostedTreeTest.cc
  lib/maths/unittest/CBoostedTreeTest.h
  lib/maths/unittest/CDataFrameUtilsTest.cc
  lib/maths/unittest/CDataFrameUtilsTest.h
Labels: :ml/DataFrameAnalysis, >non-issue, review, v7.5.0, v7.6.0, v8.0.0

#759 [7.6][ML] Better handling of unbalanced class representation in the training data
  bin/data_frame_analyzer/Main.cc
  include/api/CDataFrameBoostedTreeRunner.h
  include/core/CProgramCounters.h
  include/maths/CBoostedTree.h
  include/maths/CBoostedTreeFactory.h
  include/maths/CBoostedTreeImpl.h
  include/maths/CDataFrameCategoryEncoder.h
  include/maths/CDataFrameUtils.h
  include/maths/CSampling.h
  lib/api/CDataFrameBoostedTreeRunner.cc
  lib/api/CDataFrameClassificationRunner.cc
  lib/api/unittest/CBoostedTreeInferenceModelBuilderTest.cc
  lib/api/unittest/CDataFrameAnalyzerTest.cc
  lib/maths/CBoostedTree.cc
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/CDataFrameCategoryEncoder.cc
  lib/maths/CDataFrameUtils.cc
  lib/maths/unittest/CBoostedTreeTest.cc
  lib/maths/unittest/CBoostedTreeTest.h
  lib/maths/unittest/CDataFrameUtilsTest.cc
  lib/maths/unittest/CDataFrameUtilsTest.h
Labels: >non-issue, backport, v7.6.0

#760 [7.5][ML] Better handling of unbalanced class representation in the training data
  bin/data_frame_analyzer/Main.cc
  include/api/CDataFrameBoostedTreeRunner.h
  include/core/CProgramCounters.h
  include/maths/CBoostedTree.h
  include/maths/CBoostedTreeFactory.h
  include/maths/CBoostedTreeImpl.h
  include/maths/CDataFrameCategoryEncoder.h
  include/maths/CDataFrameUtils.h
  include/maths/CSampling.h
  lib/api/CDataFrameBoostedTreeRunner.cc
  lib/api/CDataFrameClassificationRunner.cc
  lib/api/unittest/CDataFrameAnalyzerTest.cc
  lib/maths/CBoostedTree.cc
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/CDataFrameCategoryEncoder.cc
  lib/maths/CDataFrameUtils.cc
  lib/maths/unittest/CBoostedTreeTest.cc
  lib/maths/unittest/CBoostedTreeTest.h
  lib/maths/unittest/CDataFrameUtilsTest.cc
  lib/maths/unittest/CDataFrameUtilsTest.h
Labels: >non-issue, backport, v7.5.0

#757 [ML] Fix categorization encoding error
  include/api/CInferenceModelDefinition.h
  lib/api/CBoostedTreeInferenceModelBuilder.cc
  lib/api/CInferenceModelDefinition.cc
  lib/api/unittest/CBoostedTreeInferenceModelBuilderTest.cc
  lib/api/unittest/CBoostedTreeInferenceModelBuilderTest.h
Labels: :ml, >non-issue, v7.6.0, v8.0.0

#746 [ML] Refactor spec generation for tests
  include/api/CDataFrameAnalysisSpecification.h
  include/test/CDataFrameAnalysisSpecificationFactory.h
  lib/Makefile
  lib/api/unittest/CBoostedTreeInferenceModelBuilderTest.cc
  lib/api/unittest/CDataFrameAnalysisRunnerTest.cc
  lib/api/unittest/CDataFrameAnalysisRunnerTest.h
  lib/api/unittest/CDataFrameAnalyzerTest.cc
  lib/api/unittest/Makefile
  lib/test/CDataFrameAnalysisSpecificationFactory.cc
  lib/test/Makefile
Labels: :ml, >non-issue, >refactoring, v7.6.0, v8.0.0

#758 [ML] Better error handling for data frame analysis
  lib/api/CDataFrameClassificationRunner.cc
  lib/api/CDataFrameRegressionRunner.cc
  lib/api/unittest/CDataFrameAnalysisRunnerTest.cc
  lib/api/unittest/CDataFrameAnalysisRunnerTest.h
  lib/api/unittest/CDataFrameAnalysisSpecificationTest.cc
Labels: :ml/DataFrameAnalysis, >non-issue, review, v7.5.0, v7.6.0, v8.0.0

#764 [7.6][ML] Fix categorization encoding error
  include/api/CInferenceModelDefinition.h
  lib/api/CBoostedTreeInferenceModelBuilder.cc
  lib/api/CInferenceModelDefinition.cc
  lib/api/unittest/CBoostedTreeInferenceModelBuilderTest.cc
  lib/api/unittest/CBoostedTreeInferenceModelBuilderTest.h
Labels: :ml, >non-issue, backport, v7.6.0

#762 [ML] Remove explicit filtering of the target column
  lib/api/CBoostedTreeInferenceModelBuilder.cc
  lib/api/CInferenceModelDefinition.cc
Labels: :ml, >non-issue, v7.6.0, v8.0.0

#767 [7.6][ML] Refactor spec generation for tests
  include/api/CDataFrameAnalysisSpecification.h
  include/test/CDataFrameAnalysisSpecificationFactory.h
  lib/Makefile
  lib/api/unittest/CBoostedTreeInferenceModelBuilderTest.cc
  lib/api/unittest/CDataFrameAnalysisRunnerTest.cc
  lib/api/unittest/CDataFrameAnalysisRunnerTest.h
  lib/api/unittest/CDataFrameAnalyzerTest.cc
  lib/api/unittest/Makefile
  lib/test/CDataFrameAnalysisSpecificationFactory.cc
  lib/test/Makefile
Labels: :ml, >non-issue, backport, v7.6.0

#768 [7.6][ML] Remove explicit filtering of the target column
  lib/api/CBoostedTreeInferenceModelBuilder.cc
  lib/api/CInferenceModelDefinition.cc
Labels: :ml, >non-issue, backport, v7.6.0

#769 [ML] Identity encode the target variable
  include/maths/CDataFrameCategoryEncoder.h
  lib/maths/CDataFrameCategoryEncoder.cc
  lib/maths/unittest/CDataFrameCategoryEncoderTest.cc
  lib/maths/unittest/CDataFrameCategoryEncoderTest.h
Labels: :ml/DataFrameAnalysis, >non-issue, review, v7.5.0, v7.6.0, v8.0.0

#761 [ML] Split CDataFrameAnalyzerTest class
  lib/api/unittest/CDataFrameAnalyzerOutlierTest.cc
  lib/api/unittest/CDataFrameAnalyzerOutlierTest.h
  lib/api/unittest/CDataFrameAnalyzerTest.cc
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.h
  lib/api/unittest/Main.cc
  lib/api/unittest/Makefile
Labels: :ml, >non-issue, >refactoring, v7.6.0, v8.0.0

#771 [7.5][ML] Always identity encode the target variable
  include/maths/CDataFrameCategoryEncoder.h
  lib/maths/CDataFrameCategoryEncoder.cc
  lib/maths/unittest/CDataFrameCategoryEncoderTest.cc
  lib/maths/unittest/CDataFrameCategoryEncoderTest.h
Labels: >non-issue, backport, v7.5.0

#770 [7.6][ML] Always identity encode the target variable
  include/maths/CDataFrameCategoryEncoder.h
  lib/maths/CDataFrameCategoryEncoder.cc
  lib/maths/unittest/CDataFrameCategoryEncoderTest.cc
  lib/maths/unittest/CDataFrameCategoryEncoderTest.h
Labels: >non-issue, backport, v7.6.0

#772 [7.6][ML] Split CDataFrameAnalyzerTest class
  lib/api/unittest/CDataFrameAnalyzerOutlierTest.cc
  lib/api/unittest/CDataFrameAnalyzerOutlierTest.h
  lib/api/unittest/CDataFrameAnalyzerTest.cc
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.h
  lib/api/unittest/Main.cc
  lib/api/unittest/Makefile
Labels: :ml, >non-issue, backport, v7.6.0

#763 [7.5][ML] Better error handling for data frame train model
  lib/api/CDataFrameClassificationRunner.cc
  lib/api/CDataFrameRegressionRunner.cc
  lib/api/unittest/CDataFrameAnalysisRunnerTest.cc
  lib/api/unittest/CDataFrameAnalysisRunnerTest.h
  lib/api/unittest/CDataFrameAnalysisSpecificationTest.cc
Labels: >non-issue, backport, v7.5.0

#774 [7.6][ML] Better error handling for data frame train model
  lib/api/CDataFrameClassificationRunner.cc
  lib/api/CDataFrameRegressionRunner.cc
  lib/api/unittest/CDataFrameAnalysisRunnerTest.cc
  lib/api/unittest/CDataFrameAnalysisRunnerTest.h
  lib/api/unittest/CDataFrameAnalysisSpecificationTest.cc
Labels: >non-issue, backport, v7.6.0

#773 [ML] Refactor CLogger to use custom stream
  include/core/CLogger.h
  lib/core/CLogger.cc
  lib/maths/unittest/CBoostedTreeTest.cc
Labels: :ml, >non-issue, >refactoring, v7.6.0, v8.0.0

#776 [7.6][ML] Refactor CLogger to use custom stream
  include/core/CLogger.h
  lib/core/CLogger.cc
  lib/maths/unittest/CBoostedTreeTest.cc
Labels: :ml, >non-issue, backport, v7.6.0

#778 [ML] No need to explicitly move a temporary
  lib/api/CInferenceModelDefinition.cc
Labels: :ml/DataFrameAnalysis, >non-issue, review, v7.6.0, v8.0.0

#775 [ML] Speed up boosted tree training
  docs/CHANGELOG.asciidoc
  include/maths/CBoostedTree.h
  include/maths/CBoostedTreeImpl.h
  include/test/CDataFrameAnalysisSpecificationFactory.h
  lib/api/unittest/CDataFrameAnalyzerOutlierTest.cc
  lib/api/unittest/CDataFrameAnalyzerOutlierTest.h
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.h
  lib/maths/CBoostedTree.cc
  lib/maths/CBoostedTreeImpl.cc
Labels: :ml/DataFrameAnalysis, >enhancement, review, v7.6.0, v8.0.0

#779 [7.6][ML] No need to explicitly move a temporary
  lib/api/CInferenceModelDefinition.cc
Labels: >non-issue, backport, v7.6.0

#780 [7.6][ML] Speed up boosted tree training
  docs/CHANGELOG.asciidoc
  include/maths/CBoostedTree.h
  include/maths/CBoostedTreeImpl.h
  include/test/CDataFrameAnalysisSpecificationFactory.h
  lib/api/unittest/CDataFrameAnalyzerOutlierTest.cc
  lib/api/unittest/CDataFrameAnalyzerOutlierTest.h
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.h
  lib/maths/CBoostedTree.cc
  lib/maths/CBoostedTreeImpl.cc
Labels: backport, v7.6.0

#781 [ML] Reduce peak memory usage and improve estimation for boosted tree training
  docs/CHANGELOG.asciidoc
  include/maths/CBoostedTreeImpl.h
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
  lib/maths/CBoostedTreeImpl.cc
Labels: :ml/DataFrameAnalysis, >enhancement, review, v7.6.0, v8.0.0

#782 [ML] Reduce peak memory usage and improve estimation for boosted tree training
  docs/CHANGELOG.asciidoc
  include/maths/CBoostedTreeImpl.h
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
  lib/maths/CBoostedTreeImpl.cc
Labels: backport, v7.6.0

#784 [ML] Stratified cross validation for regression
  docs/CHANGELOG.asciidoc
  include/maths/CBoostedTreeFactory.h
  include/maths/CDataFrameUtils.h
  lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
  lib/api/CDataFrameTrainBoostedTreeRegressionRunner.cc
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/CDataFrameUtils.cc
  lib/maths/unittest/CBoostedTreeTest.cc
  lib/maths/unittest/CDataFrameUtilsTest.cc
Labels: :ml/DataFrameAnalysis, >enhancement, review, v7.6.0, v8.0.0

#788 [ML] Adjust use of BOOST_REQUIRE and BOOST_TEST_REQUIRE
  lib/core/unittest/CMemoryUsageTest.cc
  lib/core/unittest/CRapidXmlParserTest.cc
  lib/maths/unittest/CCalendarFeatureTest.cc
  lib/maths/unittest/CDataFrameUtilsTest.cc
  lib/maths/unittest/CXMeansTest.cc
Labels: :ml, >test, v7.6.0, v8.0.0

#789 [7.x] Added unit test to CXMeansOnline1dTest.cc
  lib/maths/unittest/CXMeansOnline1dTest.cc
Labels: >test, backport

#792 [7.6][ML] Stratified cross validation for regression
  docs/CHANGELOG.asciidoc
  include/maths/CBoostedTreeFactory.h
  include/maths/CDataFrameUtils.h
  lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
  lib/api/CDataFrameTrainBoostedTreeRegressionRunner.cc
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/CDataFrameUtils.cc
  lib/maths/unittest/CBoostedTreeTest.cc
  lib/maths/unittest/CDataFrameUtilsTest.cc
Labels: backport, v7.6.0

#794 [7.x][ML] Adjust use of BOOST_REQUIRE and BOOST_TEST_REQUIRE
  lib/core/unittest/CMemoryUsageTest.cc
  lib/core/unittest/CRapidXmlParserTest.cc
  lib/maths/unittest/CCalendarFeatureTest.cc
  lib/maths/unittest/CDataFrameUtilsTest.cc
  lib/maths/unittest/CXMeansTest.cc
Labels: >test, backport

#791 [ML] Fix some Windows-specific cases of no assertions in tests
  lib/core/unittest/CNamedPipeFactoryTest.cc
  lib/core/unittest/COsFileFuncsTest.cc
Labels: :ml, >test, v7.6.0, v8.0.0

#797 [7.x][ML] Fix some Windows-specific cases of no assertions in tests
  lib/core/unittest/CNamedPipeFactoryTest.cc
  lib/core/unittest/COsFileFuncsTest.cc
Labels: >test, backport

#796 [ML] Factor out common test code
  include/test/CThreadDataReader.h
  include/test/CThreadDataWriter.h
  lib/api/unittest/CIoManagerTest.cc
  lib/core/unittest/CNamedPipeFactoryTest.cc
  lib/seccomp/unittest/CSystemCallFilterTest.cc
  lib/test/CThreadDataReader.cc
  lib/test/CThreadDataWriter.cc
  lib/test/Makefile
Labels: :ml, >test, v7.6.0, v8.0.0

#798 [7.x][ML] Factor out common test code
  include/test/CThreadDataReader.h
  include/test/CThreadDataWriter.h
  lib/api/unittest/CIoManagerTest.cc
  lib/core/unittest/CNamedPipeFactoryTest.cc
  lib/seccomp/unittest/CSystemCallFilterTest.cc
  lib/test/CThreadDataReader.cc
  lib/test/CThreadDataWriter.cc
  lib/test/Makefile
Labels: >test, backport

#793 [ML] Add classification labels for classification definition
  include/api/CBoostedTreeInferenceModelBuilder.h
  include/api/CInferenceModelDefinition.h
  lib/api/CBoostedTreeInferenceModelBuilder.cc
  lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
  lib/api/CInferenceModelDefinition.cc
  lib/api/unittest/CBoostedTreeInferenceModelBuilderTest.cc
Labels: :ml, >non-issue, v7.6.0, v8.0.0

#795 [ML] Tidy up test analysis spec writing
  include/api/CDataFrameOutliersRunner.h
  include/api/CDataFrameTrainBoostedTreeClassifierRunner.h
  include/api/CDataFrameTrainBoostedTreeRegressionRunner.h
  include/api/CDataFrameTrainBoostedTreeRunner.h
  include/test/CDataFrameAnalysisSpecificationFactory.h
  lib/api/CDataFrameAnalysisSpecificationJsonWriter.cc
  lib/api/CDataFrameOutliersRunner.cc
  lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
  lib/api/CDataFrameTrainBoostedTreeRegressionRunner.cc
  lib/api/CDataFrameTrainBoostedTreeRunner.cc
  lib/api/unittest/CDataFrameAnalysisRunnerTest.cc
  lib/test/CDataFrameAnalysisSpecificationFactory.cc
Labels: :ml/DataFrameAnalysis, >non-issue, >refactoring, v7.6.0, v8.0.0

#800 [ML] Add classification labels for classification definition (#793)
  include/api/CBoostedTreeInferenceModelBuilder.h
  include/api/CInferenceModelDefinition.h
  lib/api/CBoostedTreeInferenceModelBuilder.cc
  lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
  lib/api/CInferenceModelDefinition.cc
  lib/api/unittest/CBoostedTreeInferenceModelBuilderTest.cc
Labels: :ml, >non-issue, backport, v7.6.0
