Repository elastic/ml-cpp, pull requests merged in 2019-07, with the labels that each got.

#529 [7.3][ML] Workaround a bug with std::bind by changing to lambda (#514)
  lib/model/CForecastModelPersist.cc
Labels: >backport, >non-issue, v7.3.0

#522 [ML] Introduction disk usage parameter for data frames
  include/api/CDataFrameAnalysisSpecification.h
  lib/api/CDataFrameAnalysisRunner.cc
  lib/api/CDataFrameAnalysisSpecification.cc
  lib/api/unittest/CDataFrameAnalysisRunnerTest.cc
  lib/api/unittest/CDataFrameAnalysisRunnerTest.h
  lib/api/unittest/CDataFrameAnalysisSpecificationTest.cc
  lib/api/unittest/CDataFrameAnalyzerTest.cc
Labels: :ml, >non-issue, v7.3.0, v8.0.0

#531 [7.3][ML] Introduction disk usage parameter for data frames (#522)
  include/api/CDataFrameAnalysisSpecification.h
  lib/api/CDataFrameAnalysisRunner.cc
  lib/api/CDataFrameAnalysisSpecification.cc
  lib/api/unittest/CDataFrameAnalysisRunnerTest.cc
  lib/api/unittest/CDataFrameAnalysisRunnerTest.h
  lib/api/unittest/CDataFrameAnalysisSpecificationTest.cc
  lib/api/unittest/CDataFrameAnalyzerTest.cc
Labels: >backport, >non-issue, v7.3.0

#509 [FEATURE][ML] Speed up computing node statistics after split during boosted tree training
  lib/maths/CBoostedTree.cc
Labels: :ml, >enhancement, >non-issue, review

#533 [ML] Check the data frame row count is consistent with the analysis configuration
  lib/api/CDataFrameAnalyzer.cc
  lib/api/unittest/CDataFrameAnalyzerTest.cc
Labels: :ml, >non-issue, review, v7.3.0, v8.0.0

#535 [7.3][ML] Check the data frame row count is consistent with the analysis configuration
  lib/api/CDataFrameAnalyzer.cc
  lib/api/unittest/CDataFrameAnalyzerTest.cc
Labels: >backport, >non-issue, v7.3.0

#536 [ML] Move json constants to CDataFrameAnalysisSpecification definition
  include/api/CDataFrameAnalysisConfigReader.h
  include/api/CDataFrameAnalysisSpecification.h
  lib/api/CDataFrameAnalysisConfigReader.cc
  lib/api/CDataFrameAnalysisSpecification.cc
Labels: :ml, >non-issue, >refactoring, v7.4.0, v8.0.0

#537 [7.4][ML] Move json constants to CDataFrameAnalysisSpecification definition
  include/api/CDataFrameAnalysisConfigReader.h
  include/api/CDataFrameAnalysisSpecification.h
  lib/api/CDataFrameAnalysisConfigReader.cc
  lib/api/CDataFrameAnalysisSpecification.cc
Labels: :ml, >backport, >non-issue, v7.4.0

#540 [7.4][ML] Temporary directory must be set if disk usage is allowed (#534)
  include/api/CDataFrameAnalysisSpecificationJsonWriter.h
  lib/api/CDataFrameAnalysisRunner.cc
  lib/api/CDataFrameAnalysisSpecification.cc
  lib/api/CDataFrameAnalysisSpecificationJsonWriter.cc
  lib/api/Makefile.first
  lib/api/unittest/CDataFrameAnalysisRunnerTest.cc
  lib/api/unittest/CDataFrameAnalysisSpecificationTest.cc
  lib/api/unittest/CDataFrameAnalysisSpecificationTest.h
  lib/api/unittest/CDataFrameAnalyzerTest.cc
Labels: >backport, >non-issue, v7.4.0

#542 [ML] Fully migrate data frame analysis parameter reader to use std::string
  include/api/CDataFrameAnalysisConfigReader.h
  include/api/CDataFrameAnalysisRunner.h
  include/api/CDataFrameOutliersRunner.h
  lib/api/CDataFrameAnalysisConfigReader.cc
  lib/api/CDataFrameOutliersRunner.cc
  lib/api/unittest/CDataFrameMockAnalysisRunner.cc
  lib/api/unittest/CDataFrameMockAnalysisRunner.h
Labels: :ml, >non-issue, >refactoring, v7.4.0, v8.0.0

#538 [ML] Boosted tree memory estimation
  include/maths/CBoostedTree.h
  lib/api/CDataFrameBoostedTreeRunner.cc
  lib/maths/CBoostedTree.cc
Labels: :ml, >non-issue, review

#543 [7.4][ML] Fully migrate data frame analysis parameter reader to use std::string
  include/api/CDataFrameAnalysisConfigReader.h
  include/api/CDataFrameAnalysisRunner.h
  include/api/CDataFrameOutliersRunner.h
  lib/api/CDataFrameAnalysisConfigReader.cc
  lib/api/CDataFrameOutliersRunner.cc
  lib/api/unittest/CDataFrameMockAnalysisRunner.cc
  lib/api/unittest/CDataFrameMockAnalysisRunner.h
Labels: >backport, >non-issue, v7.4.0

#539 [FEATURE][ML] Tools for auto encoding categorical fields
  include/maths/CDataFrameUtils.h
  include/maths/CMic.h
  include/test/CRandomNumbers.h
  lib/core/CDataFrame.cc
  lib/maths/CDataFrameUtils.cc
  lib/maths/CMic.cc
  lib/maths/unittest/CDataFrameUtilsTest.cc
  lib/maths/unittest/CDataFrameUtilsTest.h
Labels: :ml, >non-issue, review

#544 [FEATURE][ML] Boosted tree training checkpointing
  include/maths/CBayesianOptimisation.h
  include/maths/CLinearAlgebraEigen.h
  lib/maths/CBayesianOptimisation.cc
  lib/maths/Makefile
  lib/maths/unittest/CBayesianOptimisationTest.cc
  lib/maths/unittest/CBayesianOptimisationTest.h
Labels: :ml, >non-issue

#545 [FEATURE][ML] Template reducing results read from a data frame
  lib/maths/CDataFrameUtils.cc
Labels: :ml, >non-issue, >refactoring, review

#549 [FEATURE][ML] Fix CDenseVector::fromStdVector
  include/maths/CLinearAlgebraEigen.h
  lib/maths/unittest/CLinearAlgebraTest.cc
Labels: :ml, >non-issue, review

#548 [FEATURE][ML] Automatic categorical field encoding
  include/core/CDataFrame.h
  include/maths/CBoostedTree.h
  include/maths/CDataFrameCategoryEncoder.h
  include/maths/CDataFrameUtils.h
  lib/api/CDataFrameAnalyzer.cc
  lib/core/CDataFrame.cc
  lib/maths/CDataFrameCategoryEncoder.cc
  lib/maths/CDataFrameUtils.cc
  lib/maths/CMic.cc
  lib/maths/Makefile
  lib/maths/unittest/CDataFrameCategoryEncoderTest.cc
  lib/maths/unittest/CDataFrameCategoryEncoderTest.h
  lib/maths/unittest/CDataFrameUtilsTest.cc
  lib/maths/unittest/Main.cc
  lib/maths/unittest/Makefile
Labels: :ml, >non-issue, review

#550 [ML] Add option to persist in foreground
  STYLEGUIDE.md
  bin/autodetect/CCmdLineParser.cc
  bin/autodetect/CCmdLineParser.h
  bin/autodetect/Main.cc
  bin/categorize/CCmdLineParser.cc
  bin/categorize/CCmdLineParser.h
  bin/categorize/Main.cc
  include/api/CAnomalyJob.h
  include/api/CDataProcessor.h
  include/api/CFieldDataTyper.h
  include/api/COutputChainer.h
  include/api/COutputHandler.h
  include/api/CPersistenceManager.h
  include/config/CAutoconfigurer.h
  include/model/CLimits.h
  include/model/CResourceMonitor.h
  lib/api/CAnomalyJob.cc
  lib/api/CCmdSkeleton.cc
  lib/api/CDataProcessor.cc
  lib/api/CFieldDataTyper.cc
  lib/api/COutputChainer.cc
  lib/api/COutputHandler.cc
  lib/api/CPersistenceManager.cc
  lib/api/Makefile.first
  lib/api/dump_state/Main.cc
  lib/api/unittest/CFieldDataTyperTest.cc
  lib/api/unittest/CMockDataProcessor.cc
  lib/api/unittest/CMockDataProcessor.h
  lib/api/unittest/CMultiFileDataAdderTest.cc
  lib/api/unittest/CPersistenceManagerTest.cc
  lib/api/unittest/CPersistenceManagerTest.h
  lib/api/unittest/CRestorePreviousStateTest.cc
  lib/api/unittest/CSingleStreamDataAdderTest.cc
  lib/api/unittest/CStringStoreTest.cc
  lib/api/unittest/Main.cc
  lib/api/unittest/Makefile
  lib/config/CAutoconfigurer.cc
  lib/model/CLimits.cc
  lib/model/CResourceMonitor.cc
  lib/model/unittest/CResourceLimitTest.cc
  lib/model/unittest/CResourceMonitorTest.cc
  lib/model/unittest/CSampleQueueTest.h
Labels: :ml, >non-issue, review, v7.4.0, v8.0.0

#554 [7.4][ML] Add option to persist in foreground (#550)
  STYLEGUIDE.md
  bin/autodetect/CCmdLineParser.cc
  bin/autodetect/CCmdLineParser.h
  bin/autodetect/Main.cc
  bin/categorize/CCmdLineParser.cc
  bin/categorize/CCmdLineParser.h
  bin/categorize/Main.cc
  include/api/CAnomalyJob.h
  include/api/CDataProcessor.h
  include/api/CFieldDataTyper.h
  include/api/COutputChainer.h
  include/api/COutputHandler.h
  include/api/CPersistenceManager.h
  include/config/CAutoconfigurer.h
  include/model/CLimits.h
  include/model/CResourceMonitor.h
  lib/api/CAnomalyJob.cc
  lib/api/CCmdSkeleton.cc
  lib/api/CDataProcessor.cc
  lib/api/CFieldDataTyper.cc
  lib/api/COutputChainer.cc
  lib/api/COutputHandler.cc
  lib/api/CPersistenceManager.cc
  lib/api/Makefile.first
  lib/api/dump_state/Main.cc
  lib/api/unittest/CFieldDataTyperTest.cc
  lib/api/unittest/CMockDataProcessor.cc
  lib/api/unittest/CMockDataProcessor.h
  lib/api/unittest/CMultiFileDataAdderTest.cc
  lib/api/unittest/CPersistenceManagerTest.cc
  lib/api/unittest/CPersistenceManagerTest.h
  lib/api/unittest/CRestorePreviousStateTest.cc
  lib/api/unittest/CSingleStreamDataAdderTest.cc
  lib/api/unittest/CStringStoreTest.cc
  lib/api/unittest/Main.cc
  lib/api/unittest/Makefile
  lib/config/CAutoconfigurer.cc
  lib/model/CLimits.cc
  lib/model/CResourceMonitor.cc
  lib/model/unittest/CResourceLimitTest.cc
  lib/model/unittest/CResourceMonitorTest.cc
  lib/model/unittest/CSampleQueueTest.h
Labels: :ml, >backport, >non-issue, v7.4.0

#553 [FEATURE][ML] Fix some merge fallout
  lib/api/CDataFrameAnalysisRunner.cc
  lib/api/CDataFrameBoostedTreeRunner.cc
  lib/api/unittest/CDataFrameAnalysisRunnerTest.cc
  lib/api/unittest/CDataFrameAnalysisSpecificationTest.cc
Labels: :ml, >non-issue, >refactoring, review

#555 [FEATURE][ML] Introducing factory for boosted tree creation (second try)
  include/api/CDataFrameBoostedTreeRunner.h
  include/maths/CBayesianOptimisation.h
  include/maths/CBoostedTree.h
  include/maths/CBoostedTreeFactory.h
  include/maths/CBoostedTreeImpl.h
  include/maths/CDataFrameRegressionModel.h
  lib/api/CDataFrameBoostedTreeRunner.cc
  lib/api/unittest/CDataFrameAnalyzerTest.cc
  lib/maths/CBoostedTree.cc
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/Makefile
  lib/maths/unittest/CBoostedTreeTest.cc
Labels: :ml, >non-issue, >refactoring, review

#556 [FEATURE][ML] Improve MICe when there are duplicate samples
  include/maths/CBoostedTree.h
  include/maths/CBoostedTreeFactory.h
  include/maths/CBoostedTreeImpl.h
  include/maths/CDataFrameRegressionModel.h
  lib/maths/CBoostedTree.cc
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/CMic.cc
  lib/maths/unittest/CBoostedTreeTest.cc
  lib/maths/unittest/CDataFrameCategoryEncoderTest.cc
  lib/maths/unittest/CMicTest.cc
  lib/maths/unittest/CMicTest.h
Labels: :ml, >enhancement, >non-issue, review

#541 [ML] Instruction on how to run project from CLion
  .dockerignore
  .gitignore
  README.md
  build-setup/clion/custom_build_targets_window.png
  build-setup/clion/edit_tool_window.png
  build-setup/clion/run_core_test_configuration.png
  build-setup/clion/using_clion.md
Labels: :ml, >non-issue, WIP, v7.4.0, v8.0.0

#561 Log if lstat fails for a reason other than missing file
  lib/core/CNamedPipeFactory.cc
Labels: :ml, >non-issue, v6.8.3, v7.3.1, v7.4.0, v8.0.0

#569 [ML] Only check that the supplied rows don't exceed the specified for data frame analyses
  docs/CHANGELOG.asciidoc
  lib/api/CDataFrameAnalyzer.cc
  lib/api/unittest/CDataFrameAnalyzerTest.cc
Labels: :ml/DataFrameAnalysis, >bug, review, v7.3.1, v7.4.0, v8.0.0

#570 [7.4][ML] Only check that the supplied row count doesn't exceed the specified for data frame analyses
  docs/CHANGELOG.asciidoc
  lib/api/CDataFrameAnalyzer.cc
  lib/api/unittest/CDataFrameAnalyzerTest.cc
Labels: >backport, v7.4.0

#568 [ML] Persistence for boosted trees
  include/core/CPersistUtils.h
  include/maths/CBayesianOptimisation.h
  include/maths/CBoostedTree.h
  include/maths/CBoostedTreeFactory.h
  include/maths/CBoostedTreeImpl.h
  lib/maths/CBayesianOptimisation.cc
  lib/maths/CBoostedTree.cc
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/unittest/CBayesianOptimisationTest.cc
  lib/maths/unittest/CBoostedTreeTest.cc
  lib/maths/unittest/CBoostedTreeTest.h
Labels: :ml/DataFrameAnalysis, >feature, >non-issue, review, v7.4.0, v8.0.0

#571 [ML] Persistence for boosted trees (#568)
  include/core/CPersistUtils.h
  include/maths/CBayesianOptimisation.h
  include/maths/CBoostedTree.h
  include/maths/CBoostedTreeFactory.h
  include/maths/CBoostedTreeImpl.h
  lib/maths/CBayesianOptimisation.cc
  lib/maths/CBoostedTree.cc
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/unittest/CBayesianOptimisationTest.cc
  lib/maths/unittest/CBoostedTreeTest.cc
  lib/maths/unittest/CBoostedTreeTest.h
Labels: >backport, >non-issue, v7.4.0

#565 [ML] Improve initialisation of boosted tree hyperparameter optimisation
  include/maths/CBayesianOptimisation.h
  include/maths/CBoostedTree.h
  include/maths/CBoostedTreeFactory.h
  include/maths/CBoostedTreeImpl.h
  lib/maths/CBayesianOptimisation.cc
  lib/maths/CBoostedTree.cc
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/unittest/CBayesianOptimisationTest.cc
  lib/maths/unittest/CBayesianOptimisationTest.h
  lib/maths/unittest/CBoostedTreeTest.cc
Labels: :ml/DataFrameAnalysis, >bug, >non-issue, review, v7.4.0, v8.0.0

#573 [7.3.1][ML] Only check that the supplied row count doesn't exceed the specified for data frame analyses
  docs/CHANGELOG.asciidoc
  lib/api/CDataFrameAnalyzer.cc
  lib/api/unittest/CDataFrameAnalyzerTest.cc
Labels: >backport, v7.3.1

#574 [ML] Slow tests speed up
  lib/maths/unittest/CBoostedTreeTest.cc
Labels: >non-issue, >test, review, v7.4.0, v8.0.0

#575 [7.4][ML] Improve initialisation of boosted tree hyperparameter optimisation
  include/maths/CBayesianOptimisation.h
  include/maths/CBoostedTree.h
  include/maths/CBoostedTreeFactory.h
  include/maths/CBoostedTreeImpl.h
  lib/maths/CBayesianOptimisation.cc
  lib/maths/CBoostedTree.cc
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/unittest/CBayesianOptimisationTest.cc
  lib/maths/unittest/CBayesianOptimisationTest.h
  lib/maths/unittest/CBoostedTreeTest.cc
Labels: >backport, >non-issue, v7.4.0
