Repository elastic/ml-cpp, pull requests merged in 2019-12, with the labels that each got.

#868 [7.x] Blacklist a number of prediction field names. (#861)
  docs/CHANGELOG.asciidoc
  lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
  lib/api/CDataFrameTrainBoostedTreeRegressionRunner.cc
  lib/api/unittest/CDataFrameTrainBoostedTreeClassifierRunnerTest.cc
  lib/api/unittest/CDataFrameTrainBoostedTreeRegressionRunnerTest.cc
  lib/api/unittest/Makefile
Labels: :ml, >bug, backport

#863 [ML] Assorted runtime optimisations for classification and regression
  docs/CHANGELOG.asciidoc
  include/core/CDataFrame.h
  include/core/CFloatStorage.h
  include/core/CImmutableRadixSet.h
  include/maths/CBoostedTreeHyperparameters.h
  include/maths/CBoostedTreeImpl.h
  include/maths/CBoundingBox.h
  include/maths/CKdTree.h
  include/maths/CQuantileSketch.h
  lib/core/CDataFrame.cc
  lib/core/unittest/CImmutableRadixSetTest.cc
  lib/core/unittest/Makefile
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/CQuantileSketch.cc
  lib/maths/CSignal.cc
  lib/maths/CTimeSeriesDecompositionDetail.cc
Labels: :ml/DataFrameAnalysis, >enhancement, review, v7.6.0, v8.0.0

#864 [ML] Log best hyperparameters and runtime summary
  lib/maths/CBoostedTreeImpl.cc
Labels: :ml, >non-issue, v7.6.0, v8.0.0

#859 [ML] Adding memory usage methods for categorization classes
  include/core/CCsvLineParser.h
  include/core/CMemory.h
  include/core/CStringSimilarityTester.h
  include/core/CompressUtils.h
  include/model/CBaseTokenListDataCategorizer.h
  include/model/CDataCategorizer.h
  include/model/CResourceMonitor.h
  include/model/CTokenListCategory.h
  include/model/CTokenListDataCategorizer.h
  include/model/CTokenListReverseSearchCreator.h
  include/model/CTokenListReverseSearchCreatorIntf.h
  lib/core/CCsvLineParser.cc
  lib/core/CStringSimilarityTester.cc
  lib/core/CompressUtils.cc
  lib/model/CBaseTokenListDataCategorizer.cc
  lib/model/CDataCategorizer.cc
  lib/model/CTokenListCategory.cc
  lib/model/CTokenListReverseSearchCreator.cc
  lib/model/CTokenListReverseSearchCreatorIntf.cc
  lib/model/unittest/CTokenListDataCategorizerTest.cc
Labels: :ml, >non-issue, v7.6.0, v8.0.0

#869 [7.6][ML] Log best hyperparameters and runtime summary (#864)
  lib/maths/CBoostedTreeImpl.cc
Labels: :ml, >non-issue, backport, v7.6.0

#870 [7.x][ML] Remove impossible move constructor/assignment
  include/maths/CBoostedTreeImpl.h
Labels: >non-issue, backport

#872 [7.x][ML] Adding memory usage methods for categorization classes
  include/core/CCsvLineParser.h
  include/core/CMemory.h
  include/core/CStringSimilarityTester.h
  include/core/CompressUtils.h
  include/model/CBaseTokenListDataCategorizer.h
  include/model/CDataCategorizer.h
  include/model/CResourceMonitor.h
  include/model/CTokenListCategory.h
  include/model/CTokenListDataCategorizer.h
  include/model/CTokenListReverseSearchCreator.h
  include/model/CTokenListReverseSearchCreatorIntf.h
  lib/core/CCsvLineParser.cc
  lib/core/CStringSimilarityTester.cc
  lib/core/CompressUtils.cc
  lib/model/CBaseTokenListDataCategorizer.cc
  lib/model/CDataCategorizer.cc
  lib/model/CTokenListCategory.cc
  lib/model/CTokenListReverseSearchCreator.cc
  lib/model/CTokenListReverseSearchCreatorIntf.cc
  lib/model/unittest/CTokenListDataCategorizerTest.cc
Labels: >non-issue, backport

#871 [ML] Rename anonymous namespace apply function to avoid clash
  lib/model/CEventRateBucketGatherer.cc
  lib/model/CMetricBucketGatherer.cc
Labels: :ml, >refactoring, v7.6.0, v8.0.0

#874 [7.x][ML] Rename anonymous namespace apply function to avoid clash
  lib/model/CEventRateBucketGatherer.cc
  lib/model/CMetricBucketGatherer.cc
Labels: >refactoring, backport

#867 [ML] Upgrade to clang 6.0/Apple clang 10.1 for macOS compilation
  3rd_party/3rd_party.sh
  build-setup/macos.md
  build-setup/macos_cross_compiled.md
  dev-tools/docker/build_macosx_build_image.sh
  dev-tools/docker/macosx_builder/Dockerfile
  dev-tools/docker/macosx_image/Dockerfile
  dev-tools/strip_binaries.sh
  docs/CHANGELOG.asciidoc
  mk/linux_crosscompile_macosx.mk
  mk/macosx.mk
Labels: :ml, >build, v8.0.0

#873 [7.6][ML] Assorted runtime optimisations for classification and regression
  docs/CHANGELOG.asciidoc
  include/core/CDataFrame.h
  include/core/CFloatStorage.h
  include/core/CImmutableRadixSet.h
  include/maths/CBoostedTreeHyperparameters.h
  include/maths/CBoostedTreeImpl.h
  include/maths/CBoundingBox.h
  include/maths/CKdTree.h
  include/maths/CQuantileSketch.h
  lib/core/CDataFrame.cc
  lib/core/unittest/CImmutableRadixSetTest.cc
  lib/core/unittest/Makefile
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/CQuantileSketch.cc
  lib/maths/CSignal.cc
  lib/maths/CTimeSeriesDecompositionDetail.cc
Labels: backport, v7.6.0

#877 Emit predicted category using an appropriate JSON type.
  docs/CHANGELOG.asciidoc
  include/api/CDataFrameTrainBoostedTreeClassifierRunner.h
  lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
  lib/api/unittest/CDataFrameTrainBoostedTreeClassifierRunnerTest.cc
Labels: :ml, >enhancement, v7.6.0, v8.0.0

#878 [7.x] Emit predicted category using an appropriate JSON type. (#877)
  docs/CHANGELOG.asciidoc
  include/api/CDataFrameTrainBoostedTreeClassifierRunner.h
  lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
  lib/api/unittest/CDataFrameTrainBoostedTreeClassifierRunnerTest.cc
Labels: :ml, >enhancement, backport

#875 [ML] Stop early (based on non-decreasing validation error) when adding trees to the forest
  docs/CHANGELOG.asciidoc
  include/core/CImmutableRadixSet.h
  include/core/CPackedBitVector.h
  include/maths/CBoostedTreeFactory.h
  include/maths/CBoostedTreeHyperparameters.h
  include/maths/CBoostedTreeImpl.h
  include/test/CDataFrameAnalysisSpecificationFactory.h
  lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
  lib/api/CDataFrameTrainBoostedTreeRegressionRunner.cc
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/CBoostedTreeHyperparameters.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/unittest/CBoostedTreeTest.cc
Labels: :ml/DataFrameAnalysis, >enhancement, review, v7.6.0, v8.0.0

#880 [7.6][ML] Stop early (based on non-decreasing validation error) when adding trees to the regression/classification forest
  docs/CHANGELOG.asciidoc
  include/core/CImmutableRadixSet.h
  include/core/CPackedBitVector.h
  include/maths/CBoostedTreeFactory.h
  include/maths/CBoostedTreeHyperparameters.h
  include/maths/CBoostedTreeImpl.h
  include/test/CDataFrameAnalysisSpecificationFactory.h
  lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
  lib/api/CDataFrameTrainBoostedTreeRegressionRunner.cc
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/CBoostedTreeHyperparameters.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/unittest/CBoostedTreeTest.cc
Labels: backport, v7.6.0

#879 Color style-related error messages in console output
  dev-tools/check-style.sh
Labels: :ml, >non-issue, v7.6.0, v8.0.0

#882 [7.x] Color style-related error messages in console output (#879)
  dev-tools/check-style.sh
Labels: :ml, >non-issue, backport

#884 [ML] Adjusts thresholds in CBoostedTreeTest
  lib/maths/unittest/CBoostedTreeTest.cc
Labels: :ml, >non-issue, review, test-failure, v7.6.0, v8.0.0

#885 [ML] Adjusts thresholds in CBoostedTreeTest (#884)
  lib/maths/unittest/CBoostedTreeTest.cc
Labels: :ml, >non-issue, backport, test-failure, v7.6.0

#883 [ML] Remove old clang workaround
  lib/core/Concurrency.cc
Labels: :ml, >non-issue, v8.0.0

#857 [ML] Compute SHAP values for supervised learning
  include/api/CDataFrameTrainBoostedTreeRunner.h
  include/maths/CBoostedTree.h
  include/maths/CBoostedTreeFactory.h
  include/maths/CBoostedTreeImpl.h
  include/maths/CDataFrameCategoryEncoder.h
  include/maths/CDataFrameRegressionModel.h
  include/maths/CTreeShapFeatureImportance.h
  include/test/CDataFrameAnalysisSpecificationFactory.h
  lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
  lib/api/CDataFrameTrainBoostedTreeRegressionRunner.cc
  lib/api/CDataFrameTrainBoostedTreeRunner.cc
  lib/api/unittest/CDataFrameAnalyzerFeatureImportanceTest.cc
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
  lib/api/unittest/Makefile
  lib/maths/CBoostedTree.cc
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/CDataFrameCategoryEncoder.cc
  lib/maths/CDataFrameRegressionModel.cc
  lib/maths/CTreeShapFeatureImportance.cc
  lib/maths/Makefile
  lib/maths/unittest/CTreeShapFeatureImportanceTest.cc
  lib/maths/unittest/Makefile
  lib/test/CDataFrameAnalysisSpecificationFactory.cc
Labels: :ml, >feature, >non-issue, v7.6.0, v8.0.0

#887 [ML] Tweak CBoostedTreeTest.testLogisticRegression test threshold further
  lib/maths/unittest/CBoostedTreeTest.cc
Labels: :ml, >test, v7.6.0, v8.0.0

#888 [7.6][ML] Compute SHAP values for supervised learning (#857)
  include/api/CDataFrameTrainBoostedTreeRunner.h
  include/maths/CBoostedTree.h
  include/maths/CBoostedTreeFactory.h
  include/maths/CBoostedTreeImpl.h
  include/maths/CDataFrameCategoryEncoder.h
  include/maths/CDataFrameRegressionModel.h
  include/maths/CTreeShapFeatureImportance.h
  include/test/CDataFrameAnalysisSpecificationFactory.h
  lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
  lib/api/CDataFrameTrainBoostedTreeRegressionRunner.cc
  lib/api/CDataFrameTrainBoostedTreeRunner.cc
  lib/api/unittest/CDataFrameAnalyzerFeatureImportanceTest.cc
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
  lib/api/unittest/Makefile
  lib/maths/CBoostedTree.cc
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/CDataFrameCategoryEncoder.cc
  lib/maths/CDataFrameRegressionModel.cc
  lib/maths/CTreeShapFeatureImportance.cc
  lib/maths/Makefile
  lib/maths/unittest/CTreeShapFeatureImportanceTest.cc
  lib/maths/unittest/Makefile
  lib/test/CDataFrameAnalysisSpecificationFactory.cc
Labels: :ml, >non-issue, backport

#890 [7.x][ML] Tweak CBoostedTreeTest.testLogisticRegression test threshold further
  lib/maths/unittest/CBoostedTreeTest.cc
Labels: >test, backport

#892 [ML] Switch the record memory callback usage to use a signed type for memory
  include/maths/CDataFrameRegressionModel.h
  include/maths/COutliers.h
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/COutliers.cc
Labels: :ml/DataFrameAnalysis, >non-issue, >refactoring, review, v7.6.0, v8.0.0

#889 [ML] Fix the train model per loop run time estimate
  lib/maths/CBoostedTreeImpl.cc
Labels: :ml/DataFrameAnalysis, >non-issue, review, v7.6.0, v8.0.0

#891 [ML] Upgrade Gradle Wrapper to use version 6.0.1
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  upload.gradle
Labels: :ml, >build, >non-issue, v7.6.0, v8.0.0

#893 [7.6][ML] Switch the record memory callback to use a signed type for memory
  include/maths/CDataFrameRegressionModel.h
  include/maths/COutliers.h
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/COutliers.cc
Labels: >non-issue, backport, v7.6.0

#894 [7.6][ML] Fix the train model per loop run time estimate
  lib/maths/CBoostedTreeImpl.cc
Labels: >non-issue, backport, v7.6.0

#896 [ML] Use analysis name as suffix for the state doc id
  include/api/CDataFrameAnalysisSpecification.h
  include/api/ElasticsearchStateIndex.h
  lib/api/CDataFrameAnalysisRunner.cc
  lib/api/CDataFrameAnalysisSpecification.cc
  lib/api/CDataFrameTrainBoostedTreeRunner.cc
  lib/api/ElasticsearchStateIndex.cc
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
Labels: :ml, :ml/DataFrameAnalysis, >non-issue

#897 [7.x][ML] Use analysis name as suffix for the state doc id (#896)
  include/api/CDataFrameAnalysisSpecification.h
  include/api/ElasticsearchStateIndex.h
  lib/api/CDataFrameAnalysisRunner.cc
  lib/api/CDataFrameAnalysisSpecification.cc
  lib/api/CDataFrameTrainBoostedTreeRunner.cc
  lib/api/ElasticsearchStateIndex.cc
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
Labels: :ml, :ml/DataFrameAnalysis, >non-issue, backport

#881 [ML] Faster quantile estimation
  docs/CHANGELOG.asciidoc
  include/api/CDataFrameTrainBoostedTreeRunner.h
  include/core/CFloatStorage.h
  include/maths/CBoostedTree.h
  include/maths/CPRNG.h
  include/maths/CQuantileSketch.h
  include/maths/CTreeShapFeatureImportance.h
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/CPRNG.cc
  lib/maths/CQuantileSketch.cc
  lib/maths/unittest/CBoostedTreeTest.cc
  lib/maths/unittest/CCalendarCyclicTestTest.cc
  lib/maths/unittest/CQuantileSketchTest.cc
Labels: :ml/DataFrameAnalysis, >enhancement, review, v7.6.0, v8.0.0

#902 [7.6][ML] Faster quantile estimation
  docs/CHANGELOG.asciidoc
  include/api/CDataFrameTrainBoostedTreeRunner.h
  include/core/CFloatStorage.h
  include/maths/CBoostedTree.h
  include/maths/CPRNG.h
  include/maths/CQuantileSketch.h
  include/maths/CTreeShapFeatureImportance.h
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/CPRNG.cc
  lib/maths/CQuantileSketch.cc
  lib/maths/unittest/CBoostedTreeTest.cc
  lib/maths/unittest/CCalendarCyclicTestTest.cc
  lib/maths/unittest/CQuantileSketchTest.cc
Labels: backport, v7.6.0

#895 [7.x][ML] Upgrade Gradle Wrapper to use version 6.0.1
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  upload.gradle
Labels: >non-issue, backport

#900 [ML] Cleaning-up SHAP estimation
  include/maths/CBoostedTree.h
  include/maths/CBoostedTreeImpl.h
  include/maths/CDataFrameRegressionModel.h
  include/maths/CTreeShapFeatureImportance.h
  lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
  lib/api/CDataFrameTrainBoostedTreeRegressionRunner.cc
  lib/api/unittest/CDataFrameAnalyzerFeatureImportanceTest.cc
  lib/maths/CBoostedTree.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/CTreeShapFeatureImportance.cc
  lib/maths/unittest/CTreeShapFeatureImportanceTest.cc
Labels: :ml, >non-issue, >refactoring, review, v7.6.0, v8.0.0

#905 [7.6][ML] Cleaning-up SHAP estimation
  include/maths/CBoostedTree.h
  include/maths/CBoostedTreeImpl.h
  include/maths/CDataFrameRegressionModel.h
  include/maths/CTreeShapFeatureImportance.h
  lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
  lib/api/CDataFrameTrainBoostedTreeRegressionRunner.cc
  lib/api/unittest/CDataFrameAnalyzerFeatureImportanceTest.cc
  lib/maths/CBoostedTree.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/CTreeShapFeatureImportance.cc
  lib/maths/unittest/CTreeShapFeatureImportanceTest.cc
Labels: :ml, >non-issue, backport, v7.6.0

#903 [ML] Early stopping in the line searches to compute initial regulariser values
  docs/CHANGELOG.asciidoc
  include/api/CDataFrameTrainBoostedTreeRunner.h
  include/maths/CBasicStatistics.h
  include/maths/CBayesianOptimisation.h
  include/maths/CBoostedTreeFactory.h
  lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
  lib/api/CDataFrameTrainBoostedTreeRegressionRunner.cc
  lib/api/unittest/CDataFrameAnalyzerFeatureImportanceTest.cc
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
  lib/maths/CBayesianOptimisation.cc
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/unittest/CBayesianOptimisationTest.cc
  lib/maths/unittest/CBoostedTreeTest.cc
Labels: :ml/DataFrameAnalysis, >enhancement, review, v7.6.0, v8.0.0

#904 [ML] Test missing feature values when training a regression model
  include/maths/CBoostedTree.h
  include/maths/CBoostedTreeImpl.h
  include/maths/CDataFrameRegressionModel.h
  lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
  lib/api/CDataFrameTrainBoostedTreeRegressionRunner.cc
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
  lib/maths/CBoostedTree.cc
  lib/maths/unittest/CBoostedTreeTest.cc
Labels: :ml/DataFrameAnalysis, >test, review, v7.6.0, v8.0.0

#910 [ML] Adjust platform specific artifact creation and upload
  build.gradle
  upload.gradle
Labels: :ml, >build, >non-issue, v7.6.0, v8.0.0

#911 [7.x][ML] Adjust platform specific artifact creation and upload
  build.gradle
  upload.gradle
Labels: >non-issue, backport

#908 [7.6][ML] Early stopping in the line searches to compute initial regulariser values
  docs/CHANGELOG.asciidoc
  include/api/CDataFrameTrainBoostedTreeRunner.h
  include/maths/CBasicStatistics.h
  include/maths/CBayesianOptimisation.h
  include/maths/CBoostedTreeFactory.h
  lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
  lib/api/CDataFrameTrainBoostedTreeRegressionRunner.cc
  lib/api/unittest/CDataFrameAnalyzerFeatureImportanceTest.cc
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
  lib/maths/CBayesianOptimisation.cc
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/unittest/CBayesianOptimisationTest.cc
  lib/maths/unittest/CBoostedTreeTest.cc
Labels: backport, v7.6.0

#909 [7.6][ML] Test missing feature values when training a regression model
  include/maths/CBoostedTree.h
  include/maths/CBoostedTreeImpl.h
  include/maths/CDataFrameRegressionModel.h
  lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
  lib/api/CDataFrameTrainBoostedTreeRegressionRunner.cc
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
  lib/maths/CBoostedTree.cc
  lib/maths/unittest/CBoostedTreeTest.cc
Labels: >test, backport, v7.6.0

#914 [ML] Add CHANGELOG entry for SHAP feature
  docs/CHANGELOG.asciidoc
Labels: :ml, >feature, v7.6.0, v8.0.0

#916 [7.6][ML] Add CHANGELOG entry for SHAP feature
  docs/CHANGELOG.asciidoc
Labels: :ml, >enhancement, >feature, backport, v7.6.0

#913 [ML] Rename result shap prefix
  lib/api/unittest/CDataFrameAnalyzerFeatureImportanceTest.cc
  lib/maths/CDataFrameRegressionModel.cc
Labels: :ml, >non-issue, >refactoring, v7.6.0, v8.0.0

#917 [7.6][ML] Rename result shap prefix
  lib/api/unittest/CDataFrameAnalyzerFeatureImportanceTest.cc
  lib/maths/CDataFrameRegressionModel.cc
Labels: :ml, >non-issue, backport, v7.6.0
