Repository elastic/ml-cpp, pull requests merged in 2019-03, with the labels that each got.

#408 [ML] Handle NaNs when detrending seasonal components
  docs/CHANGELOG.asciidoc
  include/maths/CAdaptiveBucketing.h
  include/maths/CCalendarComponent.h
  include/maths/CCalendarComponentAdaptiveBucketing.h
  include/maths/CMathsFuncsDetail.h
  include/maths/CRegression.h
  include/maths/CSeasonalComponent.h
  include/maths/CSeasonalComponentAdaptiveBucketing.h
  include/maths/CTimeSeriesDecomposition.h
  include/maths/CTimeSeriesDecompositionDetail.h
  lib/maths/CCalendarComponent.cc
  lib/maths/CCalendarComponentAdaptiveBucketing.cc
  lib/maths/CDecompositionComponent.cc
  lib/maths/CPeriodicityHypothesisTests.cc
  lib/maths/CSeasonalComponentAdaptiveBucketing.cc
  lib/maths/CTimeSeriesDecomposition.cc
  lib/maths/CTimeSeriesDecompositionDetail.cc
  lib/maths/unittest/CTimeSeriesDecompositionTest.cc
  lib/maths/unittest/CTimeSeriesDecompositionTest.h
Labels: :ml, >bug, review, v7.1.0, v8.0.0

#434 [7.1][ML] Handle NaNs when detrending seasonal components (#408)
  docs/CHANGELOG.asciidoc
  include/maths/CAdaptiveBucketing.h
  include/maths/CCalendarComponent.h
  include/maths/CCalendarComponentAdaptiveBucketing.h
  include/maths/CMathsFuncsDetail.h
  include/maths/CRegression.h
  include/maths/CSeasonalComponent.h
  include/maths/CSeasonalComponentAdaptiveBucketing.h
  include/maths/CTimeSeriesDecomposition.h
  include/maths/CTimeSeriesDecompositionDetail.h
  lib/maths/CCalendarComponent.cc
  lib/maths/CCalendarComponentAdaptiveBucketing.cc
  lib/maths/CDecompositionComponent.cc
  lib/maths/CPeriodicityHypothesisTests.cc
  lib/maths/CSeasonalComponentAdaptiveBucketing.cc
  lib/maths/CTimeSeriesDecomposition.cc
  lib/maths/CTimeSeriesDecompositionDetail.cc
  lib/maths/unittest/CTimeSeriesDecompositionTest.cc
  lib/maths/unittest/CTimeSeriesDecompositionTest.h
Labels: :ml, >backport, >bug, v7.1.0

#433 [ML] Threading optimisations
  include/core/CConcurrentQueue.h
  include/core/CDataFrame.h
  include/core/CStaticThreadPool.h
  include/core/Concurrency.h
  lib/core/CDataFrame.cc
  lib/core/CStaticThreadPool.cc
  lib/core/Concurrency.cc
  lib/core/unittest/CStaticThreadPoolTest.cc
Labels: :ml, >enhancement, >non-issue, review, v7.1.0, v8.0.0

#436 [7.1][ML] Threading optimisations
  include/core/CConcurrentQueue.h
  include/core/CDataFrame.h
  include/core/CStaticThreadPool.h
  include/core/Concurrency.h
  lib/core/CDataFrame.cc
  lib/core/CStaticThreadPool.cc
  lib/core/Concurrency.cc
  lib/core/unittest/CStaticThreadPoolTest.cc
Labels: >backport, >non-issue, v7.1.0

#432 [FEATURE][ML] Data frame column value quantile estimates
  include/maths/CDataFrameUtils.h
  lib/maths/CDataFrameUtils.cc
  lib/maths/unittest/CDataFrameUtilsTest.cc
  lib/maths/unittest/CDataFrameUtilsTest.h
Labels: :ml, >non-issue, review, v7.1.0, v8.0.0

#437 [ML] Improve autodetect logic for persistence
  docs/CHANGELOG.asciidoc
  include/api/CAnomalyJob.h
  include/api/CDataProcessor.h
  include/api/CFieldDataTyper.h
  include/api/COutputChainer.h
  include/api/COutputHandler.h
  include/config/CAutoconfigurer.h
  lib/api/CAnomalyJob.cc
  lib/api/CCmdSkeleton.cc
  lib/api/CFieldDataTyper.cc
  lib/api/COutputChainer.cc
  lib/api/COutputHandler.cc
  lib/api/unittest/CAnomalyJobTest.cc
  lib/api/unittest/CAnomalyJobTest.h
  lib/api/unittest/CMockDataProcessor.cc
  lib/api/unittest/CMockDataProcessor.h
  lib/config/CAutoconfigurer.cc
Labels: :ml, >bug, review, v6.7.0, v7.0.0, v7.1.0, v8.0.0

#440 [6.7][ML] Improve autodetect logic for persistence (#437)
  docs/CHANGELOG.asciidoc
  include/api/CAnomalyJob.h
  include/api/CDataProcessor.h
  include/api/CFieldDataTyper.h
  include/api/COutputChainer.h
  include/api/COutputHandler.h
  include/config/CAutoconfigurer.h
  lib/api/CAnomalyJob.cc
  lib/api/CCmdSkeleton.cc
  lib/api/CFieldDataTyper.cc
  lib/api/COutputChainer.cc
  lib/api/COutputHandler.cc
  lib/api/unittest/CAnomalyJobTest.cc
  lib/api/unittest/CAnomalyJobTest.h
  lib/api/unittest/CMockDataProcessor.cc
  lib/api/unittest/CMockDataProcessor.h
  lib/config/CAutoconfigurer.cc
Labels: :ml, >backport, >bug, v6.7.0

#441 [7.0][ML] Improve autodetect logic for persistence (#437)
  docs/CHANGELOG.asciidoc
  include/api/CAnomalyJob.h
  include/api/CDataProcessor.h
  include/api/CFieldDataTyper.h
  include/api/COutputChainer.h
  include/api/COutputHandler.h
  include/config/CAutoconfigurer.h
  lib/api/CAnomalyJob.cc
  lib/api/CCmdSkeleton.cc
  lib/api/CFieldDataTyper.cc
  lib/api/COutputChainer.cc
  lib/api/COutputHandler.cc
  lib/api/unittest/CAnomalyJobTest.cc
  lib/api/unittest/CAnomalyJobTest.h
  lib/api/unittest/CMockDataProcessor.cc
  lib/api/unittest/CMockDataProcessor.h
  lib/config/CAutoconfigurer.cc
Labels: :ml, >backport, >bug, v7.0.0

#442 [7.1][ML] Improve autodetect logic for persistence (#437)
  docs/CHANGELOG.asciidoc
  include/api/CAnomalyJob.h
  include/api/CDataProcessor.h
  include/api/CFieldDataTyper.h
  include/api/COutputChainer.h
  include/api/COutputHandler.h
  include/config/CAutoconfigurer.h
  lib/api/CAnomalyJob.cc
  lib/api/CCmdSkeleton.cc
  lib/api/CFieldDataTyper.cc
  lib/api/COutputChainer.cc
  lib/api/COutputHandler.cc
  lib/api/unittest/CAnomalyJobTest.cc
  lib/api/unittest/CAnomalyJobTest.h
  lib/api/unittest/CMockDataProcessor.cc
  lib/api/unittest/CMockDataProcessor.h
  lib/config/CAutoconfigurer.cc
Labels: :ml, >backport, >bug, v7.1.0

#438 [FEATURE][ML] Support reading/writing a mask of the rows in a data frame
  include/core/CDataFrame.h
  include/core/CDataFrameRowSlice.h
  include/core/CPackedBitVector.h
  include/maths/CCooccurrences.h
  include/maths/CKMostCorrelated.h
  include/maths/CPackedBitVector.h
  lib/core/CDataFrame.cc
  lib/core/CDataFrameRowSlice.cc
  lib/core/CPackedBitVector.cc
  lib/core/Makefile
  lib/core/unittest/CDataFrameTest.cc
  lib/core/unittest/CDataFrameTest.h
  lib/core/unittest/CPackedBitVectorTest.cc
  lib/core/unittest/CPackedBitVectorTest.h
  lib/core/unittest/Main.cc
  lib/core/unittest/Makefile
  lib/maths/CCooccurrences.cc
  lib/maths/CKMostCorrelated.cc
  lib/maths/CPackedBitVector.cc
  lib/maths/Makefile
  lib/maths/unittest/CKMostCorrelatedTest.cc
  lib/maths/unittest/CPackedBitVectorTest.cc
  lib/maths/unittest/Main.cc
  lib/maths/unittest/Makefile
Labels: :ml, review, v7.1.0, v8.0.0

#444 [ML] Fix some issues in memory monitoring and estimation
  include/maths/COutliers.h
  lib/maths/COutliers.cc
  lib/maths/unittest/COutliersTest.cc
Labels: :ml, >enhancement, >non-issue, review, v7.1.0, v8.0.0

#446 [7.1][ML] Remove CRegression and move current implementation to a more specific header
  include/maths/CCalendarComponentAdaptiveBucketing.h
  include/maths/CLeastSquaresOnlineRegression.h
  include/maths/CLeastSquaresOnlineRegressionDetail.h
  include/maths/CRegression.h
  include/maths/CSeasonalComponentAdaptiveBucketing.h
  include/maths/CTimeSeriesChangeDetector.h
  include/maths/CTimeSeriesDecompositionDetail.h
  include/maths/CTrendComponent.h
  lib/maths/CLeastSquaresOnlineRegression.cc
  lib/maths/CPeriodicityHypothesisTests.cc
  lib/maths/CSeasonalComponent.cc
  lib/maths/CSeasonalComponentAdaptiveBucketing.cc
  lib/maths/CTimeSeriesChangeDetector.cc
  lib/maths/CTimeSeriesDecompositionDetail.cc
  lib/maths/CTimeSeriesSegmentation.cc
  lib/maths/CTrendComponent.cc
  lib/maths/Makefile
  lib/maths/unittest/CLeastSquaresOnlineRegressionTest.cc
  lib/maths/unittest/CLeastSquaresOnlineRegressionTest.h
  lib/maths/unittest/CTrendComponentTest.cc
  lib/maths/unittest/Main.cc
  lib/maths/unittest/Makefile
Labels: >backport, >non-issue, v7.1.0

#445 [7.1][ML] Fix some issues in memory monitoring and estimation for outlier detection
  include/maths/COutliers.h
  lib/maths/COutliers.cc
  lib/maths/unittest/COutliersTest.cc
Labels: :ml, >backport, >non-issue, v7.1.0

#443 [FEATURE][ML] Boosted regression tree (initial commit)
  include/maths/CBoostedTree.h
  include/maths/CDataFrameRegressionModel.h
  include/maths/CDataFrameUtils.h
  lib/maths/CBoostedTree.cc
  lib/maths/CDataFrameRegressionModel.cc
  lib/maths/CDataFrameUtils.cc
  lib/maths/Makefile
  lib/maths/unittest/CBoostedTreeTest.cc
  lib/maths/unittest/CBoostedTreeTest.h
  lib/maths/unittest/CDataFrameUtilsTest.cc
  lib/maths/unittest/Main.cc
  lib/maths/unittest/Makefile
Labels: :ml, >feature, >non-issue, review

#448 [FEATURE][ML] Fix a bug in bit vector line scan
  lib/core/CPackedBitVector.cc
  lib/core/unittest/CPackedBitVectorTest.cc
  lib/core/unittest/CPackedBitVectorTest.h
Labels: :ml, >non-issue, review
