Repository elastic/ml-cpp, pull requests merged in 2019-04, with the labels that each got.

#451 [ML] Stop using the ml-linux-test Docker image
  dev-tools/docker/build_linux_test_image.sh
  dev-tools/docker/linux_test_image/Dockerfile
  dev-tools/docker/linux_tester/Dockerfile
  dev-tools/docker_test.sh
Labels: :ml, >build, >non-issue, v7.1.0, v8.0.0

#452 [7.1][ML] Stop using the ml-linux-test Docker image
  dev-tools/docker/build_linux_test_image.sh
  dev-tools/docker/linux_test_image/Dockerfile
  dev-tools/docker/linux_tester/Dockerfile
  dev-tools/docker_test.sh
Labels: >backport, >non-issue, v7.1.0

#453 [ML] Use hardened compiler options to build 3rd party libraries
  build-setup/linux.md
  dev-tools/docker/build_linux_build_image.sh
  dev-tools/docker/linux_builder/Dockerfile
  dev-tools/docker/linux_image/Dockerfile
  dev-tools/docker/linux_tester/Dockerfile
  dev-tools/vagrant/linux/provision.sh
  docs/CHANGELOG.asciidoc
Labels: :ml, >enhancement, v7.1.0, v8.0.0

#455 [7.1][ML] Use hardened compiler options to build 3rd party libraries
  build-setup/linux.md
  dev-tools/docker/build_linux_build_image.sh
  dev-tools/docker/linux_builder/Dockerfile
  dev-tools/docker/linux_image/Dockerfile
  dev-tools/docker/linux_tester/Dockerfile
  dev-tools/vagrant/linux/provision.sh
  docs/CHANGELOG.asciidoc
Labels: >backport, v7.1.0

#454 [FEATURE][ML] Add results_field to data frame analytics specification
  include/api/CDataFrameAnalysisSpecification.h
  lib/api/CDataFrameAnalysisSpecification.cc
  lib/api/CDataFrameAnalyzer.cc
  lib/api/unittest/CDataFrameAnalysisSpecificationTest.cc
  lib/api/unittest/CDataFrameAnalyzerTest.cc
Labels: :ml, >non-issue, v7.1.0, v8.0.0

#456 [7.x][ML] Add results_field to data frame analytics specification (#454)
  include/api/CDataFrameAnalysisSpecification.h
  lib/api/CDataFrameAnalysisSpecification.cc
  lib/api/CDataFrameAnalyzer.cc
  lib/api/unittest/CDataFrameAnalysisSpecificationTest.cc
  lib/api/unittest/CDataFrameAnalyzerTest.cc
Labels: :ml, >backport, >non-issue, v7.1.0

#450 [FEATURE][ML] Framework for regression model hyperparameter optimisation
  include/maths/CBayesianOptimisation.h
  include/maths/CLbfgs.h
  include/maths/CLinearAlgebraEigen.h
  lib/maths/CBayesianOptimisation.cc
  lib/maths/CBoostedTree.cc
  lib/maths/Makefile
  lib/maths/unittest/CBayesianOptimisationTest.cc
  lib/maths/unittest/CBayesianOptimisationTest.h
  lib/maths/unittest/CLbfgsTest.cc
  lib/maths/unittest/CLbfgsTest.h
  lib/maths/unittest/Main.cc
  lib/maths/unittest/Makefile
Labels: :ml, >enhancement, >non-issue, review

#459 [ML] Add the "time" syscall to the syscall filter
  docs/CHANGELOG.asciidoc
  lib/seccomp/CSystemCallFilter_Linux.cc
Labels: :ml, >enhancement, v6.7.2, v7.0.1, v7.1.0, v8.0.0

#462 [6.7][ML] Add the "time" syscall to the syscall filter
  docs/CHANGELOG.asciidoc
  lib/seccomp/CSystemCallFilter_Linux.cc
Labels: >backport, v6.7.2

#461 [7.0][ML] Add the "time" syscall to the syscall filter
  docs/CHANGELOG.asciidoc
  lib/seccomp/CSystemCallFilter_Linux.cc
Labels: >backport, v7.0.1

#460 [7.1][ML] Add the "time" syscall to the syscall filter
  docs/CHANGELOG.asciidoc
  lib/seccomp/CSystemCallFilter_Linux.cc
Labels: >backport, v7.1.0

#458 [FEATURE][ML] Boosted tree hyperparameter tuning
  include/maths/CBayesianOptimisation.h
  include/maths/CBoostedTree.h
  include/maths/CDataFrameRegressionModel.h
  lib/maths/CBoostedTree.cc
  lib/maths/unittest/CBoostedTreeTest.cc
Labels: :ml, >non-issue, review

#463 [ML] Select trend model complexity for forecasting based on evidence
  docs/CHANGELOG.asciidoc
  include/maths/CLeastSquaresOnlineRegression.h
  include/maths/CLeastSquaresOnlineRegressionDetail.h
  include/maths/CTrendComponent.h
  lib/maths/CStatisticalTests.cc
  lib/maths/CTimeSeriesDecompositionDetail.cc
  lib/maths/CTrendComponent.cc
  lib/maths/unittest/CForecastTest.cc
  lib/maths/unittest/CTimeSeriesDecompositionTest.cc
  lib/maths/unittest/CTimeSeriesModelTest.cc
  lib/maths/unittest/CTrendComponentTest.cc
  lib/maths/unittest/CTrendComponentTest.h
  lib/maths/unittest/testfiles/CTrendComponent.7.0.expected_values.txt
  lib/maths/unittest/testfiles/CTrendComponent.7.0.xml
Labels: :ml, >enhancement, review, v7.1.0, v8.0.0

#465 [7.1][ML] Select trend model complexity for forecasting based on evidence
  docs/CHANGELOG.asciidoc
  include/maths/CLeastSquaresOnlineRegression.h
  include/maths/CLeastSquaresOnlineRegressionDetail.h
  include/maths/CTrendComponent.h
  lib/maths/CStatisticalTests.cc
  lib/maths/CTimeSeriesDecompositionDetail.cc
  lib/maths/CTrendComponent.cc
  lib/maths/unittest/CForecastTest.cc
  lib/maths/unittest/CTimeSeriesDecompositionTest.cc
  lib/maths/unittest/CTimeSeriesModelTest.cc
  lib/maths/unittest/CTrendComponentTest.cc
  lib/maths/unittest/CTrendComponentTest.h
  lib/maths/unittest/testfiles/CTrendComponent.7.0.expected_values.txt
  lib/maths/unittest/testfiles/CTrendComponent.7.0.xml
Labels: >backport, v7.1.0

#464 [FEATURE][ML] Rename number_neighours to k
  include/api/CDataFrameOutliersRunner.h
  include/maths/COutliers.h
  lib/api/CDataFrameOutliersRunner.cc
  lib/api/unittest/CDataFrameAnalysisSpecificationTest.cc
  lib/api/unittest/CDataFrameAnalyzerTest.cc
  lib/maths/COutliers.cc
Labels: :ml, >non-issue

#467 [ML] Rename outlier detection param k to n_neighbors
  include/api/CDataFrameOutliersRunner.h
  include/maths/COutliers.h
  lib/api/CDataFrameOutliersRunner.cc
  lib/api/unittest/CDataFrameAnalysisSpecificationTest.cc
  lib/api/unittest/CDataFrameAnalyzerTest.cc
  lib/maths/COutliers.cc
Labels: :ml, >non-issue, v7.1.0, v8.0.0

#466 [FEATURE][ML] Wire regression into the data_frame_analyzer command
  include/api/CDataFrameBoostedTreeRunner.h
  include/maths/CBoostedTree.h
  include/maths/CDataFrameRegressionModel.h
  lib/api/CDataFrameAnalysisSpecification.cc
  lib/api/CDataFrameBoostedTreeRunner.cc
  lib/api/Makefile.first
  lib/api/unittest/CDataFrameAnalyzerTest.cc
  lib/api/unittest/CDataFrameAnalyzerTest.h
  lib/maths/CBoostedTree.cc
  lib/maths/unittest/CBoostedTreeTest.cc
Labels: :ml, >non-issue, review

#470 [ML] Use hardening options for gcc 7.3 build
  build-setup/linux.md
  dev-tools/docker/build_linux_build_image.sh
  dev-tools/docker/linux_builder/Dockerfile
  dev-tools/docker/linux_image/Dockerfile
  dev-tools/docker/linux_tester/Dockerfile
  dev-tools/vagrant/linux/provision.sh
Labels: :ml, >non-issue, v7.1.0, v8.0.0

#471 [7.1][ML] Use hardening options for gcc 7.3 build
  build-setup/linux.md
  dev-tools/docker/build_linux_build_image.sh
  dev-tools/docker/linux_builder/Dockerfile
  dev-tools/docker/linux_image/Dockerfile
  dev-tools/docker/linux_tester/Dockerfile
  dev-tools/vagrant/linux/provision.sh
Labels: :ml, >backport, >non-issue, v7.1.0

#472 [ML] Improve behaviour of outlier detection with when nearly all points are duplicates
  include/maths/COutliers.h
  lib/maths/COutliers.cc
  lib/maths/unittest/COutliersTest.cc
  lib/maths/unittest/COutliersTest.h
Labels: :ml, >non-issue, review, v7.1.0, v8.0.0

#473 [ML] Improve behaviour of outlier detection with when nearly all points are duplicates
  include/maths/COutliers.h
  lib/maths/COutliers.cc
  lib/maths/unittest/COutliersTest.cc
  lib/maths/unittest/COutliersTest.h
Labels: >backport, >non-issue, v7.1.0

#468 [ML] Improve residual model selection
  docs/CHANGELOG.asciidoc
  include/maths/COneOfNPrior.h
  include/maths/Constants.h
  lib/api/unittest/CAnomalyJobLimitTest.cc
  lib/maths/CMultivariateOneOfNPrior.cc
  lib/maths/COneOfNPrior.cc
  lib/maths/Constants.cc
  lib/maths/Makefile
  lib/maths/unittest/COneOfNPriorTest.cc
  lib/model/unittest/CEventRateModelTest.cc
  lib/model/unittest/CMetricAnomalyDetectorTest.cc
Labels: :ml, >enhancement, affects-results, review, v7.1.0, v8.0.0
