Repository elastic/ml-cpp, pull requests merged in 2019-01, with the labels that each got.

#354 [ML] Update seccomp filter for Fedora 29
  docs/CHANGELOG.asciidoc
  lib/seccomp/CSystemCallFilter_Linux.cc
Labels: :ml, >enhancement, v6.7.0, v7.0.0

#345 [FEATURE][ML] Groundwork for partitioning data frame analyses
  include/api/CDataFrameAnalysisRunner.h
  include/api/CDataFrameAnalysisSpecification.h
  include/api/CDataFrameOutliersRunner.h
  include/core/CDataFrame.h
  include/maths/CKdTree.h
  include/maths/CLinearAlgebraShims.h
  include/maths/CLocalOutlierFactors.h
  lib/api/CDataFrameAnalysisRunner.cc
  lib/api/CDataFrameAnalysisSpecification.cc
  lib/api/CDataFrameAnalyzer.cc
  lib/api/CDataFrameOutliersRunner.cc
  lib/api/unittest/CDataFrameAnalysisRunnerTest.cc
  lib/api/unittest/CDataFrameAnalysisRunnerTest.h
  lib/api/unittest/CDataFrameAnalysisSpecificationTest.cc
  lib/api/unittest/Main.cc
  lib/api/unittest/Makefile
  lib/core/CDataFrame.cc
Labels: :ml, review

#349 [FEATURE][ML] Migrate to perform orthogonalisation via Householder
  include/maths/CGramSchmidt.h
  include/maths/CLocalOutlierFactors.h
  include/maths/COrthogonaliser.h
  include/maths/CRandomProjectionClusterer.h
  lib/maths/CGramSchmidt.cc
  lib/maths/Makefile
  lib/maths/unittest/CLocalOutlierFactorsTest.cc
  lib/maths/unittest/COrthogonaliserTest.cc
  lib/maths/unittest/COrthogonaliserTest.h
  lib/maths/unittest/CPcaTest.cc
  lib/maths/unittest/CRandomProjectionClustererTest.cc
  lib/maths/unittest/Main.cc
  lib/maths/unittest/Makefile
Labels: :ml, >enhancement, review

#352 [ML] do not exit the worker after warning about failed cleanup
  lib/api/CForecastRunner.cc
Labels: :ml, >bug, v6.5.5, v6.6.0, v6.7.0, v7.0.0

#353 [6.7][ML] do not exit the worker after warning about failed cleanup
  docs/CHANGELOG.asciidoc
  lib/api/CForecastRunner.cc
Labels: :ml, >backport, v6.7.0

#357 [6.6][ML] do not exit the worker after warning about failed cleanup
  docs/CHANGELOG.asciidoc
  lib/api/CForecastRunner.cc
Labels: :ml, >backport, v6.6.0

#356 [6.5][ML] do not exit the worker after warning about failed cleanup
  docs/CHANGELOG.asciidoc
  lib/api/CForecastRunner.cc
Labels: :ml, >backport, v6.5.5

#361 Update setup instructions for Mojave
  build-setup/macos.md
Labels: >non-issue, v6.7.0, v7.0.0

#358 [FEATURE][ML] Store and retrieve doc id (32 bit hashes) for data frame analyses
  include/api/CDataFrameAnalyzer.h
  include/core/CDataFrame.h
  include/core/CDataFrameRowSlice.h
  lib/api/CDataFrameAnalysisSpecification.cc
  lib/api/CDataFrameAnalyzer.cc
  lib/api/unittest/CDataFrameAnalyzerTest.cc
  lib/api/unittest/CDataFrameAnalyzerTest.h
  lib/core/CDataFrame.cc
  lib/core/CDataFrameRowSlice.cc
  lib/core/unittest/CDataFrameTest.cc
  lib/core/unittest/CDataFrameTest.h
Labels: :ml, review

#363 [FEATURE][ML] Rename doc ids to doc hashes...
  include/api/CDataFrameAnalyzer.h
  include/core/CDataFrame.h
  include/core/CDataFrameRowSlice.h
  lib/api/CDataFrameAnalyzer.cc
  lib/api/unittest/CDataFrameAnalyzerTest.cc
  lib/api/unittest/CDataFrameAnalyzerTest.h
  lib/core/CDataFrame.cc
  lib/core/CDataFrameRowSlice.cc
  lib/core/unittest/CDataFrameTest.cc
  lib/core/unittest/CDataFrameTest.h
Labels: :ml

#362 [FEATURE][ML] Progress monitoring
  include/api/CDataFrameAnalysisRunner.h
  include/core/CLoopProgress.h
  include/core/Concurrency.h
  include/maths/CLocalOutlierFactors.h
  include/maths/CRegressionDetail.h
  lib/api/CDataFrameAnalysisRunner.cc
  lib/api/CDataFrameOutliersRunner.cc
  lib/api/unittest/CDataFrameAnalysisSpecificationTest.cc
  lib/api/unittest/CDataFrameAnalyzerTest.cc
  lib/core/CLoopProgress.cc
  lib/core/Concurrency.cc
  lib/core/Makefile
  lib/core/unittest/CConcurrencyTest.cc
  lib/core/unittest/CConcurrencyTest.h
  lib/core/unittest/CLoopProgressTest.cc
  lib/core/unittest/CLoopProgressTest.h
  lib/core/unittest/Main.cc
  lib/core/unittest/Makefile
  lib/maths/CLocalOutlierFactors.cc
  lib/maths/unittest/CLocalOutlierFactorsTest.cc
  lib/maths/unittest/CLocalOutlierFactorsTest.h
Labels: :ml, >enhancement, review

#359 [FEATURE][ML] Reduce bookkeeping memory usage for outlier detection
  include/maths/CKdTree.h
  include/maths/CLocalOutlierFactors.h
  lib/maths/unittest/CLocalOutlierFactorsTest.cc
Labels: :ml, >refactoring, review

#368 [FEATURE][ML] Ensure progress is less than one for unfinished data frame analysis tasks
  include/api/CDataFrameAnalysisRunner.h
  include/api/CDataFrameAnalysisSpecification.h
  lib/api/CDataFrameAnalysisRunner.cc
  lib/api/CDataFrameAnalysisSpecification.cc
  lib/api/CDataFrameOutliersRunner.cc
  lib/api/unittest/CDataFrameAnalysisSpecificationTest.cc
  lib/api/unittest/CDataFrameMockAnalysisRunner.cc
  lib/api/unittest/CDataFrameMockAnalysisRunner.h
  lib/api/unittest/Makefile
  lib/test/CTestRunner.cc
Labels: :ml, >enhancement
