Repository elastic/ml-cpp, pull requests merged in 2020-12, with the labels that each got.

#1597 [ML] Initialise CLimits from JSON config
  bin/autodetect/Main.cc
  include/api/CAnomalyJobConfig.h
  include/model/CLimits.h
  lib/api/CAnomalyJobConfig.cc
  lib/api/unittest/CAnomalyJobConfigTest.cc
  lib/model/CLimits.cc
  lib/model/unittest/CLimitsTest.cc
Labels: :ml, >non-issue, review, v7.11.0, v8.0.0

#1599 [7.x][ML] Initialise CLimits from JSON config (#1597)
  bin/autodetect/Main.cc
  include/api/CAnomalyJobConfig.h
  include/model/CLimits.h
  lib/api/CAnomalyJobConfig.cc
  lib/api/unittest/CAnomalyJobConfigTest.cc
  lib/model/CLimits.cc
  lib/model/unittest/CLimitsTest.cc
Labels: :ml, >non-issue, backport, v7.11.0

#1600 [ML] Address spurious anomalies after reinitialising time series decomposition
  lib/maths/CTimeSeriesDecompositionDetail.cc
  lib/maths/unittest/CForecastTest.cc
  lib/maths/unittest/CTimeSeriesDecompositionTest.cc
  lib/maths/unittest/CTimeSeriesModelTest.cc
  lib/model/unittest/CEventRateModelTest.cc
Labels: :ml, >non-issue, review

#1602 [ML] Init AD model config from JSON config
  bin/autodetect/CCmdLineParser.cc
  bin/autodetect/CCmdLineParser.h
  bin/autodetect/Main.cc
  include/api/CAnomalyJob.h
  include/api/CAnomalyJobConfig.h
  include/api/CConfigUpdater.h
  lib/api/CAnomalyJob.cc
  lib/api/CAnomalyJobConfig.cc
  lib/api/CConfigUpdater.cc
  lib/api/dump_state/Main.cc
  lib/api/unittest/CAnomalyJobConfigTest.cc
  lib/api/unittest/CAnomalyJobLimitTest.cc
  lib/api/unittest/CAnomalyJobTest.cc
  lib/api/unittest/CConfigUpdaterTest.cc
  lib/api/unittest/CForecastRunnerTest.cc
  lib/api/unittest/CMultiFileDataAdderTest.cc
  lib/api/unittest/CPersistenceManagerTest.cc
  lib/api/unittest/CRestorePreviousStateTest.cc
  lib/api/unittest/CSingleStreamDataAdderTest.cc
  lib/api/unittest/CStringStoreTest.cc
  lib/api/unittest/CTestAnomalyJob.cc
  lib/api/unittest/CTestAnomalyJob.h
Labels: :ml, >non-issue, review, v7.11.0, v8.0.0

#1605 [7.x][ML] Init AD model config from JSON config (#1602)
  bin/autodetect/CCmdLineParser.cc
  bin/autodetect/CCmdLineParser.h
  bin/autodetect/Main.cc
  include/api/CAnomalyJob.h
  include/api/CAnomalyJobConfig.h
  include/api/CConfigUpdater.h
  lib/api/CAnomalyJob.cc
  lib/api/CAnomalyJobConfig.cc
  lib/api/CConfigUpdater.cc
  lib/api/dump_state/Main.cc
  lib/api/unittest/CAnomalyJobConfigTest.cc
  lib/api/unittest/CAnomalyJobLimitTest.cc
  lib/api/unittest/CAnomalyJobTest.cc
  lib/api/unittest/CConfigUpdaterTest.cc
  lib/api/unittest/CForecastRunnerTest.cc
  lib/api/unittest/CMultiFileDataAdderTest.cc
  lib/api/unittest/CPersistenceManagerTest.cc
  lib/api/unittest/CRestorePreviousStateTest.cc
  lib/api/unittest/CSingleStreamDataAdderTest.cc
  lib/api/unittest/CStringStoreTest.cc
  lib/api/unittest/CTestAnomalyJob.cc
  lib/api/unittest/CTestAnomalyJob.h
Labels: :ml, >non-issue, backport, v7.11.0

#1603 [ML] Addressing a QA regression due to 1451 and 1580
  lib/maths/CTimeSeriesDecompositionDetail.cc
  lib/maths/CTimeSeriesTestForSeasonality.cc
Labels: :ml, >non-issue, review

#1607 [ML] Init AD job config with scheduled events
  bin/autodetect/Main.cc
  include/api/CAnomalyJobConfig.h
  lib/api/CAnomalyJobConfig.cc
  lib/api/CConfigUpdater.cc
  lib/api/unittest/CAnomalyJobConfigTest.cc
  lib/api/unittest/CConfigUpdaterTest.cc
Labels: :ml, >non-issue, review, v7.11.0, v8.0.0

#1604 [ML] Avoid overfit when reinitialising the residual model with new seasonal components
  include/maths/CSignal.h
  include/maths/CTimeSeriesSegmentation.h
  include/maths/CTimeSeriesTestForSeasonality.h
  lib/maths/CSignal.cc
  lib/maths/CTimeSeriesDecompositionDetail.cc
  lib/maths/CTimeSeriesSegmentation.cc
  lib/maths/CTimeSeriesTestForSeasonality.cc
  lib/maths/unittest/CSignalTest.cc
  lib/maths/unittest/CTimeSeriesSegmentationTest.cc
Labels: :ml, >non-issue, review

#1611 [ML] Fix invalid writes and increase robustness
  include/maths/CTimeSeriesDecompositionDetail.h
  include/maths/CTimeSeriesTestForSeasonality.h
  lib/maths/CAdaptiveBucketing.cc
  lib/maths/CExpandingWindow.cc
  lib/maths/CSignal.cc
  lib/maths/CTimeSeriesDecompositionDetail.cc
  lib/maths/CTimeSeriesSegmentation.cc
  lib/maths/CTimeSeriesTestForSeasonality.cc
Labels: :ml, >non-issue, review

#1610 [ML] Fix incorrect forecast bounds
  include/api/CForecastRunner.h
  include/maths/CModel.h
  lib/api/CForecastRunner.cc
  lib/maths/CModel.cc
  lib/maths/unittest/CForecastTest.cc
Labels: :ml, >non-issue, v7.11.0, v8.0.0

#1613 [7.x][ML] Fix incorrect forecast bounds
  include/api/CForecastRunner.h
  include/maths/CModel.h
  lib/api/CForecastRunner.cc
  lib/maths/CModel.cc
  lib/maths/unittest/CForecastTest.cc
Labels: >non-issue, backport, v7.11.0

#1612 [ML] Fix hyperparameter scaling
  docs/CHANGELOG.asciidoc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/unittest/CBoostedTreeTest.cc
Labels: :ml, >bug, v7.11.0, v8.0.0

#1617 [ML] Remove computed statistics instrumentation
  include/api/CDataFrameAnalysisInstrumentation.h
  include/maths/CBoostedTreeLeafNodeStatistics.h
  include/maths/CDataFrameAnalysisInstrumentationInterface.h
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/CBoostedTreeLeafNodeStatistics.cc
Labels: :ml, >non-issue, >refactoring, review, v7.11.0, v8.0.0

#1621 [7.x][ML] Fix hyperparameter scaling
  docs/CHANGELOG.asciidoc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/unittest/CBoostedTreeTest.cc
Labels: :ml, >bug, v7.11.0

#1622 [7.x][ML] Remove computed statistics instrumentation
  include/api/CDataFrameAnalysisInstrumentation.h
  include/maths/CBoostedTreeLeafNodeStatistics.h
  include/maths/CDataFrameAnalysisInstrumentationInterface.h
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/CBoostedTreeLeafNodeStatistics.cc
Labels: :ml, >non-issue, >refactoring, v7.11.0

#1615 [ML] Warn and error level log throttling
  docs/CHANGELOG.asciidoc
  include/core/CLogger.h
  include/core/CLoggerThrottler.h
  include/core/LogMacros.h
  lib/core/CLogger.cc
  lib/core/CLoggerThrottler.cc
  lib/core/Makefile
  lib/core/unittest/CLoggerTest.cc
  lib/core/unittest/CLoggerThrottlerTest.cc
  lib/core/unittest/Makefile
Labels: :ml, :ml/DataFrameAnalysis, >enhancement, review, v7.11.0, v8.0.0

#1620 [ML] Switch to using global memory constants
  include/core/Constants.h
  include/test/CDataFrameAnalyzerTrainingFactory.h
  lib/api/CAnomalyJobConfig.cc
  lib/api/CDataFrameAnalysisInstrumentation.cc
  lib/api/CDataFrameAnalysisRunner.cc
  lib/api/CInferenceModelDefinition.cc
  lib/api/CSingleStreamDataAdder.cc
  lib/api/unittest/CAnomalyJobLimitTest.cc
  lib/api/unittest/CDataFrameAnalysisInstrumentationTest.cc
  lib/api/unittest/CDataFrameAnalysisRunnerTest.cc
  lib/core/CDataFrame.cc
  lib/core/CStringUtils.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/unittest/CBoostedTreeTest.cc
  lib/model/CResourceMonitor.cc
  lib/model/unittest/CResourceMonitorTest.cc
Labels: :ml, :ml/DataFrameAnalysis, >non-issue, >refactoring, review, v7.12.0, v8.0.0

#1619 [ML] Parse field clauses using CAnomalyJobConfig
  bin/autodetect/Main.cc
  include/api/CAnomalyJob.h
  include/api/CAnomalyJobConfig.h
  lib/api/CAnomalyJob.cc
  lib/api/CAnomalyJobConfig.cc
  lib/api/unittest/CAnomalyJobConfigTest.cc
  lib/api/unittest/CAnomalyJobLimitTest.cc
  lib/api/unittest/CAnomalyJobTest.cc
  lib/api/unittest/CForecastRunnerTest.cc
  lib/api/unittest/CStringStoreTest.cc
  lib/api/unittest/CTestAnomalyJob.cc
  lib/api/unittest/CTestAnomalyJob.h
Labels: :ml, >non-issue, review, v7.12.0, v8.0.0

#1626 [7.11][ML] Warn and error level log throttling
  docs/CHANGELOG.asciidoc
  include/core/CLogger.h
  include/core/CLoggerThrottler.h
  include/core/LogMacros.h
  lib/core/CLogger.cc
  lib/core/CLoggerThrottler.cc
  lib/core/Makefile
  lib/core/unittest/CLoggerTest.cc
  lib/core/unittest/CLoggerThrottlerTest.cc
  lib/core/unittest/Makefile
Labels: backport, v7.11.0

#1623 [ML] Include assignment_memory_basis in model_size_stats
  bin/autodetect/Main.cc
  bin/categorize/Main.cc
  docs/CHANGELOG.asciidoc
  include/core/CProgramCounters.h
  include/model/CResourceMonitor.h
  include/model/ModelTypes.h
  lib/api/CAnomalyJob.cc
  lib/api/CCmdSkeleton.cc
  lib/api/CModelSizeStatsJsonWriter.cc
  lib/api/unittest/CJsonOutputWriterTest.cc
  lib/api/unittest/CModelSnapshotJsonWriterTest.cc
  lib/core/CProgramCounters.cc
  lib/model/CResourceMonitor.cc
  lib/model/ModelTypes.cc
  lib/model/unittest/CResourceMonitorTest.cc
Labels: :ml, >enhancement, v7.11.0, v8.0.0

#1629 [7.x][ML] Include assignment_memory_basis in model_size_stats
  bin/autodetect/Main.cc
  bin/categorize/Main.cc
  docs/CHANGELOG.asciidoc
  include/core/CProgramCounters.h
  include/model/CResourceMonitor.h
  include/model/ModelTypes.h
  lib/api/CAnomalyJob.cc
  lib/api/CCmdSkeleton.cc
  lib/api/CModelSizeStatsJsonWriter.cc
  lib/api/unittest/CJsonOutputWriterTest.cc
  lib/api/unittest/CModelSnapshotJsonWriterTest.cc
  lib/core/CProgramCounters.cc
  lib/model/CResourceMonitor.cc
  lib/model/ModelTypes.cc
  lib/model/unittest/CResourceMonitorTest.cc
Labels: backport, v7.11.0

#1631 [ML] Make coefficient of variation formula more robust
  lib/model/CResourceMonitor.cc
  lib/model/unittest/CResourceMonitorTest.cc
Labels: :ml, >non-issue, v7.11.0, v8.0.0

#1630 [ML] Improve test to decide whether to drop seasonal components
  include/maths/CTimeSeriesTestForSeasonality.h
  lib/maths/CTimeSeriesTestForSeasonality.cc
  lib/maths/unittest/CTimeSeriesDecompositionTest.cc
Labels: :ml, >enhancement, >non-issue, affects-results, review, v7.11.0, v8.0.0

#1632 [7.x][ML] Make coefficient of variation formula more robust
  lib/model/CResourceMonitor.cc
  lib/model/unittest/CResourceMonitorTest.cc
Labels: >non-issue, backport, v7.11.0

#1633 [7.11][ML] Improve test to decide whether to drop seasonal components
  include/maths/CTimeSeriesTestForSeasonality.h
  lib/maths/CTimeSeriesTestForSeasonality.cc
  lib/maths/unittest/CTimeSeriesDecompositionTest.cc
Labels: >non-issue, backport, v7.11.0

#1628 [7.x][ML] Parse field clauses using CAnomalyJobConfig (#1619)
  bin/autodetect/Main.cc
  include/api/CAnomalyJob.h
  include/api/CAnomalyJobConfig.h
  lib/api/CAnomalyJob.cc
  lib/api/CAnomalyJobConfig.cc
  lib/api/unittest/CAnomalyJobConfigTest.cc
  lib/api/unittest/CAnomalyJobLimitTest.cc
  lib/api/unittest/CAnomalyJobTest.cc
  lib/api/unittest/CForecastRunnerTest.cc
  lib/api/unittest/CStringStoreTest.cc
  lib/api/unittest/CTestAnomalyJob.cc
  lib/api/unittest/CTestAnomalyJob.h
Labels: :ml, >non-issue, backport, v7.12.0

#1624 [7.12][ML] Switch to using global memory constants
  include/core/Constants.h
  include/test/CDataFrameAnalyzerTrainingFactory.h
  lib/api/CAnomalyJobConfig.cc
  lib/api/CDataFrameAnalysisInstrumentation.cc
  lib/api/CDataFrameAnalysisRunner.cc
  lib/api/CInferenceModelDefinition.cc
  lib/api/CSingleStreamDataAdder.cc
  lib/api/unittest/CAnomalyJobLimitTest.cc
  lib/api/unittest/CDataFrameAnalysisInstrumentationTest.cc
  lib/api/unittest/CDataFrameAnalysisRunnerTest.cc
  lib/core/CDataFrame.cc
  lib/core/CStringUtils.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/unittest/CBoostedTreeTest.cc
  lib/model/CResourceMonitor.cc
  lib/model/unittest/CResourceMonitorTest.cc
Labels: >non-issue, backport, v7.12.0

#1634 [ML] Fix edge case in start up behaviour for non-diurnal seasonality
  docs/CHANGELOG.asciidoc
  lib/maths/CSignal.cc
Labels: :ml, >enhancement, review, v7.12.0, v8.0.0

#1636 [7.12][ML] Fix edge case in start up behaviour for non-diurnal seasonality
  docs/CHANGELOG.asciidoc
  lib/maths/CSignal.cc
Labels: backport, v7.12.0

#1635 [ML] Use JSON config for categorization
  bin/autodetect/Main.cc
  bin/categorize/Main.cc
  include/api/CAnomalyJob.h
  include/api/CAnomalyJobConfig.h
  include/api/CAnomalyJobConfigReader.h
  include/api/CConfigUpdater.h
  include/api/CFieldDataCategorizer.h
  lib/api/CAnomalyJob.cc
  lib/api/CAnomalyJobConfig.cc
  lib/api/CAnomalyJobConfigReader.cc
  lib/api/CConfigUpdater.cc
  lib/api/CFieldDataCategorizer.cc
  lib/api/dump_state/Main.cc
  lib/api/unittest/CAnomalyJobConfigTest.cc
  lib/api/unittest/CAnomalyJobLimitTest.cc
  lib/api/unittest/CAnomalyJobTest.cc
  lib/api/unittest/CConfigUpdaterTest.cc
  lib/api/unittest/CFieldDataCategorizerTest.cc
  lib/api/unittest/CForecastRunnerTest.cc
  lib/api/unittest/CMultiFileDataAdderTest.cc
  lib/api/unittest/CPersistenceManagerTest.cc
  lib/api/unittest/CRestorePreviousStateTest.cc
  lib/api/unittest/CSingleStreamDataAdderTest.cc
  lib/api/unittest/CStringStoreTest.cc
  lib/api/unittest/CTestAnomalyJob.cc
  lib/api/unittest/CTestAnomalyJob.h
  lib/api/unittest/CTestFieldDataCategorizer.cc
  lib/api/unittest/CTestFieldDataCategorizer.h
  lib/api/unittest/testfiles/new_mlfields.json
  lib/api/unittest/testfiles/new_mlfields_over.json
  lib/api/unittest/testfiles/new_mlfields_partition.json
  lib/api/unittest/testfiles/new_persist_categorization.json
  lib/api/unittest/testfiles/new_persist_count.json
  lib/api/unittest/testfiles/new_persist_dc.json
  lib/api/unittest/testfiles/new_persist_per_partition_categorization.json
Labels: :ml, >non-issue, review, v7.12.0, v8.0.0

#1637 [7.x][ML] Use JSON config for categorization (#1635)
  bin/autodetect/Main.cc
  bin/categorize/Main.cc
  include/api/CAnomalyJob.h
  include/api/CAnomalyJobConfig.h
  include/api/CAnomalyJobConfigReader.h
  include/api/CConfigUpdater.h
  include/api/CFieldDataCategorizer.h
  lib/api/CAnomalyJob.cc
  lib/api/CAnomalyJobConfig.cc
  lib/api/CAnomalyJobConfigReader.cc
  lib/api/CConfigUpdater.cc
  lib/api/CFieldDataCategorizer.cc
  lib/api/dump_state/Main.cc
  lib/api/unittest/CAnomalyJobConfigTest.cc
  lib/api/unittest/CAnomalyJobLimitTest.cc
  lib/api/unittest/CAnomalyJobTest.cc
  lib/api/unittest/CConfigUpdaterTest.cc
  lib/api/unittest/CFieldDataCategorizerTest.cc
  lib/api/unittest/CForecastRunnerTest.cc
  lib/api/unittest/CMultiFileDataAdderTest.cc
  lib/api/unittest/CPersistenceManagerTest.cc
  lib/api/unittest/CRestorePreviousStateTest.cc
  lib/api/unittest/CSingleStreamDataAdderTest.cc
  lib/api/unittest/CStringStoreTest.cc
  lib/api/unittest/CTestAnomalyJob.cc
  lib/api/unittest/CTestAnomalyJob.h
  lib/api/unittest/CTestFieldDataCategorizer.cc
  lib/api/unittest/CTestFieldDataCategorizer.h
  lib/api/unittest/testfiles/new_mlfields.json
  lib/api/unittest/testfiles/new_mlfields_over.json
  lib/api/unittest/testfiles/new_mlfields_partition.json
  lib/api/unittest/testfiles/new_persist_categorization.json
  lib/api/unittest/testfiles/new_persist_count.json
  lib/api/unittest/testfiles/new_persist_dc.json
  lib/api/unittest/testfiles/new_persist_per_partition_categorization.json
Labels: :ml, >non-issue, backport, v7.12.0

#1639 [ML] Avoid applying scale change points when the scale can't be accurately estimated
  include/maths/CTimeSeriesTestForChange.h
  lib/maths/CTimeSeriesDecompositionDetail.cc
  lib/maths/CTimeSeriesTestForChange.cc
  lib/maths/unittest/CTimeSeriesModelTest.cc
Labels: :ml, >non-issue, affects-results, review, v7.11.0, v7.12.0, v8.0.0

#1640 [ML] Parse rule filters and scheduled events from JSON config files
  bin/autodetect/CCmdLineParser.cc
  bin/autodetect/CCmdLineParser.h
  bin/autodetect/Main.cc
  include/api/CAnomalyJobConfig.h
  include/core/CPatternSet.h
  lib/api/CAnomalyJobConfig.cc
  lib/api/unittest/CAnomalyJobConfigTest.cc
  lib/core/CPatternSet.cc
Labels: :ml, >non-issue, review, v7.12.0, v8.0.0

#1641 [7.x][ML] Parse filters and events from JSON config files (#1640)
  bin/autodetect/CCmdLineParser.cc
  bin/autodetect/CCmdLineParser.h
  bin/autodetect/Main.cc
  include/api/CAnomalyJobConfig.h
  include/core/CPatternSet.h
  lib/api/CAnomalyJobConfig.cc
  lib/api/unittest/CAnomalyJobConfigTest.cc
  lib/core/CPatternSet.cc
Labels: :ml, >non-issue, backport, v7.12.0
