Repository elastic/ml-cpp, pull requests merged in 2020-03, with the labels that each got.

#1034 [ML] Distinguish missing and empty categorical values
  docs/CHANGELOG.asciidoc
  include/api/CDataFrameAnalysisSpecification.h
  include/api/CDataFrameAnalysisSpecificationJsonWriter.h
  include/core/CDataFrame.h
  include/test/CDataFrameAnalysisSpecificationFactory.h
  lib/api/CDataFrameAnalysisSpecification.cc
  lib/api/CDataFrameAnalysisSpecificationJsonWriter.cc
  lib/api/unittest/CBoostedTreeInferenceModelBuilderTest.cc
  lib/api/unittest/CDataFrameAnalysisRunnerTest.cc
  lib/api/unittest/CDataFrameAnalysisSpecificationTest.cc
  lib/api/unittest/CDataFrameAnalyzerFeatureImportanceTest.cc
  lib/api/unittest/CDataFrameAnalyzerOutlierTest.cc
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
  lib/api/unittest/CDataFrameTrainBoostedTreeClassifierRunnerTest.cc
  lib/api/unittest/CDataFrameTrainBoostedTreeRegressionRunnerTest.cc
  lib/core/CDataFrame.cc
  lib/core/CStringUtils.cc
  lib/maths/CDataFrameUtils.cc
  lib/test/CDataFrameAnalysisSpecificationFactory.cc
Labels: :ml/DataFrameAnalysis, >enhancement, review, v7.7.0, v8.0.0

#1035 [7.7][ML] Distinguish missing and empty categorical values
  docs/CHANGELOG.asciidoc
  include/api/CDataFrameAnalysisSpecification.h
  include/api/CDataFrameAnalysisSpecificationJsonWriter.h
  include/core/CDataFrame.h
  include/test/CDataFrameAnalysisSpecificationFactory.h
  lib/api/CDataFrameAnalysisSpecification.cc
  lib/api/CDataFrameAnalysisSpecificationJsonWriter.cc
  lib/api/unittest/CBoostedTreeInferenceModelBuilderTest.cc
  lib/api/unittest/CDataFrameAnalysisRunnerTest.cc
  lib/api/unittest/CDataFrameAnalysisSpecificationTest.cc
  lib/api/unittest/CDataFrameAnalyzerFeatureImportanceTest.cc
  lib/api/unittest/CDataFrameAnalyzerOutlierTest.cc
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
  lib/api/unittest/CDataFrameTrainBoostedTreeClassifierRunnerTest.cc
  lib/api/unittest/CDataFrameTrainBoostedTreeRegressionRunnerTest.cc
  lib/core/CDataFrame.cc
  lib/core/CStringUtils.cc
  lib/maths/CDataFrameUtils.cc
  lib/test/CDataFrameAnalysisSpecificationFactory.cc
Labels: backport, v7.7.0

#1022 [ML] Format memory instrumentation output
  docs/CHANGELOG.asciidoc
  include/api/CDataFrameAnalysisInstrumentation.h
  lib/api/CDataFrameAnalysisInstrumentation.cc
  lib/api/CDataFrameOutliersRunner.cc
  lib/api/CDataFrameTrainBoostedTreeRunner.cc
  lib/api/unittest/CDataFrameAnalysisInstrumentationTest.cc
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
  lib/api/unittest/CDataFrameMockAnalysisRunner.cc
  lib/api/unittest/CDataFrameMockAnalysisRunner.h
  lib/api/unittest/Makefile
Labels: :ml, >enhancement, v7.7.0, v8.0.0

#1038 [7.7][ML] Format memory instrumentation output
  docs/CHANGELOG.asciidoc
  include/api/CDataFrameAnalysisInstrumentation.h
  lib/api/CDataFrameAnalysisInstrumentation.cc
  lib/api/CDataFrameOutliersRunner.cc
  lib/api/CDataFrameTrainBoostedTreeRunner.cc
  lib/api/unittest/CDataFrameAnalysisInstrumentationTest.cc
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
  lib/api/unittest/CDataFrameMockAnalysisRunner.cc
  lib/api/unittest/CDataFrameMockAnalysisRunner.h
  lib/api/unittest/Makefile
Labels: backport, v7.7.0

#1036 [ML] Remove special case handling for missing target field for classification
  include/api/CDataFrameAnalysisRunner.h
  include/api/CDataFrameAnalysisSpecification.h
  include/api/CDataFrameTrainBoostedTreeClassifierRunner.h
  include/core/CDataFrame.h
  lib/api/CDataFrameAnalysisRunner.cc
  lib/api/CDataFrameAnalysisSpecification.cc
  lib/api/CDataFrameAnalyzer.cc
  lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
  lib/api/unittest/CDataFrameAnalysisRunnerTest.cc
  lib/api/unittest/CDataFrameAnalysisSpecificationTest.cc
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
  lib/core/CDataFrame.cc
Labels: :ml/DataFrameAnalysis, >non-issue, >refactoring, review, v7.7.0, v8.0.0

#1041 [ML] Error in handling of precision loss in logistic loss gradient and curvature
  lib/maths/CBoostedTreeLoss.cc
Labels: :ml/DataFrameAnalysis, >bug, >non-issue, review, v7.7.0, v8.0.0

#1043 [7.7][ML] Fix handling of numerical precision loss in logistic loss gradient and curvature
  lib/maths/CBoostedTreeLoss.cc
Labels: >non-issue, backport, v7.7.0

#1042 [ML] Correct missing category handling
  include/core/CDataFrame.h
  include/maths/CDataFrameUtils.h
  lib/core/CDataFrame.cc
  lib/maths/CDataFrameCategoryEncoder.cc
  lib/maths/CDataFrameUtils.cc
  lib/maths/unittest/CDataFrameUtilsTest.cc
Labels: :ml/DataFrameAnalysis, >bug, >non-issue, review, v7.7.0, v8.0.0

#1045 [ML] Temporarily disable writing memory usage
  lib/api/CDataFrameAnalysisInstrumentation.cc
Labels: :ml/DataFrameAnalysis, >non-issue, v7.7.0, v8.0.0

#1046 [7.7][ML] Don't write memory usage
  lib/api/CDataFrameAnalysisInstrumentation.cc
Labels: >non-issue, backport, v7.7.0

#1044 [7.7][ML] Correct missing category handling
  include/core/CDataFrame.h
  include/maths/CDataFrameUtils.h
  lib/core/CDataFrame.cc
  lib/maths/CDataFrameCategoryEncoder.cc
  lib/maths/CDataFrameUtils.cc
  lib/maths/unittest/CDataFrameUtilsTest.cc
Labels: >non-issue, backport, v7.7.0

#1048 [ML] Start writing memory usage again
  include/api/CDataFrameAnalysisInstrumentation.h
  include/api/CDataFrameAnalysisSpecification.h
  include/api/CDataFrameAnalyzer.h
  include/core/CRapidJsonConcurrentLineWriter.h
  lib/api/CDataFrameAnalysisInstrumentation.cc
  lib/api/CDataFrameAnalysisSpecification.cc
  lib/api/CDataFrameAnalyzer.cc
  lib/api/unittest/CDataFrameAnalysisInstrumentationTest.cc
  lib/api/unittest/CDataFrameAnalysisSpecificationTest.cc
Labels: :ml/DataFrameAnalysis, >bug, >non-issue, review, v7.7.0, v8.0.0

#1039 [7.7][ML] Remove special case handling for missing target field
  include/api/CDataFrameAnalysisRunner.h
  include/api/CDataFrameAnalysisSpecification.h
  include/api/CDataFrameTrainBoostedTreeClassifierRunner.h
  include/core/CDataFrame.h
  lib/api/CDataFrameAnalysisRunner.cc
  lib/api/CDataFrameAnalysisSpecification.cc
  lib/api/CDataFrameAnalyzer.cc
  lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
  lib/api/unittest/CDataFrameAnalysisRunnerTest.cc
  lib/api/unittest/CDataFrameAnalysisSpecificationTest.cc
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
  lib/core/CDataFrame.cc
Labels: >non-issue, backport, v7.7.0

#1047 [ML] Rename maximum_number_trees to max_trees
  docs/CHANGELOG.asciidoc
  include/api/CDataFrameTrainBoostedTreeRunner.h
  lib/api/CDataFrameTrainBoostedTreeRunner.cc
Labels: :ml/DataFrameAnalysis, >bug, v7.7.0, v8.0.0

#1049 [7.7][ML] Start writing memory usage again
  include/api/CDataFrameAnalysisInstrumentation.h
  include/api/CDataFrameAnalysisSpecification.h
  include/api/CDataFrameAnalyzer.h
  include/core/CRapidJsonConcurrentLineWriter.h
  lib/api/CDataFrameAnalysisInstrumentation.cc
  lib/api/CDataFrameAnalysisSpecification.cc
  lib/api/CDataFrameAnalyzer.cc
  lib/api/unittest/CDataFrameAnalysisInstrumentationTest.cc
  lib/api/unittest/CDataFrameAnalysisSpecificationTest.cc
Labels: >non-issue, backport, v7.7.0

#1050 [7.x][ML] Rename maximum_number_trees to max_trees (#1047)
  docs/CHANGELOG.asciidoc
  include/api/CDataFrameTrainBoostedTreeRunner.h
  lib/api/CDataFrameTrainBoostedTreeRunner.cc
Labels: :ml, :ml/DataFrameAnalysis, >bug, backport

#1051 [ML] Remove deprecated maximum_number_trees
  include/api/CDataFrameTrainBoostedTreeRunner.h
  lib/api/CDataFrameTrainBoostedTreeRunner.cc
  lib/test/CDataFrameAnalysisSpecificationFactory.cc
Labels: :ml, :ml/DataFrameAnalysis, >non-issue, v7.7.0, v8.0.0

#1037 [ML] Multinomial logistic regression
  docs/CHANGELOG.asciidoc
  include/maths/CBoostedTreeLoss.h
  include/maths/CKMeans.h
  include/maths/CKMeansOnline.h
  include/maths/CLinearAlgebraEigen.h
  include/maths/CLinearAlgebraShims.h
  include/maths/CTools.h
  include/maths/CToolsDetail.h
  include/maths/CXMeansOnline.h
  include/maths/Constants.h
  lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/CBoostedTreeLoss.cc
  lib/maths/unittest/CBoostedTreeLossTest.cc
  lib/maths/unittest/CBoostedTreeTest.cc
  lib/maths/unittest/CDataFrameUtilsTest.cc
  lib/maths/unittest/CKMeansOnlineTest.cc
  lib/maths/unittest/CMultivariateMultimodalPriorTest.cc
  lib/maths/unittest/CXMeansOnlineTest.cc
  lib/maths/unittest/Makefile
Labels: :ml/DataFrameAnalysis, >feature, v7.7.0, v8.0.0

#1053 [7.7][ML] Multinomial logistic regression
  docs/CHANGELOG.asciidoc
  include/maths/CBoostedTreeLoss.h
  include/maths/CKMeans.h
  include/maths/CKMeansOnline.h
  include/maths/CLinearAlgebraEigen.h
  include/maths/CLinearAlgebraShims.h
  include/maths/CTools.h
  include/maths/CToolsDetail.h
  include/maths/CXMeansOnline.h
  include/maths/Constants.h
  lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/CBoostedTreeLoss.cc
  lib/maths/unittest/CBoostedTreeLossTest.cc
  lib/maths/unittest/CBoostedTreeTest.cc
  lib/maths/unittest/CDataFrameUtilsTest.cc
  lib/maths/unittest/CKMeansOnlineTest.cc
  lib/maths/unittest/CMultivariateMultimodalPriorTest.cc
  lib/maths/unittest/CXMeansOnlineTest.cc
  lib/maths/unittest/Makefile
Labels: backport, v7.7.0

#1052 [7.x][ML] Remove deprecated maximum_number_trees (#1051)
  include/api/CDataFrameTrainBoostedTreeRunner.h
  lib/api/CDataFrameTrainBoostedTreeRunner.cc
  lib/test/CDataFrameAnalysisSpecificationFactory.cc
Labels: :ml, :ml/DataFrameAnalysis, >non-issue, backport

#1054 [ML] Add classification num_classes param
  include/api/CDataFrameTrainBoostedTreeClassifierRunner.h
  lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
Labels: :ml, :ml/DataFrameAnalysis, >non-issue, v7.7.0, v8.0.0

#1055 [7.x][ML] Add classification num_classes param (#1054)
  include/api/CDataFrameTrainBoostedTreeClassifierRunner.h
  lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
Labels: :ml, :ml/DataFrameAnalysis, >non-issue, backport

#1056 [ML] Wire in multiclass classification to the data frame analyzer command
  include/api/CBoostedTreeInferenceModelBuilder.h
  include/api/CDataFrameTrainBoostedTreeClassifierRunner.h
  include/api/CInferenceModelDefinition.h
  include/maths/CBasicStatistics.h
  include/maths/CBoostedTree.h
  include/maths/CBoostedTreeImpl.h
  include/maths/CBoostedTreeLoss.h
  include/maths/CDataFramePredictiveModel.h
  include/maths/CDataFrameUtils.h
  include/maths/CInformationCriteria.h
  include/maths/CKMeans.h
  include/maths/CLinearAlgebra.h
  include/maths/CLinearAlgebraEigen.h
  include/maths/CLinearAlgebraShims.h
  include/test/CDataFrameAnalysisSpecificationFactory.h
  lib/api/CBoostedTreeInferenceModelBuilder.cc
  lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
  lib/api/CDataFrameTrainBoostedTreeRegressionRunner.cc
  lib/api/CInferenceModelDefinition.cc
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
  lib/api/unittest/CDataFrameTrainBoostedTreeClassifierRunnerTest.cc
  lib/maths/CBoostedTree.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/CBoostedTreeLeafNodeStatistics.cc
  lib/maths/CBoostedTreeLoss.cc
  lib/maths/CDataFrameUtils.cc
  lib/maths/unittest/CBoostedTreeTest.cc
  lib/test/CDataFrameAnalysisSpecificationFactory.cc
Labels: :ml/DataFrameAnalysis, >non-issue, review, v7.7.0, v8.0.0

#1058 [7.7][ML] Wire in multiclass classification to the data frame analyzer command
  include/api/CBoostedTreeInferenceModelBuilder.h
  include/api/CDataFrameTrainBoostedTreeClassifierRunner.h
  include/api/CInferenceModelDefinition.h
  include/maths/CBasicStatistics.h
  include/maths/CBoostedTree.h
  include/maths/CBoostedTreeImpl.h
  include/maths/CBoostedTreeLoss.h
  include/maths/CDataFramePredictiveModel.h
  include/maths/CDataFrameUtils.h
  include/maths/CInformationCriteria.h
  include/maths/CKMeans.h
  include/maths/CLinearAlgebra.h
  include/maths/CLinearAlgebraEigen.h
  include/maths/CLinearAlgebraShims.h
  include/test/CDataFrameAnalysisSpecificationFactory.h
  lib/api/CBoostedTreeInferenceModelBuilder.cc
  lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
  lib/api/CDataFrameTrainBoostedTreeRegressionRunner.cc
  lib/api/CInferenceModelDefinition.cc
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
  lib/api/unittest/CDataFrameTrainBoostedTreeClassifierRunnerTest.cc
  lib/maths/CBoostedTree.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/CBoostedTreeLeafNodeStatistics.cc
  lib/maths/CBoostedTreeLoss.cc
  lib/maths/CDataFrameUtils.cc
  lib/maths/unittest/CBoostedTreeTest.cc
  lib/test/CDataFrameAnalysisSpecificationFactory.cc
Labels: >non-issue, backport, v7.7.0

#1057 [ML] Fix some bugs in multinomial logistic loss derivatives
  lib/maths/CBoostedTreeLoss.cc
  lib/maths/unittest/CBoostedTreeLossTest.cc
  lib/maths/unittest/CBoostedTreeTest.cc
Labels: :ml/DataFrameAnalysis, >bug, >non-issue, review, v7.7.0, v8.0.0

#1059 [7.6][ML] Correct logistic loss function
  docs/CHANGELOG.asciidoc
  include/maths/CBoostedTree.h
  lib/maths/CBoostedTree.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/unittest/CBoostedTreeTest.cc
Labels: backport, v7.6.2

#1061 [7.7][ML] Fix some bugs in multinomial logistic loss derivatives
  lib/maths/CBoostedTreeLoss.cc
  lib/maths/unittest/CBoostedTreeLossTest.cc
  lib/maths/unittest/CBoostedTreeTest.cc
Labels: >non-issue, backport, v7.7.0

#1063 [ML] Better handling of near singular loss Hessian
  include/maths/CBoostedTreeLeafNodeStatistics.h
  include/maths/CLinearAlgebraEigen.h
  lib/maths/CBoostedTreeLeafNodeStatistics.cc
  lib/maths/unittest/CBoostedTreeTest.cc
Labels: :ml/DataFrameAnalysis, >bug, >non-issue, review, v7.7.0, v8.0.0

#1064 [7.7][ML] Better handling of near singular loss Hessian
  include/maths/CBoostedTreeLeafNodeStatistics.h
  include/maths/CLinearAlgebraEigen.h
  lib/maths/CBoostedTreeLeafNodeStatistics.cc
  lib/maths/unittest/CBoostedTreeTest.cc
Labels: >non-issue, backport, v7.7.0

#1065 [ML] Fix the maximum accuracy objective for binary classification
  lib/maths/CBoostedTreeImpl.cc
Labels: :ml/DataFrameAnalysis, >bug, >non-issue, review, v7.7.0, v8.0.0

#1066 [7.7][ML] Fix the maximum accuracy objective for binary classification
  lib/maths/CBoostedTreeImpl.cc
Labels: >non-issue, backport, v7.7.0

#1031 [ML] Instrumentation information for boosted tree learning
  docs/CHANGELOG.asciidoc
  include/api/CDataFrameAnalysisInstrumentation.h
  include/maths/CBoostedTreeFactory.h
  include/maths/CBoostedTreeImpl.h
  include/maths/CDataFrameAnalysisInstrumentationInterface.h
  include/maths/COutliers.h
  include/test/CDataFrameAnalyzerTrainingFactory.h
  lib/api/CDataFrameAnalysisInstrumentation.cc
  lib/api/unittest/CDataFrameAnalysisInstrumentationTest.cc
  lib/api/unittest/CDataFrameAnalyzerOutlierTest.cc
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
  lib/api/unittest/CDataFrameMockAnalysisRunner.h
  lib/api/unittest/testfiles/instrumentation/classification_stats.schema.json
  lib/api/unittest/testfiles/instrumentation/memory_usage.schema.json
  lib/api/unittest/testfiles/instrumentation/outlier_detection_stats.schema.json
  lib/api/unittest/testfiles/instrumentation/regression_stats.schema.json
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/COutliers.cc
  lib/maths/unittest/CBoostedTreeTest.cc
  lib/maths/unittest/COutliersTest.cc
  lib/test/CDataFrameAnalyzerTrainingFactory.cc
  lib/test/Makefile
Labels: :ml, >enhancement, v7.7.0, v8.0.0

#1067 [7.x][ML] Instrumentation information for boosted tree learning
  docs/CHANGELOG.asciidoc
  include/api/CDataFrameAnalysisInstrumentation.h
  include/maths/CBoostedTreeFactory.h
  include/maths/CBoostedTreeImpl.h
  include/maths/CDataFrameAnalysisInstrumentationInterface.h
  include/maths/COutliers.h
  include/test/CDataFrameAnalyzerTrainingFactory.h
  lib/api/CDataFrameAnalysisInstrumentation.cc
  lib/api/unittest/CDataFrameAnalysisInstrumentationTest.cc
  lib/api/unittest/CDataFrameAnalyzerOutlierTest.cc
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
  lib/api/unittest/CDataFrameMockAnalysisRunner.h
  lib/api/unittest/testfiles/instrumentation/classification_stats.schema.json
  lib/api/unittest/testfiles/instrumentation/memory_usage.schema.json
  lib/api/unittest/testfiles/instrumentation/outlier_detection_stats.schema.json
  lib/api/unittest/testfiles/instrumentation/regression_stats.schema.json
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/COutliers.cc
  lib/maths/unittest/CBoostedTreeTest.cc
  lib/maths/unittest/COutliersTest.cc
  lib/test/CDataFrameAnalyzerTrainingFactory.cc
  lib/test/Makefile
Labels: :ml, >enhancement, backport, v7.7.0

#1069 [ML] Speed ups for multiclass classification
  include/maths/CBoostedTreeLoss.h
  include/maths/CLbfgs.h
  include/maths/CTools.h
  include/maths/CToolsDetail.h
  lib/api/CDataFrameAnalysisSpecification.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/CBoostedTreeLoss.cc
  lib/maths/unittest/CBoostedTreeLossTest.cc
  lib/maths/unittest/CBoostedTreeTest.cc
  lib/maths/unittest/CToolsTest.cc
Labels: :ml/DataFrameAnalysis, >enhancement, >non-issue, review, v7.7.0, v8.0.0

#1072 [7.7][ML] Speed ups for multiclass classification
  include/maths/CBoostedTreeLoss.h
  include/maths/CLbfgs.h
  include/maths/CTools.h
  include/maths/CToolsDetail.h
  lib/api/CDataFrameAnalysisSpecification.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/CBoostedTreeLoss.cc
  lib/maths/unittest/CBoostedTreeLossTest.cc
  lib/maths/unittest/CBoostedTreeTest.cc
  lib/maths/unittest/CToolsTest.cc
Labels: >non-issue, backport, v7.7.0

#1068 [ML] Instrumentation for outlier detection
  docs/CHANGELOG.asciidoc
  include/api/CDataFrameAnalysisInstrumentation.h
  include/maths/CDataFrameAnalysisInstrumentationInterface.h
  include/maths/COutliers.h
  lib/api/CDataFrameAnalysisInstrumentation.cc
  lib/api/CDataFrameOutliersRunner.cc
  lib/api/unittest/CDataFrameAnalysisInstrumentationTest.cc
  lib/api/unittest/testfiles/instrumentation/outlier_detection_stats.schema.json
  lib/maths/COutliers.cc
Labels: :ml, >enhancement, v7.7.0, v8.0.0

#1070 [ML] More speed ups for multiclass classification
  include/maths/CBoostedTreeLoss.h
  include/maths/CKMeans.h
  include/maths/CKMeansOnline.h
  include/maths/CKdTree.h
  include/maths/CLinearAlgebraShims.h
  lib/maths/CBoostedTreeLoss.cc
  lib/maths/unittest/CBoostedTreeTest.cc
  lib/maths/unittest/CKMeansOnlineTest.cc
  lib/maths/unittest/CKMeansTest.cc
  lib/maths/unittest/CMultivariateMultimodalPriorTest.cc
  lib/maths/unittest/CXMeansOnlineTest.cc
Labels: :ml/DataFrameAnalysis, >enhancement, >non-issue, review, v7.7.0, v8.0.0

#1073 [7.x][ML] Instrumentation for outlier detection
  docs/CHANGELOG.asciidoc
  include/api/CDataFrameAnalysisInstrumentation.h
  include/maths/CDataFrameAnalysisInstrumentationInterface.h
  include/maths/COutliers.h
  lib/api/CDataFrameAnalysisInstrumentation.cc
  lib/api/CDataFrameOutliersRunner.cc
  lib/api/unittest/CDataFrameAnalysisInstrumentationTest.cc
  lib/api/unittest/testfiles/instrumentation/outlier_detection_stats.schema.json
  lib/maths/COutliers.cc
Labels: :ml, >enhancement, backport, v7.7.0

#1071 [ML] calculate feature importance for multi-class results
  docs/CHANGELOG.asciidoc
  include/api/CDataFrameTrainBoostedTreeRunner.h
  include/maths/CTreeShapFeatureImportance.h
  include/test/CDataFrameAnalysisSpecificationFactory.h
  lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
  lib/api/CDataFrameTrainBoostedTreeRegressionRunner.cc
  lib/api/CDataFrameTrainBoostedTreeRunner.cc
  lib/api/unittest/CDataFrameAnalyzerFeatureImportanceTest.cc
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
  lib/maths/CTreeShapFeatureImportance.cc
  lib/maths/unittest/CTreeShapFeatureImportanceTest.cc
  lib/test/CDataFrameAnalysisSpecificationFactory.cc
Labels: :ml, >enhancement, v7.7.0, v8.0.0

#1075 [7.x] [ML] calculate feature importance for multi-class results (#1071)
  docs/CHANGELOG.asciidoc
  include/api/CDataFrameTrainBoostedTreeRunner.h
  include/maths/CTreeShapFeatureImportance.h
  include/test/CDataFrameAnalysisSpecificationFactory.h
  lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
  lib/api/CDataFrameTrainBoostedTreeRegressionRunner.cc
  lib/api/CDataFrameTrainBoostedTreeRunner.cc
  lib/api/unittest/CDataFrameAnalyzerFeatureImportanceTest.cc
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
  lib/maths/CTreeShapFeatureImportance.cc
  lib/maths/unittest/CTreeShapFeatureImportanceTest.cc
  lib/test/CDataFrameAnalysisSpecificationFactory.cc
Labels: :ml, backport

#1074 [7.7][ML] More speed ups for multiclass classification
  include/maths/CBoostedTreeLoss.h
  include/maths/CKMeans.h
  include/maths/CKMeansOnline.h
  include/maths/CKdTree.h
  include/maths/CLinearAlgebraShims.h
  lib/maths/CBoostedTreeLoss.cc
  lib/maths/unittest/CBoostedTreeTest.cc
  lib/maths/unittest/CKMeansOnlineTest.cc
  lib/maths/unittest/CKMeansTest.cc
  lib/maths/unittest/CMultivariateMultimodalPriorTest.cc
  lib/maths/unittest/CXMeansOnlineTest.cc
Labels: >non-issue, backport, v7.7.0

#1076 [ML] Activate instrumentation output
  lib/api/CDataFrameAnalysisInstrumentation.cc
  lib/api/unittest/CDataFrameAnalysisInstrumentationTest.cc
Labels: :ml, >non-issue, v7.7.0, v8.0.0

#1077 [7.x][ML] Activate instrumentation output
  lib/api/CDataFrameAnalysisInstrumentation.cc
  lib/api/unittest/CDataFrameAnalysisInstrumentationTest.cc
Labels: :ml, >non-issue, backport, v7.7.0

#1078 [ML] Fix non-optimised Linux compilation
  include/maths/CKMeansOnline.h
Labels: :ml, >non-issue, v7.7.0, v8.0.0

#1081 [7.x][ML] Fix non-optimised Linux compilation
  include/maths/CKMeansOnline.h
Labels: >non-issue, backport

#1082 [ML] Rework the approximate loss function for choosing leaf values for multiclass classification
  include/maths/CBoostedTreeLoss.h
  include/maths/CSampling.h
  lib/maths/CBoostedTreeLoss.cc
  lib/maths/CDataFrameUtils.cc
  lib/maths/COutliers.cc
  lib/maths/CSampling.cc
  lib/maths/unittest/CSamplingTest.cc
Labels: :ml/DataFrameAnalysis, >enhancement, >non-issue, review, v7.7.0, v7.8.0, v8.0.0

#1083 [ML] Avoid temporaries in vector expressions
  include/maths/CLbfgs.h
  include/maths/CLinearAlgebraEigen.h
  include/maths/CTools.h
  include/maths/CToolsDetail.h
  lib/api/unittest/CDataFrameAnalyzerFeatureImportanceTest.cc
  lib/maths/CBayesianOptimisation.cc
  lib/maths/CBoostedTreeLoss.cc
  lib/maths/unittest/CBoostedTreeLossTest.cc
  lib/maths/unittest/CBoostedTreeTest.cc
  lib/maths/unittest/CToolsTest.cc
Labels: :ml/DataFrameAnalysis, >non-issue, review, v7.7.0, v7.8.0, v8.0.0

#1084 [7.8][ML] Rework the approximate loss function for choosing leaf values for multiclass classification
  include/maths/CBoostedTreeLoss.h
  include/maths/CSampling.h
  lib/maths/CBoostedTreeLoss.cc
  lib/maths/CDataFrameUtils.cc
  lib/maths/COutliers.cc
  lib/maths/CSampling.cc
  lib/maths/unittest/CSamplingTest.cc
Labels: >non-issue, backport, v7.7.0

#1085 [7.7][ML] Rework the approximate loss function for choosing leaf values for multiclass classification
  include/maths/CBoostedTreeLoss.h
  include/maths/CSampling.h
  lib/maths/CBoostedTreeLoss.cc
  lib/maths/CDataFrameUtils.cc
  lib/maths/COutliers.cc
  lib/maths/CSampling.cc
  lib/maths/unittest/CSamplingTest.cc
Labels: >non-issue, backport, v7.7.0

#1087 [7.8][ML] Avoid temporaries in vector expressions
  include/maths/CLbfgs.h
  include/maths/CLinearAlgebraEigen.h
  include/maths/CTools.h
  include/maths/CToolsDetail.h
  lib/api/unittest/CDataFrameAnalyzerFeatureImportanceTest.cc
  lib/maths/CBayesianOptimisation.cc
  lib/maths/CBoostedTreeLoss.cc
  lib/maths/unittest/CBoostedTreeLossTest.cc
  lib/maths/unittest/CBoostedTreeTest.cc
  lib/maths/unittest/CToolsTest.cc
Labels: >non-issue, backport, v7.8.0

#1088 [7.7][ML] Avoid temporaries in vector expressions
  include/maths/CLbfgs.h
  include/maths/CLinearAlgebraEigen.h
  include/maths/CTools.h
  include/maths/CToolsDetail.h
  lib/api/unittest/CDataFrameAnalyzerFeatureImportanceTest.cc
  lib/maths/CBayesianOptimisation.cc
  lib/maths/CBoostedTreeLoss.cc
  lib/maths/unittest/CBoostedTreeLossTest.cc
  lib/maths/unittest/CBoostedTreeTest.cc
  lib/maths/unittest/CToolsTest.cc
Labels: >non-issue, backport, v7.7.0

#1086 [ML] Fix out-of-bounds read in multiclass feature importance unit test
  include/api/CDataFrameAnalysisInstrumentation.h
  include/maths/CSampling.h
  lib/api/CDataFrameAnalysisInstrumentation.cc
  lib/api/unittest/CDataFrameAnalysisInstrumentationTest.cc
  lib/api/unittest/CDataFrameAnalyzerFeatureImportanceTest.cc
Labels: :ml/DataFrameAnalysis, >bug, >non-issue, >test, review, v7.7.0, v7.8.0, v8.0.0

#1090 [7.8][ML] Fix out-of-bounds read in multiclass feature importance unit test
  include/api/CDataFrameAnalysisInstrumentation.h
  include/maths/CSampling.h
  lib/api/CDataFrameAnalysisInstrumentation.cc
  lib/api/unittest/CDataFrameAnalysisInstrumentationTest.cc
  lib/api/unittest/CDataFrameAnalyzerFeatureImportanceTest.cc
Labels: >non-issue, backport, v7.8.0

#1091 [7.7][ML] Fix out-of-bounds read in multiclass feature importance unit test
  include/api/CDataFrameAnalysisInstrumentation.h
  include/maths/CSampling.h
  lib/api/CDataFrameAnalysisInstrumentation.cc
  lib/api/unittest/CDataFrameAnalysisInstrumentationTest.cc
  lib/api/unittest/CDataFrameAnalyzerFeatureImportanceTest.cc
Labels: >non-issue, backport, v7.7.0

#1089 [ML] Extend .gitignore to work with VSCode
  .dockerignore
  .gitignore
Labels: :ml, >non-issue, v7.8.0, v8.0.0

#1079 [ML] Logging additional information for results
  lib/api/CDataFrameAnalyzer.cc
Labels: :ml, >non-issue, v7.7.0, v7.8.0, v8.0.0

#1093 [7.x][ML] Extend .gitignore to work with VSCode
  .dockerignore
  .gitignore
Labels: :ml, >non-issue, backport, v7.8.0

#1095 [7.7][ML] Logging additional information for results
  lib/api/CDataFrameAnalyzer.cc
Labels: :ml, >non-issue, backport, v7.7.0

#1094 [7.x][ML] Logging additional information for results (#1079)
  lib/api/CDataFrameAnalyzer.cc
Labels: :ml, >non-issue, backport, v7.8.0

#1092 [ML] Speedup calculating leaf values for multiclass classification
  include/maths/CBoostedTreeLoss.h
  lib/maths/CBoostedTreeLoss.cc
  lib/maths/unittest/CBoostedTreeLossTest.cc
Labels: :ml/DataFrameAnalysis, >enhancement, >non-issue, review, v7.7.0, v7.8.0, v8.0.0

#1098 [ML] Enable system call filter for data_frame_analyzer
  bin/data_frame_analyzer/Main.cc
  docs/CHANGELOG.asciidoc
Labels: :ml/DataFrameAnalysis, >enhancement, v7.7.0, v7.8.0, v8.0.0

#1096 [ML] Instrumentation parameter names should match analysis config where applicable
  include/api/CDataFrameTrainBoostedTreeClassifierRunner.h
  include/api/CDataFrameTrainBoostedTreeRunner.h
  include/maths/CBoostedTreeFactory.h
  lib/api/CDataFrameAnalysisInstrumentation.cc
  lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
  lib/api/CDataFrameTrainBoostedTreeRunner.cc
  lib/api/unittest/testfiles/instrumentation/classification_stats.schema.json
  lib/api/unittest/testfiles/instrumentation/regression_stats.schema.json
  lib/maths/CBoostedTreeFactory.cc
  lib/test/CDataFrameAnalysisSpecificationFactory.cc
Labels: :ml/DataFrameAnalysis, >non-issue, review, v7.7.0, v7.8.0, v8.0.0

#1100 [7.7][ML] Speedup calculating leaf values for multiclass classification
  include/maths/CBoostedTreeLoss.h
  lib/maths/CBoostedTreeLoss.cc
  lib/maths/unittest/CBoostedTreeLossTest.cc
Labels: >non-issue, backport, v7.7.0

#1103 [7.8][ML] Instrumentation parameter names should match analysis config where applicable
  include/api/CDataFrameTrainBoostedTreeClassifierRunner.h
  include/api/CDataFrameTrainBoostedTreeRunner.h
  include/maths/CBoostedTreeFactory.h
  lib/api/CDataFrameAnalysisInstrumentation.cc
  lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
  lib/api/CDataFrameTrainBoostedTreeRunner.cc
  lib/api/unittest/testfiles/instrumentation/classification_stats.schema.json
  lib/api/unittest/testfiles/instrumentation/regression_stats.schema.json
  lib/maths/CBoostedTreeFactory.cc
  lib/test/CDataFrameAnalysisSpecificationFactory.cc
Labels: >non-issue, backport, v7.8.0

#1099 [7.8][ML] Speedup calculating leaf values for multiclass classification
  include/maths/CBoostedTreeLoss.h
  lib/maths/CBoostedTreeLoss.cc
  lib/maths/unittest/CBoostedTreeLossTest.cc
Labels: >non-issue, backport, v7.8.0

#1104 [7.7][ML] Instrumentation parameter names should match analysis config where applicable
  include/api/CDataFrameTrainBoostedTreeClassifierRunner.h
  include/api/CDataFrameTrainBoostedTreeRunner.h
  include/maths/CBoostedTreeFactory.h
  lib/api/CDataFrameAnalysisInstrumentation.cc
  lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
  lib/api/CDataFrameTrainBoostedTreeRunner.cc
  lib/api/unittest/testfiles/instrumentation/classification_stats.schema.json
  lib/api/unittest/testfiles/instrumentation/regression_stats.schema.json
  lib/maths/CBoostedTreeFactory.cc
  lib/test/CDataFrameAnalysisSpecificationFactory.cc
Labels: >non-issue, backport, v7.7.0

#1107 [7.x][ML] Enable system call filter for data_frame_analyzer
  bin/data_frame_analyzer/Main.cc
  docs/CHANGELOG.asciidoc
Labels: backport

#1108 [7.7][ML] Enable system call filter for data_frame_analyzer
  bin/data_frame_analyzer/Main.cc
  docs/CHANGELOG.asciidoc
Labels: backport
