Repository elastic/ml-cpp, pull requests merged in 2020-10, with the labels that each got.

#1512 [7.10][ML] Avoid log spam when we only have missing values for a feature computing candidate splits for regression and classification
  docs/CHANGELOG.asciidoc
  lib/maths/CBoostedTreeImpl.cc
Labels: backport, v7.10.0

#1519 [ML] Fix total feature importance unit tests
  include/api/CInferenceModelMetadata.h
  lib/api/CInferenceModelMetadata.cc
Labels: :ml, >non-issue, v7.10.0, v8.0.0

#1521 [7.x][ML] Fix total feature importance unit tests
  include/api/CInferenceModelMetadata.h
  lib/api/CInferenceModelMetadata.cc
Labels: :ml, >non-issue, backport, v7.10.0

#1522 [ML] Store feature importance baselines in model metadata
  include/api/CInferenceModelMetadata.h
  include/maths/CTreeShapFeatureImportance.h
  lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
  lib/api/CDataFrameTrainBoostedTreeRegressionRunner.cc
  lib/api/CInferenceModelMetadata.cc
  lib/api/unittest/CDataFrameAnalyzerFeatureImportanceTest.cc
  lib/maths/CTreeShapFeatureImportance.cc
Labels: :ml, >non-issue, v7.10.0, v8.0.0

#1524 [7.10][ML] Store feature importance baselines in model metadata (#1522)
  include/api/CInferenceModelMetadata.h
  include/maths/CTreeShapFeatureImportance.h
  lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
  lib/api/CDataFrameTrainBoostedTreeRegressionRunner.cc
  lib/api/CInferenceModelMetadata.cc
  lib/api/unittest/CDataFrameAnalyzerFeatureImportanceTest.cc
  lib/maths/CTreeShapFeatureImportance.cc
Labels: >non-issue, backport, v7.10.0

#1523 [ML] Move model test helper functions to base class
  lib/model/unittest/CCountingModelTest.cc
  lib/model/unittest/CEventRateModelTest.cc
  lib/model/unittest/CEventRatePopulationModelTest.cc
  lib/model/unittest/CMetricModelTest.cc
  lib/model/unittest/CMetricPopulationModelTest.cc
  lib/model/unittest/CModelTestFixtureBase.cc
  lib/model/unittest/CModelTestFixtureBase.h
  lib/model/unittest/Makefile
Labels: :ml, >non-issue, >test, review, v7.10.0, v8.0.0

#1525 [7.x][ML] Move model test helper functions to base class (#1523)
  lib/model/unittest/CCountingModelTest.cc
  lib/model/unittest/CEventRateModelTest.cc
  lib/model/unittest/CEventRatePopulationModelTest.cc
  lib/model/unittest/CMetricModelTest.cc
  lib/model/unittest/CMetricPopulationModelTest.cc
  lib/model/unittest/CModelTestFixtureBase.cc
  lib/model/unittest/CModelTestFixtureBase.h
  lib/model/unittest/Makefile
Labels: :ml, >non-issue, backport, v7.10.0

#1526 [ML] Allow unbounded num_top_classes in classification analysis
  include/api/CDataFrameAnalysisConfigReader.h
  include/api/CDataFrameTrainBoostedTreeClassifierRunner.h
  lib/api/CDataFrameAnalysisConfigReader.cc
  lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
Labels: :ml, >non-issue, v7.10.0, v7.11.0, v8.0.0

#1528 [7.x] [ML] Allow unbounded num_top_classes in classification analysis (#1526)
  include/api/CDataFrameAnalysisConfigReader.h
  include/api/CDataFrameTrainBoostedTreeClassifierRunner.h
  lib/api/CDataFrameAnalysisConfigReader.cc
  lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
Labels: :ml, >non-issue, backport

#1529 [7.10] [ML] Allow unbounded num_top_classes in classification analysis (#1526)
  include/api/CDataFrameAnalysisConfigReader.h
  include/api/CDataFrameTrainBoostedTreeClassifierRunner.h
  lib/api/CDataFrameAnalysisConfigReader.cc
  lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
Labels: :ml, >non-issue, backport

#1531 [ML] Remove some dead code
  include/maths/CSignal.h
  lib/maths/CSignal.cc
  lib/maths/CTimeSeriesTestForSeasonality.cc
  lib/maths/unittest/CSignalTest.cc
Labels: :ml, >non-issue, >refactoring, review

#1530 [ML] Anomaly detection residual model initialisation improvements
  include/maths/CExpandingWindow.h
  include/maths/CTimeSeriesDecomposition.h
  include/maths/CTimeSeriesDecompositionDetail.h
  include/maths/CTimeSeriesDecompositionInterface.h
  include/maths/CTimeSeriesDecompositionStub.h
  include/maths/CTimeSeriesSegmentation.h
  include/maths/CTimeSeriesTestForSeasonality.h
  lib/api/unittest/CRestorePreviousStateTest.cc
  lib/maths/CExpandingWindow.cc
  lib/maths/CTimeSeriesDecomposition.cc
  lib/maths/CTimeSeriesDecompositionDetail.cc
  lib/maths/CTimeSeriesDecompositionStub.cc
  lib/maths/CTimeSeriesModel.cc
  lib/maths/CTimeSeriesSegmentation.cc
  lib/maths/CTimeSeriesTestForSeasonality.cc
  lib/maths/unittest/CTimeSeriesDecompositionTest.cc
  lib/maths/unittest/CTimeSeriesModelTest.cc
Labels: :ml, >enhancement, >non-issue, affects-results, review

#1527 [ML] Provide factory setup for creating models
  lib/model/unittest/CCountingModelTest.cc
  lib/model/unittest/CEventRateModelTest.cc
  lib/model/unittest/CEventRatePopulationModelTest.cc
  lib/model/unittest/CMetricModelTest.cc
  lib/model/unittest/CMetricPopulationModelTest.cc
  lib/model/unittest/CModelTestFixtureBase.h
Labels: :ml, >non-issue, >test, review, v7.11.0, v8.0.0

#1532 [7.x][ML] Provide factory setup for creating models (#1527)
  lib/model/unittest/CCountingModelTest.cc
  lib/model/unittest/CEventRateModelTest.cc
  lib/model/unittest/CEventRatePopulationModelTest.cc
  lib/model/unittest/CMetricModelTest.cc
  lib/model/unittest/CMetricPopulationModelTest.cc
  lib/model/unittest/CModelTestFixtureBase.h
Labels: :ml, >non-issue, >test, backport, v7.11.0

#1516 [ML] Prefer smaller models with similar performance
  docs/CHANGELOG.asciidoc
  include/maths/CBoostedTreeImpl.h
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/unittest/CBoostedTreeTest.cc
Labels: :ml, >enhancement, >non-issue, v7.11.0, v8.0.0

#1533 [7.x][ML] Prefer smaller models with similar performance
  docs/CHANGELOG.asciidoc
  include/maths/CBoostedTreeImpl.h
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/unittest/CBoostedTreeTest.cc
Labels: :ml, >enhancement, backport, v7.11.0

#1535 [ML] Retry pulling of Docker images to work around network issues
  dev-tools/docker/build_check_style_image.sh
  dev-tools/docker/build_linux_aarch64_cross_build_image.sh
  dev-tools/docker/build_linux_aarch64_native_build_image.sh
  dev-tools/docker/build_linux_build_image.sh
  dev-tools/docker/build_macosx_build_image.sh
  dev-tools/docker/prefetch_docker_image.sh
  dev-tools/docker_build.sh
  dev-tools/docker_check_style.sh
  dev-tools/docker_test.sh
  dev-tools/jenkins_ci.sh
Labels: :ml, >build, v7.11.0, v8.0.0

#1536 [ML] Amalgamate addArrival methods
  lib/model/unittest/CCountingModelTest.cc
  lib/model/unittest/CEventRateModelTest.cc
  lib/model/unittest/CEventRatePopulationModelTest.cc
  lib/model/unittest/CMetricModelTest.cc
  lib/model/unittest/CMetricPopulationModelTest.cc
  lib/model/unittest/CModelTestFixtureBase.cc
  lib/model/unittest/CModelTestFixtureBase.h
Labels: :ml, >non-issue, >test, review, v7.11.0, v8.0.0

#1539 [7.x][ML] Amalgamate addArrival methods in model tests (#1536)
  lib/model/unittest/CCountingModelTest.cc
  lib/model/unittest/CEventRateModelTest.cc
  lib/model/unittest/CEventRatePopulationModelTest.cc
  lib/model/unittest/CMetricModelTest.cc
  lib/model/unittest/CMetricPopulationModelTest.cc
  lib/model/unittest/CModelTestFixtureBase.cc
  lib/model/unittest/CModelTestFixtureBase.h
Labels: :ml, >non-issue, >test, backport, v7.11.0

#1538 [7.x][ML] Retry pulling of Docker images to work around network issues
  dev-tools/docker/build_check_style_image.sh
  dev-tools/docker/build_linux_aarch64_cross_build_image.sh
  dev-tools/docker/build_linux_aarch64_native_build_image.sh
  dev-tools/docker/build_linux_build_image.sh
  dev-tools/docker/build_macosx_build_image.sh
  dev-tools/docker/prefetch_docker_image.sh
  dev-tools/docker_build.sh
  dev-tools/docker_check_style.sh
  dev-tools/docker_test.sh
  dev-tools/jenkins_ci.sh
Labels: backport, v7.11.0

#1540 [ML] Add argument for config file to autodetect
  bin/autodetect/CCmdLineParser.cc
  bin/autodetect/CCmdLineParser.h
  bin/autodetect/Main.cc
Labels: :ml, >non-issue, >refactoring, review, v7.11.0, v8.0.0

#1541 [7.x][ML] Add argument for config file to autodetect (#1540)
  bin/autodetect/CCmdLineParser.cc
  bin/autodetect/CCmdLineParser.h
  bin/autodetect/Main.cc
Labels: :ml, >non-issue, backport, v7.11.0

#1520 [ML] Make controller send responses for each command received
  bin/autodetect/CCmdLineParser.cc
  bin/controller/CCmdLineParser.cc
  bin/controller/CCmdLineParser.h
  bin/controller/CCommandProcessor.cc
  bin/controller/CCommandProcessor.h
  bin/controller/CResponseJsonWriter.cc
  bin/controller/CResponseJsonWriter.h
  bin/controller/Main.cc
  bin/controller/Makefile
  bin/controller/unittest/CCommandProcessorTest.cc
  bin/controller/unittest/CResponseJsonWriterTest.cc
  bin/controller/unittest/Makefile
  docs/CHANGELOG.asciidoc
Labels: :ml, >enhancement, v7.11.0, v8.0.0

#1534 [7.x][ML] Make controller send responses for each command received
  bin/autodetect/CCmdLineParser.cc
  bin/controller/CCmdLineParser.cc
  bin/controller/CCmdLineParser.h
  bin/controller/CCommandProcessor.cc
  bin/controller/CCommandProcessor.h
  bin/controller/CResponseJsonWriter.cc
  bin/controller/CResponseJsonWriter.h
  bin/controller/Main.cc
  bin/controller/Makefile
  bin/controller/unittest/CCommandProcessorTest.cc
  bin/controller/unittest/CResponseJsonWriterTest.cc
  bin/controller/unittest/Makefile
  docs/CHANGELOG.asciidoc
Labels: backport, v7.11.0

#1542 [7.10][ML] Retry pulling of Docker images to work around network issues
  dev-tools/docker/build_check_style_image.sh
  dev-tools/docker/build_linux_aarch64_cross_build_image.sh
  dev-tools/docker/build_linux_aarch64_native_build_image.sh
  dev-tools/docker/build_linux_build_image.sh
  dev-tools/docker/build_macosx_build_image.sh
  dev-tools/docker/prefetch_docker_image.sh
  dev-tools/docker_build.sh
  dev-tools/docker_check_style.sh
  dev-tools/docker_test.sh
  dev-tools/jenkins_ci.sh
Labels: backport, v7.10.0

#1543 [ML] Time series segmentation improvements
  include/maths/CSignal.h
  include/maths/CTimeSeriesSegmentation.h
  include/maths/CTimeSeriesTestForSeasonality.h
  lib/maths/CSignal.cc
  lib/maths/CTimeSeriesChangeDetector.cc
  lib/maths/CTimeSeriesModel.cc
  lib/maths/CTimeSeriesSegmentation.cc
  lib/maths/CTimeSeriesTestForSeasonality.cc
  lib/maths/unittest/CForecastTest.cc
  lib/maths/unittest/CSignalTest.cc
  lib/maths/unittest/CTimeSeriesDecompositionTest.cc
  lib/maths/unittest/CTimeSeriesModelTest.cc
  lib/maths/unittest/CTimeSeriesSegmentationTest.cc
  lib/maths/unittest/CTimeSeriesTestForSeasonalityTest.cc
  lib/model/unittest/CMetricModelTest.cc
Labels: >enhancement, >non-issue, review

#1546 [ML] Correcting model state min_version
  docs/CHANGELOG.asciidoc
  lib/api/CAnomalyJob.cc
Labels: :ml, >bug, v7.10.0, v7.11.0, v8.0.0

#1547 [7.x][ML] Correcting model state min_version
  docs/CHANGELOG.asciidoc
  lib/api/CAnomalyJob.cc
Labels: backport, v7.11.0

#1548 [7.10][ML] Correcting model state min_version
  docs/CHANGELOG.asciidoc
  lib/api/CAnomalyJob.cc
Labels: backport, v7.10.0

#1544 [ML] Time series time shift segmentation
  include/maths/CTimeSeriesSegmentation.h
  lib/maths/CTimeSeriesSegmentation.cc
  lib/maths/unittest/CTimeSeriesSegmentationTest.cc
Labels: :ml, >enhancement, >non-issue, review
