Repository elastic/ml-cpp, pull requests merged in 2020-01, with the labels that each got.

#921 [ML] Copy categorization data structures before background persist
  docs/CHANGELOG.asciidoc
  include/api/CPersistenceManager.h
  include/model/CBaseTokenListDataCategorizer.h
  include/model/CDataCategorizer.h
  lib/api/CFieldDataCategorizer.cc
  lib/api/unittest/CPersistenceManagerTest.cc
  lib/model/CBaseTokenListDataCategorizer.cc
Labels: :ml, >bug, v7.5.2, v7.6.0, v8.0.0

#923 [7.x][ML] Copy categorization data structures before background persist
  docs/CHANGELOG.asciidoc
  include/api/CPersistenceManager.h
  include/model/CBaseTokenListDataCategorizer.h
  include/model/CDataCategorizer.h
  lib/api/CFieldDataCategorizer.cc
  lib/api/unittest/CPersistenceManagerTest.cc
  lib/model/CBaseTokenListDataCategorizer.cc
Labels: backport

#924 [7.5][ML] Copy categorization data structures before background persist
  docs/CHANGELOG.asciidoc
  include/api/CBaseTokenListDataTyper.h
  include/api/CDataTyper.h
  lib/api/CBaseTokenListDataTyper.cc
  lib/api/CFieldDataTyper.cc
  lib/api/unittest/CPersistenceManagerTest.cc
  lib/api/unittest/CPersistenceManagerTest.h
Labels: backport

#920 [ML] Fix return of SHAP values for dependent variable issue
  lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
  lib/api/CDataFrameTrainBoostedTreeRegressionRunner.cc
  lib/api/unittest/CDataFrameAnalyzerFeatureImportanceTest.cc
  lib/maths/CBoostedTreeImpl.cc
Labels: :ml, >non-issue, review, v7.6.0, v8.0.0

#925 [7.6][ML] Fix return of SHAP values for dependent variable issue
  lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
  lib/api/CDataFrameTrainBoostedTreeRegressionRunner.cc
  lib/api/unittest/CDataFrameAnalyzerFeatureImportanceTest.cc
  lib/maths/CBoostedTreeImpl.cc
Labels: :ml, >non-issue, backport, v7.6.0

#928 [ML] Rename top_shap_values param to top_feature_importance_values
  include/api/CDataFrameTrainBoostedTreeRunner.h
  lib/api/CDataFrameTrainBoostedTreeRunner.cc
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
  lib/test/CDataFrameAnalysisSpecificationFactory.cc
Labels: :ml, :ml/DataFrameAnalysis, >non-issue, v7.6.0, v8.0.0

#930 [7.x][ML] Rename top_shap_values param to top_feature_importance_valu…
  include/api/CDataFrameTrainBoostedTreeRunner.h
  lib/api/CDataFrameTrainBoostedTreeRunner.cc
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
  lib/test/CDataFrameAnalysisSpecificationFactory.cc
Labels: :ml, :ml/DataFrameAnalysis, >non-issue, backport

#915 [ML] Stop cross-validation early if the parameters have high predicted test loss
  docs/CHANGELOG.asciidoc
  include/api/CDataFrameTrainBoostedTreeRunner.h
  include/maths/CBoostedTreeFactory.h
  include/maths/CBoostedTreeImpl.h
  include/maths/CTreeShapFeatureImportance.h
  lib/api/CDataFrameTrainBoostedTreeRunner.cc
  lib/api/unittest/CDataFrameAnalyzerFeatureImportanceTest.cc
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/CTreeShapFeatureImportance.cc
Labels: :ml/DataFrameAnalysis, >enhancement, review, v7.6.0, v8.0.0

#931 [7.6][ML] Stop cross-validation early if the parameters have high predicted test loss
  docs/CHANGELOG.asciidoc
  include/api/CDataFrameTrainBoostedTreeRunner.h
  include/maths/CBoostedTreeFactory.h
  include/maths/CBoostedTreeImpl.h
  include/maths/CTreeShapFeatureImportance.h
  lib/api/CDataFrameTrainBoostedTreeRunner.cc
  lib/api/unittest/CDataFrameAnalyzerFeatureImportanceTest.cc
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/CTreeShapFeatureImportance.cc
Labels: backport, v7.6.0

#929 [ML] Fix unit test segfault
  lib/api/unittest/CDataFrameAnalyzerFeatureImportanceTest.cc
Labels: :ml, >non-issue, v7.6.0, v8.0.0

#932 [ML] Rename to num_top_feature_importance_values
  include/api/CDataFrameTrainBoostedTreeRunner.h
  lib/api/CDataFrameTrainBoostedTreeRunner.cc
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
  lib/test/CDataFrameAnalysisSpecificationFactory.cc
Labels: :ml, :ml/DataFrameAnalysis, >non-issue, v7.6.0, v8.0.0

#933 [7.6][ML] Fix unit test segfault
  lib/api/unittest/CDataFrameAnalyzerFeatureImportanceTest.cc
Labels: :ml, >non-issue, backport, v7.6.0

#934 [7.x][ML] Rename to num_top_feature_importance_values (#932)
  include/api/CDataFrameTrainBoostedTreeRunner.h
  lib/api/CDataFrameTrainBoostedTreeRunner.cc
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
  lib/test/CDataFrameAnalysisSpecificationFactory.cc
Labels: :ml, :ml/DataFrameAnalysis, >non-issue, backport

#926 [ML] Set the class assignment probability threshold to maximise minimum recall
  docs/CHANGELOG.asciidoc
  include/api/CDataFrameTrainBoostedTreeClassifierRunner.h
  include/maths/CBoostedTree.h
  include/maths/CBoostedTreeFactory.h
  include/maths/CBoostedTreeImpl.h
  include/maths/CDataFramePredictiveModel.h
  include/maths/CDataFrameUtils.h
  include/maths/CSolvers.h
  lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
  lib/api/unittest/CDataFrameAnalyzerFeatureImportanceTest.cc
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
  lib/api/unittest/CDataFrameTrainBoostedTreeClassifierRunnerTest.cc
  lib/maths/CBoostedTree.cc
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/CDataFramePredictiveModel.cc
  lib/maths/CDataFrameUtils.cc
  lib/maths/Makefile
  lib/maths/unittest/CBoostedTreeTest.cc
Labels: :ml/DataFrameAnalysis, >enhancement, review, v7.6.0, v8.0.0

#936 [7.6][ML] Set the class assignment probability threshold to maximise minimum recall
  docs/CHANGELOG.asciidoc
  include/api/CDataFrameTrainBoostedTreeClassifierRunner.h
  include/maths/CBoostedTree.h
  include/maths/CBoostedTreeFactory.h
  include/maths/CBoostedTreeImpl.h
  include/maths/CDataFramePredictiveModel.h
  include/maths/CDataFrameUtils.h
  include/maths/CSolvers.h
  lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
  lib/api/unittest/CDataFrameAnalyzerFeatureImportanceTest.cc
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
  lib/api/unittest/CDataFrameTrainBoostedTreeClassifierRunnerTest.cc
  lib/maths/CBoostedTree.cc
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/CDataFramePredictiveModel.cc
  lib/maths/CDataFrameUtils.cc
  lib/maths/Makefile
  lib/maths/unittest/CBoostedTreeTest.cc
Labels: backport, v7.6.0

#937 [ML] Correct the top class probabilities
  include/api/CDataFrameTrainBoostedTreeClassifierRunner.h
  include/api/CDataFrameTrainBoostedTreeRegressionRunner.h
  include/test/CDataFrameAnalysisSpecificationFactory.h
  lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
  lib/api/CDataFrameTrainBoostedTreeRegressionRunner.cc
  lib/api/unittest/CBoostedTreeInferenceModelBuilderTest.cc
  lib/api/unittest/CDataFrameAnalyzerFeatureImportanceTest.cc
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
  lib/api/unittest/CDataFrameTrainBoostedTreeClassifierRunnerTest.cc
  lib/api/unittest/CDataFrameTrainBoostedTreeRegressionRunnerTest.cc
  lib/test/CDataFrameAnalysisSpecificationFactory.cc
Labels: :ml/DataFrameAnalysis, >non-issue, review, v7.6.0, v7.7.0, v8.0.0

#939 [7.7][ML] Correct top class probabilities
  include/api/CDataFrameTrainBoostedTreeClassifierRunner.h
  include/api/CDataFrameTrainBoostedTreeRegressionRunner.h
  include/test/CDataFrameAnalysisSpecificationFactory.h
  lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
  lib/api/CDataFrameTrainBoostedTreeRegressionRunner.cc
  lib/api/unittest/CBoostedTreeInferenceModelBuilderTest.cc
  lib/api/unittest/CDataFrameAnalyzerFeatureImportanceTest.cc
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
  lib/api/unittest/CDataFrameTrainBoostedTreeClassifierRunnerTest.cc
  lib/api/unittest/CDataFrameTrainBoostedTreeRegressionRunnerTest.cc
  lib/test/CDataFrameAnalysisSpecificationFactory.cc
Labels: >non-issue, backport, v7.7.0

#940 [ML] Fix memory leak in tokenization tests
  lib/maths/unittest/CNaiveBayesTest.cc
  lib/model/unittest/CTokenListDataCategorizerTest.cc
Labels: :ml, >test, v7.6.0, v7.7.0, v8.0.0

#943 [7.x][ML] Fix memory leak in tokenization tests
  lib/maths/unittest/CNaiveBayesTest.cc
  lib/model/unittest/CTokenListDataCategorizerTest.cc
Labels: >test, backport

#944 [7.6][ML] Fix memory leak in tokenization tests
  lib/maths/unittest/CNaiveBayesTest.cc
  lib/model/unittest/CTokenListDataCategorizerTest.cc
Labels: >test, backport

#941 [7.6][ML] Correct top class probabilities
  include/api/CDataFrameTrainBoostedTreeClassifierRunner.h
  include/api/CDataFrameTrainBoostedTreeRegressionRunner.h
  include/test/CDataFrameAnalysisSpecificationFactory.h
  lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
  lib/api/CDataFrameTrainBoostedTreeRegressionRunner.cc
  lib/api/unittest/CBoostedTreeInferenceModelBuilderTest.cc
  lib/api/unittest/CDataFrameAnalyzerFeatureImportanceTest.cc
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
  lib/api/unittest/CDataFrameTrainBoostedTreeClassifierRunnerTest.cc
  lib/api/unittest/CDataFrameTrainBoostedTreeRegressionRunnerTest.cc
  lib/test/CDataFrameAnalysisSpecificationFactory.cc
Labels: >non-issue, backport, v7.6.0

#938 [ML] Write out classification weights in the model definition
  include/api/CBoostedTreeInferenceModelBuilder.h
  include/api/CInferenceModelDefinition.h
  include/maths/CBoostedTree.h
  lib/api/CBoostedTreeInferenceModelBuilder.cc
  lib/api/CBoostedTreeRegressionInferenceModelBuilder.cc
  lib/api/CInferenceModelDefinition.cc
  lib/api/Makefile.first
  lib/api/unittest/CBoostedTreeInferenceModelBuilderTest.cc
  lib/maths/CBoostedTreeImpl.cc
Labels: :ml/DataFrameAnalysis, >non-issue, review, v7.6.0, v7.7.0, v8.0.0

#945 [ML] Default initialise the best hyperparameters
  include/maths/CBoostedTreeHyperparameters.h
Labels: :ml/DataFrameAnalysis, >non-issue, review, v7.7.0, v8.0.0

#946 [7.7][ML] Write out classification weights in the model definition
  include/api/CBoostedTreeInferenceModelBuilder.h
  include/api/CInferenceModelDefinition.h
  include/maths/CBoostedTree.h
  lib/api/CBoostedTreeInferenceModelBuilder.cc
  lib/api/CBoostedTreeRegressionInferenceModelBuilder.cc
  lib/api/CInferenceModelDefinition.cc
  lib/api/Makefile.first
  lib/api/unittest/CBoostedTreeInferenceModelBuilderTest.cc
  lib/maths/CBoostedTreeImpl.cc
Labels: >non-issue, backport, v7.7.0

#947 [7.6][ML] Write out classification weights in the model definition
  include/api/CBoostedTreeInferenceModelBuilder.h
  include/api/CInferenceModelDefinition.h
  include/maths/CBoostedTree.h
  lib/api/CBoostedTreeInferenceModelBuilder.cc
  lib/api/CBoostedTreeRegressionInferenceModelBuilder.cc
  lib/api/CInferenceModelDefinition.cc
  lib/api/Makefile.first
  lib/api/unittest/CBoostedTreeInferenceModelBuilderTest.cc
  lib/maths/CBoostedTreeImpl.cc
Labels: >non-issue, backport, v7.6.0

#950 [ML] Include out-of-order as well as in-order terms in reverse search
  docs/CHANGELOG.asciidoc
  include/model/CTokenListReverseSearchCreator.h
  include/model/CTokenListReverseSearchCreatorIntf.h
  lib/api/unittest/CFieldDataCategorizerTest.cc
  lib/model/CTokenListDataCategorizerBase.cc
  lib/model/CTokenListReverseSearchCreator.cc
  lib/model/unittest/CTokenListReverseSearchCreatorTest.cc
Labels: :ml, >bug, v6.8.7, v7.6.0, v7.7.0, v8.0.0

#951 [ML] Fix invalid read in tests
  lib/maths/CBoostedTree.cc
  lib/maths/unittest/CTreeShapFeatureImportanceTest.cc
Labels: >test, review, v7.6.0, v7.7.0, v8.0.0

#954 [7.x][ML] Include out-of-order as well as in-order terms in reverse search
  docs/CHANGELOG.asciidoc
  include/model/CTokenListReverseSearchCreator.h
  include/model/CTokenListReverseSearchCreatorIntf.h
  lib/api/unittest/CFieldDataCategorizerTest.cc
  lib/model/CTokenListDataCategorizerBase.cc
  lib/model/CTokenListReverseSearchCreator.cc
  lib/model/unittest/CTokenListReverseSearchCreatorTest.cc
Labels: backport

#956 [6.8][ML] Include out-of-order as well as in-order terms in reverse search
  docs/CHANGELOG.asciidoc
  include/api/CTokenListReverseSearchCreator.h
  include/api/CTokenListReverseSearchCreatorIntf.h
  lib/api/CBaseTokenListDataTyper.cc
  lib/api/CTokenListReverseSearchCreator.cc
  lib/api/unittest/CFieldDataTyperTest.cc
  lib/api/unittest/CFieldDataTyperTest.h
  lib/api/unittest/CTokenListReverseSearchCreatorTest.cc
  lib/api/unittest/CTokenListReverseSearchCreatorTest.h
Labels: backport

#952 [7.7][ML] Fix invalid read in tests
  lib/maths/CBoostedTree.cc
  lib/maths/unittest/CTreeShapFeatureImportanceTest.cc
Labels: >bug, >non-issue, backport, v7.7.0

#955 [7.6][ML] Include out-of-order as well as in-order terms in reverse search
  docs/CHANGELOG.asciidoc
  include/model/CTokenListReverseSearchCreator.h
  include/model/CTokenListReverseSearchCreatorIntf.h
  lib/api/unittest/CFieldDataCategorizerTest.cc
  lib/model/CTokenListDataCategorizerBase.cc
  lib/model/CTokenListReverseSearchCreator.cc
  lib/model/unittest/CTokenListReverseSearchCreatorTest.cc
Labels: backport

#953 [7.6][ML] Fix invalid read in tests
  lib/maths/CBoostedTree.cc
  lib/maths/unittest/CTreeShapFeatureImportanceTest.cc
Labels: >bug, >non-issue, backport, v7.6.0

#957 [ML] Remove abstract interface for reverse search creation
  include/model/CTokenListDataCategorizer.h
  include/model/CTokenListDataCategorizerBase.h
  include/model/CTokenListReverseSearchCreator.h
  include/model/CTokenListReverseSearchCreatorIntf.h
  lib/api/CFieldDataCategorizer.cc
  lib/model/CTokenListDataCategorizerBase.cc
  lib/model/CTokenListReverseSearchCreator.cc
  lib/model/CTokenListReverseSearchCreatorIntf.cc
  lib/model/Makefile
  lib/model/unittest/CTokenListDataCategorizerTest.cc
  lib/model/unittest/CTokenListReverseSearchCreatorTest.cc
Labels: :ml, >refactoring, v7.7.0, v8.0.0

#958 [7.x][ML] Remove abstract interface for reverse search creation
  include/model/CTokenListDataCategorizer.h
  include/model/CTokenListDataCategorizerBase.h
  include/model/CTokenListReverseSearchCreator.h
  include/model/CTokenListReverseSearchCreatorIntf.h
  lib/api/CFieldDataCategorizer.cc
  lib/model/CTokenListDataCategorizerBase.cc
  lib/model/CTokenListReverseSearchCreator.cc
  lib/model/CTokenListReverseSearchCreatorIntf.cc
  lib/model/Makefile
  lib/model/unittest/CTokenListDataCategorizerTest.cc
  lib/model/unittest/CTokenListReverseSearchCreatorTest.cc
Labels: >refactoring, backport

#960 [ML] Downgrade noisy logging to trace logging
  lib/api/CDataFrameAnalysisSpecification.cc
Labels: :ml/DataFrameAnalysis, >bug, >non-issue, review, v7.6.0, v7.7.0, v8.0.0

#962 [7.7][ML] Downgrade noisy logging to trace
  lib/api/CDataFrameAnalysisSpecification.cc
Labels: >non-issue, backport, v7.7.0

#963 [7.6][ML] Downgrade noisy logging to trace
  lib/api/CDataFrameAnalysisSpecification.cc
Labels: >non-issue, backport, v7.6.0

#948 [ML] Line search for best learn rate
  docs/CHANGELOG.asciidoc
  include/core/CLoopProgress.h
  include/maths/CBoostedTreeFactory.h
  lib/core/CLoopProgress.cc
  lib/core/unittest/CLoopProgressTest.cc
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/unittest/CBoostedTreeTest.cc
Labels: :ml/DataFrameAnalysis, >enhancement, review, v7.7.0, v8.0.0

#966 [ML] Modernize the categorization code
  include/model/CDataCategorizer.h
  include/model/CTokenListCategory.h
  include/model/CTokenListDataCategorizer.h
  include/model/CTokenListDataCategorizerBase.h
  include/model/CTokenListReverseSearchCreator.h
  lib/api/CFieldDataCategorizer.cc
  lib/api/unittest/CRestorePreviousStateTest.cc
  lib/model/CDataCategorizer.cc
  lib/model/CTokenListCategory.cc
  lib/model/CTokenListDataCategorizerBase.cc
  lib/model/CTokenListReverseSearchCreator.cc
  lib/model/unittest/CTokenListCategoryTest.cc
  lib/model/unittest/CTokenListDataCategorizerBaseTest.cc
  lib/model/unittest/CTokenListReverseSearchCreatorTest.cc
  lib/model/unittest/Makefile
Labels: :ml, >refactoring, v7.7.0, v8.0.0

#965 [ML] Bug in bounds calculation for the main optimisation hyperparameter search
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/unittest/CBoostedTreeTest.cc
Labels: :ml/DataFrameAnalysis, >bug, >non-issue, review, v7.6.0, v7.7.0, v8.0.0

#964 [7.7][ML] Line search for best learn rate
  docs/CHANGELOG.asciidoc
  include/core/CLoopProgress.h
  include/maths/CBoostedTreeFactory.h
  lib/core/CLoopProgress.cc
  lib/core/unittest/CLoopProgressTest.cc
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/unittest/CBoostedTreeTest.cc
Labels: backport, v7.7.0

#967 [7.x][ML] Modernize the categorization code
  include/model/CDataCategorizer.h
  include/model/CTokenListCategory.h
  include/model/CTokenListDataCategorizer.h
  include/model/CTokenListDataCategorizerBase.h
  include/model/CTokenListReverseSearchCreator.h
  lib/api/CFieldDataCategorizer.cc
  lib/api/unittest/CRestorePreviousStateTest.cc
  lib/model/CDataCategorizer.cc
  lib/model/CTokenListCategory.cc
  lib/model/CTokenListDataCategorizerBase.cc
  lib/model/CTokenListReverseSearchCreator.cc
  lib/model/unittest/CTokenListCategoryTest.cc
  lib/model/unittest/CTokenListDataCategorizerBaseTest.cc
  lib/model/unittest/CTokenListReverseSearchCreatorTest.cc
  lib/model/unittest/Makefile
Labels: >refactoring, backport

#968 [7.7][ML] Bug in bounds calculation for the main hyperparameter optimisation search
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/unittest/CBoostedTreeTest.cc
Labels: >non-issue, backport, v7.7.0

#969 [7.6][ML] Bug in bounds calculation for the main hyperparameter optimisation search
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/unittest/CBoostedTreeTest.cc
Labels: >non-issue, backport, v7.6.0

#971 [ML] Adjust test threshold for debug build
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
Labels: :ml/DataFrameAnalysis, >test, v7.7.0, v8.0.0

#972 [7.x][ML] Adjust test threshold for debug build
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
Labels: >test, backport

#975 [ML] Update the inference schema model definition unit test
  include/api/CInferenceModelDefinition.h
  lib/api/CBoostedTreeInferenceModelBuilder.cc
  lib/api/CInferenceModelDefinition.cc
  lib/api/unittest/CBoostedTreeInferenceModelBuilderTest.cc
  lib/api/unittest/testfiles/inference_json_schema/model_definition.schema.json
Labels: :ml, >non-issue, v7.7.0, v8.0.0

#906 [ML] Instrument Data Frame Analysis Job to report state information to Java backend
  docs/CHANGELOG.asciidoc
  include/api/CDataFrameAnalysisInstrumentation.h
  include/api/CDataFrameAnalysisRunner.h
  include/api/CDataFrameAnalysisSpecification.h
  include/api/CDataFrameOutliersRunner.h
  include/api/CDataFrameTrainBoostedTreeRunner.h
  include/core/CProgramCounters.h
  include/maths/CBoostedTree.h
  include/maths/CBoostedTreeFactory.h
  include/maths/CBoostedTreeImpl.h
  include/maths/CDataFrameAnalysisInstrumentationInterface.h
  include/maths/CDataFramePredictiveModel.h
  include/maths/COutliers.h
  lib/api/CDataFrameAnalysisInstrumentation.cc
  lib/api/CDataFrameAnalysisRunner.cc
  lib/api/CDataFrameAnalysisSpecification.cc
  lib/api/CDataFrameAnalyzer.cc
  lib/api/CDataFrameOutliersRunner.cc
  lib/api/CDataFrameTrainBoostedTreeRunner.cc
  lib/api/Makefile.first
  lib/api/unittest/CDataFrameAnalysisSpecificationTest.cc
  lib/api/unittest/CDataFrameAnalyzerOutlierTest.cc
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
  lib/api/unittest/CDataFrameMockAnalysisRunner.cc
  lib/api/unittest/CDataFrameMockAnalysisRunner.h
  lib/maths/CBoostedTree.cc
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/CDataFramePredictiveModel.cc
  lib/maths/COutliers.cc
  lib/maths/unittest/CBoostedTreeTest.cc
  lib/maths/unittest/COutliersTest.cc
Labels: :ml, >enhancement, >feature, v7.7.0, v8.0.0

#978 [ML] Instrument Data Frame Analysis Job to report state information to Java backend
  docs/CHANGELOG.asciidoc
  include/api/CDataFrameAnalysisInstrumentation.h
  include/api/CDataFrameAnalysisRunner.h
  include/api/CDataFrameAnalysisSpecification.h
  include/api/CDataFrameOutliersRunner.h
  include/api/CDataFrameTrainBoostedTreeRunner.h
  include/core/CProgramCounters.h
  include/maths/CBoostedTree.h
  include/maths/CBoostedTreeFactory.h
  include/maths/CBoostedTreeImpl.h
  include/maths/CDataFrameAnalysisInstrumentationInterface.h
  include/maths/CDataFramePredictiveModel.h
  include/maths/COutliers.h
  lib/api/CDataFrameAnalysisInstrumentation.cc
  lib/api/CDataFrameAnalysisRunner.cc
  lib/api/CDataFrameAnalysisSpecification.cc
  lib/api/CDataFrameAnalyzer.cc
  lib/api/CDataFrameOutliersRunner.cc
  lib/api/CDataFrameTrainBoostedTreeRunner.cc
  lib/api/Makefile.first
  lib/api/unittest/CDataFrameAnalysisSpecificationTest.cc
  lib/api/unittest/CDataFrameAnalyzerOutlierTest.cc
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
  lib/api/unittest/CDataFrameMockAnalysisRunner.cc
  lib/api/unittest/CDataFrameMockAnalysisRunner.h
  lib/maths/CBoostedTree.cc
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/CDataFramePredictiveModel.cc
  lib/maths/COutliers.cc
  lib/maths/unittest/CBoostedTreeTest.cc
  lib/maths/unittest/COutliersTest.cc
Labels: :ml, >enhancement, >feature, backport, v7.7.0

#977 [ML] Update the inference schema model definition unit test
  include/api/CInferenceModelDefinition.h
  lib/api/CBoostedTreeInferenceModelBuilder.cc
  lib/api/CInferenceModelDefinition.cc
  lib/api/unittest/CBoostedTreeInferenceModelBuilderTest.cc
  lib/api/unittest/testfiles/inference_json_schema/model_definition.schema.json
Labels: :ml, >non-issue, backport, v7.7.0

#970 [ML] Use largest ordered subset of categorization tokens for regex
  docs/CHANGELOG.asciidoc
  include/model/CTokenListCategory.h
  lib/api/unittest/CFieldDataCategorizerTest.cc
  lib/api/unittest/CRestorePreviousStateTest.cc
  lib/model/CTokenListCategory.cc
  lib/model/CTokenListDataCategorizerBase.cc
  lib/model/unittest/CTokenListCategoryTest.cc
Labels: :ml, >bug, v7.7.0, v8.0.0

#980 [7.x][ML] Use largest ordered subset of categorization tokens for regex
  docs/CHANGELOG.asciidoc
  include/model/CTokenListCategory.h
  lib/api/unittest/CFieldDataCategorizerTest.cc
  lib/api/unittest/CRestorePreviousStateTest.cc
  lib/model/CTokenListCategory.cc
  lib/model/CTokenListDataCategorizerBase.cc
  lib/model/unittest/CTokenListCategoryTest.cc
Labels: backport

#981 [ML] Interface changes to support multi-parameter loss functions
  include/api/CDataFrameAnalysisInstrumentation.h
  include/maths/CBoostedTree.h
  include/maths/CDataFrameAnalysisInstrumentationInterface.h
  include/maths/COutliers.h
  lib/api/CDataFrameAnalysisInstrumentation.cc
  lib/api/CDataFrameAnalysisRunner.cc
  lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
  lib/maths/CBoostedTree.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/unittest/CBoostedTreeTest.cc
Labels: :ml/DataFrameAnalysis, >non-issue, >refactoring, review, v7.7.0, v8.0.0

#983 [7.7][ML] Interface changes to support multi-parameter loss functions
  include/api/CDataFrameAnalysisInstrumentation.h
  include/maths/CBoostedTree.h
  include/maths/CDataFrameAnalysisInstrumentationInterface.h
  include/maths/COutliers.h
  lib/api/CDataFrameAnalysisInstrumentation.cc
  lib/api/CDataFrameAnalysisRunner.cc
  lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
  lib/maths/CBoostedTree.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/unittest/CBoostedTreeTest.cc
Labels: >non-issue, backport, v7.7.0

#979 [ML] Feature importance unit test for missing data
  lib/api/unittest/CDataFrameAnalyzerFeatureImportanceTest.cc
Labels: :ml, >non-issue, >test, v7.7.0, v8.0.0

#986 [ML] Silence unnecessary clang warning
  mk/linux_crosscompile_macosx.mk
  mk/macosx.mk
Labels: :ml, >build, >non-issue, v8.0.0
