Repository elastic/ml-cpp, pull requests merged in 2020-05, with the labels that each got.

#1179 [ML] Multiphase progress reporting for data frame analyses
  docs/CHANGELOG.asciidoc
  include/api/CDataFrameAnalysisInstrumentation.h
  include/api/CDataFrameAnalyzer.h
  include/maths/CBoostedTreeFactory.h
  include/maths/CBoostedTreeImpl.h
  include/maths/CDataFrameAnalysisInstrumentationInterface.h
  include/maths/CDataFrameCategoryEncoder.h
  include/maths/COutliers.h
  lib/api/CDataFrameAnalysisInstrumentation.cc
  lib/api/CDataFrameAnalyzer.cc
  lib/api/unittest/CDataFrameAnalysisInstrumentationTest.cc
  lib/api/unittest/CDataFrameAnalyzerOutlierTest.cc
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/CDataFrameCategoryEncoder.cc
  lib/maths/COutliers.cc
  lib/maths/unittest/CBoostedTreeTest.cc
  lib/maths/unittest/COutliersTest.cc
Labels: :ml/DataFrameAnalysis, >enhancement, review, v7.8.0, v8.0.0

#1184 Fix combine script used with search state splitter program
  devbin/state_search_splitter/Main.cc
  devbin/state_search_splitter/combine.sh
Labels: :ml, >non-issue, v7.8.0, v8.0.0

#1186 [7.x] Fix combine script used with search state splitter program
  devbin/state_search_splitter/Main.cc
  devbin/state_search_splitter/combine.sh
Labels: >non-issue, backport, v7.8.0

#1187 [7.8][ML] Multiphase progress reporting for data frame analyses
  docs/CHANGELOG.asciidoc
  include/api/CDataFrameAnalysisInstrumentation.h
  include/api/CDataFrameAnalyzer.h
  include/maths/CBoostedTreeFactory.h
  include/maths/CBoostedTreeImpl.h
  include/maths/CDataFrameAnalysisInstrumentationInterface.h
  include/maths/CDataFrameCategoryEncoder.h
  include/maths/COutliers.h
  lib/api/CDataFrameAnalysisInstrumentation.cc
  lib/api/CDataFrameAnalyzer.cc
  lib/api/unittest/CDataFrameAnalysisInstrumentationTest.cc
  lib/api/unittest/CDataFrameAnalyzerOutlierTest.cc
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/CDataFrameCategoryEncoder.cc
  lib/maths/COutliers.cc
  lib/maths/unittest/CBoostedTreeTest.cc
  lib/maths/unittest/COutliersTest.cc
Labels: backport, v7.8.0

#1188 [ML] Output progress for final training even if we don't have this step
  lib/maths/CBoostedTreeImpl.cc
Labels: :ml/DataFrameAnalysis, >non-issue, review, v7.8.0, v8.0.0

#1185 [ML] Fix override of maximum permitted trees for classification and regression
  docs/CHANGELOG.asciidoc
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/unittest/CBoostedTreeTest.cc
Labels: :ml/DataFrameAnalysis, >bug, review, v7.8.0, v8.0.0

#1177 [ML] Reduce false positives for the periodic component test for anomaly detection
  docs/CHANGELOG.asciidoc
  include/maths/CPeriodicityHypothesisTests.h
  lib/maths/CPeriodicityHypothesisTests.cc
  lib/maths/CTimeSeriesModel.cc
  lib/maths/unittest/CPeriodicityHypothesisTestsTest.cc
  lib/maths/unittest/CTimeSeriesDecompositionTest.cc
Labels: :ml, >enhancement, affects-results, review, v7.8.0, v8.0.0

#1189 [7.8][ML] Output progress for final training even if we don't have this step
  lib/maths/CBoostedTreeImpl.cc
Labels: >non-issue, backport, v7.8.0

#1191 [7.8][ML] Reduce false positives for the periodic component test for anomaly detection
  docs/CHANGELOG.asciidoc
  include/maths/CPeriodicityHypothesisTests.h
  lib/maths/CPeriodicityHypothesisTests.cc
  lib/maths/CTimeSeriesModel.cc
  lib/maths/unittest/CPeriodicityHypothesisTestsTest.cc
  lib/maths/unittest/CTimeSeriesDecompositionTest.cc
Labels: backport, v7.8.0

#1190 [7.8][ML] Fix override of maximum permitted trees for classification and regression
  docs/CHANGELOG.asciidoc
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/unittest/CBoostedTreeTest.cc
Labels: backport, v7.8.0

#1168 [ML] Pseudo-Huber loss function
  docs/CHANGELOG.asciidoc
  include/api/CDataFrameTrainBoostedTreeRegressionRunner.h
  include/maths/CBoostedTreeImpl.h
  include/maths/CBoostedTreeLoss.h
  include/test/CDataFrameAnalysisSpecificationFactory.h
  include/test/CDataFrameAnalyzerTrainingFactory.h
  lib/api/CDataFrameTrainBoostedTreeRegressionRunner.cc
  lib/api/unittest/CDataFrameAnalysisInstrumentationTest.cc
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/CBoostedTreeLoss.cc
  lib/maths/unittest/CBoostedTreeLossTest.cc
  lib/maths/unittest/CBoostedTreeTest.cc
  lib/test/CDataFrameAnalysisSpecificationFactory.cc
Labels: :ml, >enhancement, v7.8.0, v8.0.0

#1192 [ML] Add a constant to the prediction which minimises the unregularised loss for classification and regression
  docs/CHANGELOG.asciidoc
  include/maths/CBoostedTreeImpl.h
  lib/api/unittest/CDataFrameAnalyzerFeatureImportanceTest.cc
  lib/maths/CBoostedTreeImpl.cc
Labels: :ml/DataFrameAnalysis, >enhancement, review, v7.8.0, v8.0.0

#1194 [7.8][ML] Add a constant to the prediction which minimises the unregularised loss for classification and regression
  docs/CHANGELOG.asciidoc
  include/maths/CBoostedTreeImpl.h
  lib/api/unittest/CDataFrameAnalyzerFeatureImportanceTest.cc
  lib/maths/CBoostedTreeImpl.cc
Labels: backport, v7.8.0

#1193 [ML] Reset memory status from soft limit to ok below threshold
  docs/CHANGELOG.asciidoc
  include/model/CAnomalyDetectorModel.h
  include/model/CResourceMonitor.h
  lib/model/CResourceMonitor.cc
  lib/model/unittest/CResourceMonitorTest.cc
  lib/model/unittest/CTokenListDataCategorizerTest.cc
Labels: :ml, >bug, v7.8.0, v8.0.0

#1195 Fix test threshold
  lib/maths/unittest/CBoostedTreeTest.cc
Labels: :ml, >test, v8.0.0

#1196 [7.x][ML] Reset memory status from soft limit to ok below threshold
  docs/CHANGELOG.asciidoc
  include/model/CAnomalyDetectorModel.h
  include/model/CResourceMonitor.h
  lib/model/CResourceMonitor.cc
  lib/model/unittest/CResourceMonitorTest.cc
  lib/model/unittest/CTokenListDataCategorizerTest.cc
Labels: backport, v7.8.0

#1198 [7.x][ML] Pseudo-Huber loss function
  docs/CHANGELOG.asciidoc
  include/api/CDataFrameTrainBoostedTreeRegressionRunner.h
  include/maths/CBoostedTreeImpl.h
  include/maths/CBoostedTreeLoss.h
  include/test/CDataFrameAnalysisSpecificationFactory.h
  include/test/CDataFrameAnalyzerTrainingFactory.h
  lib/api/CDataFrameTrainBoostedTreeRegressionRunner.cc
  lib/api/unittest/CDataFrameAnalysisInstrumentationTest.cc
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/CBoostedTreeLoss.cc
  lib/maths/unittest/CBoostedTreeLossTest.cc
  lib/maths/unittest/CBoostedTreeTest.cc
  lib/test/CDataFrameAnalysisSpecificationFactory.cc
Labels: :ml, >enhancement, backport, v7.9.0

#1199 [7.8][ML] Pseudo-Huber loss function
  docs/CHANGELOG.asciidoc
  include/api/CDataFrameTrainBoostedTreeRegressionRunner.h
  include/maths/CBoostedTreeImpl.h
  include/maths/CBoostedTreeLoss.h
  include/test/CDataFrameAnalysisSpecificationFactory.h
  include/test/CDataFrameAnalyzerTrainingFactory.h
  lib/api/CDataFrameTrainBoostedTreeRegressionRunner.cc
  lib/api/unittest/CDataFrameAnalysisInstrumentationTest.cc
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/CBoostedTreeLoss.cc
  lib/maths/unittest/CBoostedTreeLossTest.cc
  lib/maths/unittest/CBoostedTreeTest.cc
  lib/test/CDataFrameAnalysisSpecificationFactory.cc
Labels: :ml, >enhancement, backport, v7.8.0

#1203 Do nothing on aarch64 workers on old branches
  dev-tools/jenkins_ci.sh
Labels: :ml, >build, >non-issue, v6.8.10, v7.6.3, v7.7.1

#1197 [ML] Fix restore for boosted tree and improve tests
  docs/CHANGELOG.asciidoc
  include/api/CDataFrameAnalysisInstrumentation.h
  include/maths/CBoostedTreeLoss.h
  include/test/CDataFrameAnalysisSpecificationFactory.h
  include/test/CDataFrameAnalyzerTrainingFactory.h
  lib/api/CDataFrameAnalysisInstrumentation.cc
  lib/api/unittest/CDataFrameAnalyzerOutlierTest.cc
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/CBoostedTreeHyperparameters.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/CBoostedTreeLoss.cc
  lib/maths/unittest/CBoostedTreeTest.cc
  lib/maths/unittest/testfiles/error_bayesian_optimisation_state.json
  lib/maths/unittest/testfiles/error_boosted_tree_impl_state.json
  lib/test/CDataFrameAnalysisSpecificationFactory.cc
Labels: :ml/DataFrameAnalysis, >bug, review, v7.8.0, v7.9.0, v8.0.0

#1206 Do nothing on aarch64 workers on old branches
  dev-tools/jenkins_ci.sh
Labels: >non-issue, backport, v6.8.10

#1205 Do nothing on aarch64 workers on old branches
  dev-tools/jenkins_ci.sh
Labels: >non-issue, backport, v7.6.3

#1207 [7.9][ML] Fix restore for boosted tree and improve test coverage
  docs/CHANGELOG.asciidoc
  include/api/CDataFrameAnalysisInstrumentation.h
  include/maths/CBoostedTreeLoss.h
  include/test/CDataFrameAnalysisSpecificationFactory.h
  include/test/CDataFrameAnalyzerTrainingFactory.h
  lib/api/CDataFrameAnalysisInstrumentation.cc
  lib/api/unittest/CDataFrameAnalyzerOutlierTest.cc
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/CBoostedTreeHyperparameters.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/CBoostedTreeLoss.cc
  lib/maths/unittest/CBoostedTreeTest.cc
  lib/maths/unittest/testfiles/error_bayesian_optimisation_state.json
  lib/maths/unittest/testfiles/error_boosted_tree_impl_state.json
  lib/test/CDataFrameAnalysisSpecificationFactory.cc
Labels: backport, v7.9.0

#1208 [7.8][ML] Fix restore for boosted tree and improve test coverage
  docs/CHANGELOG.asciidoc
  include/api/CDataFrameAnalysisInstrumentation.h
  include/maths/CBoostedTreeLoss.h
  include/test/CDataFrameAnalysisSpecificationFactory.h
  include/test/CDataFrameAnalyzerTrainingFactory.h
  lib/api/CDataFrameAnalysisInstrumentation.cc
  lib/api/unittest/CDataFrameAnalyzerOutlierTest.cc
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/CBoostedTreeHyperparameters.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/CBoostedTreeLoss.cc
  lib/maths/unittest/CBoostedTreeTest.cc
  lib/maths/unittest/testfiles/error_bayesian_optimisation_state.json
  lib/maths/unittest/testfiles/error_boosted_tree_impl_state.json
  lib/test/CDataFrameAnalysisSpecificationFactory.cc
Labels: backport, v7.8.0

#1201 [ML] Only remove discontinuities initialising seasonal components if they were part of the hypothesis we selected
  docs/CHANGELOG.asciidoc
  lib/maths/CPeriodicityHypothesisTests.cc
Labels: :ml, >bug, review, v7.8.0, v7.9.0, v8.0.0

#1209 [7.9][ML] Only remove discontinuities initialising seasonal components if they were part of the hypothesis we selected
  docs/CHANGELOG.asciidoc
  lib/maths/CPeriodicityHypothesisTests.cc
Labels: backport, v7.9.0

#1210 [7.8][ML] Only remove discontinuities initialising seasonal components if they were part of the hypothesis we selected
  docs/CHANGELOG.asciidoc
  lib/maths/CPeriodicityHypothesisTests.cc
Labels: backport, v7.8.0

#1204 Adjust JDK for running ES integration tests on aarch64
  dev-tools/run_es_tests.sh
  lib/maths/unittest/CBoostedTreeTest.cc
Labels: :ml, >build, >non-issue, v7.8.0, v7.9.0, v8.0.0

#1211 [7.x] Adjust JDK for running ES integration tests on aarch64
  dev-tools/run_es_tests.sh
  lib/maths/unittest/CBoostedTreeTest.cc
Labels: >non-issue, backport, v7.9.0

#1212 [7.8] Adjust JDK for running ES integration tests on aarch64
  dev-tools/run_es_tests.sh
  lib/maths/unittest/CBoostedTreeTest.cc
Labels: >non-issue, backport, v7.8.0

#1213 Make ES integration tests work on reused Jenkins workers
  dev-tools/run_es_tests.sh
Labels: :ml, >build, >non-issue, v6.8.10, v7.7.1, v7.8.0, v7.9.0, v8.0.0

#1214 [6.8] Make ES integration tests work on reused Jenkins workers
  dev-tools/run_es_tests.sh
Labels: >non-issue, backport, v6.8.10

#1216 [7.8] Make ES integration tests work on reused Jenkins workers
  dev-tools/run_es_tests.sh
Labels: >non-issue, backport, v7.8.0

#1215 [7.7] Make ES integration tests work on reused Jenkins workers
  dev-tools/run_es_tests.sh
Labels: >non-issue, backport, v7.7.1

#1217 [7.x] Make ES integration tests work on reused Jenkins workers
  dev-tools/run_es_tests.sh
Labels: >non-issue, backport, v7.9.0

#1200 [ML] Add offset in the MSLE computation
  include/maths/CBoostedTreeLoss.h
  lib/maths/CBoostedTreeLoss.cc
Labels: :ml, >non-issue, v7.8.0, v7.9.0, v8.0.0

#1220 [ML] Work around gcc alignas bug
  lib/core/unittest/CAlignmentTest.cc
Labels: :ml, >non-issue, v7.8.0, v7.9.0, v8.0.0

#1222 [7.x][ML] Work around gcc alignas bug
  lib/core/unittest/CAlignmentTest.cc
Labels: >non-issue, backport, v7.9.0

#1223 [7.8][ML] Work around gcc alignas bug
  lib/core/unittest/CAlignmentTest.cc
Labels: >non-issue, backport, v7.8.0

#1219 [7.x][ML] Add offset in the MSLE computation
  include/maths/CBoostedTreeLoss.h
  lib/maths/CBoostedTreeLoss.cc
Labels: :ml, >non-issue, backport, v7.9.0

#1218 [7.8][ML] Add offset in the MSLE computation
  include/maths/CBoostedTreeLoss.h
  lib/maths/CBoostedTreeLoss.cc
Labels: :ml, >non-issue, backport, v7.8.0

#1226 [ML] Fix flakey progress monitoring test
  lib/api/unittest/CDataFrameAnalyzerOutlierTest.cc
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
Labels: :ml/DataFrameAnalysis, >test, v7.8.0, v7.9.0, v8.0.0

#1225 [ML] Fix possible cause for "Bad variance scale nan" log errors
  docs/CHANGELOG.asciidoc
  lib/maths/CAdaptiveBucketing.cc
  lib/maths/CCalendarComponentAdaptiveBucketing.cc
  lib/maths/CTimeSeriesDecomposition.cc
Labels: :ml, >bug, review, v7.7.1, v7.8.0, v7.9.0, v8.0.0

#1227 [7.9][ML] Fix possible cause for "Bad variance scale nan" log errors
  docs/CHANGELOG.asciidoc
  lib/maths/CAdaptiveBucketing.cc
  lib/maths/CCalendarComponentAdaptiveBucketing.cc
  lib/maths/CTimeSeriesDecomposition.cc
Labels: backport, v7.9.0

#1221 [ML] Only log failure to ignore SIGPIPE once
  include/core/CNamedPipeFactory.h
  lib/core/CLogger.cc
  lib/core/CNamedPipeFactory.cc
  lib/core/CNamedPipeFactory_Windows.cc
Labels: :ml, >non-issue, v7.8.0, v7.9.0, v8.0.0

#1229 [7.8][ML] Fix possible cause for "Bad variance scale nan" log errors
  docs/CHANGELOG.asciidoc
  lib/maths/CAdaptiveBucketing.cc
  lib/maths/CCalendarComponentAdaptiveBucketing.cc
  lib/maths/CTimeSeriesDecomposition.cc
Labels: backport, v7.8.0

#1228 [7.9][ML] Fix flakey progress monitoring test
  lib/api/unittest/CDataFrameAnalyzerOutlierTest.cc
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
Labels: >test, backport, v7.9.0

#1230 [7.8][ML] Fix flakey progress monitoring test
  lib/api/unittest/CDataFrameAnalyzerOutlierTest.cc
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
Labels: >test, backport, v7.8.0

#1231 [ML] Fix weights to maximize minimum recall for multiclass classification
  lib/maths/CDataFrameUtils.cc
  lib/maths/unittest/CDataFrameUtilsTest.cc
Labels: :ml/DataFrameAnalysis, >bug, >non-issue, review, v7.8.0, v7.9.0, v8.0.0

#1232 [7.x][ML] Only log failure to ignore SIGPIPE once
  include/core/CNamedPipeFactory.h
  lib/core/CLogger.cc
  lib/core/CNamedPipeFactory.cc
  lib/core/CNamedPipeFactory_Windows.cc
Labels: >non-issue, backport, v7.9.0

#1233 [7.8][ML] Only log failure to ignore SIGPIPE once
  include/core/CNamedPipeFactory.h
  lib/core/CLogger.cc
  lib/core/CNamedPipeFactory.cc
  lib/core/CNamedPipeFactory_Windows.cc
Labels: >non-issue, backport, v7.8.0

#1170 [ML] Upgrade to gcc 9.3 for Linux compilation
  3rd_party/3rd_party.sh
  3rd_party/licenses/libxml2-INFO.csv
  build-setup/linux.md
  build-setup/linux_aarch64_cross_compiled.md
  dev-tools/docker/build_linux_aarch64_cross_build_image.sh
  dev-tools/docker/build_linux_aarch64_native_build_image.sh
  dev-tools/docker/build_linux_build_image.sh
  dev-tools/docker/docker_entrypoint.sh
  dev-tools/docker/linux_aarch64_cross_builder/Dockerfile
  dev-tools/docker/linux_aarch64_cross_image/Dockerfile
  dev-tools/docker/linux_aarch64_native_builder/Dockerfile
  dev-tools/docker/linux_aarch64_native_image/Dockerfile
  dev-tools/docker/linux_aarch64_native_tester/Dockerfile
  dev-tools/docker/linux_builder/Dockerfile
  dev-tools/docker/linux_image/Dockerfile
  dev-tools/docker/linux_tester/Dockerfile
  dev-tools/vagrant/linux/provision.sh
  docs/CHANGELOG.asciidoc
  lib/core/unittest/CAlignmentTest.cc
  lib/maths/unittest/CBasicStatisticsTest.cc
  lib/maths/unittest/CBoostedTreeTest.cc
  lib/seccomp/CSystemCallFilter_Linux.cc
  lib/seccomp/CSystemCallFilter_MacOSX.cc
  lib/seccomp/CSystemCallFilter_Windows.cc
  mk/linux.mk
  mk/linux_crosscompile_linux.mk
  set_env.sh
Labels: :ml, >build, v8.0.0

#1235 [7.9][ML] Fix weights to maximize minimum recall for multiclass classification
  lib/maths/CDataFrameUtils.cc
  lib/maths/unittest/CDataFrameUtilsTest.cc
Labels: >non-issue, backport, v7.9.0

#1141 [7.7][ML] Fix periodic persistence of categorizer state
  bin/autodetect/Main.cc
  bin/categorize/Main.cc
  docs/CHANGELOG.asciidoc
  include/api/CAnomalyJob.h
  include/api/CFieldDataCategorizer.h
  lib/api/CAnomalyJob.cc
  lib/api/CFieldDataCategorizer.cc
  lib/api/dump_state/Main.cc
  lib/api/unittest/CAnomalyJobLimitTest.cc
  lib/api/unittest/CAnomalyJobTest.cc
  lib/api/unittest/CFieldDataCategorizerTest.cc
  lib/api/unittest/CForecastRunnerTest.cc
  lib/api/unittest/CMultiFileDataAdderTest.cc
  lib/api/unittest/COutputChainerTest.cc
  lib/api/unittest/CPersistenceManagerTest.cc
  lib/api/unittest/CRestorePreviousStateTest.cc
  lib/api/unittest/CSingleStreamDataAdderTest.cc
  lib/api/unittest/CStringStoreTest.cc
  lib/api/unittest/CTestAnomalyJob.cc
  lib/api/unittest/CTestAnomalyJob.h
  lib/api/unittest/CTestFieldDataCategorizer.cc
  lib/api/unittest/CTestFieldDataCategorizer.h
  lib/api/unittest/Makefile
Labels: backport, v7.7.1

#1236 [7.8][ML] Fix weights to maximize minimum recall for multiclass classification
  lib/maths/CDataFrameUtils.cc
  lib/maths/unittest/CDataFrameUtilsTest.cc
Labels: >non-issue, backport, v7.8.0

#1240 [7.7][ML] Fix printing values for multiclass feature importance
  docs/CHANGELOG.asciidoc
  lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
Labels: :ml, >bug, backport, v7.7.1

#1237 [ML] Fix timestamp issue for instrumentation
  docs/CHANGELOG.asciidoc
  lib/api/CDataFrameAnalysisInstrumentation.cc
  lib/api/unittest/CDataFrameAnalysisInstrumentationTest.cc
  lib/core/CTimeUtils.cc
Labels: :ml, >bug, v7.7.1, v7.8.0, v7.9.0, v8.0.0

#1243 [7.8][ML] Fix timestamp issue for instrumentation
  docs/CHANGELOG.asciidoc
  lib/api/CDataFrameAnalysisInstrumentation.cc
  lib/api/unittest/CDataFrameAnalysisInstrumentationTest.cc
  lib/core/CTimeUtils.cc
Labels: :ml, >bug, v7.8.0

#1244 [7.x][ML] Fix timestamp issue for instrumentation
  docs/CHANGELOG.asciidoc
  lib/api/CDataFrameAnalysisInstrumentation.cc
  lib/api/unittest/CDataFrameAnalysisInstrumentationTest.cc
  lib/core/CTimeUtils.cc
Labels: :ml, >bug, v7.9.0

#1246 [ML] Fix bad function call exception in anomaly detection
  docs/CHANGELOG.asciidoc
  include/maths/CTimeSeriesDecompositionDetail.h
  lib/maths/CTimeSeriesDecomposition.cc
  lib/maths/CTimeSeriesDecompositionDetail.cc
  lib/maths/CTimeSeriesModel.cc
  lib/maths/unittest/CTimeSeriesDecompositionTest.cc
Labels: :ml, >bug, review, v7.7.1, v7.8.0, v7.9.0, v8.0.0

#1242 [7.7][ML] Fix timestamp issue for instrumentation
  docs/CHANGELOG.asciidoc
  lib/api/CDataFrameAnalysisInstrumentation.cc
  lib/api/unittest/CDataFrameAnalysisInstrumentationTest.cc
  lib/core/CTimeUtils.cc
Labels: backport, v7.7.1

#1249 [7.8][ML] Fix bad function call exception in anomaly detection
  docs/CHANGELOG.asciidoc
  include/maths/CTimeSeriesDecompositionDetail.h
  lib/maths/CTimeSeriesDecomposition.cc
  lib/maths/CTimeSeriesDecompositionDetail.cc
  lib/maths/CTimeSeriesModel.cc
  lib/maths/unittest/CTimeSeriesDecompositionTest.cc
Labels: backport, v7.8.0

#1248 [7.9][ML] Fix bad function call exception in anomaly detection
  docs/CHANGELOG.asciidoc
  include/maths/CTimeSeriesDecompositionDetail.h
  lib/maths/CTimeSeriesDecomposition.cc
  lib/maths/CTimeSeriesDecompositionDetail.cc
  lib/maths/CTimeSeriesModel.cc
  lib/maths/unittest/CTimeSeriesDecompositionTest.cc
Labels: backport, v7.9.0

#1241 [7.7][ML] Fix a bug in adaptive local regression
  docs/CHANGELOG.asciidoc
  include/maths/CAdaptiveBucketing.h
  include/maths/CTools.h
  include/maths/CToolsDetail.h
  lib/maths/CAdaptiveBucketing.cc
  lib/maths/CTools.cc
  lib/maths/unittest/CAdaptiveBucketingTest.cc
  lib/maths/unittest/CToolsTest.cc
  lib/maths/unittest/Makefile
Labels: backport, v7.7.1

#1250 [7.7][ML] Fix bad function call exception in anomaly detection
  docs/CHANGELOG.asciidoc
  include/maths/CTimeSeriesDecompositionDetail.h
  lib/maths/CTimeSeriesDecomposition.cc
  lib/maths/CTimeSeriesDecompositionDetail.cc
  lib/maths/CTimeSeriesModel.cc
  lib/maths/unittest/CTimeSeriesDecompositionTest.cc
Labels: backport, v7.7.1

#1251 Rename identifier to detectorIndex so that the naming is consistent between C++ and Java
  include/model/CCountingModelFactory.h
  include/model/CEventRateModelFactory.h
  include/model/CEventRatePopulationModelFactory.h
  include/model/CMetricModelFactory.h
  include/model/CMetricPopulationModelFactory.h
  include/model/CModelFactory.h
  include/model/CSearchKey.h
  lib/api/CAnomalyJob.cc
  lib/model/CAnomalyDetectorModelConfig.cc
  lib/model/CCountingModelFactory.cc
  lib/model/CEventRateModelFactory.cc
  lib/model/CEventRatePopulationModelFactory.cc
  lib/model/CMetricModelFactory.cc
  lib/model/CMetricPopulationModelFactory.cc
  lib/model/CSearchKey.cc
  lib/model/unittest/CEventRateModelTest.cc
  lib/model/unittest/CEventRatePopulationModelTest.cc
  lib/model/unittest/CMetricModelTest.cc
  lib/model/unittest/CMetricPopulationModelTest.cc
  lib/model/unittest/CResourceLimitTest.cc
Labels: :ml, >non-issue, v7.9.0, v8.0.0

#1239 [ML] Fix weights to maximize minimum recall for multiclass classification when the training data is missing classes
  lib/maths/CDataFrameUtils.cc
Labels: :ml/DataFrameAnalysis, >bug, >non-issue, review, v7.8.0, v7.9.0, v8.0.0

#1254 [7.7][ML] Fix possible cause for "Bad variance scale nan" log errors
  docs/CHANGELOG.asciidoc
  lib/maths/CAdaptiveBucketing.cc
  lib/maths/CCalendarComponentAdaptiveBucketing.cc
  lib/maths/CTimeSeriesDecomposition.cc
Labels: backport, v7.7.1

#1255 [7.x] Rename identifier to detectorIndex so that the naming is consistent between C++ and Java (#1251)
  include/model/CCountingModelFactory.h
  include/model/CEventRateModelFactory.h
  include/model/CEventRatePopulationModelFactory.h
  include/model/CMetricModelFactory.h
  include/model/CMetricPopulationModelFactory.h
  include/model/CModelFactory.h
  include/model/CSearchKey.h
  lib/api/CAnomalyJob.cc
  lib/model/CAnomalyDetectorModelConfig.cc
  lib/model/CCountingModelFactory.cc
  lib/model/CEventRateModelFactory.cc
  lib/model/CEventRatePopulationModelFactory.cc
  lib/model/CMetricModelFactory.cc
  lib/model/CMetricPopulationModelFactory.cc
  lib/model/CSearchKey.cc
  lib/model/unittest/CEventRateModelTest.cc
  lib/model/unittest/CEventRatePopulationModelTest.cc
  lib/model/unittest/CMetricModelTest.cc
  lib/model/unittest/CMetricPopulationModelTest.cc
  lib/model/unittest/CResourceLimitTest.cc
Labels: :ml, >non-issue, backport

#1257 [ML] Switch off CDS archive for ES test Gradle on aarch64
  dev-tools/run_es_tests.sh
Labels: :ml, >test, v7.8.0, v7.9.0, v8.0.0

#1256 [7.9][ML] Fix weights to maximize minimum recall for multiclass classification when the training data is missing classes
  lib/maths/CDataFrameUtils.cc
Labels: >non-issue, backport, v7.9.0

#1258 [ML] Add source URL to 3rd party info when we have to say how to get it
  3rd_party/licenses/boost-INFO.csv
  3rd_party/licenses/eigen-INFO.csv
  3rd_party/licenses/gcc-runtime-INFO.csv
  3rd_party/licenses/libxml2-INFO.csv
  3rd_party/licenses/moby-INFO.csv
  3rd_party/licenses/msinttypes-INFO.csv
  3rd_party/licenses/rapidjson-INFO.csv
  3rd_party/licenses/rapidxml-INFO.csv
  3rd_party/licenses/scowl-INFO.csv
  3rd_party/licenses/strptime-INFO.csv
  3rd_party/licenses/visualstudio2017-INFO.csv
  3rd_party/licenses/zlib-INFO.csv
Labels: :ml, >non-issue, v6.8.10, v7.7.1, v7.8.0, v7.9.0, v8.0.0

#1261 [7.8][ML] Switch off CDS archive for ES test Gradle on aarch64
  dev-tools/run_es_tests.sh
Labels: >test, backport, v7.8.0

#1266 [6.8][ML] Add source URL to 3rd party info when we have to say how to get it
  3rd_party/licenses/apr-INFO.csv
  3rd_party/licenses/apr-iconv-INFO.csv
  3rd_party/licenses/apr-util-INFO.csv
  3rd_party/licenses/boost-INFO.csv
  3rd_party/licenses/eigen-INFO.csv
  3rd_party/licenses/gcc-runtime-INFO.csv
  3rd_party/licenses/libxml2-INFO.csv
  3rd_party/licenses/log4cxx-INFO.csv
  3rd_party/licenses/moby-INFO.csv
  3rd_party/licenses/msinttypes-INFO.csv
  3rd_party/licenses/rapidjson-INFO.csv
  3rd_party/licenses/rapidxml-INFO.csv
  3rd_party/licenses/scowl-INFO.csv
  3rd_party/licenses/strptime-INFO.csv
  3rd_party/licenses/visualstudio2013express-INFO.csv
  3rd_party/licenses/zlib-INFO.csv
Labels: >non-issue, backport, v6.8.10

#1265 [7.7][ML] Add source URL to 3rd party info when we have to say how to get it
  3rd_party/licenses/boost-INFO.csv
  3rd_party/licenses/eigen-INFO.csv
  3rd_party/licenses/gcc-runtime-INFO.csv
  3rd_party/licenses/libxml2-INFO.csv
  3rd_party/licenses/moby-INFO.csv
  3rd_party/licenses/msinttypes-INFO.csv
  3rd_party/licenses/rapidjson-INFO.csv
  3rd_party/licenses/rapidxml-INFO.csv
  3rd_party/licenses/scowl-INFO.csv
  3rd_party/licenses/strptime-INFO.csv
  3rd_party/licenses/visualstudio2017-INFO.csv
  3rd_party/licenses/zlib-INFO.csv
Labels: >non-issue, backport, v7.7.1

#1264 [7.8][ML] Add source URL to 3rd party info when we have to say how to get it
  3rd_party/licenses/boost-INFO.csv
  3rd_party/licenses/eigen-INFO.csv
  3rd_party/licenses/gcc-runtime-INFO.csv
  3rd_party/licenses/libxml2-INFO.csv
  3rd_party/licenses/moby-INFO.csv
  3rd_party/licenses/msinttypes-INFO.csv
  3rd_party/licenses/rapidjson-INFO.csv
  3rd_party/licenses/rapidxml-INFO.csv
  3rd_party/licenses/scowl-INFO.csv
  3rd_party/licenses/strptime-INFO.csv
  3rd_party/licenses/visualstudio2017-INFO.csv
  3rd_party/licenses/zlib-INFO.csv
Labels: >non-issue, backport, v7.8.0

#1263 [7.x][ML] Add source URL to 3rd party info when we have to say how to get it
  3rd_party/licenses/boost-INFO.csv
  3rd_party/licenses/eigen-INFO.csv
  3rd_party/licenses/gcc-runtime-INFO.csv
  3rd_party/licenses/libxml2-INFO.csv
  3rd_party/licenses/moby-INFO.csv
  3rd_party/licenses/msinttypes-INFO.csv
  3rd_party/licenses/rapidjson-INFO.csv
  3rd_party/licenses/rapidxml-INFO.csv
  3rd_party/licenses/scowl-INFO.csv
  3rd_party/licenses/strptime-INFO.csv
  3rd_party/licenses/visualstudio2017-INFO.csv
  3rd_party/licenses/zlib-INFO.csv
Labels: >non-issue, backport, v7.9.0

#1260 [7.x][ML] Switch off CDS archive for ES test Gradle on aarch64
  dev-tools/run_es_tests.sh
Labels: >test, backport, v7.9.0

#1262 [7.8][ML] Fix weights to maximize minimum recall for multiclass classification when the training data is missing classes
  lib/maths/CDataFrameUtils.cc
Labels: >non-issue, backport, v7.8.0

#1267 [ML] Special case handling for autocorrelation of a constant
  lib/maths/CSignal.cc
Labels: :ml, >non-issue, review, v7.9.0, v8.0.0

#1269 [7.9][ML] Special case handling for autocorrelation of a constant
  lib/maths/CSignal.cc
Labels: >non-issue, backport, v7.9.0

#1259 Do not pass detectorIndex to CAnomalyDetector
  include/api/CAnomalyJob.h
  include/model/CAnomalyDetector.h
  include/model/CAnomalyDetectorModel.h
  include/model/CSimpleCountDetector.h
  lib/api/CAnomalyJob.cc
  lib/api/unittest/CAnomalyJobLimitTest.cc
  lib/model/CAnomalyDetector.cc
  lib/model/CAnomalyDetectorModel.cc
  lib/model/CSearchKey.cc
  lib/model/CSimpleCountDetector.cc
  lib/model/unittest/CEventRateAnomalyDetectorTest.cc
  lib/model/unittest/CMetricAnomalyDetectorTest.cc
  lib/model/unittest/CResourceLimitTest.cc
  lib/model/unittest/CResourceMonitorTest.cc
Labels: :ml, >non-issue, v7.9.0, v8.0.0

#1270 [7.x] Do not pass detectorIndex to CAnomalyDetector (#1259)
  include/api/CAnomalyJob.h
  include/model/CAnomalyDetector.h
  include/model/CAnomalyDetectorModel.h
  include/model/CSimpleCountDetector.h
  lib/api/CAnomalyJob.cc
  lib/api/unittest/CAnomalyJobLimitTest.cc
  lib/model/CAnomalyDetector.cc
  lib/model/CAnomalyDetectorModel.cc
  lib/model/CSearchKey.cc
  lib/model/CSimpleCountDetector.cc
  lib/model/unittest/CEventRateAnomalyDetectorTest.cc
  lib/model/unittest/CMetricAnomalyDetectorTest.cc
  lib/model/unittest/CResourceLimitTest.cc
  lib/model/unittest/CResourceMonitorTest.cc
Labels: :ml, >non-issue, backport

#1271 [ML] Improve time series decomposition adaption
  include/maths/CAdaptiveBucketing.h
  include/maths/CLeastSquaresOnlineRegression.h
  include/maths/CLeastSquaresOnlineRegressionDetail.h
  include/maths/CSeasonalComponent.h
  include/maths/CSeasonalComponentAdaptiveBucketing.h
  lib/api/unittest/CAnomalyJobLimitTest.cc
  lib/maths/CAdaptiveBucketing.cc
  lib/maths/CPeriodicityHypothesisTests.cc
  lib/maths/CSeasonalComponent.cc
  lib/maths/CSeasonalComponentAdaptiveBucketing.cc
  lib/maths/CTimeSeriesDecompositionDetail.cc
  lib/maths/unittest/CCalendarComponentAdaptiveBucketingTest.cc
  lib/maths/unittest/CForecastTest.cc
  lib/maths/unittest/CPeriodicityHypothesisTestsTest.cc
  lib/maths/unittest/CSeasonalComponentAdaptiveBucketingTest.cc
  lib/maths/unittest/CSeasonalComponentTest.cc
  lib/maths/unittest/CTimeSeriesDecompositionTest.cc
  lib/maths/unittest/CTimeSeriesModelTest.cc
  lib/model/unittest/CEventRateModelTest.cc
  lib/model/unittest/CMetricModelTest.cc
Labels: :ml, >enhancement, >non-issue, affects-results, review

#1276 [DOCS] Adjust release note for reduced process priority
  docs/CHANGELOG.asciidoc
Labels: :ml, >docs, v7.8.0, v7.9.0, v8.0.0

#1274 [ML] Don't lose precision when persisting state
  docs/CHANGELOG.asciidoc
  include/core/CPersistUtils.h
  include/maths/CChecksum.h
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
  lib/core/CStringUtils.cc
  lib/core/unittest/CJsonStatePersistInserterTest.cc
  lib/core/unittest/CPersistUtilsTest.cc
  lib/core/unittest/CRapidXmlStatePersistInserterTest.cc
  lib/core/unittest/CStringUtilsTest.cc
  lib/model/unittest/CAnomalyScoreTest.cc
  lib/model/unittest/CSampleQueueTest.cc
Labels: :ml, >enhancement, review, v7.9.0, v8.0.0

#1238 Adding forecast parameter max_model_memory
  docs/CHANGELOG.asciidoc
  include/api/CForecastRunner.h
  include/model/CResourceMonitor.h
  lib/api/CForecastRunner.cc
  lib/api/unittest/CForecastRunnerTest.cc
  lib/model/CResourceMonitor.cc
Labels: :ml, >enhancement, v7.9.0, v8.0.0

#1286 [ML] Fix debug build
  include/api/CForecastRunner.h
  lib/api/CForecastRunner.cc
Labels: :ml, >non-issue, v8.0.0

#1279 [7.x] Adding forecast parameter max_model_memory (#1238)
  docs/CHANGELOG.asciidoc
  include/api/CForecastRunner.h
  include/model/CResourceMonitor.h
  lib/api/CForecastRunner.cc
  lib/api/unittest/CForecastRunnerTest.cc
  lib/model/CResourceMonitor.cc
Labels: backport

#1285 [7.9][ML] Don't lose precision when persisting state
  docs/CHANGELOG.asciidoc
  include/core/CPersistUtils.h
  include/maths/CChecksum.h
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
  lib/core/CStringUtils.cc
  lib/core/unittest/CJsonStatePersistInserterTest.cc
  lib/core/unittest/CPersistUtilsTest.cc
  lib/core/unittest/CRapidXmlStatePersistInserterTest.cc
  lib/core/unittest/CStringUtilsTest.cc
  lib/model/unittest/CAnomalyScoreTest.cc
  lib/model/unittest/CSampleQueueTest.cc
Labels: backport, v7.9.0

#1277 [ML] Parallelise the feature importance calculation for classification and regression over trees
  docs/CHANGELOG.asciidoc
  include/core/Concurrency.h
  include/maths/CTreeShapFeatureImportance.h
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/CTreeShapFeatureImportance.cc
  lib/maths/unittest/CTreeShapFeatureImportanceTest.cc
Labels: :ml/DataFrameAnalysis, >enhancement, review, v7.9.0, v8.0.0
