Repository elastic/ml-cpp, pull requests merged in 2020-06, with the labels that each got.

#1292 [7.9][ML] Parallelise the feature importance calculation for classification and regression over trees
  docs/CHANGELOG.asciidoc
  include/core/Concurrency.h
  include/maths/CTreeShapFeatureImportance.h
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/CTreeShapFeatureImportance.cc
  lib/maths/unittest/CTreeShapFeatureImportanceTest.cc
Labels: backport, v7.9.0

#1268 [ML] Fix blow up of model bounds
  docs/CHANGELOG.asciidoc
  include/maths/CMultimodalPrior.h
  include/maths/CMultimodalPriorUtils.h
  lib/maths/CMultimodalPrior.cc
  lib/maths/unittest/CMultimodalPriorTest.cc
Labels: :ml, >enhancement, review, v7.9.0, v8.0.0

#1295 [7.9][ML] Fix blow up of model bounds
  docs/CHANGELOG.asciidoc
  include/maths/CMultimodalPrior.h
  include/maths/CMultimodalPriorUtils.h
  lib/maths/CMultimodalPrior.cc
  lib/maths/unittest/CMultimodalPriorTest.cc
Labels: backport, v7.9.0

#1296 [ML] Silence some gcc warnings
  include/core/Concurrency.h
  include/maths/CBoostedTreeLoss.h
  lib/core/unittest/CImmutableRadixSetTest.cc
  lib/maths/CTimeSeriesDecompositionDetail.cc
  lib/maths/unittest/CTimeSeriesModelTest.cc
Labels: >non-issue, >refactoring, v7.9.0, v8.0.0

#1294 [ML] Report memory usage during DFA job initialization
  docs/CHANGELOG.asciidoc
  include/api/CDataFrameAnalysisInstrumentation.h
  lib/api/CDataFrameAnalysisInstrumentation.cc
  lib/api/CDataFrameAnalyzer.cc
  lib/api/unittest/CDataFrameAnalysisInstrumentationTest.cc
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/COutliers.cc
Labels: :ml/DataFrameAnalysis, >enhancement, v7.9.0, v8.0.0

#1297 [ML] Improve seasonal component test parameterisation
  include/core/Constants.h
  include/maths/CPeriodicityHypothesisTests.h
  include/maths/CTimeSeriesDecompositionDetail.h
  lib/maths/CPeriodicityHypothesisTests.cc
  lib/maths/CTimeSeriesDecompositionDetail.cc
  lib/maths/unittest/CTimeSeriesDecompositionTest.cc
Labels: :ml, >non-issue, review

#1300 [ML] Add state checkpoints during coarse parameter search for classification and regression
  docs/CHANGELOG.asciidoc
  include/core/CPersistUtils.h
  include/maths/CBoostedTreeFactory.h
  include/maths/CBoostedTreeImpl.h
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/unittest/CBoostedTreeTest.cc
Labels: :ml/DataFrameAnalysis, >enhancement, review, v7.9.0, v8.0.0

#1301 [ML] Report memory usage during DFA job initialization (#1294)
  docs/CHANGELOG.asciidoc
  include/api/CDataFrameAnalysisInstrumentation.h
  lib/api/CDataFrameAnalysisInstrumentation.cc
  lib/api/CDataFrameAnalyzer.cc
  lib/api/unittest/CDataFrameAnalysisInstrumentationTest.cc
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/COutliers.cc
Labels: :ml/DataFrameAnalysis, >enhancement, backport, v7.9.0

#1303 [7.9][ML] Add state checkpoints during coarse parameter search for classification and regression
  docs/CHANGELOG.asciidoc
  include/core/CPersistUtils.h
  include/core/Concurrency.h
  include/maths/CBoostedTreeFactory.h
  include/maths/CBoostedTreeImpl.h
  include/maths/CBoostedTreeLoss.h
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
  lib/core/unittest/CImmutableRadixSetTest.cc
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/CTimeSeriesDecompositionDetail.cc
  lib/maths/unittest/CBoostedTreeTest.cc
  lib/maths/unittest/CTimeSeriesModelTest.cc
Labels: backport, v7.9.0

#1302 [ML] Fix "Unable to compute percentiles: doesn't bracket root..." log errors
  lib/maths/CMultimodalPrior.cc
Labels: :ml, >non-issue, review, v7.9.0, v8.0.0

#1304 [7.9][ML] Fix "Unable to compute percentiles: doesn't bracket root..." log errors
  lib/maths/CMultimodalPrior.cc
Labels: >non-issue, backport, v7.9.0

#1247 Report model change annotations via result stream
  docs/CHANGELOG.asciidoc
  include/api/CAnnotationJsonWriter.h
  include/api/CAnomalyJob.h
  include/maths/CModel.h
  include/maths/CTimeSeriesDecomposition.h
  include/maths/CTimeSeriesDecompositionDetail.h
  include/maths/CTimeSeriesDecompositionInterface.h
  include/maths/CTimeSeriesDecompositionStub.h
  include/maths/CTimeSeriesModel.h
  include/maths/MathsTypes.h
  include/model/CAnnotation.h
  include/model/CAnomalyDetector.h
  include/model/CAnomalyDetectorModel.h
  include/model/CCountingModel.h
  include/model/CEventRateModel.h
  include/model/CEventRatePopulationModel.h
  include/model/CMetricModel.h
  include/model/CMetricPopulationModel.h
  include/model/CModelFactory.h
  include/model/CModelParams.h
  lib/api/CAnnotationJsonWriter.cc
  lib/api/CAnomalyJob.cc
  lib/api/Makefile.first
  lib/api/unittest/CAnnotationJsonWriterTest.cc
  lib/api/unittest/CConfigUpdaterTest.cc
  lib/api/unittest/Makefile
  lib/maths/CModel.cc
  lib/maths/CTimeSeriesDecomposition.cc
  lib/maths/CTimeSeriesDecompositionDetail.cc
  lib/maths/CTimeSeriesDecompositionStub.cc
  lib/maths/CTimeSeriesModel.cc
  lib/model/CAnnotation.cc
  lib/model/CAnomalyDetector.cc
  lib/model/CAnomalyDetectorModelConfig.cc
  lib/model/CCountingModel.cc
  lib/model/CEventRateModel.cc
  lib/model/CEventRatePopulationModel.cc
  lib/model/CMetricModel.cc
  lib/model/CMetricPopulationModel.cc
  lib/model/CModelFactory.cc
  lib/model/CModelParams.cc
  lib/model/Makefile
  lib/model/unittest/Mocks.cc
  lib/model/unittest/Mocks.h
Labels: :ml, >feature, v7.9.0, v8.0.0

#1306 [7.x] Report model change annotations via result stream (#1247)
  docs/CHANGELOG.asciidoc
  include/api/CAnnotationJsonWriter.h
  include/api/CAnomalyJob.h
  include/maths/CModel.h
  include/maths/CTimeSeriesDecomposition.h
  include/maths/CTimeSeriesDecompositionDetail.h
  include/maths/CTimeSeriesDecompositionInterface.h
  include/maths/CTimeSeriesDecompositionStub.h
  include/maths/CTimeSeriesModel.h
  include/maths/MathsTypes.h
  include/model/CAnnotation.h
  include/model/CAnomalyDetector.h
  include/model/CAnomalyDetectorModel.h
  include/model/CCountingModel.h
  include/model/CEventRateModel.h
  include/model/CEventRatePopulationModel.h
  include/model/CMetricModel.h
  include/model/CMetricPopulationModel.h
  include/model/CModelFactory.h
  include/model/CModelParams.h
  lib/api/CAnnotationJsonWriter.cc
  lib/api/CAnomalyJob.cc
  lib/api/Makefile.first
  lib/api/unittest/CAnnotationJsonWriterTest.cc
  lib/api/unittest/CConfigUpdaterTest.cc
  lib/api/unittest/Makefile
  lib/maths/CModel.cc
  lib/maths/CTimeSeriesDecomposition.cc
  lib/maths/CTimeSeriesDecompositionDetail.cc
  lib/maths/CTimeSeriesDecompositionStub.cc
  lib/maths/CTimeSeriesModel.cc
  lib/model/CAnnotation.cc
  lib/model/CAnomalyDetector.cc
  lib/model/CAnomalyDetectorModelConfig.cc
  lib/model/CCountingModel.cc
  lib/model/CEventRateModel.cc
  lib/model/CEventRatePopulationModel.cc
  lib/model/CMetricModel.cc
  lib/model/CMetricPopulationModel.cc
  lib/model/CModelFactory.cc
  lib/model/CModelParams.cc
  lib/model/Makefile
  lib/model/unittest/Mocks.cc
  lib/model/unittest/Mocks.h
Labels: :ml, >feature, backport

#1312 [ML] Improve data access pattern computing best splits for classification and regression
  docs/CHANGELOG.asciidoc
  include/maths/CBoostedTreeImpl.h
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/CSampling.cc
  lib/maths/unittest/CSamplingTest.cc
Labels: :ml/DataFrameAnalysis, >enhancement, review, v7.9.0, v8.0.0

#1314 [7.9][ML] Tailor the data frame slice size per analysis type
  include/api/CDataFrameAnalysisRunner.h
  include/api/CDataFrameOutliersRunner.h
  include/api/CDataFrameTrainBoostedTreeRunner.h
  include/core/CDataFrame.h
  include/core/Concurrency.h
  include/maths/CBoostedTreeLoss.h
  lib/api/CDataFrameAnalysisSpecification.cc
  lib/api/CDataFrameOutliersRunner.cc
  lib/api/CDataFrameTrainBoostedTreeRunner.cc
  lib/api/unittest/CDataFrameMockAnalysisRunner.cc
  lib/api/unittest/CDataFrameMockAnalysisRunner.h
  lib/core/CDataFrame.cc
  lib/maths/CBoostedTree.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/CBoostedTreeLoss.cc
Labels: >non-issue, backport, v7.9.0

#1315 [7.9][ML] Improve data access pattern computing best splits for classification and regression
  docs/CHANGELOG.asciidoc
  include/maths/CBoostedTreeImpl.h
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/CSampling.cc
  lib/maths/unittest/CSamplingTest.cc
Labels: backport, v7.9.0

#1319 [ML] Remove Vagrant setup files
  dev-tools/vagrant/.gitignore
  dev-tools/vagrant/linux/README.md
  dev-tools/vagrant/linux/Vagrantfile
  dev-tools/vagrant/linux/provision.sh
Labels: :ml, >non-issue, v7.9.0, v8.0.0

#1321 [7.x][ML] Remove Vagrant setup files
  dev-tools/vagrant/.gitignore
  dev-tools/vagrant/linux/README.md
  dev-tools/vagrant/linux/Vagrantfile
  dev-tools/vagrant/linux/provision.sh
Labels: >non-issue, backport, v7.9.0

#1311 [ML] Better interrupt handling during named pipe connection
  bin/controller/CBlockingCallCancellerThread.cc
  bin/controller/CBlockingCallCancellerThread.h
  bin/controller/Main.cc
  bin/controller/unittest/CBlockingCallCancellerThreadTest.cc
  docs/CHANGELOG.asciidoc
  include/core/CLogger.h
  include/core/CNamedPipeFactory.h
  lib/api/CIoManager.cc
  lib/core/CLogger.cc
  lib/core/CNamedPipeFactory.cc
  lib/core/CNamedPipeFactory_Windows.cc
  lib/core/CThread.cc
  lib/core/unittest/CNamedPipeFactoryTest.cc
  lib/seccomp/unittest/CSystemCallFilterTest.cc
Labels: :ml, >bug, v6.8.11, v7.8.1, v7.9.0, v8.0.0

#1324 [7.x][ML] Better interrupt handling during named pipe connection
  bin/controller/CBlockingCallCancellerThread.cc
  bin/controller/CBlockingCallCancellerThread.h
  bin/controller/Main.cc
  bin/controller/unittest/CBlockingCallCancellerThreadTest.cc
  docs/CHANGELOG.asciidoc
  include/core/CLogger.h
  include/core/CNamedPipeFactory.h
  lib/api/CIoManager.cc
  lib/core/CLogger.cc
  lib/core/CNamedPipeFactory.cc
  lib/core/CNamedPipeFactory_Windows.cc
  lib/core/CThread.cc
  lib/core/unittest/CNamedPipeFactoryTest.cc
  lib/seccomp/unittest/CSystemCallFilterTest.cc
Labels: backport, v7.9.0

#1326 [6.8][ML] Better interrupt handling during named pipe connection
  bin/controller/CBlockingCallCancellerThread.cc
  bin/controller/CBlockingCallCancellerThread.h
  bin/controller/Main.cc
  bin/controller/unittest/CBlockingCallCancellerThreadTest.cc
  docs/CHANGELOG.asciidoc
  include/core/CLogger.h
  include/core/CNamedPipeFactory.h
  lib/api/CIoManager.cc
  lib/core/CLogger.cc
  lib/core/CNamedPipeFactory.cc
  lib/core/CNamedPipeFactory_Windows.cc
  lib/core/CThread.cc
  lib/core/unittest/CNamedPipeFactoryTest.cc
  lib/seccomp/Makefile
  lib/seccomp/unittest/CSystemCallFilterTest.cc
Labels: backport, v6.8.11

#1325 [7.8][ML] Better interrupt handling during named pipe connection
  bin/controller/CBlockingCallCancellerThread.cc
  bin/controller/CBlockingCallCancellerThread.h
  bin/controller/Main.cc
  bin/controller/unittest/CBlockingCallCancellerThreadTest.cc
  docs/CHANGELOG.asciidoc
  include/core/CLogger.h
  include/core/CNamedPipeFactory.h
  lib/api/CIoManager.cc
  lib/core/CLogger.cc
  lib/core/CNamedPipeFactory.cc
  lib/core/CNamedPipeFactory_Windows.cc
  lib/core/CThread.cc
  lib/core/unittest/CNamedPipeFactoryTest.cc
  lib/seccomp/unittest/CSystemCallFilterTest.cc
Labels: backport, v7.8.1

#1317 [ML] Threading speedups for classification and regression
  docs/CHANGELOG.asciidoc
  include/core/CDataFrame.h
  include/core/CImmutableRadixSet.h
  include/core/CPackedBitVector.h
  include/core/Concurrency.h
  include/maths/CBoostedTreeImpl.h
  include/maths/CBoostedTreeLeafNodeStatistics.h
  include/maths/CBoostedTreeUtils.h
  include/maths/CDataFrameCategoryEncoder.h
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
  lib/core/CDataFrame.cc
  lib/core/CPackedBitVector.cc
  lib/core/unittest/CConcurrencyTest.cc
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/CBoostedTreeLeafNodeStatistics.cc
  lib/maths/CBoostedTreeUtils.cc
  lib/maths/CDataFrameCategoryEncoder.cc
  lib/maths/CDataFrameUtils.cc
  lib/maths/unittest/CBoostedTreeTest.cc
Labels: :ml/DataFrameAnalysis, >enhancement, review, v7.9.0, v8.0.0

#1323 [ML] Remove volatile and update thread-safe static initialisation
  include/api/CDataFrameAnalysisRunner.h
  include/api/CForecastRunner.h
  include/core/CDualThreadStreamBuf.h
  include/core/CLogger.h
  include/core/CTimeUtils.h
  include/core/CWordDictionary.h
  lib/api/CForecastRunner.cc
  lib/core/CDualThreadStreamBuf.cc
  lib/core/CLogger.cc
  lib/core/CTimeUtils.cc
  lib/core/CWordDictionary.cc
Labels: :ml, >non-issue, v7.9.0, v8.0.0

#1328 [ML] Fix "Unable to compute percentiles: doesn't bracket root..." log errors (part 2)
  lib/maths/CMultimodalPrior.cc
Labels: :ml, >non-issue, review, v7.9.0, v8.0.0

#1331 [ML] Adjust 3rd party info for Moby
  3rd_party/licenses/moby-INFO.csv
Labels: :ml, >non-issue, v6.8.11, v7.8.1, v7.9.0, v8.0.0

#1330 [7.x][ML] Remove volatile and update thread-safe static initialisation
  include/api/CDataFrameAnalysisRunner.h
  include/api/CForecastRunner.h
  include/core/CDualThreadStreamBuf.h
  include/core/CLogger.h
  include/core/CTimeUtils.h
  include/core/CWordDictionary.h
  lib/api/CForecastRunner.cc
  lib/core/CDualThreadStreamBuf.cc
  lib/core/CLogger.cc
  lib/core/CTimeUtils.cc
  lib/core/CWordDictionary.cc
Labels: >non-issue, backport, v7.9.0

#1334 [7.x][ML] Adjust 3rd party info for Moby
  3rd_party/licenses/moby-INFO.csv
Labels: >non-issue, backport, v7.9.0

#1335 [7.8][ML] Adjust 3rd party info for Moby
  3rd_party/licenses/moby-INFO.csv
Labels: >non-issue, backport, v7.8.1

#1336 [6.8][ML] Adjust 3rd party info for Moby
  3rd_party/licenses/moby-INFO.csv
Labels: >non-issue, backport, v6.8.11

#1338 [ML] UTF-16 String length computation
  include/core/CStringUtils.h
  lib/core/CStringUtils.cc
  lib/core/unittest/CStringUtilsTest.cc
Labels: :ml, >non-issue, v7.9.0, v8.0.0

#1339 [ML] Make swap and move functions noexcept where possible
  include/api/CFieldConfig.h
  include/core/CDataFrameRowSlice.h
  include/maths/CAdaptiveBucketing.h
  include/maths/CBjkstUniqueValues.h
  include/maths/CCountMinSketch.h
  include/maths/CDecompositionComponent.h
  include/maths/CKMeansOnline.h
  include/maths/CLassoLogisticRegression.h
  include/maths/CMultinomialConjugate.h
  include/maths/CMultivariatePrior.h
  include/maths/CPrior.h
  include/model/CAnnotatedProbability.h
  include/model/CHierarchicalResults.h
  include/model/CSearchKey.h
  lib/api/CFieldConfig.cc
  lib/core/CDataFrameRowSlice.cc
  lib/maths/CAdaptiveBucketing.cc
  lib/maths/CBjkstUniqueValues.cc
  lib/maths/CCountMinSketch.cc
  lib/maths/CDecompositionComponent.cc
  lib/maths/CLassoLogisticRegression.cc
  lib/maths/CMultinomialConjugate.cc
  lib/maths/CMultivariatePrior.cc
  lib/maths/CPrior.cc
  lib/model/CAnnotatedProbability.cc
  lib/model/CHierarchicalResults.cc
  lib/model/CSearchKey.cc
Labels: :ml, >refactoring, v7.9.0, v8.0.0

#1332 [7.9][ML] Threading speedups for classification and regression
  docs/CHANGELOG.asciidoc
  include/core/CDataFrame.h
  include/core/CImmutableRadixSet.h
  include/core/CPackedBitVector.h
  include/core/Concurrency.h
  include/maths/CBoostedTreeImpl.h
  include/maths/CBoostedTreeLeafNodeStatistics.h
  include/maths/CBoostedTreeUtils.h
  include/maths/CDataFrameCategoryEncoder.h
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
  lib/core/CDataFrame.cc
  lib/core/CPackedBitVector.cc
  lib/core/unittest/CConcurrencyTest.cc
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/CBoostedTreeLeafNodeStatistics.cc
  lib/maths/CBoostedTreeUtils.cc
  lib/maths/CDataFrameCategoryEncoder.cc
  lib/maths/CDataFrameUtils.cc
  lib/maths/unittest/CBoostedTreeTest.cc
Labels: backport, v7.9.0

#1333 [7.9][ML] Fix "Unable to compute percentiles: doesn't bracket root..." log errors (part 2)
  lib/maths/CMultimodalPrior.cc
Labels: >non-issue, backport, v7.9.0

#1316 [ML] Generate memory size info for compressed model definition
  include/api/CInferenceModelDefinition.h
  lib/api/CInferenceModelDefinition.cc
  lib/api/unittest/CBoostedTreeInferenceModelBuilderTest.cc
  lib/api/unittest/testfiles/model_size_info/model_size_info.schema.json
Labels: :ml, >non-issue, v7.9.0, v8.0.0

#1342 [7.x][ML] UTF-16 String length computation
  include/core/CStringUtils.h
  lib/core/CStringUtils.cc
  lib/core/unittest/CStringUtilsTest.cc
Labels: :ml, >non-issue, backport, v7.9.0

#1343 [7.x][ML] Make swap and move functions noexcept where possible
  include/api/CFieldConfig.h
  include/core/CDataFrameRowSlice.h
  include/maths/CAdaptiveBucketing.h
  include/maths/CBjkstUniqueValues.h
  include/maths/CCountMinSketch.h
  include/maths/CDecompositionComponent.h
  include/maths/CKMeansOnline.h
  include/maths/CLassoLogisticRegression.h
  include/maths/CMultinomialConjugate.h
  include/maths/CMultivariatePrior.h
  include/maths/CPrior.h
  include/model/CAnnotatedProbability.h
  include/model/CHierarchicalResults.h
  include/model/CSearchKey.h
  lib/api/CFieldConfig.cc
  lib/core/CDataFrameRowSlice.cc
  lib/maths/CAdaptiveBucketing.cc
  lib/maths/CBjkstUniqueValues.cc
  lib/maths/CCountMinSketch.cc
  lib/maths/CDecompositionComponent.cc
  lib/maths/CLassoLogisticRegression.cc
  lib/maths/CMultinomialConjugate.cc
  lib/maths/CMultivariatePrior.cc
  lib/maths/CPrior.cc
  lib/model/CAnnotatedProbability.cc
  lib/model/CHierarchicalResults.cc
  lib/model/CSearchKey.cc
Labels: >non-issue, backport, v7.9.0

#1346 [7.x][ML] Generate memory size info for compressed model definition
  include/api/CInferenceModelDefinition.h
  lib/api/CInferenceModelDefinition.cc
  lib/api/unittest/CBoostedTreeInferenceModelBuilderTest.cc
  lib/api/unittest/testfiles/model_size_info/model_size_info.schema.json
Labels: :ml, >non-issue, backport, v7.9.0

#1341 [ML] Only compute boosted tree leaf row masks if they are needed
  include/maths/CBoostedTreeLeafNodeStatistics.h
  lib/maths/CBoostedTreeLeafNodeStatistics.cc
Labels: :ml/DataFrameAnalysis, >non-issue, review, v7.9.0, v8.0.0

#1347 [7.9][ML] Only compute boosted tree leaf row masks if they are needed
  include/maths/CBoostedTreeLeafNodeStatistics.h
  lib/maths/CBoostedTreeLeafNodeStatistics.cc
Labels: >non-issue, backport, v7.9.0

#1351 [ML] Trap potential cause of SIGFPE
  docs/CHANGELOG.asciidoc
  include/maths/CIntegerTools.h
  lib/maths/CIntegerTools.cc
Labels: :ml, >bug, review, v6.8.11, v7.8.1, v7.9.0, v8.0.0

#1355 [6.8][ML] Trap potential cause of SIGFPE
  docs/CHANGELOG.asciidoc
  include/maths/CIntegerTools.h
  lib/maths/CIntegerTools.cc
Labels: backport, v6.8.0

#1354 [7.8][ML] Trap potential cause of SIGFPE
  docs/CHANGELOG.asciidoc
  include/maths/CIntegerTools.h
  lib/maths/CIntegerTools.cc
Labels: backport, v7.8.0

#1353 [7.9][ML] Trap potential cause of SIGFPE
  docs/CHANGELOG.asciidoc
  include/maths/CIntegerTools.h
  lib/maths/CIntegerTools.cc
Labels: backport, v7.9.0

#1358 Format time period in model change annotation using CTimeUtils::durationToString
  include/core/CTimeUtils.h
  lib/core/CTimeUtils.cc
  lib/core/unittest/CTimeUtilsTest.cc
  lib/maths/CTimeSeriesDecompositionDetail.cc
Labels: :ml, >non-issue, v7.9.0, v8.0.0

#1359 [7.x] Format time period in model change annotation using CTimeUtils::durationToString (#1358)
  include/core/CTimeUtils.h
  lib/core/CTimeUtils.cc
  lib/core/unittest/CTimeUtilsTest.cc
  lib/maths/CTimeSeriesDecompositionDetail.cc
Labels: :ml, >non-issue, backport

#1360 [ML] Don't require time is supplied when adding an annotation
  include/maths/CModel.h
  include/maths/CTimeSeriesDecomposition.h
  include/maths/CTimeSeriesDecompositionDetail.h
  include/maths/CTimeSeriesDecompositionInterface.h
  include/maths/MathsTypes.h
  lib/maths/CTimeSeriesDecompositionDetail.cc
  lib/maths/CTimeSeriesModel.cc
  lib/model/CEventRateModel.cc
  lib/model/CEventRatePopulationModel.cc
  lib/model/CMetricModel.cc
  lib/model/CMetricPopulationModel.cc
Labels: :ml, >non-issue, >refactoring, v7.9.0, v8.0.0

#1356 [ML] Implement stop-on-warn for per-partition categorization
  bin/autodetect/CCmdLineParser.cc
  bin/autodetect/CCmdLineParser.h
  bin/autodetect/Main.cc
  bin/categorize/Main.cc
  docs/CHANGELOG.asciidoc
  include/api/CAnnotationJsonWriter.h
  include/api/CFieldDataCategorizer.h
  include/api/CJsonOutputWriter.h
  include/api/CSingleFieldDataCategorizer.h
  include/model/CAnnotation.h
  include/model/CDataCategorizer.h
  include/model/CTokenListDataCategorizerBase.h
  lib/api/CAnnotationJsonWriter.cc
  lib/api/CAnomalyJob.cc
  lib/api/CFieldDataCategorizer.cc
  lib/api/CJsonOutputWriter.cc
  lib/api/CSingleFieldDataCategorizer.cc
  lib/api/dump_state/Main.cc
  lib/api/unittest/CAnnotationJsonWriterTest.cc
  lib/api/unittest/CFieldDataCategorizerTest.cc
  lib/api/unittest/CPersistenceManagerTest.cc
  lib/api/unittest/CRestorePreviousStateTest.cc
  lib/api/unittest/CSingleStreamDataAdderTest.cc
  lib/api/unittest/CTestFieldDataCategorizer.cc
  lib/api/unittest/CTestFieldDataCategorizer.h
  lib/model/CAnnotation.cc
  lib/model/CEventRateModel.cc
  lib/model/CEventRatePopulationModel.cc
  lib/model/CMetricModel.cc
  lib/model/CMetricPopulationModel.cc
  lib/model/CTokenListDataCategorizerBase.cc
  lib/model/unittest/CTokenListDataCategorizerTest.cc
Labels: :ml, >enhancement, v7.9.0, v8.0.0

#1361 [7.9][ML] Don't require time is supplied when adding an annotation
  include/maths/CModel.h
  include/maths/CTimeSeriesDecomposition.h
  include/maths/CTimeSeriesDecompositionDetail.h
  include/maths/CTimeSeriesDecompositionInterface.h
  include/maths/MathsTypes.h
  lib/maths/CTimeSeriesDecompositionDetail.cc
  lib/maths/CTimeSeriesModel.cc
  lib/model/CEventRateModel.cc
  lib/model/CEventRatePopulationModel.cc
  lib/model/CMetricModel.cc
  lib/model/CMetricPopulationModel.cc
Labels: >non-issue, backport, v7.9.0

#1340 [ML] Improve bit vector encoding efficiency for sparse vectors
  docs/CHANGELOG.asciidoc
  include/core/CPackedBitVector.h
  include/maths/CBoostedTreeFactory.h
  include/maths/CBoostedTreeLeafNodeStatistics.h
  include/maths/CBoostedTreeUtils.h
  lib/api/CDataFrameTrainBoostedTreeRunner.cc
  lib/core/CPackedBitVector.cc
  lib/core/unittest/CPackedBitVectorTest.cc
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/CBoostedTreeLeafNodeStatistics.cc
  lib/maths/unittest/CBoostedTreeTest.cc
Labels: :ml/DataFrameAnalysis, >enhancement, review, v7.9.0, v8.0.0

#1345 [ML] Add memory_status to memory_stats
  include/api/CDataFrameAnalysisInstrumentation.h
  include/api/CInferenceModelDefinition.h
  lib/api/CDataFrameAnalysisInstrumentation.cc
  lib/api/unittest/CDataFrameAnalyzerOutlierTest.cc
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
  lib/api/unittest/testfiles/instrumentation/memory_usage.schema.json
Labels: :ml, >non-issue, v7.9.0, v8.0.0

#1363 [7.x][ML] Add memory_status to memory_stats
  include/api/CDataFrameAnalysisInstrumentation.h
  include/api/CInferenceModelDefinition.h
  lib/api/CDataFrameAnalysisInstrumentation.cc
  lib/api/unittest/CDataFrameAnalyzerOutlierTest.cc
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
  lib/api/unittest/testfiles/instrumentation/memory_usage.schema.json
Labels: :ml, >non-issue, backport, v7.9.0

#1349 [ML] Output inference definition in compressed format
  .gitignore
  docs/CHANGELOG.asciidoc
  include/api/CInferenceModelDefinition.h
  lib/api/CBoostedTreeInferenceModelBuilder.cc
  lib/api/CDataFrameAnalyzer.cc
  lib/api/CInferenceModelDefinition.cc
  lib/api/Makefile.first
  lib/api/unittest/CBoostedTreeInferenceModelBuilderTest.cc
  lib/api/unittest/Makefile
Labels: :ml, >enhancement, v7.9.0, v8.0.0

#1362 [7.9][ML] Improve bit vector encoding efficiency for sparse vectors
  docs/CHANGELOG.asciidoc
  include/core/CPackedBitVector.h
  include/maths/CBoostedTreeFactory.h
  include/maths/CBoostedTreeLeafNodeStatistics.h
  include/maths/CBoostedTreeUtils.h
  lib/api/CDataFrameTrainBoostedTreeRunner.cc
  lib/core/CPackedBitVector.cc
  lib/core/unittest/CPackedBitVectorTest.cc
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/CBoostedTreeLeafNodeStatistics.cc
  lib/maths/unittest/CBoostedTreeTest.cc
Labels: backport, v7.9.0

#1366 [ML] Return inference model definition before writing prediction results
  include/api/CDataFrameAnalyzer.h
  lib/api/CDataFrameAnalyzer.cc
Labels: :ml, >non-issue, v7.9.0, v8.0.0

#1367 [7.x][ML] Implement stop-on-warn for per-partition categorization
  bin/autodetect/CCmdLineParser.cc
  bin/autodetect/CCmdLineParser.h
  bin/autodetect/Main.cc
  bin/categorize/Main.cc
  docs/CHANGELOG.asciidoc
  include/api/CAnnotationJsonWriter.h
  include/api/CFieldDataCategorizer.h
  include/api/CJsonOutputWriter.h
  include/api/CSingleFieldDataCategorizer.h
  include/model/CAnnotation.h
  include/model/CDataCategorizer.h
  include/model/CTokenListDataCategorizerBase.h
  lib/api/CAnnotationJsonWriter.cc
  lib/api/CAnomalyJob.cc
  lib/api/CFieldDataCategorizer.cc
  lib/api/CJsonOutputWriter.cc
  lib/api/CSingleFieldDataCategorizer.cc
  lib/api/dump_state/Main.cc
  lib/api/unittest/CAnnotationJsonWriterTest.cc
  lib/api/unittest/CFieldDataCategorizerTest.cc
  lib/api/unittest/CPersistenceManagerTest.cc
  lib/api/unittest/CRestorePreviousStateTest.cc
  lib/api/unittest/CSingleStreamDataAdderTest.cc
  lib/api/unittest/CTestFieldDataCategorizer.cc
  lib/api/unittest/CTestFieldDataCategorizer.h
  lib/model/CAnnotation.cc
  lib/model/CEventRateModel.cc
  lib/model/CEventRatePopulationModel.cc
  lib/model/CMetricModel.cc
  lib/model/CMetricPopulationModel.cc
  lib/model/CTokenListDataCategorizerBase.cc
  lib/model/unittest/CTokenListDataCategorizerTest.cc
Labels: backport, v7.9.0

#1365 [7.x][ML] Output inference definition in compressed format
  .gitignore
  docs/CHANGELOG.asciidoc
  include/api/CInferenceModelDefinition.h
  lib/api/CBoostedTreeInferenceModelBuilder.cc
  lib/api/CDataFrameAnalyzer.cc
  lib/api/CInferenceModelDefinition.cc
  lib/api/Makefile.first
  lib/api/unittest/CBoostedTreeInferenceModelBuilderTest.cc
  lib/api/unittest/Makefile
Labels: :ml, >enhancement, backport, v7.9.0
