Repository elastic/ml-cpp, pull requests merged in 2020-07, with the labels that each got.

#1368 [7.x][ML] Return inference model definition before writing prediction results
  include/api/CDataFrameAnalyzer.h
  lib/api/CDataFrameAnalyzer.cc
Labels: :ml, >non-issue, backport, v7.9.0

#1371 [ML] Avoid instantiating string for writing model definition
  include/api/CInferenceModelDefinition.h
  include/core/CRapidJsonConcurrentLineWriter.h
  lib/api/CDataFrameAnalyzer.cc
  lib/api/CInferenceModelDefinition.cc
  lib/api/unittest/CBoostedTreeInferenceModelBuilderTest.cc
Labels: :ml, >non-issue, >refactoring, WIP, v7.9.0, v8.0.0

#1373 Add description (e.g.: "daily", "weekend weekly") to the annotation text
  include/maths/CPeriodicityHypothesisTests.h
  lib/maths/CPeriodicityHypothesisTests.cc
  lib/maths/CTimeSeriesDecompositionDetail.cc
Labels: :ml, >non-issue, v7.9.0, v8.0.0

#1374 [7.x][ML] Avoid instantiating string for writing model definition
  include/api/CInferenceModelDefinition.h
  include/core/CRapidJsonConcurrentLineWriter.h
  lib/api/CDataFrameAnalyzer.cc
  lib/api/CInferenceModelDefinition.cc
  lib/api/unittest/CBoostedTreeInferenceModelBuilderTest.cc
Labels: :ml, >non-issue, >refactoring, backport, v7.9.0

#1376 [7.x] Add description (e.g.: "daily", "weekend weekly") to the annotation text (#1373)
  include/maths/CPeriodicityHypothesisTests.h
  lib/maths/CPeriodicityHypothesisTests.cc
  lib/maths/CTimeSeriesDecompositionDetail.cc
Labels: :ml, >non-issue, backport

#1377 [ML] Memory correction coefficient fixed
  include/maths/CBoostedTreeImpl.h
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/unittest/CBoostedTreeTest.cc
Labels: :ml, >non-issue, v7.9.0, v8.0.0

#1378 [7.x][ML] Memory correction coefficient fixed
  include/maths/CBoostedTreeImpl.h
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/unittest/CBoostedTreeTest.cc
Labels: :ml, >non-issue, backport, v7.9.0

#1380 [ML] Add more logging to forecasting disk space check
  lib/api/CForecastRunner.cc
Labels: :ml, >non-issue, v7.9.0, v8.0.0

#1375 [ML] Adds exponent aggregator to the inference model definition
  docs/CHANGELOG.asciidoc
  include/api/CBoostedTreeInferenceModelBuilder.h
  include/api/CInferenceModelDefinition.h
  include/maths/CBoostedTree.h
  lib/api/CBoostedTreeInferenceModelBuilder.cc
  lib/api/CInferenceModelDefinition.cc
  lib/api/unittest/CBoostedTreeInferenceModelBuilderTest.cc
  lib/maths/CBoostedTreeImpl.cc
Labels: :ml, >bug, v7.8.2, v7.9.0, v8.0.0

#1379 [ML] Fix cause of SIGSEGV for classification and regression
  docs/CHANGELOG.asciidoc
  include/core/CDataFrame.h
  include/maths/CBoostedTreeImpl.h
  lib/core/CDataFrame.cc
  lib/core/unittest/CDataFrameTest.cc
  lib/maths/CBoostedTreeFactory.cc
Labels: :ml/DataFrameAnalysis, >bug, v7.8.2, v7.9.0, v8.0.0

#1350 [ML] Improvement initialisation of seasonal components
  include/maths/CExpandingWindow.h
  include/maths/CTools.h
  include/maths/Constants.h
  lib/maths/CAdaptiveBucketing.cc
  lib/maths/CExpandingWindow.cc
  lib/maths/CPeriodicityHypothesisTests.cc
  lib/maths/CTimeSeriesDecompositionDetail.cc
  lib/maths/CTimeSeriesModel.cc
  lib/maths/CTools.cc
  lib/maths/unittest/CExpandingWindowTest.cc
  lib/maths/unittest/CForecastTest.cc
  lib/maths/unittest/CPeriodicityHypothesisTestsTest.cc
  lib/maths/unittest/CTimeSeriesChangeDetectorTest.cc
  lib/maths/unittest/CTimeSeriesDecompositionTest.cc
  lib/maths/unittest/CTimeSeriesModelTest.cc
  lib/model/unittest/CEventRateModelTest.cc
Labels: :ml, >non-issue, review, v7.9.0, v8.0.0

#1383 [7.x][ML] Adds exponent aggregator to the inference model definition
  docs/CHANGELOG.asciidoc
  include/api/CBoostedTreeInferenceModelBuilder.h
  include/api/CInferenceModelDefinition.h
  include/maths/CBoostedTree.h
  lib/api/CBoostedTreeInferenceModelBuilder.cc
  lib/api/CInferenceModelDefinition.cc
  lib/api/unittest/CBoostedTreeInferenceModelBuilderTest.cc
  lib/maths/CBoostedTreeImpl.cc
Labels: :ml, >bug, backport, v7.9.0

#1382 [ML] Add more logging to forecasting disk space check
  lib/api/CForecastRunner.cc
Labels: >non-issue, backport, v7.9.0

#1384 [7.9][ML] Fix cause of SIGSEGV for classification and regression
  docs/CHANGELOG.asciidoc
  include/core/CDataFrame.h
  include/maths/CBoostedTreeImpl.h
  lib/core/CDataFrame.cc
  lib/core/unittest/CDataFrameTest.cc
  lib/maths/CBoostedTreeFactory.cc
Labels: backport, v7.9.0

#1381 [ML] Simplifications to anomaly detection framework
  include/api/CAnomalyJob.h
  include/api/CDataProcessor.h
  include/api/CFieldDataCategorizer.h
  include/api/CJsonOutputWriter.h
  include/api/COutputChainer.h
  include/api/COutputHandler.h
  lib/api/CAnomalyJob.cc
  lib/api/CFieldDataCategorizer.cc
  lib/api/CJsonOutputWriter.cc
  lib/api/COutputChainer.cc
  lib/api/COutputHandler.cc
  lib/api/unittest/CAnomalyJobTest.cc
  lib/api/unittest/CFieldDataCategorizerTest.cc
  lib/api/unittest/CJsonOutputWriterTest.cc
  lib/api/unittest/CMockDataProcessor.cc
  lib/api/unittest/CMockDataProcessor.h
Labels: :ml, >refactoring, v7.9.0, v8.0.0

#1390 [7.x][ML] Simplifications to anomaly detection framework
  include/api/CAnomalyJob.h
  include/api/CDataProcessor.h
  include/api/CFieldDataCategorizer.h
  include/api/CJsonOutputWriter.h
  include/api/COutputChainer.h
  include/api/COutputHandler.h
  lib/api/CAnomalyJob.cc
  lib/api/CFieldDataCategorizer.cc
  lib/api/CJsonOutputWriter.cc
  lib/api/COutputChainer.cc
  lib/api/COutputHandler.cc
  lib/api/unittest/CAnomalyJobTest.cc
  lib/api/unittest/CFieldDataCategorizerTest.cc
  lib/api/unittest/CJsonOutputWriterTest.cc
  lib/api/unittest/CMockDataProcessor.cc
  lib/api/unittest/CMockDataProcessor.h
Labels: >refactoring, backport, v7.9.0

#1388 [7.8][ML] Adds exponent aggregator to the inference model definition
  docs/CHANGELOG.asciidoc
  include/api/CBoostedTreeInferenceModelBuilder.h
  include/api/CInferenceModelDefinition.h
  include/maths/CBoostedTree.h
  lib/api/CBoostedTreeInferenceModelBuilder.cc
  lib/api/CInferenceModelDefinition.cc
  lib/api/unittest/CBoostedTreeInferenceModelBuilderTest.cc
  lib/maths/CBoostedTreeImpl.cc
Labels: :ml, >bug, v7.8.2

#1385 [7.8][ML] Fix cause of SIGSEGV for classification and regression
  docs/CHANGELOG.asciidoc
  include/core/CDataFrame.h
  include/maths/CBoostedTreeImpl.h
  lib/core/CDataFrame.cc
  lib/core/unittest/CDataFrameTest.cc
  lib/maths/CBoostedTreeFactory.cc
Labels: backport, v7.8.2

#1369 [ML] Trap potential causes of inverted forecast bounds
  docs/CHANGELOG.asciidoc
  lib/maths/CDecompositionComponent.cc
  lib/maths/CTimeSeriesDecomposition.cc
  lib/maths/CTrendComponent.cc
  lib/maths/unittest/CForecastTest.cc
Labels: :ml, >bug, review, v7.9.0, v8.0.0

#1391 [ML] Fix change detector restore
  docs/CHANGELOG.asciidoc
  include/maths/CTimeSeriesChangeDetector.h
  lib/maths/CTimeSeriesChangeDetector.cc
Labels: :ml, >bug, v6.8.12, v7.8.2, v7.9.0, v8.0.0

#1392 [6.8][ML] Fix change detector restore
  docs/CHANGELOG.asciidoc
  include/maths/CTimeSeriesChangeDetector.h
  lib/maths/CTimeSeriesChangeDetector.cc
Labels: backport, v6.8.12

#1393 [7.x][ML] Fix change detector restore
  docs/CHANGELOG.asciidoc
  include/maths/CTimeSeriesChangeDetector.h
  lib/maths/CTimeSeriesChangeDetector.cc
Labels: backport, v7.9.0

#1394 [7.8][ML] Fix change detector restore
  docs/CHANGELOG.asciidoc
  include/maths/CTimeSeriesChangeDetector.h
  lib/maths/CTimeSeriesChangeDetector.cc
Labels: backport, v7.8.2

#1397 [ML] Update user instructions for memory limit surpass
  lib/api/CDataFrameAnalysisInstrumentation.cc
Labels: :ml, >non-issue, v7.9.0, v8.0.0

#1396 [7.9][ML] Trap potential causes of inverted forecast bounds
  docs/CHANGELOG.asciidoc
  lib/maths/CDecompositionComponent.cc
  lib/maths/CTimeSeriesDecomposition.cc
  lib/maths/CTrendComponent.cc
  lib/maths/unittest/CForecastTest.cc
Labels: backport, v7.9.0

#1399 [ML] Fix a race in writing the memory usage message after circuit breaking
  lib/api/CDataFrameAnalysisInstrumentation.cc
Labels: :ml/DataFrameAnalysis, >bug, >non-issue, review, v7.9.0, v8.0.0

#1398 [7.x][ML] Update user instructions for memory limit surpass
  lib/api/CDataFrameAnalysisInstrumentation.cc
Labels: :ml, >non-issue, backport, v7.9.0

#1400 [7.9][ML] Fix a race in writing the memory usage message after circuit breaking
  lib/api/CDataFrameAnalysisInstrumentation.cc
Labels: >non-issue, backport, v7.9.0

#1389 Make CResourceMonitor report peak model memory usage
  docs/CHANGELOG.asciidoc
  include/core/CProgramCounters.h
  include/model/CResourceMonitor.h
  lib/api/CModelSizeStatsJsonWriter.cc
  lib/api/unittest/CJsonOutputWriterTest.cc
  lib/api/unittest/CModelSnapshotJsonWriterTest.cc
  lib/model/CResourceMonitor.cc
  lib/model/unittest/CMetricAnomalyDetectorTest.cc
  lib/model/unittest/CResourceMonitorTest.cc
Labels: :ml, >enhancement, v7.9.0, v8.0.0

#1402 [ML] Fix for SIGSEGV forecasting
  docs/CHANGELOG.asciidoc
  lib/model/CAnomalyDetector.cc
Labels: :ml, >bug, review, v6.8.12, v7.8.2, v7.9.0, v8.0.0

#1403 [7.x] Make CResourceMonitor report peak model memory usage (#1389)
  docs/CHANGELOG.asciidoc
  include/core/CProgramCounters.h
  include/model/CResourceMonitor.h
  lib/api/CModelSizeStatsJsonWriter.cc
  lib/api/unittest/CJsonOutputWriterTest.cc
  lib/api/unittest/CModelSnapshotJsonWriterTest.cc
  lib/model/CResourceMonitor.cc
  lib/model/unittest/CMetricAnomalyDetectorTest.cc
  lib/model/unittest/CResourceMonitorTest.cc
Labels: :ml, >enhancement, backport

#1404 [7.9][ML] Fix for SIGSEGV forecasting
  docs/CHANGELOG.asciidoc
  lib/model/CAnomalyDetector.cc
Labels: backport, v7.9.0

#1405 [7.8][ML] Fix for SIGSEGV forecasting
  docs/CHANGELOG.asciidoc
  lib/model/CAnomalyDetector.cc
Labels: backport, v7.9.0

#1406 [ML] Restrict growth of max matching string length for categories
  docs/CHANGELOG.asciidoc
  include/model/CTokenListCategory.h
  lib/model/CTokenListCategory.cc
  lib/model/CTokenListDataCategorizerBase.cc
  lib/model/unittest/CTokenListDataCategorizerTest.cc
Labels: :ml, >bug, v7.10.0, v7.9.0, v8.0.0

#1410 [7.x][ML] Restrict growth of max matching string length for categories
  docs/CHANGELOG.asciidoc
  include/model/CTokenListCategory.h
  lib/model/CTokenListCategory.cc
  lib/model/CTokenListDataCategorizerBase.cc
  lib/model/unittest/CTokenListDataCategorizerTest.cc
Labels: backport, v7.10.0

#1407 [ML] New memory estimation correction function
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/unittest/CBoostedTreeTest.cc
Labels: :ml, >non-issue, v7.10.0, v7.9.0, v8.0.0

#1411 [7.9][ML] Restrict growth of max matching string length for categories
  docs/CHANGELOG.asciidoc
  include/model/CTokenListCategory.h
  lib/model/CTokenListCategory.cc
  lib/model/CTokenListDataCategorizerBase.cc
  lib/model/unittest/CTokenListDataCategorizerTest.cc
Labels: backport, v7.9.0

#1408 [ML] handles new optional analysis parameter `feature_processors`
  include/api/CBoostedTreeInferenceModelBuilder.h
  include/api/CDataFrameTrainBoostedTreeRunner.h
  include/api/CInferenceModelDefinition.h
  include/test/CDataFrameAnalysisSpecificationFactory.h
  lib/api/CBoostedTreeInferenceModelBuilder.cc
  lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
  lib/api/CDataFrameTrainBoostedTreeRegressionRunner.cc
  lib/api/CDataFrameTrainBoostedTreeRunner.cc
  lib/api/CInferenceModelDefinition.cc
  lib/api/unittest/CBoostedTreeInferenceModelBuilderTest.cc
  lib/test/CDataFrameAnalysisSpecificationFactory.cc
Labels: :ml, >non-issue, v7.10.0, v8.0.0

#1412 [7.x][ML] New memory estimation correction function
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/unittest/CBoostedTreeTest.cc
Labels: :ml, >non-issue, backport, v7.10.0

#1415 [ML] Testing for no change should not use the change trend model
  lib/maths/CTimeSeriesChangeDetector.cc
Labels: >bug, >non-issue, v6.8.12, v7.10.0, v7.8.2, v7.9.0, v8.0.0

#1416 [7.8][ML] Testing for no change should not use the change trend model
  lib/maths/CTimeSeriesChangeDetector.cc
Labels: >non-issue, backport, v7.8.1

#1413 [7.9][ML] New memory estimation correction function
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/unittest/CBoostedTreeTest.cc
Labels: :ml, >non-issue, backport, v7.9.0

#1418 [7.10][ML] Testing for no change should not use the change trend model
  lib/maths/CTimeSeriesChangeDetector.cc
Labels: >non-issue, backport, v7.10.0

#1414 [7.x] [ML] handles new optional analysis parameter `feature_processors` (#1408)
  include/api/CBoostedTreeInferenceModelBuilder.h
  include/api/CDataFrameTrainBoostedTreeRunner.h
  include/api/CInferenceModelDefinition.h
  include/test/CDataFrameAnalysisSpecificationFactory.h
  lib/api/CBoostedTreeInferenceModelBuilder.cc
  lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
  lib/api/CDataFrameTrainBoostedTreeRegressionRunner.cc
  lib/api/CDataFrameTrainBoostedTreeRunner.cc
  lib/api/CInferenceModelDefinition.cc
  lib/api/unittest/CBoostedTreeInferenceModelBuilderTest.cc
  lib/test/CDataFrameAnalysisSpecificationFactory.cc
Labels: :ml, >non-issue, backport

#1409 [ML] Refactor data processor chaining
  bin/autodetect/Main.cc
  bin/categorize/Main.cc
  bin/normalize/Main.cc
  include/api/CCsvInputParser.h
  include/api/CCsvOutputWriter.h
  include/api/CDataProcessor.h
  include/api/CFieldDataCategorizer.h
  include/api/CInputParser.h
  include/api/CLengthEncodedInputParser.h
  include/api/CNdInputParser.h
  include/api/CNdJsonInputParser.h
  include/api/CNdJsonOutputWriter.h
  include/api/CNullOutput.h
  include/api/COutputChainer.h
  include/api/CResultNormalizer.h
  include/api/CSimpleOutputWriter.h
  lib/api/CCmdSkeleton.cc
  lib/api/CCsvInputParser.cc
  lib/api/CCsvOutputWriter.cc
  lib/api/CDataProcessor.cc
  lib/api/CFieldDataCategorizer.cc
  lib/api/CInputParser.cc
  lib/api/CLengthEncodedInputParser.cc
  lib/api/CNdInputParser.cc
  lib/api/CNdJsonInputParser.cc
  lib/api/CNdJsonOutputWriter.cc
  lib/api/CNullOutput.cc
  lib/api/COutputChainer.cc
  lib/api/COutputHandler.cc
  lib/api/CResultNormalizer.cc
  lib/api/CSimpleOutputWriter.cc
  lib/api/Makefile.first
  lib/api/dump_state/Main.cc
  lib/api/unittest/CAnomalyJobLimitTest.cc
  lib/api/unittest/CCsvInputParserTest.cc
  lib/api/unittest/CCsvOutputWriterTest.cc
  lib/api/unittest/CFieldDataCategorizerTest.cc
  lib/api/unittest/CLengthEncodedInputParserTest.cc
  lib/api/unittest/CMockDataProcessor.cc
  lib/api/unittest/CMockDataProcessor.h
  lib/api/unittest/COutputChainerTest.cc
  lib/api/unittest/CPersistenceManagerTest.cc
  lib/api/unittest/CRestorePreviousStateTest.cc
  lib/api/unittest/CSingleStreamDataAdderTest.cc
  lib/api/unittest/CTestFieldDataCategorizer.cc
  lib/api/unittest/CTestFieldDataCategorizer.h
  lib/api/unittest/Makefile
Labels: :ml, >refactoring, v7.10.0, v8.0.0

#1420 [ML] Fix undefined behaviour
  include/api/CDataFrameTrainBoostedTreeRunner.h
  include/api/CInferenceModelDefinition.h
  include/test/CDataFrameAnalysisSpecificationFactory.h
  lib/api/CDataFrameTrainBoostedTreeRunner.cc
  lib/api/CInferenceModelDefinition.cc
  lib/test/CDataFrameAnalysisSpecificationFactory.cc
Labels: >bug, >non-issue, review, v7.10.0, v8.0.0

#1421 [7.x][ML] Refactor data processor chaining
  bin/autodetect/Main.cc
  bin/categorize/Main.cc
  bin/normalize/Main.cc
  include/api/CCsvInputParser.h
  include/api/CCsvOutputWriter.h
  include/api/CDataProcessor.h
  include/api/CFieldDataCategorizer.h
  include/api/CInputParser.h
  include/api/CLengthEncodedInputParser.h
  include/api/CNdInputParser.h
  include/api/CNdJsonInputParser.h
  include/api/CNdJsonOutputWriter.h
  include/api/CNullOutput.h
  include/api/COutputChainer.h
  include/api/CResultNormalizer.h
  include/api/CSimpleOutputWriter.h
  lib/api/CCmdSkeleton.cc
  lib/api/CCsvInputParser.cc
  lib/api/CCsvOutputWriter.cc
  lib/api/CDataProcessor.cc
  lib/api/CFieldDataCategorizer.cc
  lib/api/CInputParser.cc
  lib/api/CLengthEncodedInputParser.cc
  lib/api/CNdInputParser.cc
  lib/api/CNdJsonInputParser.cc
  lib/api/CNdJsonOutputWriter.cc
  lib/api/CNullOutput.cc
  lib/api/COutputChainer.cc
  lib/api/COutputHandler.cc
  lib/api/CResultNormalizer.cc
  lib/api/CSimpleOutputWriter.cc
  lib/api/Makefile.first
  lib/api/dump_state/Main.cc
  lib/api/unittest/CAnomalyJobLimitTest.cc
  lib/api/unittest/CCsvInputParserTest.cc
  lib/api/unittest/CCsvOutputWriterTest.cc
  lib/api/unittest/CFieldDataCategorizerTest.cc
  lib/api/unittest/CLengthEncodedInputParserTest.cc
  lib/api/unittest/CMockDataProcessor.cc
  lib/api/unittest/CMockDataProcessor.h
  lib/api/unittest/COutputChainerTest.cc
  lib/api/unittest/CPersistenceManagerTest.cc
  lib/api/unittest/CRestorePreviousStateTest.cc
  lib/api/unittest/CSingleStreamDataAdderTest.cc
  lib/api/unittest/CTestFieldDataCategorizer.cc
  lib/api/unittest/CTestFieldDataCategorizer.h
  lib/api/unittest/Makefile
Labels: >refactoring, backport, v7.10.0

#1424 [ML] Fix custom processor tests
  lib/api/unittest/CBoostedTreeInferenceModelBuilderTest.cc
Labels: :ml/DataFrameAnalysis, >non-issue, v7.10.0, v8.0.0

#1423 [7.10][ML] Fix undefined behaviour
  include/api/CDataFrameTrainBoostedTreeRunner.h
  include/api/CInferenceModelDefinition.h
  include/test/CDataFrameAnalysisSpecificationFactory.h
  lib/api/CDataFrameTrainBoostedTreeRunner.cc
  lib/api/CInferenceModelDefinition.cc
  lib/test/CDataFrameAnalysisSpecificationFactory.cc
Labels: >non-issue, backport, v7.10.0

#1419 [7.9][ML] Testing for no change should not use the change trend model
  lib/maths/CTimeSeriesChangeDetector.cc
Labels: >non-issue, backport, v7.9.0

#1417 [6.8][ML] Testing for no change should not use the change trend model
  lib/maths/CTimeSeriesChangeDetector.cc
Labels: >non-issue, backport, v6.8.12

#1425 [7.x][ML] Fix custom processor tests
  lib/api/unittest/CBoostedTreeInferenceModelBuilderTest.cc
Labels: >non-issue, backport, v7.10.0

#1422 [ML] Remove dead code in simple output writers
  include/api/CCsvOutputWriter.h
  include/api/CNdJsonOutputWriter.h
  include/api/CSimpleOutputWriter.h
  lib/api/CCsvOutputWriter.cc
  lib/api/CNdJsonOutputWriter.cc
  lib/api/CSimpleOutputWriter.cc
  lib/api/unittest/CCsvOutputWriterTest.cc
  lib/api/unittest/CNdJsonOutputWriterTest.cc
Labels: :ml, >refactoring, v7.10.0, v8.0.0

#1427 Fix deprecated Gradle API usage
  build.gradle
  buildSrc/build.gradle
  gradle.properties
  upload.gradle
Labels: >build, >non-issue, v7.10.0, v7.9.0, v8.0.0

#1430 [7.x] Fix deprecated Gradle API usage
  build.gradle
  buildSrc/build.gradle
  gradle.properties
  upload.gradle
Labels: >non-issue, backport, v7.10.0

#1431 [7.9] Fix deprecated Gradle API usage
  build.gradle
  buildSrc/build.gradle
  gradle.properties
  upload.gradle
Labels: >non-issue, backport, v7.9.0

#1370 Add script and config for FOSSA scanning
  .fossa.yml
  dev-tools/fossa_scan.sh
Labels: :ml, >non-issue, v6.8.12, v7.10.0, v7.8.2, v7.9.0, v8.0.0

#1433 [6.8] Add script and config for FOSSA scanning
  .fossa.yml
  dev-tools/fossa_scan.sh
Labels: >non-issue, backport, v6.8.12

#1434 [7.8] Add script and config for FOSSA scanning
  .fossa.yml
  dev-tools/fossa_scan.sh
Labels: >non-issue, backport, v7.8.2

#1435 [7.9] Add script and config for FOSSA scanning
  .fossa.yml
  dev-tools/fossa_scan.sh
Labels: >non-issue, backport, v7.9.0

#1436 [7.x] Add script and config for FOSSA scanning
  .fossa.yml
  dev-tools/fossa_scan.sh
Labels: >non-issue, backport, v7.10.0

#1432 [ML] Fixing memory_status output on fatal error
  lib/api/CDataFrameAnalysisInstrumentation.cc
  lib/api/unittest/CDataFrameAnalyzerOutlierTest.cc
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
  lib/core/CRapidJsonConcurrentLineWriter.cc
Labels: :ml, >non-issue, v7.10.0, v7.9.0, v8.0.0

#1439 [7.9][ML] Fixing memory_status output on fatal error
  lib/api/CDataFrameAnalysisInstrumentation.cc
  lib/api/unittest/CDataFrameAnalyzerOutlierTest.cc
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
  lib/core/CRapidJsonConcurrentLineWriter.cc
Labels: :ml, >non-issue, backport, v7.9.0

#1438 [7.x][ML] Fixing memory_status output on fatal error
  lib/api/CDataFrameAnalysisInstrumentation.cc
  lib/api/unittest/CDataFrameAnalyzerOutlierTest.cc
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
  lib/core/CRapidJsonConcurrentLineWriter.cc
Labels: :ml, >non-issue, backport, v7.10.0

#1429 [ML] Upgrade to clang 8/Apple clang 11.3.1 for macOS compilation
  3rd_party/3rd_party.sh
  build-setup/macos.md
  build-setup/macos_cross_compiled.md
  dev-tools/docker/build_macosx_build_image.sh
  dev-tools/docker/macosx_builder/Dockerfile
  dev-tools/docker/macosx_image/Dockerfile
  dev-tools/strip_binaries.sh
  docs/CHANGELOG.asciidoc
  mk/linux_crosscompile_macosx.mk
Labels: :ml, >build, v8.0.0
