Repository elastic/ml-cpp, pull requests merged in 2020-04, with the labels that each got.

#1097 [ML] Add instructions for building valgrind
  build-setup/linux.md
Labels: :ml, >non-issue, v7.8.0, v8.0.0

#1115 [ML] Add instructions for building valgrind
  build-setup/linux.md
Labels: >non-issue, backport

#1111 [ML] take training_percent into account when estimating memory
  docs/CHANGELOG.asciidoc
  include/api/CDataFrameTrainBoostedTreeRunner.h
  lib/api/CDataFrameTrainBoostedTreeRunner.cc
  lib/maths/unittest/CBoostedTreeTest.cc
Labels: :ml, >enhancement, v7.8.0, v8.0.0

#1102 [ML] Speed up the lat_long function
  docs/CHANGELOG.asciidoc
  include/maths/CKMeans.h
  include/maths/CKMeansOnline.h
  include/maths/CXMeansOnline.h
  lib/maths/CInformationCriteria.cc
Labels: :ml, >enhancement, review, v7.8.0, v8.0.0

#1114 [ML] Improve bad input handling in distribution models
  docs/CHANGELOG.asciidoc
  lib/maths/CGammaRateConjugate.cc
  lib/maths/CLogNormalMeanPrecConjugate.cc
  lib/maths/CNormalMeanPrecConjugate.cc
  lib/maths/COneOfNPrior.cc
  lib/maths/CPoissonMeanConjugate.cc
  lib/maths/CPrior.cc
Labels: :ml, >enhancement, review, v7.8.0, v8.0.0

#1116 [7.x] [ML] take training_percent into account when estimating memory (#1111)
  docs/CHANGELOG.asciidoc
  include/api/CDataFrameTrainBoostedTreeRunner.h
  lib/api/CDataFrameTrainBoostedTreeRunner.cc
  lib/maths/unittest/CBoostedTreeTest.cc
Labels: :ml, backport

#1062 [ML] Adding num_matches and preferred_to_categories output to categories
  docs/CHANGELOG.asciidoc
  include/api/CFieldDataCategorizer.h
  include/api/CJsonOutputWriter.h
  include/model/CDataCategorizer.h
  include/model/CTokenListCategory.h
  include/model/CTokenListDataCategorizerBase.h
  lib/api/CFieldDataCategorizer.cc
  lib/api/CJsonOutputWriter.cc
  lib/api/unittest/CFieldDataCategorizerTest.cc
  lib/api/unittest/CJsonOutputWriterTest.cc
  lib/model/CTokenListCategory.cc
  lib/model/CTokenListDataCategorizerBase.cc
  lib/model/unittest/CTokenListDataCategorizerTest.cc
Labels: :ml, >enhancement, v7.8.0, v8.0.0

#1120 [7.x] [ML] Adding num_matches and preferred_to_categories output to categories (#1062)
  docs/CHANGELOG.asciidoc
  include/api/CFieldDataCategorizer.h
  include/api/CJsonOutputWriter.h
  include/model/CDataCategorizer.h
  include/model/CTokenListCategory.h
  include/model/CTokenListDataCategorizerBase.h
  lib/api/CFieldDataCategorizer.cc
  lib/api/CJsonOutputWriter.cc
  lib/api/unittest/CFieldDataCategorizerTest.cc
  lib/api/unittest/CJsonOutputWriterTest.cc
  lib/model/CTokenListCategory.cc
  lib/model/CTokenListDataCategorizerBase.cc
  lib/model/unittest/CTokenListDataCategorizerTest.cc
Labels: :ml, backport

#1119 [7.8][ML] Improve bad input handling in distribution models
  docs/CHANGELOG.asciidoc
  lib/maths/CGammaRateConjugate.cc
  lib/maths/CLogNormalMeanPrecConjugate.cc
  lib/maths/CNormalMeanPrecConjugate.cc
  lib/maths/COneOfNPrior.cc
  lib/maths/CPoissonMeanConjugate.cc
  lib/maths/CPrior.cc
Labels: backport, v7.8.0

#1122 [ML] Fix off-by-one error in usurped categories
  include/model/CTokenListDataCategorizerBase.h
  lib/model/CTokenListDataCategorizerBase.cc
  lib/model/unittest/CTokenListDataCategorizerTest.cc
Labels: :ml, >non-issue, v7.8.0, v8.0.0

#1117 [ML] Add getpriority/setpriority to Linux system call whitelist
  lib/seccomp/CSystemCallFilter_Linux.cc
Labels: :ml, >non-issue, v7.8.0, v8.0.0

#1123 [7.x][ML] Fix off-by-one error in usurped categories
  include/model/CTokenListDataCategorizerBase.h
  lib/model/CTokenListDataCategorizerBase.cc
  lib/model/unittest/CTokenListDataCategorizerTest.cc
Labels: >non-issue, backport

#1118 [7.8][ML] Speed up the lat_long function
  docs/CHANGELOG.asciidoc
  include/maths/CKMeans.h
  include/maths/CKMeansOnline.h
  include/maths/CXMeansOnline.h
  lib/maths/CInformationCriteria.cc
Labels: backport, v7.8.0

#1124 [7.x][ML] Add getpriority/setpriority to Linux system call whitelist
  lib/seccomp/CSystemCallFilter_Linux.cc
Labels: >non-issue, backport

#1113 [ML] Multiclass maximise minimum recall
  docs/CHANGELOG.asciidoc
  include/maths/CBoostedTreeImpl.h
  include/maths/CDataFrameUtils.h
  include/maths/CTools.h
  include/maths/CToolsDetail.h
  include/test/CDataFrameAnalyzerTrainingFactory.h
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/CBoostedTreeLoss.cc
  lib/maths/CDataFrameUtils.cc
  lib/maths/unittest/CBoostedTreeTest.cc
  lib/maths/unittest/CDataFrameUtilsTest.cc
  lib/maths/unittest/CToolsTest.cc
  lib/test/CDataFrameAnalyzerTrainingFactory.cc
Labels: :ml/DataFrameAnalysis, >enhancement, review, v7.8.0, v8.0.0

#1126 [ML] Round up data frame analytics memory estimates to next MB
  docs/CHANGELOG.asciidoc
  lib/api/CDataFrameAnalysisRunner.cc
  lib/api/unittest/CDataFrameAnalysisRunnerTest.cc
  lib/api/unittest/CMemoryUsageEstimationResultJsonWriterTest.cc
Labels: :ml/DataFrameAnalysis, >enhancement, v7.8.0, v8.0.0

#1128 [7.x][ML] Round up data frame analytics memory estimates to next MB
  docs/CHANGELOG.asciidoc
  lib/api/CDataFrameAnalysisRunner.cc
  lib/api/unittest/CDataFrameAnalysisRunnerTest.cc
  lib/api/unittest/CMemoryUsageEstimationResultJsonWriterTest.cc
Labels: backport

#1133 [7.8][ML] Multiclass maximise minimum recall
  docs/CHANGELOG.asciidoc
  include/maths/CBoostedTreeImpl.h
  include/maths/CDataFrameUtils.h
  include/maths/CTools.h
  include/maths/CToolsDetail.h
  include/test/CDataFrameAnalyzerTrainingFactory.h
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/CBoostedTreeLoss.cc
  lib/maths/CDataFrameUtils.cc
  lib/maths/unittest/CBoostedTreeTest.cc
  lib/maths/unittest/CDataFrameUtilsTest.cc
  lib/maths/unittest/CToolsTest.cc
  lib/test/CDataFrameAnalyzerTrainingFactory.cc
Labels: backport, v7.8.0

#1127 [ML] Reduce differences in regression and classification results between target platforms
  docs/CHANGELOG.asciidoc
  include/core/CIEEE754.h
  include/maths/CBoostedTreeLeafNodeStatistics.h
  include/maths/CLbfgs.h
  include/maths/CTools.h
  include/maths/CToolsDetail.h
  lib/api/unittest/CDataFrameAnalyzerFeatureImportanceTest.cc
  lib/core/CIEEE754.cc
  lib/maths/CBayesianOptimisation.cc
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/CBoostedTreeLeafNodeStatistics.cc
  lib/maths/CBoostedTreeLoss.cc
  lib/maths/unittest/CBayesianOptimisationTest.cc
  lib/maths/unittest/CBoostedTreeTest.cc
  lib/maths/unittest/CToolsTest.cc
Labels: :ml/DataFrameAnalysis, >enhancement, review, v7.8.0, v8.0.0

#1132 [ML] Native compilation and unit test for Linux on aarch64
  3rd_party/3rd_party.sh
  build-setup/linux.md
  lib/maths/unittest/CBasicStatisticsTest.cc
  lib/maths/unittest/CSplineTest.cc
  lib/maths/unittest/CXMeansOnlineTest.cc
  lib/model/unittest/CMetricDataGathererTest.cc
  lib/seccomp/CSystemCallFilter_Linux.cc
  mk/linux.mk
  set_env.sh
Labels: :ml, >non-issue, v7.8.0, v8.0.0

#1134 [7.x][ML] Native compilation and unit test for Linux on aarch64
  3rd_party/3rd_party.sh
  build-setup/linux.md
  lib/maths/unittest/CBasicStatisticsTest.cc
  lib/maths/unittest/CSplineTest.cc
  lib/maths/unittest/CXMeansOnlineTest.cc
  lib/model/unittest/CMetricDataGathererTest.cc
  lib/seccomp/CSystemCallFilter_Linux.cc
  mk/linux.mk
  set_env.sh
Labels: >non-issue, backport, v7.8.0

#1125 [ML] Eagerly discard node statistics for leaves which we will never split
  docs/CHANGELOG.asciidoc
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
  lib/api/unittest/CDataFrameMockAnalysisRunner.h
  lib/maths/CBoostedTreeImpl.cc
Labels: :ml/DataFrameAnalysis, >enhancement, review, v7.8.0, v8.0.0

#1137 [ML] Fix periodic persistence of categorizer state
  bin/autodetect/Main.cc
  bin/categorize/Main.cc
  docs/CHANGELOG.asciidoc
  include/api/CAnomalyJob.h
  include/api/CFieldDataCategorizer.h
  lib/api/CAnomalyJob.cc
  lib/api/CFieldDataCategorizer.cc
  lib/api/dump_state/Main.cc
  lib/api/unittest/CAnomalyJobLimitTest.cc
  lib/api/unittest/CAnomalyJobTest.cc
  lib/api/unittest/CFieldDataCategorizerTest.cc
  lib/api/unittest/CForecastRunnerTest.cc
  lib/api/unittest/CMultiFileDataAdderTest.cc
  lib/api/unittest/COutputChainerTest.cc
  lib/api/unittest/CPersistenceManagerTest.cc
  lib/api/unittest/CRestorePreviousStateTest.cc
  lib/api/unittest/CSingleStreamDataAdderTest.cc
  lib/api/unittest/CStringStoreTest.cc
  lib/api/unittest/CTestAnomalyJob.cc
  lib/api/unittest/CTestAnomalyJob.h
  lib/api/unittest/CTestFieldDataCategorizer.cc
  lib/api/unittest/CTestFieldDataCategorizer.h
  lib/api/unittest/Makefile
Labels: :ml, >bug, v7.7.1, v7.8.0, v8.0.0

#1139 [ML] Normalize hardware architecture from Java
  build.gradle
Labels: :ml, >non-issue, v8.0.0

#1140 [7.x][ML] Fix periodic persistence of categorizer state
  bin/autodetect/Main.cc
  bin/categorize/Main.cc
  docs/CHANGELOG.asciidoc
  include/api/CAnomalyJob.h
  include/api/CFieldDataCategorizer.h
  lib/api/CAnomalyJob.cc
  lib/api/CFieldDataCategorizer.cc
  lib/api/dump_state/Main.cc
  lib/api/unittest/CAnomalyJobLimitTest.cc
  lib/api/unittest/CAnomalyJobTest.cc
  lib/api/unittest/CFieldDataCategorizerTest.cc
  lib/api/unittest/CForecastRunnerTest.cc
  lib/api/unittest/CMultiFileDataAdderTest.cc
  lib/api/unittest/COutputChainerTest.cc
  lib/api/unittest/CPersistenceManagerTest.cc
  lib/api/unittest/CRestorePreviousStateTest.cc
  lib/api/unittest/CSingleStreamDataAdderTest.cc
  lib/api/unittest/CStringStoreTest.cc
  lib/api/unittest/CTestAnomalyJob.cc
  lib/api/unittest/CTestAnomalyJob.h
  lib/api/unittest/CTestFieldDataCategorizer.cc
  lib/api/unittest/CTestFieldDataCategorizer.h
  lib/api/unittest/Makefile
Labels: backport, v7.8.0

#1101 [ML] Implement MSLE loss function for regression
  docs/CHANGELOG.asciidoc
  include/api/CDataFrameTrainBoostedTreeRegressionRunner.h
  include/maths/CBoostedTreeLoss.h
  include/test/CDataFrameAnalysisSpecificationFactory.h
  include/test/CDataFrameAnalyzerTrainingFactory.h
  lib/api/CDataFrameTrainBoostedTreeRegressionRunner.cc
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/CBoostedTreeLoss.cc
  lib/maths/unittest/CBoostedTreeLossTest.cc
  lib/test/CDataFrameAnalysisSpecificationFactory.cc
  lib/test/CDataFrameAnalyzerTrainingFactory.cc
Labels: :ml, >enhancement, v7.8.0, v8.0.0

#1143 [7.x][ML] Implement MSLE loss function for regression
  docs/CHANGELOG.asciidoc
  include/api/CDataFrameTrainBoostedTreeRegressionRunner.h
  include/maths/CBoostedTreeLoss.h
  include/test/CDataFrameAnalysisSpecificationFactory.h
  include/test/CDataFrameAnalyzerTrainingFactory.h
  lib/api/CDataFrameTrainBoostedTreeRegressionRunner.cc
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/CBoostedTreeLoss.cc
  lib/maths/unittest/CBoostedTreeLossTest.cc
  lib/test/CDataFrameAnalysisSpecificationFactory.cc
  lib/test/CDataFrameAnalyzerTrainingFactory.cc
Labels: :ml, >enhancement, backport, v7.8.0

#1142 [ML] Ensure the performance critical data are 16 byte aligned for data frame analyses
  docs/CHANGELOG.asciidoc
  include/api/CDataFrameTrainBoostedTreeRunner.h
  include/core/CAlignment.h
  include/core/CDataFrame.h
  include/core/CDataFrameRowSlice.h
  include/maths/CBoostedTreeImpl.h
  include/maths/CBoostedTreeLeafNodeStatistics.h
  include/maths/CBoostedTreeUtils.h
  include/maths/CDataFrameUtils.h
  include/maths/CInformationCriteria.h
  include/maths/CKMeans.h
  include/maths/CLinearAlgebraEigen.h
  include/maths/CLinearAlgebraFwd.h
  include/maths/CLinearAlgebraShims.h
  include/maths/CTypeTraits.h
  lib/api/CDataFrameAnalysisRunner.cc
  lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
  lib/api/CDataFrameTrainBoostedTreeRegressionRunner.cc
  lib/api/unittest/CDataFrameAnalysisRunnerTest.cc
  lib/core/CDataFrame.cc
  lib/core/CDataFrameRowSlice.cc
  lib/core/Makefile
  lib/core/unittest/CAlignmentTest.cc
  lib/core/unittest/CDataFrameTest.cc
  lib/core/unittest/Makefile
  lib/maths/CBoostedTree.cc
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/CBoostedTreeLeafNodeStatistics.cc
  lib/maths/CBoostedTreeUtils.cc
  lib/maths/COutliers.cc
  lib/maths/CTreeShapFeatureImportance.cc
  lib/maths/unittest/CBoostedTreeLeafNodeStatisticsTest.cc
  lib/maths/unittest/CDataFrameCategoryEncoderTest.cc
  lib/maths/unittest/COutliersTest.cc
  mk/linux.mk
  mk/linux_crosscompile_linux.mk
  mk/linux_crosscompile_macosx.mk
  mk/macosx.mk
  mk/windows.mk
Labels: :ml/DataFrameAnalysis, >enhancement, review, v7.8.0, v8.0.0

#1145 [ML] Silence gcc warnings
  include/maths/COutliers.h
  include/test/CDataFrameAnalyzerTrainingFactory.h
  lib/api/CDataFrameTrainBoostedTreeRegressionRunner.cc
  lib/config/unittest/CReportWriterTest.cc
  lib/maths/COutliers.cc
  lib/maths/unittest/CMicTest.cc
  lib/maths/unittest/CMultivariateMultimodalPriorTest.cc
  lib/maths/unittest/CPeriodicityHypothesisTestsTest.cc
  lib/maths/unittest/CRandomizedPeriodicityTestTest.cc
  lib/maths/unittest/CTimeSeriesDecompositionTest.cc
  lib/maths/unittest/CTreeShapFeatureImportanceTest.cc
  lib/maths/unittest/CTrendComponentTest.cc
  lib/model/CResourceMonitor.cc
  lib/model/CRuleCondition.cc
  lib/model/unittest/CEventRatePopulationDataGathererTest.cc
  lib/model/unittest/CEventRatePopulationModelTest.cc
  lib/model/unittest/CSampleQueueTest.cc
Labels: >non-issue, >refactoring, review, v7.8.0, v8.0.0

#1146 [ML] Fix macOS sandbox rules
  lib/seccomp/CSystemCallFilter_MacOSX.cc
Labels: :ml, >non-issue, v7.8.0, v8.0.0

#1147 [7.x][ML] Fix macOS sandbox rules
  lib/seccomp/CSystemCallFilter_MacOSX.cc
Labels: >non-issue, backport, v7.8.0

#1144 [ML] Fix printing values for multiclass feature importance
  docs/CHANGELOG.asciidoc
  lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
Labels: :ml, >bug, v7.7.1, v7.8.0, v8.0.0

#1148 [7.8][ML] Eagerly discard node statistics for leaves which we will never split
  docs/CHANGELOG.asciidoc
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
  lib/api/unittest/CDataFrameMockAnalysisRunner.h
  lib/maths/CBoostedTreeImpl.cc
Labels: backport, v7.8.0

#1151 [7.8][ML] Reduce variability in regression and classification results across our target platforms
  docs/CHANGELOG.asciidoc
  include/core/CIEEE754.h
  include/maths/CBoostedTreeLeafNodeStatistics.h
  include/maths/CLbfgs.h
  include/maths/CTools.h
  include/maths/CToolsDetail.h
  lib/api/unittest/CDataFrameAnalyzerFeatureImportanceTest.cc
  lib/core/CIEEE754.cc
  lib/maths/CBayesianOptimisation.cc
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/CBoostedTreeLeafNodeStatistics.cc
  lib/maths/CBoostedTreeLoss.cc
  lib/maths/unittest/CBayesianOptimisationTest.cc
  lib/maths/unittest/CBoostedTreeTest.cc
  lib/maths/unittest/CToolsTest.cc
Labels: backport, v7.8.0

#1149 [ML] Some move related optimisations
  include/api/CForecastRunner.h
  include/core/CSmallVector.h
  include/core/Concurrency.h
  include/maths/CDataFrameCategoryEncoder.h
  include/maths/CLinearAlgebraEigen.h
  lib/api/CForecastRunner.cc
  lib/core/CDataFrameRowSlice.cc
  lib/core/CStaticThreadPool.cc
  lib/maths/CDataFrameCategoryEncoder.cc
Labels: :ml/DataFrameAnalysis, >non-issue, review, v7.8.0, v8.0.0

#1152 [7.8][ML] Ensure the performance critical data are 16 byte aligned for data frame analyses
  docs/CHANGELOG.asciidoc
  include/api/CDataFrameTrainBoostedTreeRunner.h
  include/core/CAlignment.h
  include/core/CDataFrame.h
  include/core/CDataFrameRowSlice.h
  include/maths/CBoostedTreeImpl.h
  include/maths/CBoostedTreeLeafNodeStatistics.h
  include/maths/CBoostedTreeUtils.h
  include/maths/CDataFrameUtils.h
  include/maths/CInformationCriteria.h
  include/maths/CKMeans.h
  include/maths/CLinearAlgebraEigen.h
  include/maths/CLinearAlgebraFwd.h
  include/maths/CLinearAlgebraShims.h
  include/maths/CTypeTraits.h
  lib/api/CDataFrameAnalysisRunner.cc
  lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
  lib/api/CDataFrameTrainBoostedTreeRegressionRunner.cc
  lib/api/unittest/CDataFrameAnalysisRunnerTest.cc
  lib/core/CDataFrame.cc
  lib/core/CDataFrameRowSlice.cc
  lib/core/Makefile
  lib/core/unittest/CAlignmentTest.cc
  lib/core/unittest/CDataFrameTest.cc
  lib/core/unittest/Makefile
  lib/maths/CBoostedTree.cc
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/CBoostedTreeLeafNodeStatistics.cc
  lib/maths/CBoostedTreeUtils.cc
  lib/maths/COutliers.cc
  lib/maths/CTreeShapFeatureImportance.cc
  lib/maths/unittest/CBoostedTreeLeafNodeStatisticsTest.cc
  lib/maths/unittest/CDataFrameCategoryEncoderTest.cc
  lib/maths/unittest/COutliersTest.cc
  mk/linux.mk
  mk/linux_crosscompile_linux.mk
  mk/linux_crosscompile_macosx.mk
  mk/macosx.mk
  mk/windows.mk
Labels: backport, v7.8.0

#1153 [7.8][ML] Silence gcc warnings
  include/maths/COutliers.h
  include/test/CDataFrameAnalyzerTrainingFactory.h
  lib/api/CDataFrameTrainBoostedTreeRegressionRunner.cc
  lib/config/unittest/CReportWriterTest.cc
  lib/maths/COutliers.cc
  lib/maths/unittest/CMicTest.cc
  lib/maths/unittest/CMultivariateMultimodalPriorTest.cc
  lib/maths/unittest/CPeriodicityHypothesisTestsTest.cc
  lib/maths/unittest/CRandomizedPeriodicityTestTest.cc
  lib/maths/unittest/CTimeSeriesDecompositionTest.cc
  lib/maths/unittest/CTreeShapFeatureImportanceTest.cc
  lib/maths/unittest/CTrendComponentTest.cc
  lib/model/CResourceMonitor.cc
  lib/model/CRuleCondition.cc
  lib/model/unittest/CEventRatePopulationDataGathererTest.cc
  lib/model/unittest/CEventRatePopulationModelTest.cc
  lib/model/unittest/CSampleQueueTest.cc
Labels: >non-issue, backport, v7.8.0

#1154 [7.8][ML] Some move related optimisations
  include/api/CForecastRunner.h
  include/core/CSmallVector.h
  include/core/Concurrency.h
  include/maths/CDataFrameCategoryEncoder.h
  include/maths/CLinearAlgebraEigen.h
  lib/api/CForecastRunner.cc
  lib/core/CDataFrameRowSlice.cc
  lib/core/CStaticThreadPool.cc
  lib/maths/CDataFrameCategoryEncoder.cc
Labels: >non-issue, backport, v7.8.0

#1150 [7.x][ML] Fix printing values for multiclass feature importance
  docs/CHANGELOG.asciidoc
  lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
Labels: :ml, >bug, backport, v7.8.0

#1155 [ML] Boosted tree tidy ups
  include/maths/CBoostedTreeLeafNodeStatistics.h
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/CBoostedTreeLeafNodeStatistics.cc
  lib/maths/CBoostedTreeLoss.cc
Labels: :ml/DataFrameAnalysis, >non-issue, >refactoring, review, v7.8.0, v8.0.0

#1156 [ML] Fix memory usage estimation for vectors with a custom allocator
  include/core/CMemory.h
  lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
  lib/core/unittest/CDataFrameTest.cc
  lib/core/unittest/CMemoryUsageTest.cc
Labels: :ml, >bug, >non-issue, review, v7.8.0, v8.0.0

#1158 [ML] Improve stability of trend decomposition for very sparse data
  docs/CHANGELOG.asciidoc
  lib/model/CEventRateModel.cc
  lib/model/CIndividualModel.cc
  lib/model/CMetricModel.cc
Labels: :ml, >enhancement, affects-results, review, v7.8.0, v8.0.0

#1159 [ML] Report analytics progress as phase_progress
  lib/api/CDataFrameAnalyzer.cc
  lib/api/unittest/CDataFrameAnalyzerOutlierTest.cc
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
Labels: :ml, :ml/DataFrameAnalysis, >non-issue, v7.8.0, v8.0.0

#1160 [ML] Trap and fail if no regressors are provided to classification or regression
  docs/CHANGELOG.asciidoc
  include/api/CDataFrameAnalysisRunner.h
  include/api/CDataFrameAnalysisSpecification.h
  include/api/CDataFrameOutliersRunner.h
  include/api/CDataFrameTrainBoostedTreeRunner.h
  lib/api/CDataFrameAnalysisSpecification.cc
  lib/api/CDataFrameAnalyzer.cc
  lib/api/CDataFrameOutliersRunner.cc
  lib/api/CDataFrameTrainBoostedTreeRunner.cc
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
  lib/api/unittest/CDataFrameMockAnalysisRunner.cc
  lib/api/unittest/CDataFrameMockAnalysisRunner.h
Labels: :ml/DataFrameAnalysis, >bug, review, v7.8.0, v8.0.0

#1164 Update Xcode version advice
  build-setup/macos.md
Labels: :ml, >docs, v8.0.0

#1163 [7.x][ML] Report analytics progress as phase_progress (#1159)
  lib/api/CDataFrameAnalyzer.cc
  lib/api/unittest/CDataFrameAnalyzerOutlierTest.cc
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
Labels: :ml, :ml/DataFrameAnalysis, >non-issue, backport

#1162 [7.8][ML] Fix memory usage estimation for vectors with a custom allocator
  include/core/CMemory.h
  lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
  lib/core/unittest/CDataFrameTest.cc
  lib/core/unittest/CMemoryUsageTest.cc
Labels: >non-issue, backport, v7.8.0

#1161 [7.8][ML] Boosted tree tidy ups
  include/maths/CBoostedTreeLeafNodeStatistics.h
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/CBoostedTreeLeafNodeStatistics.cc
  lib/maths/CBoostedTreeLoss.cc
Labels: >non-issue, backport, v7.8.0

#1165 [7.8][ML] Improve stability of trend decomposition for very sparse data
  docs/CHANGELOG.asciidoc
  lib/model/CEventRateModel.cc
  lib/model/CIndividualModel.cc
  lib/model/CMetricModel.cc
Labels: backport, v7.8.0

#1166 [7.8][ML] Trap and fail if no regressors are provided to classification or regression
  docs/CHANGELOG.asciidoc
  include/api/CDataFrameAnalysisRunner.h
  include/api/CDataFrameAnalysisSpecification.h
  include/api/CDataFrameOutliersRunner.h
  include/api/CDataFrameTrainBoostedTreeRunner.h
  lib/api/CDataFrameAnalysisSpecification.cc
  lib/api/CDataFrameAnalyzer.cc
  lib/api/CDataFrameOutliersRunner.cc
  lib/api/CDataFrameTrainBoostedTreeRunner.cc
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
  lib/api/unittest/CDataFrameMockAnalysisRunner.cc
  lib/api/unittest/CDataFrameMockAnalysisRunner.h
Labels: backport, v7.8.0

#1157 [ML] Fix a bug in adaptive local regression
  docs/CHANGELOG.asciidoc
  include/maths/CAdaptiveBucketing.h
  include/maths/CTools.h
  include/maths/CToolsDetail.h
  lib/maths/CAdaptiveBucketing.cc
  lib/maths/CTools.cc
  lib/maths/unittest/CAdaptiveBucketingTest.cc
  lib/maths/unittest/CToolsTest.cc
  lib/maths/unittest/Makefile
Labels: :ml, >bug, affects-results, review, v7.8.0, v8.0.0

#1175 [7.8][ML] Fix a bug in adaptive local regression
  docs/CHANGELOG.asciidoc
  include/maths/CAdaptiveBucketing.h
  include/maths/CTools.h
  include/maths/CToolsDetail.h
  lib/maths/CAdaptiveBucketing.cc
  lib/maths/CTools.cc
  lib/maths/unittest/CAdaptiveBucketingTest.cc
  lib/maths/unittest/CToolsTest.cc
  lib/maths/unittest/Makefile
Labels: backport, v7.8.0

#1167 [ML] Limit categorization memory usage
  docs/CHANGELOG.asciidoc
  include/api/CFieldDataCategorizer.h
  include/model/CDataCategorizer.h
  include/model/CResourceMonitor.h
  include/model/CTokenListDataCategorizerBase.h
  lib/api/CBenchMarker.cc
  lib/api/CFieldDataCategorizer.cc
  lib/api/CModelSizeStatsJsonWriter.cc
  lib/api/unittest/CModelSnapshotJsonWriterTest.cc
  lib/model/CDataCategorizer.cc
  lib/model/CTokenListDataCategorizerBase.cc
  lib/model/unittest/CTokenListDataCategorizerTest.cc
Labels: :ml, >bug, v7.8.0, v8.0.0

#1176 [7.x][ML] Limit categorization memory usage
  docs/CHANGELOG.asciidoc
  include/api/CFieldDataCategorizer.h
  include/model/CDataCategorizer.h
  include/model/CResourceMonitor.h
  include/model/CTokenListDataCategorizerBase.h
  lib/api/CBenchMarker.cc
  lib/api/CFieldDataCategorizer.cc
  lib/api/CModelSizeStatsJsonWriter.cc
  lib/api/unittest/CModelSnapshotJsonWriterTest.cc
  lib/model/CDataCategorizer.cc
  lib/model/CTokenListDataCategorizerBase.cc
  lib/model/unittest/CTokenListDataCategorizerTest.cc
Labels: backport, v7.8.0
