Repository elastic/ml-cpp, pull requests merged in 2020-11, with the labels that each got.

#1551 [ML] Trap edge case causing model bounds to blow up to max double
  docs/CHANGELOG.asciidoc
  include/maths/CClusterer.h
  include/maths/CKMeansOnline1d.h
  include/maths/CMultivariateMultimodalPrior.h
  include/maths/CMultivariatePrior.h
  include/maths/CXMeansOnline.h
  include/maths/CXMeansOnline1d.h
  lib/maths/CKMeansOnline1d.cc
  lib/maths/CMultimodalPrior.cc
  lib/maths/CMultivariateOneOfNPrior.cc
  lib/maths/CMultivariatePrior.cc
  lib/maths/CXMeansOnline1d.cc
  lib/maths/unittest/CXMeansOnline1dTest.cc
  lib/maths/unittest/CXMeansOnlineTest.cc
Labels: :ml, >bug, affects-results, review, v7.11.0, v8.0.0

#1553 [7.11][ML] Trap edge case causing model bounds to blow up to around max double
  docs/CHANGELOG.asciidoc
  include/maths/CClusterer.h
  include/maths/CKMeansOnline1d.h
  include/maths/CMultivariateMultimodalPrior.h
  include/maths/CMultivariatePrior.h
  include/maths/CXMeansOnline.h
  include/maths/CXMeansOnline1d.h
  lib/maths/CKMeansOnline1d.cc
  lib/maths/CMultimodalPrior.cc
  lib/maths/CMultivariateOneOfNPrior.cc
  lib/maths/CMultivariatePrior.cc
  lib/maths/CXMeansOnline1d.cc
  lib/maths/unittest/CXMeansOnline1dTest.cc
  lib/maths/unittest/CXMeansOnlineTest.cc
Labels: backport, v7.11.0

#1555 [ML] Fix error logging for foreground persistence
  lib/api/CAnomalyJob.cc
Labels: :ml, >non-issue, review, v7.11.0, v8.0.0

#1557 [7.x][ML] Fix error logging for foreground persistence (#1555)
  lib/api/CAnomalyJob.cc
Labels: :ml, >non-issue, backport, v7.11.0

#1556 [ML] Adding a minimum disk space forecast parameter
  include/api/CForecastRunner.h
  lib/api/CForecastRunner.cc
  lib/api/unittest/CForecastRunnerTest.cc
Labels: :ml, >non-issue, v7.10.1, v7.11.0, v8.0.0

#1552 [ML] Parse anomaly job JSON config file
  bin/autodetect/CCmdLineParser.cc
  bin/autodetect/CCmdLineParser.h
  bin/autodetect/Main.cc
  bin/data_frame_analyzer/Main.cc
  include/api/CAnomalyJobConfig.h
  include/api/CAnomalyJobConfigReader.h
  include/api/CDetectionRulesJsonParser.h
  include/core/CStringUtils.h
  include/core/CTimeUtils.h
  include/core/Constants.h
  lib/api/CAnomalyJobConfig.cc
  lib/api/CAnomalyJobConfigReader.cc
  lib/api/CDetectionRulesJsonParser.cc
  lib/api/Makefile.first
  lib/api/unittest/CAnomalyJobConfigTest.cc
  lib/api/unittest/Makefile
  lib/core/CStringUtils.cc
  lib/core/CTimeUtils.cc
  lib/core/unittest/CStringUtilsTest.cc
  lib/core/unittest/CTimeUtilsTest.cc
Labels: :ml, >non-issue, >refactoring, review, v7.11.0, v8.0.0

#1558 [7.x][ML] Adding a minimum disk space forecast parameter
  include/api/CForecastRunner.h
  lib/api/CForecastRunner.cc
  lib/api/unittest/CForecastRunnerTest.cc
Labels: >non-issue, backport, v7.11.0

#1560 [7.x][ML] Parse anomaly job JSON config file (#1552)
  bin/autodetect/CCmdLineParser.cc
  bin/autodetect/CCmdLineParser.h
  bin/autodetect/Main.cc
  bin/data_frame_analyzer/Main.cc
  include/api/CAnomalyJobConfig.h
  include/api/CAnomalyJobConfigReader.h
  include/api/CDetectionRulesJsonParser.h
  include/core/CStringUtils.h
  include/core/CTimeUtils.h
  include/core/Constants.h
  lib/api/CAnomalyJobConfig.cc
  lib/api/CAnomalyJobConfigReader.cc
  lib/api/CDetectionRulesJsonParser.cc
  lib/api/Makefile.first
  lib/api/unittest/CAnomalyJobConfigTest.cc
  lib/api/unittest/Makefile
  lib/core/CStringUtils.cc
  lib/core/CTimeUtils.cc
  lib/core/unittest/CStringUtilsTest.cc
  lib/core/unittest/CTimeUtilsTest.cc
Labels: :ml, >non-issue, backport, v7.11.0

#1561 [ML] Fixing move constructor/assignment for CForecastRunner::SForecast
  include/api/CForecastRunner.h
  lib/api/CForecastRunner.cc
Labels: :ml, >non-issue, v7.10.1, v7.11.0, v8.0.0

#1563 [6.8][ML] Retry pulling of Docker images to work around network issues
  dev-tools/docker/build_check_style_image.sh
  dev-tools/docker/build_linux-musl_build_image.sh
  dev-tools/docker/build_linux_build_image.sh
  dev-tools/docker/build_linux_test_image.sh
  dev-tools/docker/build_macosx_build_image.sh
  dev-tools/docker/prefetch_docker_image.sh
  dev-tools/docker_build.sh
  dev-tools/docker_check_style.sh
  dev-tools/docker_test.sh
  dev-tools/jenkins_ci.sh
Labels: >non-issue, backport, v6.8.14

#1562 [ML] Initialize detectors parser with filters map
  bin/autodetect/Main.cc
  include/api/CAnomalyJobConfig.h
  include/api/CAnomalyJobConfigReader.h
  include/api/CDetectionRulesJsonParser.h
  lib/api/CAnomalyJobConfig.cc
  lib/api/CAnomalyJobConfigReader.cc
  lib/api/CDetectionRulesJsonParser.cc
  lib/api/unittest/CAnomalyJobConfigTest.cc
Labels: :ml, >non-issue, review, v7.11.0, v8.0.0

#1549 [ML] Short circuit seasonal component gradient calculation
  docs/CHANGELOG.asciidoc
  lib/maths/CSeasonalComponentAdaptiveBucketing.cc
Labels: :ml, >enhancement, review, v7.11.0, v8.0.0

#1564 [7.x][ML] Initialize detectors parser with filters map (#1562)
  bin/autodetect/Main.cc
  include/api/CAnomalyJobConfig.h
  include/api/CAnomalyJobConfigReader.h
  include/api/CDetectionRulesJsonParser.h
  lib/api/CAnomalyJobConfig.cc
  lib/api/CAnomalyJobConfigReader.cc
  lib/api/CDetectionRulesJsonParser.cc
  lib/api/unittest/CAnomalyJobConfigTest.cc
Labels: :ml, >non-issue, backport, v7.11.0

#1559 [7.10][ML] Adding a minimum disk space forecast parameter
  include/api/CForecastRunner.h
  lib/api/CForecastRunner.cc
  lib/api/unittest/CForecastRunnerTest.cc
Labels: >non-issue, backport, v7.10.1

#1565 [7.x][ML] Fixing move constructor/assignment for CForecastRunner::SForecast
  include/api/CForecastRunner.h
  lib/api/CForecastRunner.cc
Labels: >non-issue, backport, v7.11.0

#1537 [ML] Gain upper bound estimation for classification and regression
  docs/CHANGELOG.asciidoc
  include/api/CDataFrameAnalysisInstrumentation.h
  include/maths/CBoostedTreeLeafNodeStatistics.h
  include/maths/CDataFrameAnalysisInstrumentationInterface.h
  include/test/CRandomNumbers.h
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/CBoostedTreeLeafNodeStatistics.cc
  lib/maths/unittest/CBoostedTreeLeafNodeStatisticsTest.cc
  lib/test/CRandomNumbers.cc
Labels: :ml, >enhancement, v7.11.0, v8.0.0

#1567 [7.11][ML] Short circuit seasonal component gradient calculation (#1549)
  docs/CHANGELOG.asciidoc
  lib/maths/CSeasonalComponentAdaptiveBucketing.cc
Labels: backport, v7.11.0

#1566 [7.10][ML] Fixing move constructor/assignment for CForecastRunner::SForecast
  include/api/CForecastRunner.h
  lib/api/CForecastRunner.cc
Labels: >non-issue, backport, v7.10.1

#1569 [ML] Remove references to the .ml-state index from C++ code
  include/api/CAnomalyJob.h
  include/api/CFieldDataCategorizer.h
  include/api/CSingleStreamDataAdder.h
  include/api/ElasticsearchStateIndex.h
  include/core/CDataAdder.h
  include/core/CDataSearcher.h
  include/core/CStateCompressor.h
  include/core/CStateDecompressor.h
  include/test/CMultiFileDataAdder.h
  lib/api/CAnomalyJob.cc
  lib/api/CDataFrameAnalysisRunner.cc
  lib/api/CDataFrameTrainBoostedTreeRunner.cc
  lib/api/CFieldDataCategorizer.cc
  lib/api/CSingleStreamDataAdder.cc
  lib/api/ElasticsearchStateIndex.cc
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
  lib/api/unittest/CFieldDataCategorizerTest.cc
  lib/api/unittest/CMockDataAdder.cc
  lib/api/unittest/CMockDataAdder.h
  lib/api/unittest/CMockSearcher.cc
  lib/api/unittest/CMockSearcher.h
  lib/api/unittest/CMultiFileDataAdderTest.cc
  lib/core/CDataSearcher.cc
  lib/core/CStateCompressor.cc
  lib/core/CStateDecompressor.cc
  lib/core/unittest/CStateCompressorTest.cc
  lib/test/CMultiFileDataAdder.cc
  lib/test/CMultiFileSearcher.cc
Labels: :ml, >non-issue, v7.11.0, v8.0.0

#1571 [ML] A few minor fixes and warning removals
  include/maths/CBoostedTreeLeafNodeStatistics.h
  include/maths/CDataFrameAnalysisInstrumentationInterface.h
  lib/core/CDataFrame.cc
  lib/maths/CBoostedTreeImpl.cc
Labels: :ml/DataFrameAnalysis, >non-issue, v7.11.0, v8.0.0

#1570 [ML] Migrate away from inheriting from std::iterator
  include/core/CDataFrame.h
  include/core/CPackedBitVector.h
  include/maths/CLinearAlgebraEigen.h
  lib/maths/CBjkstUniqueValues.cc
Labels: >non-issue, >refactoring, review, v7.11.0, v8.0.0

#1572 [ML] Include peak memory usage in model snapshots
  bin/autodetect/Main.cc
  docs/CHANGELOG.asciidoc
Labels: :ml, >bug, review, v7.10.1, v7.11.0, v8.0.0

#1568 [7.x][ML] Gain upper bound estimation for classification and regression
  docs/CHANGELOG.asciidoc
  include/api/CDataFrameAnalysisInstrumentation.h
  include/maths/CBoostedTreeLeafNodeStatistics.h
  include/maths/CDataFrameAnalysisInstrumentationInterface.h
  include/test/CRandomNumbers.h
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/CBoostedTreeLeafNodeStatistics.cc
  lib/maths/unittest/CBoostedTreeLeafNodeStatisticsTest.cc
  lib/test/CRandomNumbers.cc
  mk/windows.mk
Labels: :ml, >enhancement, backport, v7.11.0

#1575 [7.x][ML] Include peak memory usage in model snapshots (#1572)
  bin/autodetect/Main.cc
  docs/CHANGELOG.asciidoc
Labels: :ml, >bug, backport, v7.11.0

#1550 [ML] New change point detection
  include/core/CPersistUtils.h
  include/maths/CChecksum.h
  include/maths/CExpandingWindow.h
  include/maths/CInformationCriteria.h
  include/maths/CModel.h
  include/maths/CTimeSeriesChangeDetector.h
  include/maths/CTimeSeriesDecomposition.h
  include/maths/CTimeSeriesDecompositionDetail.h
  include/maths/CTimeSeriesDecompositionInterface.h
  include/maths/CTimeSeriesDecompositionStub.h
  include/maths/CTimeSeriesModel.h
  include/maths/CTimeSeriesSegmentation.h
  include/maths/CTimeSeriesTestForChange.h
  include/maths/CTimeSeriesTestForSeasonality.h
  include/maths/CTrendComponent.h
  lib/api/CAnomalyJob.cc
  lib/api/unittest/CAnomalyJobLimitTest.cc
  lib/maths/CExpandingWindow.cc
  lib/maths/CModel.cc
  lib/maths/CTimeSeriesChangeDetector.cc
  lib/maths/CTimeSeriesDecomposition.cc
  lib/maths/CTimeSeriesDecompositionDetail.cc
  lib/maths/CTimeSeriesDecompositionStub.cc
  lib/maths/CTimeSeriesModel.cc
  lib/maths/CTimeSeriesSegmentation.cc
  lib/maths/CTimeSeriesTestForChange.cc
  lib/maths/CTimeSeriesTestForSeasonality.cc
  lib/maths/CTrendComponent.cc
  lib/maths/Makefile
  lib/maths/unittest/CTimeSeriesChangeDetectorTest.cc
  lib/maths/unittest/CTimeSeriesDecompositionTest.cc
  lib/maths/unittest/CTimeSeriesModelTest.cc
  lib/maths/unittest/CTimeSeriesSegmentationTest.cc
  lib/maths/unittest/CTimeSeriesTestForChangeTest.cc
  lib/maths/unittest/CTimeSeriesTestForSeasonalityTest.cc
  lib/maths/unittest/Makefile
  lib/model/CEventRateModel.cc
  lib/model/CEventRatePopulationModel.cc
  lib/model/CMetricModel.cc
  lib/model/CMetricPopulationModel.cc
  lib/model/CModelDetailsView.cc
  lib/model/unittest/CEventRateModelTest.cc
  lib/model/unittest/CEventRatePopulationModelTest.cc
  lib/model/unittest/CMetricAnomalyDetectorTest.cc
  lib/model/unittest/CMetricPopulationModelTest.cc
  lib/model/unittest/CProbabilityAndInfluenceCalculatorTest.cc
  lib/model/unittest/CResourceLimitTest.cc
  lib/model/unittest/CResourceMonitorTest.cc
Labels: :ml, >enhancement, >non-issue, review

#1576 [7.10][ML] Include peak memory usage in model snapshots (#1572)
  bin/autodetect/Main.cc
  docs/CHANGELOG.asciidoc
Labels: :ml, >bug, backport, v7.10.1

#1574 [7.x][ML] Remove references to the .ml-state index from C++ code
  include/api/CAnomalyJob.h
  include/api/CFieldDataCategorizer.h
  include/api/CSingleStreamDataAdder.h
  include/api/ElasticsearchStateIndex.h
  include/core/CDataAdder.h
  include/core/CDataSearcher.h
  include/core/CStateCompressor.h
  include/core/CStateDecompressor.h
  include/test/CMultiFileDataAdder.h
  lib/api/CAnomalyJob.cc
  lib/api/CDataFrameAnalysisRunner.cc
  lib/api/CDataFrameTrainBoostedTreeRunner.cc
  lib/api/CFieldDataCategorizer.cc
  lib/api/CSingleStreamDataAdder.cc
  lib/api/ElasticsearchStateIndex.cc
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
  lib/api/unittest/CFieldDataCategorizerTest.cc
  lib/api/unittest/CMockDataAdder.cc
  lib/api/unittest/CMockDataAdder.h
  lib/api/unittest/CMockSearcher.cc
  lib/api/unittest/CMockSearcher.h
  lib/api/unittest/CMultiFileDataAdderTest.cc
  lib/core/CDataSearcher.cc
  lib/core/CStateCompressor.cc
  lib/core/CStateDecompressor.cc
  lib/core/unittest/CStateCompressorTest.cc
  lib/test/CMultiFileDataAdder.cc
  lib/test/CMultiFileSearcher.cc
Labels: >non-issue, backport, v7.11.0

#1577 [7.x][ML] A few minor fixes and warning removals
  include/maths/CBoostedTreeLeafNodeStatistics.h
  include/maths/CDataFrameAnalysisInstrumentationInterface.h
  lib/core/CDataFrame.cc
  lib/maths/CBoostedTreeImpl.cc
Labels: >non-issue, backport, v7.11.0

#1578 [ML] Work around erroneous reference requirement for std::vector::assign
  include/core/CPackedBitVector.h
Labels: >non-issue, >refactoring, v7.11.0, v8.0.0

#1573 [7.11][ML] Migrate away from inheriting from std::iterator
  include/core/CDataFrame.h
  include/core/CPackedBitVector.h
  include/maths/CLinearAlgebraEigen.h
  lib/maths/CBjkstUniqueValues.cc
Labels: >non-issue, backport, v7.11.0

#1579 [ML] Fixing the debug build
  lib/api/CAnomalyJobConfig.cc
Labels: :ml, >non-issue, v7.11.0, v8.0.0

#1582 [7.x][ML] Fixing the debug build
  lib/api/CAnomalyJobConfig.cc
Labels: >non-issue, backport, v7.11.0

#1581 [7.11][ML] Work around erroneous reference requirement for std::vector::assign
  include/core/CPackedBitVector.h
Labels: >non-issue, backport, v7.11.0

#1583 [ML] Make sure we don't try and test significance when there is insufficient data
  lib/maths/CTimeSeriesTestForChange.cc
  lib/maths/CTimeSeriesTestForSeasonality.cc
Labels: :ml, >non-issue, review

#1585 [ML] Recalculate memory usage before upgrading model state
  include/model/CResourceMonitor.h
  lib/api/CAnomalyJob.cc
  lib/model/CResourceMonitor.cc
  lib/model/unittest/CResourceMonitorTest.cc
Labels: :ml, >non-issue, v7.11.0, v8.0.0

#1587 [7.x][ML] Recalculate memory usage before upgrading model state
  include/model/CResourceMonitor.h
  lib/api/CAnomalyJob.cc
  lib/model/CResourceMonitor.cc
  lib/model/unittest/CResourceMonitorTest.cc
Labels: >non-issue, backport, v7.11.0

#1586 [ML] Trap potential cause of log errors from CXMeansOnline1d
  docs/CHANGELOG.asciidoc
  lib/maths/CNaturalBreaksClassifier.cc
  lib/maths/CXMeansOnline1d.cc
Labels: :ml, >bug, affects-results, review, v7.11.0, v8.0.0

#1580 [ML] Fix test fallout from new change point detection
  include/maths/CExpandingWindow.h
  include/maths/CSignal.h
  include/maths/CTimeSeriesDecompositionDetail.h
  include/maths/CTimeSeriesSegmentation.h
  include/maths/CTimeSeriesTestForChange.h
  include/maths/CTimeSeriesTestForSeasonality.h
  include/maths/CTrendComponent.h
  include/maths/Constants.h
  lib/maths/CExpandingWindow.cc
  lib/maths/CSignal.cc
  lib/maths/CTimeSeriesDecompositionDetail.cc
  lib/maths/CTimeSeriesSegmentation.cc
  lib/maths/CTimeSeriesTestForChange.cc
  lib/maths/CTimeSeriesTestForSeasonality.cc
  lib/maths/CTrendComponent.cc
  lib/maths/unittest/CExpandingWindowTest.cc
  lib/maths/unittest/CSignalTest.cc
  lib/maths/unittest/CTimeSeriesDecompositionTest.cc
  lib/maths/unittest/CTimeSeriesModelTest.cc
  lib/maths/unittest/CTimeSeriesSegmentationTest.cc
  lib/maths/unittest/CTimeSeriesTestForChangeTest.cc
  lib/maths/unittest/CTimeSeriesTestForSeasonalityTest.cc
  lib/model/unittest/CEventRateModelTest.cc
  lib/model/unittest/CMetricModelTest.cc
  lib/model/unittest/CMetricPopulationModelTest.cc
Labels: :ml, >enhancement, >non-issue, review

#1588 [7.11][ML] Trap potential cause of log errors from CXMeansOnline1d
  docs/CHANGELOG.asciidoc
  lib/maths/CNaturalBreaksClassifier.cc
  lib/maths/CXMeansOnline1d.cc
Labels: backport, v7.11.0

#1589 [ML] Addressing a QA regression due to 1451 and 1580
  include/maths/CExpandingWindow.h
  include/maths/CSeasonalComponentAdaptiveBucketing.h
  include/maths/CSignal.h
  include/maths/CTimeSeriesDecompositionDetail.h
  include/maths/CTimeSeriesTestForChange.h
  include/maths/CTimeSeriesTestForSeasonality.h
  include/maths/CTrendComponent.h
  lib/maths/CExpandingWindow.cc
  lib/maths/CSeasonalComponent.cc
  lib/maths/CSeasonalComponentAdaptiveBucketing.cc
  lib/maths/CSignal.cc
  lib/maths/CTimeSeriesDecompositionDetail.cc
  lib/maths/CTimeSeriesTestForChange.cc
  lib/maths/CTimeSeriesTestForSeasonality.cc
  lib/maths/CTrendComponent.cc
  lib/maths/unittest/CExpandingWindowTest.cc
  lib/maths/unittest/CTimeSeriesTestForSeasonalityTest.cc
Labels: :ml, >non-issue, review

#1591 [ML] Avoid misleading error message
  lib/core/CLogger.cc
Labels: :ml, >non-issue, v7.10.2, v7.11.0, v8.0.0

#1592 [7.x][ML] Avoid misleading error message
  lib/core/CLogger.cc
Labels: >non-issue, backport, v7.11.0

#1593 [7.10][ML] Avoid misleading error message
  lib/core/CLogger.cc
Labels: >non-issue, backport, v7.10.2

#1596 [ML] Handle edge case where missing values mean we can't test the existing seasonality
  include/maths/CTimeSeriesTestForSeasonality.h
  lib/maths/CTimeSeriesTestForSeasonality.cc
Labels: :ml, >non-issue, review

#1595 [ML] Avoid potential integer overflow
  lib/maths/CExpandingWindow.cc
  lib/maths/CTimeSeriesDecompositionDetail.cc
Labels: :ml, >non-issue, review
