Repository elastic/ml-cpp, pull requests merged in 2021-09, with the labels that each got.

#2005 [ML] Ensure initialiser list ctor is used
  bin/pytorch_inference/Main.cc
Labels: >non-issue, v8.0.0, 3rd party models

#2007 [ML] Fix invalid reference when initialising input sizes
  bin/pytorch_inference/Main.cc
Labels: >non-issue, v8.0.0, 3rd party models

#1995 [ML] Improve initialisation of search for the best tree topology change penalty
  include/maths/CBoostedTree.h
  include/maths/CBoostedTreeFactory.h
  include/maths/CBoostedTreeLeafNodeStatistics.h
  include/test/CDataFrameAnalysisSpecificationFactory.h
  lib/api/CRetrainableModelJsonReader.cc
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
  lib/maths/CBoostedTree.cc
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/CBoostedTreeLeafNodeStatistics.cc
  lib/maths/CBoostedTreeLeafNodeStatisticsIncremental.cc
  lib/maths/unittest/CBoostedTreeLeafNodeStatisticsTest.cc
  lib/maths/unittest/CBoostedTreeTest.cc
  lib/maths/unittest/CTreeShapFeatureImportanceTest.cc
  lib/test/CDataFrameAnalysisSpecificationFactory.cc
Labels: review, >non-issue, :ml/DataFrameAnalysis

#1948 [ML][PYTORCH] Add benchmark mode to the evaluate.py script
  bin/pytorch_inference/evaluate.py
Labels: >non-issue, v8.0.0, 3rd party models

#2013 [ML] Cleanly handle mismatch in the classification config num_classes and the number classes in the data
  include/api/CDataFrameTrainBoostedTreeClassifierRunner.h
  lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
  lib/maths/CDataFrameUtils.cc
Labels: review, >non-issue, :ml/DataFrameAnalysis

#2009 [ML] Store and restore training jobs with models
  jupyter/src/.bumpversion.cfg
  jupyter/src/incremental_learning/__init__.py
  jupyter/src/incremental_learning/config.py
  jupyter/src/incremental_learning/job.py
  jupyter/src/incremental_learning/storage.py
  jupyter/src/setup.py
  jupyter/tests/incremental_learning/test_store_restore.py
Labels: review, >non-issue, :ml/DataFrameAnalysis

#2010 [ML] Output logs from data_frame_analyzer
  jupyter/src/.bumpversion.cfg
  jupyter/src/incremental_learning/__init__.py
  jupyter/src/incremental_learning/job.py
  jupyter/src/setup.py
Labels: review, >non-issue, :ml/DataFrameAnalysis

#2016 [ML] Raise runtime error when C++ process fails
  jupyter/src/.bumpversion.cfg
  jupyter/src/incremental_learning/__init__.py
  jupyter/src/incremental_learning/job.py
  jupyter/src/setup.py
Labels: >non-issue, :ml/DataFrameAnalysis

#2015 [ML] Missing parameters from update config in test framework
  jupyter/src/.bumpversion.cfg
  jupyter/src/incremental_learning/__init__.py
  jupyter/src/incremental_learning/job.py
  jupyter/src/setup.py
Labels: >bug, review, >non-issue, :ml/DataFrameAnalysis

#2011 [ML] Obtain prediction probabilities
  jupyter/src/.bumpversion.cfg
  jupyter/src/incremental_learning/__init__.py
  jupyter/src/incremental_learning/job.py
  jupyter/src/setup.py
  jupyter/tests/incremental_learning/test_classification.py
Labels: review, >non-issue, :ml/DataFrameAnalysis

#2018 [ML][PYTORCH] Remove debug logging of inference requests
  bin/pytorch_inference/Main.cc
Labels: >non-issue, v8.0.0, 3rd party models

#2017 [ML] Add an option to force update the model
  include/api/CDataFrameTrainBoostedTreeRunner.h
  include/maths/CBoostedTreeFactory.h
  include/maths/CBoostedTreeImpl.h
  jupyter/scripts/incremental_learning/experiment_driver.py
  jupyter/scripts/incremental_learning/job_submitter.py
  jupyter/src/incremental_learning/job.py
  lib/api/CDataFrameTrainBoostedTreeRunner.cc
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/CBoostedTreeImpl.cc
Labels: review, >non-issue, :ml/DataFrameAnalysis

#2021 [ML] Reinitialise predictions before estimating initial loss
  jupyter/src/incremental_learning/transforms.py
  lib/maths/CBoostedTreeImpl.cc
Labels: >bug, review, >non-issue, :ml/DataFrameAnalysis

#2022 [ML] Random seed support for experiment tracking
  jupyter/src/.bumpversion.cfg
  jupyter/src/incremental_learning/__init__.py
  jupyter/src/incremental_learning/job.py
  jupyter/src/setup.py
  jupyter/tests/incremental_learning/test_regression.py
  jupyter/tests/incremental_learning/test_sacred.py
Labels: >non-issue, :ml/DataFrameAnalysis

#2023 [ML] Parallelize calls to forward on pytorch models
  bin/pytorch_inference/CCmdLineParser.cc
  bin/pytorch_inference/CCmdLineParser.h
  bin/pytorch_inference/Main.cc
  bin/pytorch_inference/evaluate.py
Labels: >non-issue, :ml

#2008 [ML] Update PyTorch and build oneDNN in linux-x86_64 docker file
  3rd_party/3rd_party.sh
  3rd_party/licenses/MKL-INFO.txt
  3rd_party/licenses/MKL-LICENSE.txt
  3rd_party/licenses/MKL-NOTICE.txt
  build-setup/linux.md
  dev-tools/docker/build_linux_build_image.sh
  dev-tools/docker/linux_builder/Dockerfile
  dev-tools/docker/linux_image/Dockerfile
  dev-tools/docker/linux_tester/Dockerfile
Labels: >build, >non-issue, v8.0.0

#2020 [ML][PYTORCH] Update macOS build to libtorch 1.9
  build-setup/macos.md
  dev-tools/docker/build_macosx_build_image.sh
  dev-tools/docker/macosx_builder/Dockerfile
  dev-tools/docker/macosx_image/Dockerfile
  dev-tools/download_macos_deps.sh
Labels: >build, >non-issue, v8.0.0, 3rd party models

#2024 [ML] Performance optimisation for classification and regression model training
  docs/CHANGELOG.asciidoc
  include/api/CDataFrameTrainBoostedTreeRunner.h
  include/core/CDataFrame.h
  include/core/CFloatStorage.h
  include/core/CImmutableRadixSet.h
  include/maths/CBoostedTreeFactory.h
  include/maths/CBoostedTreeImpl.h
  include/maths/CBoostedTreeLeafNodeStatistics.h
  include/maths/CBoostedTreeUtils.h
  lib/api/CDataFrameTrainBoostedTreeRunner.cc
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
  lib/core/unittest/CImmutableRadixSetTest.cc
  lib/core/unittest/Makefile
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/CBoostedTreeLeafNodeStatistics.cc
  lib/maths/unittest/CBoostedTreeLeafNodeStatisticsTest.cc
Labels: >enhancement, review, :ml/DataFrameAnalysis, v7.16.0

#2025 [ML] Only start thread pool for parallel forwarding if multiple threads
  bin/pytorch_inference/Main.cc
Labels: >non-issue, :ml, v8.0.0

#2027 [ML] Performance optimisation for classification and regression model training
  include/core/CDataFrame.h
  include/core/CFloatStorage.h
  include/core/CImmutableRadixSet.h
  include/maths/CBoostedTreeFactory.h
  include/maths/CBoostedTreeImpl.h
  include/maths/CBoostedTreeLeafNodeStatistics.h
  include/maths/CBoostedTreeLeafNodeStatisticsIncremental.h
  include/maths/CBoostedTreeLeafNodeStatisticsScratch.h
  include/maths/CBoostedTreeUtils.h
  lib/api/CDataFrameTrainBoostedTreeRunner.cc
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
  lib/core/unittest/CImmutableRadixSetTest.cc
  lib/core/unittest/Makefile
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/CBoostedTreeLeafNodeStatistics.cc
  lib/maths/CBoostedTreeLeafNodeStatisticsIncremental.cc
  lib/maths/CBoostedTreeLeafNodeStatisticsScratch.cc
  lib/maths/unittest/CBoostedTreeLeafNodeStatisticsTest.cc
Labels: >non-issue, :ml/DataFrameAnalysis

#2029 [ML] Set LibTorch math lib threads to one
  bin/pytorch_inference/Main.cc
Labels: >non-issue, :ml, v8.0.0

#2030 [ML] Upgrade to PyTorch 1.9 on Windows
  build-setup/windows.md
  dev-tools/download_windows_deps.ps1
Labels: >build, >non-issue, :ml, v8.0.0, 3rd party models

#2028 [ML] Upgrade to gcc 10.3 for Linux compilation
  3rd_party/3rd_party.sh
  3rd_party/licenses/gcc-runtime-INFO.csv
  build-setup/linux.md
  build-setup/linux_aarch64_cross_compiled.md
  dev-tools/docker/build_linux_aarch64_cross_build_image.sh
  dev-tools/docker/build_linux_aarch64_native_build_image.sh
  dev-tools/docker/build_linux_build_image.sh
  dev-tools/docker/linux_aarch64_cross_builder/Dockerfile
  dev-tools/docker/linux_aarch64_cross_image/Dockerfile
  dev-tools/docker/linux_aarch64_native_builder/Dockerfile
  dev-tools/docker/linux_aarch64_native_image/Dockerfile
  dev-tools/docker/linux_aarch64_native_tester/Dockerfile
  dev-tools/docker/linux_builder/Dockerfile
  dev-tools/docker/linux_image/Dockerfile
  dev-tools/docker/linux_tester/Dockerfile
  docs/CHANGELOG.asciidoc
  include/core/CLoopProgress.h
  lib/maths/unittest/CBoostedTreeTest.cc
  lib/maths/unittest/CXMeansOnlineTest.cc
  mk/linux.mk
  mk/linux_crosscompile_linux.mk
  set_env.sh
Labels: >build, :ml, v8.0.0

#2032 [ML] Use gcc 10.3 Docker image for Jupyter Dockerfile
  jupyter/docker/Dockerfile
  lib/maths/CBoostedTreeLeafNodeStatistics.cc
  lib/maths/unittest/CDataFrameUtilsTest.cc
Labels: >non-issue, :ml

#2034 [ML] Fix Windows debug build of pytorch_inference
  bin/pytorch_inference/CCommandParser.cc
Labels: >non-issue, :ml, v8.0.0

#2026 [ML][PYTORCH] Use InferenceMode RAII guard
  bin/pytorch_inference/Main.cc
Labels: >non-issue, v8.0.0, 3rd party models

#2036 [ML] Fix unit tests for skip_model_update rule
  lib/model/unittest/CEventRatePopulationModelTest.cc
  lib/model/unittest/CMetricModelTest.cc
  lib/model/unittest/CMetricPopulationModelTest.cc
Labels: review, >non-issue, :ml, >test, v8.0.0, v7.16.0

#2040 [ML] Upgrading Gradle to version 7.2
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: >build, >non-issue, :ml, v8.0.0, v7.16.0

#2044 [ML] Update issue link
  lib/model/unittest/CMetricModelTest.cc
  lib/model/unittest/CMetricPopulationModelTest.cc
Labels: >non-issue, >test, v8.0.0, v7.16.0

#2042 [ML] Remove all trace of elasticsearch-extra
  build.gradle
  mk/defines.mk
  upload.gradle
Labels: >build, >non-issue, :ml, v8.0.0, v7.16.0

#2045 [ML] Update linked for muted tests
  lib/model/unittest/CMetricModelTest.cc
  lib/model/unittest/CMetricPopulationModelTest.cc
Labels: >non-issue, backport, v7.16.0

#2041 [7.x] [ML] Upgrading Gradle to version 7.2
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: >non-issue, backport, v7.16.0

#2046 [ML] Remove obsolete warning
  include/core/CStateMachine.h
Labels: >non-issue, :ml, v8.0.0, v7.16.0

#2047 [7.x] [ML] Remove all trace of elasticsearch-extra
  build.gradle
  mk/defines.mk
  upload.gradle
Labels: >non-issue, backport, v7.16.0

#2048 [7.x] [ML] Remove obsolete warning
  include/core/CStateMachine.h
Labels: >non-issue, backport, v7.16.0

#2039 [ML] Fix Docker build caching
  jupyter/docker/Dockerfile
  jupyter/docker/linux_image/Dockerfile
Labels: :ml/DataFrameAnalysis

#2050 [ML] Add threading benchmark mode to LibTorch evaluate.py
  bin/pytorch_inference/evaluate.py
Labels: >non-issue, :ml, v8.0.0

#2054 [ML] Rename LibTorch threading parameters
  bin/pytorch_inference/CCmdLineParser.cc
  bin/pytorch_inference/CCmdLineParser.h
  bin/pytorch_inference/Main.cc
  bin/pytorch_inference/evaluate.py
Labels: >non-issue, :ml, v8.0.0
