Repository elastic/ml-cpp, pull requests merged in 2021-08, with the labels that each got.

#1973 [ML] Switch ml-cpp repo to Elastic License 2.0 on incremental training branch
  include/api/CDataSummarizationJsonTags.h
  include/api/CDataSummarizationJsonWriter.h
  include/api/CRetrainableModelJsonReader.h
  include/api/CSerializableToJson.h
  include/maths/CBoostedTreeLeafNodeStatisticsIncremental.h
  include/maths/CBoostedTreeLeafNodeStatisticsScratch.h
  jupyter/src/incremental_learning/misc.py
  lib/api/CDataSummarizationJsonTags.cc
  lib/api/CDataSummarizationJsonWriter.cc
  lib/api/CRetrainableModelJsonReader.cc
  lib/api/CSerializableToJson.cc
  lib/api/unittest/CDataSummarizationJsonSerializerTest.cc
  lib/api/unittest/CSerializableToJsonTest.cc
  lib/maths/CBoostedTreeLeafNodeStatisticsIncremental.cc
  lib/maths/CBoostedTreeLeafNodeStatisticsScratch.cc
  lib/maths/unittest/BoostedTreeTestData.cc
  lib/maths/unittest/BoostedTreeTestData.h
  lib/maths/unittest/CBoostedTreeTest.cc
  lib/maths/unittest/CBoostedTreeUtilsTest.cc
Labels: :ml/DataFrameAnalysis, >non-issue

#1962 [ML] Aggressively prune dead split fields
  docs/CHANGELOG.asciidoc
  include/api/CAnomalyJob.h
  include/api/CAnomalyJobConfig.h
  include/model/CAnomalyDetector.h
  include/model/CAnomalyDetectorModelConfig.h
  include/model/FunctionTypes.h
  lib/api/CAnomalyJob.cc
  lib/api/CAnomalyJobConfig.cc
  lib/api/unittest/CAnomalyJobConfigTest.cc
  lib/model/CAnomalyDetector.cc
  lib/model/CAnomalyDetectorModelConfig.cc
  lib/model/FunctionTypes.cc
Labels: :ml, >enhancement, >feature, review, v7.15.0, v8.0.0

#1978 [ML] Fix multiple 7.15 entries in changelog
  docs/CHANGELOG.asciidoc
Labels: :ml, >docs, >non-issue, review, v8.0.0

#1977 [7.x][ML] Aggressively prune dead split fields (#1962)
  docs/CHANGELOG.asciidoc
  include/api/CAnomalyJob.h
  include/api/CAnomalyJobConfig.h
  include/model/CAnomalyDetector.h
  include/model/CAnomalyDetectorModelConfig.h
  include/model/FunctionTypes.h
  lib/api/CAnomalyJob.cc
  lib/api/CAnomalyJobConfig.cc
  lib/api/unittest/CAnomalyJobConfigTest.cc
  lib/model/CAnomalyDetector.cc
  lib/model/CAnomalyDetectorModelConfig.cc
  lib/model/FunctionTypes.cc
Labels: :ml, >feature, backport, v7.15.0

#1979 [ML] Adding --include-build docs
  CONTRIBUTING.md
Labels: :ml, >docs, v7.15.0, v8.0.0

#1980 [7.x] [ML] Adding --include-build docs
  CONTRIBUTING.md
Labels: >docs, backport, v7.15.0

#1982 [ML] Fix python unit tests
  jupyter/src/incremental_learning/job.py
  jupyter/tests/incremental_learning/test_regression.py
Labels: :ml/DataFrameAnalysis, >non-issue

#1983 [ML] Script to simulate different types of concept drift
  jupyter/data/datasets/boston.csv
  jupyter/src/incremental_learning/transforms.py
  jupyter/tests/incremental_learning/test_transforms.py
Labels: >non-issue, :ml/DataFrameAnalysis

#1987 [ML] Add readme for submitting jobs
  jupyter/scripts/incremental_learning/README.md
Labels: >non-issue, :ml/DataFrameAnalysis, >docs

#1986 [ML] Do not persist detectors with only empty models
  include/maths/CModel.h
  include/model/CAnomalyDetector.h
  include/model/CAnomalyDetectorModel.h
  include/model/CCountingModel.h
  include/model/CEventRatePopulationModel.h
  include/model/CIndividualModel.h
  include/model/CMetricPopulationModel.h
  lib/api/CAnomalyJob.cc
  lib/api/unittest/CStringStoreTest.cc
  lib/maths/CModel.cc
  lib/model/CAnomalyDetector.cc
  lib/model/CAnomalyDetectorModel.cc
  lib/model/CEventRatePopulationModel.cc
  lib/model/CIndividualModel.cc
  lib/model/CMetricPopulationModel.cc
  lib/model/unittest/Mocks.cc
  lib/model/unittest/Mocks.h
Labels: review, >non-issue, :ml, v8.0.0, v7.15.0

#1988 [7.x][ML] Do not persist detectors with only empty models (#1986)
  include/maths/CModel.h
  include/model/CAnomalyDetector.h
  include/model/CAnomalyDetectorModel.h
  include/model/CCountingModel.h
  include/model/CEventRatePopulationModel.h
  include/model/CIndividualModel.h
  include/model/CMetricPopulationModel.h
  lib/api/CAnomalyJob.cc
  lib/api/unittest/CStringStoreTest.cc
  lib/maths/CModel.cc
  lib/model/CAnomalyDetector.cc
  lib/model/CAnomalyDetectorModel.cc
  lib/model/CEventRatePopulationModel.cc
  lib/model/CIndividualModel.cc
  lib/model/CMetricPopulationModel.cc
  lib/model/unittest/Mocks.cc
  lib/model/unittest/Mocks.h
Labels: >non-issue, :ml, backport, v7.15.0

#1990 [7.x][ML] Improve hyperparameter tuning performance
  docs/CHANGELOG.asciidoc
  include/api/CDataFrameAnalysisInstrumentation.h
  include/api/CDataFrameTrainBoostedTreeRunner.h
  include/api/CInferenceModelMetadata.h
  include/maths/CBayesianOptimisation.h
  include/maths/CBoostedTree.h
  include/maths/CBoostedTreeFactory.h
  include/maths/CBoostedTreeImpl.h
  include/maths/CDataFrameAnalysisInstrumentationInterface.h
  include/maths/CDataFramePredictiveModel.h
  include/maths/CDataFrameUtils.h
  include/maths/CLowess.h
  include/maths/CLowessDetail.h
  include/maths/CMixtureDistribution.h
  include/maths/CSolvers.h
  lib/api/CDataFrameAnalysisInstrumentation.cc
  lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
  lib/api/CDataFrameTrainBoostedTreeRegressionRunner.cc
  lib/api/CDataFrameTrainBoostedTreeRunner.cc
  lib/api/CInferenceModelMetadata.cc
  lib/api/unittest/CDataFrameAnalyzerFeatureImportanceTest.cc
  lib/maths/CBayesianOptimisation.cc
  lib/maths/CBoostedTree.cc
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/CDataFrameUtils.cc
  lib/maths/unittest/CBoostedTreeTest.cc
  lib/maths/unittest/CDataFrameUtilsTest.cc
  lib/maths/unittest/CLowessTest.cc
  lib/maths/unittest/COneOfNPriorTest.cc
  lib/maths/unittest/CSolversTest.cc
  lib/maths/unittest/Makefile
  lib/maths/unittest/TestUtils.cc
Labels: backport, v7.15.0

#1989 [ML] Submit series of experiments using configuration json
  jupyter/scripts/incremental_learning/.gitignore
  jupyter/scripts/incremental_learning/README.md
  jupyter/scripts/incremental_learning/experiment_driver.py
  jupyter/scripts/incremental_learning/experiments.json
  jupyter/scripts/incremental_learning/job.tpl
  jupyter/scripts/incremental_learning/job_submitter.py
  jupyter/scripts/incremental_learning/submit.sh
  jupyter/tests/incremental_learning/test_transforms.py
Labels: >non-issue, :ml

#1991 [7.x][ML] Add logging so we know which round we exited hyperparameter tuning
  lib/maths/CBoostedTreeImpl.cc
Labels: >non-issue, backport, v7.15.0

#1992 [7.x][ML] Improve regression and classification QoR for small data sets
  docs/CHANGELOG.asciidoc
  include/maths/CBoostedTreeImpl.h
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/CDataFrameUtils.cc
  lib/maths/unittest/CBoostedTreeTest.cc
  lib/maths/unittest/CDataFrameUtilsTest.cc
Labels: backport, v7.15.0

#1993 [ML] Improve test robustness
  lib/maths/unittest/CBoostedTreeTest.cc
Labels: >non-issue, >test, v8.0.0, :ml/DataFrameAnalysis

#1997 [ML] Fix potential undefined behaviour in classification and regression training
  docs/CHANGELOG.asciidoc
  lib/maths/CBoostedTreeLeafNodeStatistics.cc
Labels: >bug, v8.0.0, :ml/DataFrameAnalysis, v7.15.0

#2000 [7.x][ML] Fix potential undefined behaviour in classification and regression training
  docs/CHANGELOG.asciidoc
  lib/maths/CBoostedTreeLeafNodeStatistics.cc
Labels: backport, v7.16.0

#1999 [7.15][ML] Fix potential undefined behaviour in classification and regression training
  docs/CHANGELOG.asciidoc
  lib/maths/CBoostedTreeLeafNodeStatistics.cc
Labels: backport, v7.15.0

#1994 [ML] Scripting to generate full incremental training test matrix
  jupyter/Makefile
  jupyter/README.md
  jupyter/data/configs/boston.json
  jupyter/data/configs/ccpp.json
  jupyter/data/configs/classification-2d.json
  jupyter/scripts/incremental_learning/experiment_driver.py
  jupyter/scripts/incremental_learning/experiments.json
  jupyter/scripts/incremental_learning/generate_experiment_matrix.py
  jupyter/scripts/incremental_learning/transform_templates.json
  jupyter/src/incremental_learning/config.py
  jupyter/src/incremental_learning/transforms.py
  jupyter/template_config.ini
  jupyter/tests/incremental_learning/test_transforms.py
Labels: >non-issue, :ml/DataFrameAnalysis

#1961 [ML][PYTORCH] Batch inference requests
  bin/pytorch_inference/CCommandParser.cc
  bin/pytorch_inference/CCommandParser.h
  bin/pytorch_inference/Main.cc
  bin/pytorch_inference/evaluate.py
  bin/pytorch_inference/examples/ner/test_run.json
  bin/pytorch_inference/examples/sentiment_analysis/test_run.json
  bin/pytorch_inference/unittest/CCommandParserTest.cc
Labels: >non-issue, :ml, v8.0.0, 3rd party models

#2004 [ML] Update boost download URL
  build-setup/linux.md
  build-setup/macos.md
  build-setup/windows.md
  dev-tools/docker/linux_aarch64_native_image/Dockerfile
  dev-tools/docker/linux_image/Dockerfile
Labels: >build, v8.0.0, >docs, v7.15.0

#2006 [ML] Update boost download URL
  build-setup/linux.md
  build-setup/macos.md
  build-setup/windows.md
  dev-tools/docker/linux_aarch64_native_image/Dockerfile
  dev-tools/docker/linux_image/Dockerfile
Labels: backport, >docs, v7.15.0
