Repository elastic/ml-cpp, pull requests merged in 2021-11, with the labels that each got.

#2100 [7.16] [ML] Lock the clang version used to build Boost in ARM CI
  dev-tools/jenkins_ci.sh
  mk/macosx.mk
Labels: >non-issue, backport, v7.16.0

#2099 [8.0] [ML] Lock the clang version used to build Boost in ARM CI
  dev-tools/jenkins_ci.sh
  mk/macosx.mk
Labels: >non-issue, backport, v8.0.0

#2101 [7.15] [ML] Lock the clang version used to build Boost in ARM CI
  dev-tools/jenkins_ci.sh
  mk/macosx.mk
Labels: >non-issue, backport, v7.15.2

#2097 [ML] Support supplying hyperparameter ranges
  include/api/CDataFrameAnalysisConfigReader.h
  include/maths/analytics/CBoostedTreeFactory.h
  include/maths/analytics/CBoostedTreeHyperparameters.h
  include/test/CDataFrameAnalyzerTrainingFactory.h
  lib/api/CDataFrameTrainBoostedTreeRunner.cc
  lib/api/unittest/CDataFrameAnalysisSpecificationTest.cc
  lib/maths/analytics/CBoostedTreeFactory.cc
  lib/maths/analytics/CBoostedTreeImpl.cc
  lib/maths/analytics/unittest/CBoostedTreeHyperparametersTest.cc
  lib/maths/analytics/unittest/CBoostedTreeTest.cc
  lib/test/CDataFrameAnalysisSpecificationFactory.cc
Labels: review, >non-issue, :ml/DataFrameAnalysis

#2095 [ML] Upgrade Boost to version 1.77
  3rd_party/3rd_party.sh
  3rd_party/licenses/boost-INFO.csv
  build-setup/linux.md
  build-setup/macos.md
  build-setup/windows.md
  dev-tools/docker/build_linux_aarch64_cross_build_image.sh
  dev-tools/docker/build_linux_aarch64_native_build_image.sh
  dev-tools/docker/build_linux_build_image.sh
  dev-tools/docker/build_macosx_build_image.sh
  dev-tools/docker/linux_aarch64_cross_builder/Dockerfile
  dev-tools/docker/linux_aarch64_cross_image/Dockerfile
  dev-tools/docker/linux_aarch64_native_builder/Dockerfile
  dev-tools/docker/linux_aarch64_native_image/Dockerfile
  dev-tools/docker/linux_aarch64_native_tester/Dockerfile
  dev-tools/docker/linux_builder/Dockerfile
  dev-tools/docker/linux_image/Dockerfile
  dev-tools/docker/linux_tester/Dockerfile
  dev-tools/docker/macosx_builder/Dockerfile
  dev-tools/docker/macosx_image/Dockerfile
  dev-tools/download_macos_deps.sh
  dev-tools/download_windows_deps.ps1
  dev-tools/jenkins_ci.sh
  docs/CHANGELOG.asciidoc
  lib/core/CNamedPipeFactory.cc
  lib/seccomp/CSystemCallFilter_Linux.cc
  mk/linux.mk
  mk/linux_crosscompile_linux.mk
  mk/linux_crosscompile_macosx.mk
  mk/macosx.mk
  mk/windows.mk
Labels: >build, :ml, v8.1.0

#2105 [7.15] [ML] Fix blocking call cancellation on recent glibc
  docs/CHANGELOG.asciidoc
  lib/seccomp/CSystemCallFilter_Linux.cc
  lib/seccomp/unittest/CSystemCallFilterTest.cc
Labels: backport, v7.15.2

#2102 [ML] Fix blocking call cancellation on recent glibc
  docs/CHANGELOG.asciidoc
  lib/core/CNamedPipeFactory.cc
  lib/seccomp/CSystemCallFilter_Linux.cc
  lib/seccomp/unittest/CSystemCallFilterTest.cc
Labels: >bug, :ml, v8.0.0, v7.16.0, v8.1.0, v7.15.2

#2088 [ML] Fix multi-step learning
  jupyter/notebooks/prototypes/Analyze multi-step data.ipynb
  jupyter/notebooks/prototypes/Update by query.ipynb
  jupyter/scripts/multi_step_sampling/experiment_driver.py
  jupyter/scripts/multi_step_sampling/generate_experiment_matrix.py
  jupyter/scripts/multi_step_sampling/job.tpl
  jupyter/scripts/multi_step_sampling/job_submitter.py
  jupyter/src/incremental_learning/config.py
  jupyter/src/incremental_learning/elasticsearch.py
  jupyter/src/incremental_learning/job.py
Labels: >non-issue, WIP, :ml/DataFrameAnalysis

#2110 [ML] Fix for test case assertions
  lib/maths/time_series/CTimeSeriesModel.cc
Labels: review, >non-issue, :ml, v8.0.0, v7.16.0, v8.1.0

#2104 [7.16] [ML] Fix blocking call cancellation on recent glibc
  docs/CHANGELOG.asciidoc
  lib/seccomp/CSystemCallFilter_Linux.cc
  lib/seccomp/unittest/CSystemCallFilterTest.cc
Labels: backport, v7.16.0

#2112 [7.16][ML] Fix for test case assertions (#2110)
  lib/maths/time_series/CTimeSeriesModel.cc
Labels: >non-issue, :ml, backport, v7.16.0

#2109 [ML] Better vector and matrix checksum implementation
  include/maths/common/CLinearAlgebra.h
Labels: review, >non-issue, :ml, v8.0.0, v7.16.0, v8.1.0

#2114 [7.16][ML] Better vector and matrix checksum implementation
  include/maths/common/CLinearAlgebra.h
Labels: >non-issue, backport, v7.16.0

#2113 [8.0][ML] Better vector and matrix checksum implementation
  include/maths/common/CLinearAlgebra.h
Labels: >non-issue, backport, v8.0.0

#2103 [8.0] [ML] Fix blocking call cancellation on recent glibc
  docs/CHANGELOG.asciidoc
  lib/seccomp/CSystemCallFilter_Linux.cc
  lib/seccomp/unittest/CSystemCallFilterTest.cc
Labels: backport, v8.0.0

#2111 [8.0][ML] Fix for test case assertions (#2110)
  lib/maths/time_series/CTimeSeriesModel.cc
Labels: >non-issue, :ml, backport, v8.0.0

#2108 [ML] Fix divide by zero in MSLE and Huber loss functions
  lib/maths/analytics/CBoostedTreeLoss.cc
Labels: review, >non-issue, v8.0.0, :ml/DataFrameAnalysis, v7.16.0, v8.1.0

#2118 [ML] Adding an unbuffered istream wrapper for RapidJSON
  bin/pytorch_inference/CCommandParser.cc
  include/core/CRapidJsonUnbufferedIStreamWrapper.h
  include/core/CStateDecompressor.h
  lib/core/CRapidJsonUnbufferedIStreamWrapper.cc
  lib/core/CStateDecompressor.cc
  lib/core/Makefile
  lib/core/unittest/CRapidJsonUnbufferedIStreamWrapperTest.cc
  lib/core/unittest/Makefile
Labels: >non-issue, :ml, v8.1.0

#2096 [ML] Improve skip_model_update behaviour.
  docs/CHANGELOG.asciidoc
  include/model/CAnnotatedProbability.h
  include/model/CAnomalyDetectorModel.h
  lib/model/CAnnotatedProbability.cc
  lib/model/CAnomalyDetectorModel.cc
  lib/model/CEventRateModel.cc
  lib/model/CEventRatePopulationModel.cc
  lib/model/CHierarchicalResultsNormalizer.cc
  lib/model/CMetricModel.cc
  lib/model/CMetricPopulationModel.cc
Labels: >enhancement, review, :ml, affects-results, v8.1.0

#2117 [7.16][ML] Fix divide by zero in MSLE and Huber loss functions
  lib/maths/analytics/CBoostedTreeLoss.cc
Labels: >non-issue, backport, v7.16.0

#2116 [8.0][ML] Fix divide by zero in MSLE and Huber loss functions
  lib/maths/analytics/CBoostedTreeLoss.cc
Labels: >non-issue, backport, v8.0.0

#2122 Update CHANGELOG.asciidoc
  docs/CHANGELOG.asciidoc
Labels: >docs

#2121 [ML] Fixing RapidJSON istream wrapper on incremental learning branch
  lib/api/unittest/CSerializableToJsonTest.cc
Labels: :ml/DataFrameAnalysis

#2123 [ML] Fix C++17 deprecation warnings
  include/core/Concurrency.h
  include/maths/common/CBjkstUniqueValues.h
  include/maths/common/CMixtureDistribution.h
  include/maths/common/CSetTools.h
  include/maths/time_series/CCountMinSketch.h
  include/model/CModelTools.h
  lib/core/unittest/CMemoryUsageTest.cc
  lib/maths/common/CBjkstUniqueValues.cc
  lib/maths/time_series/CCountMinSketch.cc
  lib/model/CModelTools.cc
Labels: review, >non-issue, :ml, v8.1.0

#2127 [ML] Re-run seccomp unit tests on more Linux distributions
  3rd_party/3rd_party.sh
  build.gradle
  dev-tools/docker/docker_entrypoint.sh
  dev-tools/docker_test.sh
  dev-tools/jenkins_ci.sh
Labels: :ml, >test, v8.1.0

#2128 [ML] Fix a bug in hyperparameter scaling for classification and regression model training
  docs/CHANGELOG.asciidoc
  lib/maths/analytics/CBoostedTreeFactory.cc
  lib/maths/analytics/unittest/CBoostedTreeTest.cc
Labels: >bug, review, :ml/DataFrameAnalysis, v8.1.0

#2132 [ML] Upgrade to gradle 7.3
  gradle/wrapper/gradle-wrapper.properties
Labels: >build, >non-issue, :ml, v8.0.0, v7.16.0, v8.1.0

#2133 [8.0] [ML] Upgrade to gradle 7.3
  gradle/wrapper/gradle-wrapper.properties
Labels: >non-issue, backport, v8.0.0

#2134 [7.16] [ML] Upgrade to gradle 7.3
  gradle/wrapper/gradle-wrapper.properties
Labels: >non-issue, backport, v7.16.0

#2136 [ML] Replace rapidjson::istreamwrapper in CJsonStateRestoreTraverser
  include/core/CJsonStateRestoreTraverser.h
  lib/core/CJsonStateRestoreTraverser.cc
Labels: >non-issue, :ml, v8.1.0

#2138 [ML] Removing null pointer output workaround for Boost.Test
  include/test/BoostTestPointerOutput.h
Labels: :ml, >test, v8.1.0

#2139 [ML] Set model state compatibility version to 8.0.0
  docs/CHANGELOG.asciidoc
  lib/api/CAnomalyJob.cc
Labels: >bug, :ml, v8.0.0, v8.1.0

#2140 [8.0] [ML] Set model state compatibility version to 8.0.0
  docs/CHANGELOG.asciidoc
  lib/api/CAnomalyJob.cc
Labels: backport, v8.0.0

#2125 [ML] Refactor parameter search initialisation
  include/maths/analytics/CBoostedTreeFactory.h
  include/maths/analytics/CBoostedTreeHyperparameters.h
  include/maths/analytics/CBoostedTreeImpl.h
  include/maths/analytics/CBoostedTreeUtils.h
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
  lib/api/unittest/CInferenceModelMetadataTest.cc
  lib/maths/analytics/CBoostedTree.cc
  lib/maths/analytics/CBoostedTreeFactory.cc
  lib/maths/analytics/CBoostedTreeHyperparameters.cc
  lib/maths/analytics/CBoostedTreeImpl.cc
  lib/maths/analytics/unittest/CBoostedTreeHyperparametersTest.cc
  lib/maths/analytics/unittest/CBoostedTreeTest.cc
Labels: review, >non-issue, :ml/DataFrameAnalysis
