Repository elastic/ml-cpp, pull requests merged in 2021-07, with the labels that each got.

#1937 [ML] Time inference calls in the pytorch app
  bin/pytorch_inference/Main.cc
  bin/pytorch_inference/evaluate.py
Labels: 3rd party models, :ml, >non-issue, v8.0.0

#1942 [ML] Update year in NOTICE file
  NOTICE.txt
Labels: :ml, >non-issue, v6.8.18, v7.14.0, v7.15.0, v8.0.0

#1940 [ML] Fix prediction task
  jupyter/src/incremental_learning/misc.py
  lib/api/CDataFrameTrainBoostedTreeRunner.cc
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
  lib/maths/CBoostedTreeFactory.cc
Labels: :ml/DataFrameAnalysis, >non-issue, review

#1944 [ML] Add validElasticLicenseKeyConfirmed command line arg to ml-cpp binaries
  bin/autodetect/CCmdLineParser.cc
  bin/autodetect/CCmdLineParser.h
  bin/autodetect/Main.cc
  bin/categorize/CCmdLineParser.cc
  bin/categorize/CCmdLineParser.h
  bin/categorize/Main.cc
  bin/data_frame_analyzer/CCmdLineParser.cc
  bin/data_frame_analyzer/CCmdLineParser.h
  bin/data_frame_analyzer/Main.cc
  bin/normalize/CCmdLineParser.cc
  bin/normalize/CCmdLineParser.h
  bin/normalize/Main.cc
  bin/pytorch_inference/CCmdLineParser.cc
  bin/pytorch_inference/CCmdLineParser.h
  bin/pytorch_inference/Main.cc
Labels: :ml, >non-issue, review, v7.15.0, v8.0.0

#1945 [ML] Add validElasticLicenseKeyConfirmed command line arg to ml-cpp binaries (#1944)
  bin/autodetect/CCmdLineParser.cc
  bin/autodetect/CCmdLineParser.h
  bin/autodetect/Main.cc
  bin/categorize/CCmdLineParser.cc
  bin/categorize/CCmdLineParser.h
  bin/categorize/Main.cc
  bin/data_frame_analyzer/CCmdLineParser.cc
  bin/data_frame_analyzer/CCmdLineParser.h
  bin/data_frame_analyzer/Main.cc
  bin/normalize/CCmdLineParser.cc
  bin/normalize/CCmdLineParser.h
  bin/normalize/Main.cc
Labels: :ml, >non-issue, backport, v7.15.0

#1943 [ML] Compute retrained tree weight shrinkage by cross-validation
  include/api/CDataFrameTrainBoostedTreeRunner.h
  include/maths/CBoostedTreeFactory.h
  include/maths/CBoostedTreeHyperparameters.h
  include/maths/CBoostedTreeImpl.h
  include/maths/CBoostedTreeUtils.h
  include/maths/CDataFrameAnalysisInstrumentationInterface.h
  lib/api/CDataFrameAnalysisInstrumentation.cc
  lib/api/CDataFrameTrainBoostedTreeRunner.cc
  lib/api/CInferenceModelMetadata.cc
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/CBoostedTreeHyperparameters.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/unittest/CBoostedTreeTest.cc
Labels: :ml/DataFrameAnalysis, >enhancement, >non-issue, review

#1941 [ML] Improve hyperparameter tuning performance
  docs/CHANGELOG.asciidoc
  include/api/CDataFrameAnalysisInstrumentation.h
  include/api/CDataFrameTrainBoostedTreeRunner.h
  include/api/CInferenceModelMetadata.h
  include/maths/CBayesianOptimisation.h
  include/maths/CBoostedTree.h
  include/maths/CBoostedTreeFactory.h
  include/maths/CBoostedTreeImpl.h
  include/maths/CDataFrameAnalysisInstrumentationInterface.h
  include/maths/CDataFramePredictiveModel.h
  include/maths/CDataFrameUtils.h
  include/maths/CLowess.h
  include/maths/CLowessDetail.h
  include/maths/CMixtureDistribution.h
  include/maths/CSolvers.h
  lib/api/CDataFrameAnalysisInstrumentation.cc
  lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
  lib/api/CDataFrameTrainBoostedTreeRegressionRunner.cc
  lib/api/CDataFrameTrainBoostedTreeRunner.cc
  lib/api/CInferenceModelMetadata.cc
  lib/api/unittest/CDataFrameAnalyzerFeatureImportanceTest.cc
  lib/maths/CBayesianOptimisation.cc
  lib/maths/CBoostedTree.cc
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/CDataFrameUtils.cc
  lib/maths/unittest/CBoostedTreeTest.cc
  lib/maths/unittest/CDataFrameUtilsTest.cc
  lib/maths/unittest/CLowessTest.cc
  lib/maths/unittest/COneOfNPriorTest.cc
  lib/maths/unittest/CSolversTest.cc
  lib/maths/unittest/Makefile
  lib/maths/unittest/TestUtils.cc
Labels: :ml/DataFrameAnalysis, >enhancement, review, v7.15.0

#1946 [ML][PYTORCH] Add options for the number of inter & intra threads
  bin/pytorch_inference/CCmdLineParser.cc
  bin/pytorch_inference/CCmdLineParser.h
  bin/pytorch_inference/Main.cc
  bin/pytorch_inference/evaluate.py
  bin/pytorch_inference/examples/simplest/test_run.json
Labels: 3rd party models, >non-issue, v8.0.0

#1950 [ML][PYTORCH] Pass --validElasticLicenseKeyConfirmed argument from evaluate.py
  bin/pytorch_inference/evaluate.py
Labels: 3rd party models, :ml, >non-issue, v8.0.0

#1959 [ML] Add logging so we know which round we exited hyperparameter tuning
  lib/maths/CBoostedTreeImpl.cc
Labels: :ml/DataFrameAnalysis, >non-issue, review, v7.15.0, v8.0.0

#1958 [ML] Recompute class weights before prediction task
  lib/api/CDataFrameTrainBoostedTreeRunner.cc
  lib/maths/CBoostedTreeFactory.cc
Labels: :ml/DataFrameAnalysis, >non-issue

#1951 [ML] Correct acceptance criterion for incremental training
  include/api/CDataFrameAnalysisInstrumentation.h
  include/api/CDataFrameTrainBoostedTreeRunner.h
  include/api/CInferenceModelMetadata.h
  include/core/CDataFrame.h
  include/maths/CBoostedTree.h
  include/maths/CBoostedTreeFactory.h
  include/maths/CBoostedTreeImpl.h
  include/maths/CDataFrameAnalysisInstrumentationInterface.h
  include/maths/CDataFramePredictiveModel.h
  include/test/CDataFrameAnalysisSpecificationFactory.h
  lib/api/CDataFrameAnalysisInstrumentation.cc
  lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
  lib/api/CDataFrameTrainBoostedTreeRegressionRunner.cc
  lib/api/CDataFrameTrainBoostedTreeRunner.cc
  lib/api/CInferenceModelMetadata.cc
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
  lib/api/unittest/testfiles/model_meta_data/model_meta_data.schema.json
  lib/core/CDataFrame.cc
  lib/core/unittest/CDataFrameTest.cc
  lib/maths/CBoostedTree.cc
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/unittest/CBoostedTreeTest.cc
  lib/test/CDataFrameAnalysisSpecificationFactory.cc
Labels: :ml/DataFrameAnalysis, >non-issue, review

#1965 [ML] Remove jCenter() from buildSrc and just use mavenCentral()
  buildSrc/build.gradle
  buildSrc/src/main/groovy/org/elastic/gradle/InjectionHack.groovy
  buildSrc/src/main/groovy/org/elastic/gradle/UploadS3Task.groovy
Labels: :ml, >build, >non-issue, v7.15.0, v8.0.0

#1967 [7.x] [ML] Remove jCenter() from buildSrc and just use mavenCentral()
  buildSrc/build.gradle
  buildSrc/src/main/groovy/org/elastic/gradle/InjectionHack.groovy
  buildSrc/src/main/groovy/org/elastic/gradle/UploadS3Task.groovy
Labels: >non-issue, backport, v7.15.0

#1960 [ML] Improve regression and classification QoR for small data sets
  docs/CHANGELOG.asciidoc
  include/maths/CBoostedTreeImpl.h
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/CDataFrameUtils.cc
  lib/maths/unittest/CBoostedTreeTest.cc
  lib/maths/unittest/CDataFrameUtilsTest.cc
Labels: :ml/DataFrameAnalysis, review, v7.15.0, v8.0.0

#1968 [ML] Preparation for renaming master branch to main
  CONTRIBUTING.md
Labels: :ml, >docs, v8.0.0

#1969 [ML] Upgrade Gradle wrapper to 7.1.1
  gradle/wrapper/gradle-wrapper.properties
Labels: >build, >non-issue, v7.15.0, v8.0.0

#1970 [ML] Adding upload tasks to build.gradle
  build.gradle
  dev-tools/jenkins_ci.ps1
  dev-tools/jenkins_ci.sh
  dev-tools/jenkins_cross_compile.sh
Labels: :ml, >build, v7.15.0, v8.0.0

#1971 [7.x] [ML] Adding upload tasks to build.gradle
  build.gradle
  dev-tools/jenkins_ci.ps1
  dev-tools/jenkins_ci.sh
  dev-tools/jenkins_cross_compile.sh
Labels: >non-issue, backport, v7.15.0

#1974 [ML] Include PyTorch libraries in cross-compiled builds
  3rd_party/3rd_party.sh
Labels: 3rd party models, :ml, >non-issue, v8.0.0

#1975 [ML] S3 upload task isn't available when embedded in ES build
  build.gradle
Labels: :ml, >build, v7.15.0, v8.0.0

#1976 [7.x] [ML] S3 upload task isn't available when embedded in ES build
  build.gradle
Labels: >build, >non-issue, backport, v7.15.0
