Repository elastic/ml-cpp, pull requests merged in 2021-04, with the labels that each got.

#1841 [ML] PyTorch results should be written as an array
  bin/pytorch_inference/Main.cc
Labels: :ml, >non-issue

#1844 [ML] Cross compile solely in dedicated script
  dev-tools/jenkins_ci.sh
Labels: :ml, >build, >non-issue, v6.8.16, v7.12.1, v7.13.0, v8.0.0

#1845 [7.x][ML] Cross compile solely in dedicated script
  dev-tools/jenkins_ci.sh
Labels: >non-issue, backport, v7.13.0

#1846 [7.12][ML] Cross compile solely in dedicated script
  dev-tools/jenkins_ci.sh
Labels: >non-issue, backport, v7.12.1

#1847 [6.8][ML] Cross compile solely in dedicated script
  dev-tools/jenkins_ci.sh
  dev-tools/jenkins_cross_compile.sh
Labels: >non-issue, backport, v6.8.16

#1832 [7.13][ML] Scale regularisers for final train
  docs/CHANGELOG.asciidoc
  include/maths/CBoostedTreeImpl.h
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/unittest/CBoostedTreeTest.cc
Labels: backport, v7.13.0

#1848 [ML] Persist state for correcting loss to account for model size when training a boosted tree
  docs/CHANGELOG.asciidoc
  include/maths/CBoostedTreeImpl.h
  lib/maths/CBoostedTreeImpl.cc
Labels: :ml/DataFrameAnalysis, >bug, review, v7.13.0, v8.0.0

#1854 [7.13][ML] Persist state for correcting loss to account for model size when training a boosted tree
  docs/CHANGELOG.asciidoc
  include/maths/CBoostedTreeImpl.h
  lib/maths/CBoostedTreeImpl.cc
Labels: backport pending, v7.13.0

#1855 [ML] Gracefully handle insufficient training data for classification and regression model training
  docs/CHANGELOG.asciidoc
  lib/maths/CDataFrameUtils.cc
  lib/maths/unittest/CBoostedTreeTest.cc
Labels: :ml/DataFrameAnalysis, >bug, review, v7.13.0, v8.0.0

#1856 [ML] Don't enable trace logging in categorizer tests
  lib/model/unittest/CTokenListDataCategorizerTest.cc
Labels: :ml, >non-issue, >test, v7.13.0, v8.0.0

#1858 [7.x][ML] Don't enable trace logging in categorizer tests
  lib/model/unittest/CTokenListDataCategorizerTest.cc
Labels: >non-issue, backport, v7.13.0

#1857 [7.13][ML] Gracefully handle insufficient training data for classification and regression model training
  docs/CHANGELOG.asciidoc
  lib/maths/CDataFrameUtils.cc
  lib/maths/unittest/CBoostedTreeTest.cc
Labels: backport, v7.13.0

#1842 [ML] Initialize incremental training
  dev-tools/run_es_tests.sh
  include/api/CDataFrameAnalysisSpecification.h
  include/api/CDataFrameTrainBoostedTreeRunner.h
  include/api/CDataSummarizationJsonSerializer.h
  include/api/CInferenceModelDefinition.h
  include/core/CDataFrame.h
  include/maths/CBoostedTree.h
  include/maths/CBoostedTreeFactory.h
  include/maths/CBoostedTreeImpl.h
  include/maths/CDataFramePredictiveModel.h
  include/test/CDataFrameAnalysisSpecificationFactory.h
  lib/api/CDataFrameTrainBoostedTreeRunner.cc
  lib/api/CDataSummarizationJsonSerializer.cc
  lib/api/CInferenceModelDefinition.cc
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
  lib/api/unittest/CDataFrameTrainBoostedTreeRegressionRunnerTest.cc
  lib/api/unittest/CDataSummarizationJsonSerializerTest.cc
  lib/api/unittest/testfiles/data_summarization_schema/data_summarization.schema.json
  lib/api/unittest/testfiles/restore_incremental_model.json
  lib/core/CDataFrame.cc
  lib/maths/CBoostedTree.cc
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/CBoostedTreeUtils.cc
  lib/test/CDataFrameAnalysisSpecificationFactory.cc
Labels: :ml, >non-issue

#1861 [ML] Upload dependency report to S3 along with uber zip file
  upload.gradle
Labels: :ml, >build, >non-issue, v7.14.0, v8.0.0

#1862 [ML] Pass row iterators by constant reference to callbacks
  include/core/CDataFrame.h
  include/test/CDataFrameAnalyzerTrainingFactory.h
  lib/api/CDataFrameAnalyzer.cc
  lib/api/unittest/CDataFrameAnalysisInstrumentationTest.cc
  lib/api/unittest/CDataFrameAnalyzerOutlierTest.cc
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
  lib/api/unittest/CDataFrameTrainBoostedTreeClassifierRunnerTest.cc
  lib/core/unittest/CDataFrameTest.cc
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/CBoostedTreeLeafNodeStatistics.cc
  lib/maths/CDataFrameUtils.cc
  lib/maths/COutliers.cc
  lib/maths/CTreeShapFeatureImportance.cc
  lib/maths/unittest/CBoostedTreeTest.cc
  lib/maths/unittest/CDataFrameUtilsTest.cc
  lib/maths/unittest/COutliersTest.cc
  lib/maths/unittest/CTreeShapFeatureImportanceTest.cc
Labels: :ml/DataFrameAnalysis, >non-issue, >refactoring, review, v7.14.0, v8.0.0

#1864 [7.x][ML] Upload dependency report to S3 along with uber zip file
  upload.gradle
Labels: >non-issue, backport, v7.14.0

#1837 [ML] Wire in incremental training
  include/api/CDataFrameTrainBoostedTreeClassifierRunner.h
  include/api/CDataFrameTrainBoostedTreeRegressionRunner.h
  include/api/CDataFrameTrainBoostedTreeRunner.h
  include/maths/CBoostedTree.h
  include/maths/CBoostedTreeFactory.h
  include/maths/CBoostedTreeHyperparameters.h
  include/maths/CBoostedTreeImpl.h
  include/maths/CBoostedTreeLeafNodeStatistics.h
  include/maths/CBoostedTreeLoss.h
  include/maths/CBoostedTreeUtils.h
  include/maths/CDataFrameAnalysisInstrumentationInterface.h
  include/maths/CDataFrameCategoryEncoder.h
  include/maths/CDataFramePredictiveModel.h
  include/test/CDataFrameAnalyzerTrainingFactory.h
  lib/api/CDataFrameAnalysisInstrumentation.cc
  lib/api/CDataFrameTrainBoostedTreeRegressionRunner.cc
  lib/api/CDataFrameTrainBoostedTreeRunner.cc
  lib/api/CInferenceModelMetadata.cc
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
  lib/maths/CBoostedTree.cc
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/CBoostedTreeHyperparameters.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/CBoostedTreeLeafNodeStatistics.cc
  lib/maths/CBoostedTreeLeafNodeStatisticsIncremental.cc
  lib/maths/CBoostedTreeLeafNodeStatisticsScratch.cc
  lib/maths/CBoostedTreeLoss.cc
  lib/maths/CBoostedTreeUtils.cc
  lib/maths/CDataFrameUtils.cc
  lib/maths/unittest/CBoostedTreeLeafNodeStatisticsTest.cc
  lib/maths/unittest/CBoostedTreeLossTest.cc
  lib/maths/unittest/CBoostedTreeTest.cc
  lib/maths/unittest/CBoostedTreeUtilsTest.cc
Labels: :ml/DataFrameAnalysis, >non-issue

#1865 [7.14][ML] Pass row iterators by constant reference to data frame callbacks
  include/core/CDataFrame.h
  include/test/CDataFrameAnalyzerTrainingFactory.h
  lib/api/CDataFrameAnalyzer.cc
  lib/api/unittest/CDataFrameAnalysisInstrumentationTest.cc
  lib/api/unittest/CDataFrameAnalyzerOutlierTest.cc
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
  lib/api/unittest/CDataFrameTrainBoostedTreeClassifierRunnerTest.cc
  lib/core/unittest/CDataFrameTest.cc
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/CBoostedTreeLeafNodeStatistics.cc
  lib/maths/CDataFrameUtils.cc
  lib/maths/COutliers.cc
  lib/maths/CTreeShapFeatureImportance.cc
  lib/maths/unittest/CBoostedTreeTest.cc
  lib/maths/unittest/CDataFrameUtilsTest.cc
  lib/maths/unittest/COutliersTest.cc
  lib/maths/unittest/CTreeShapFeatureImportanceTest.cc
Labels: >non-issue, backport, v7.14.0

#1863 [ML] Update Scenario 1 Jupyter notebook
  jupyter/notebooks/evaluation_scenarios/scenario-1.ipynb
  jupyter/notebooks/utils/misc.py
  jupyter/requirements.txt
Labels: :ml, >non-issue

#1867 [ML] Output max num trees in hyperparameters metadata
  .dockerignore
  .gitignore
  docs/CHANGELOG.asciidoc
  include/api/CInferenceModelMetadata.h
  include/maths/CBoostedTreeUtils.h
  include/test/CDataFrameAnalysisSpecificationFactory.h
  include/test/CDataFrameAnalyzerTrainingFactory.h
  lib/api/CInferenceModelMetadata.cc
  lib/api/unittest/CInferenceModelMetadataTest.cc
  lib/core/CLoopProgress.cc
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/unittest/CBoostedTreeTest.cc
  lib/test/CDataFrameAnalysisSpecificationFactory.cc
Labels: :ml, >bug, v7.12.2, v7.14.0, v8.0.0

#1871 Merge branch 'master' into feature/incremental-learning
  .dockerignore
  .gitignore
  docs/CHANGELOG.asciidoc
  include/api/CInferenceModelMetadata.h
  include/maths/CBoostedTreeUtils.h
  include/test/CDataFrameAnalysisSpecificationFactory.h
  include/test/CDataFrameAnalyzerTrainingFactory.h
  lib/api/CInferenceModelMetadata.cc
  lib/api/unittest/CInferenceModelMetadataTest.cc
  lib/core/CLoopProgress.cc
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/unittest/CBoostedTreeTest.cc
  lib/test/CDataFrameAnalysisSpecificationFactory.cc
Labels: :ml, >feature, >non-issue

#1872 [ML] Fail gracefully on encountering unexpected state
  docs/CHANGELOG.asciidoc
  include/maths/CMultivariateMultimodalPrior.h
  lib/maths/CMultimodalPrior.cc
Labels: :ml, >bug, review, v7.13.0, v7.14.0, v8.0.0

#1870 [ML] Apply tree depth constraint to hyperparameter search bounding box setup
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/unittest/CBoostedTreeTest.cc
Labels: :ml/DataFrameAnalysis, >non-issue, >refactoring, review, v7.14.0, v8.0.0

#1873 [7.14][ML] Fail gracefully on encountering unexpected state
  docs/CHANGELOG.asciidoc
  include/maths/CMultivariateMultimodalPrior.h
  lib/maths/CMultimodalPrior.cc
Labels: backport, v7.14.0

#1874 [7.13][ML] Fail gracefully on encountering unexpected state
  docs/CHANGELOG.asciidoc
  include/maths/CMultivariateMultimodalPrior.h
  lib/maths/CMultimodalPrior.cc
Labels: backport, v7.13.0

#1875 [7.x][ML] Output max num trees in hyperparameters metadata
  .dockerignore
  .gitignore
  docs/CHANGELOG.asciidoc
  include/api/CInferenceModelMetadata.h
  include/maths/CBoostedTreeUtils.h
  include/test/CDataFrameAnalysisSpecificationFactory.h
  include/test/CDataFrameAnalyzerTrainingFactory.h
  lib/api/CInferenceModelMetadata.cc
  lib/api/unittest/CInferenceModelMetadataTest.cc
  lib/core/CLoopProgress.cc
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/unittest/CBoostedTreeTest.cc
  lib/test/CDataFrameAnalysisSpecificationFactory.cc
Labels: :ml, >bug, backport, v7.14.0

#1877 [7.13][ML] Output max num trees in hyperparameters metadata
  .dockerignore
  .gitignore
  docs/CHANGELOG.asciidoc
  include/api/CInferenceModelMetadata.h
  include/maths/CBoostedTreeUtils.h
  include/test/CDataFrameAnalysisSpecificationFactory.h
  include/test/CDataFrameAnalyzerTrainingFactory.h
  lib/api/CInferenceModelMetadata.cc
  lib/api/unittest/CInferenceModelMetadataTest.cc
  lib/core/CLoopProgress.cc
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/unittest/CBoostedTreeTest.cc
  lib/test/CDataFrameAnalysisSpecificationFactory.cc
Labels: :ml, >bug, backport, v7.13.0

#1876 [7.12][ML] Output max num trees in hyperparameters metadata
  .dockerignore
  .gitignore
  docs/CHANGELOG.asciidoc
  include/api/CInferenceModelMetadata.h
  include/maths/CBoostedTreeUtils.h
  include/test/CDataFrameAnalysisSpecificationFactory.h
  include/test/CDataFrameAnalyzerTrainingFactory.h
  lib/api/CInferenceModelMetadata.cc
  lib/api/unittest/CInferenceModelMetadataTest.cc
  lib/core/CLoopProgress.cc
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/unittest/CBoostedTreeTest.cc
  lib/test/CDataFrameAnalysisSpecificationFactory.cc
Labels: :ml, >bug, backport, v7.12.2

#1880 [ML] Fixing 7.12.1 and 7.13.0 changelogs
  docs/CHANGELOG.asciidoc
Labels: :ml, >docs, v7.12.2, v7.13.0, v7.14.0

#1881 [ML] Reduce input stream buffer from 8KB to 2KB
  lib/api/CLengthEncodedInputParser.cc
Labels: :ml, >non-issue, v7.12.2, v7.13.0, v7.14.0, v8.0.0

#1882 [7.x][ML] Reduce input stream buffer from 8KB to 2KB (#1881)
  lib/api/CLengthEncodedInputParser.cc
Labels: >non-issue, backport, v7.14.0

#1883 [7.13][ML] Reduce input stream buffer from 8KB to 2KB (#1881)
  lib/api/CLengthEncodedInputParser.cc
Labels: >non-issue, backport, v7.13.0

#1884 [7.12][ML] Reduce input stream buffer from 8KB to 2KB (#1881)
  lib/api/CLengthEncodedInputParser.cc
Labels: >non-issue, backport, v7.12.2

#1887 [ML] Fix CStringStore unit test
  include/core/CStoredStringPtr.h
  lib/core/CStoredStringPtr.cc
  lib/model/unittest/CStringStoreTest.cc
Labels: :ml, >non-issue, >test, v7.13.0, v7.14.0, v8.0.0
