Repository elastic/ml-cpp, pull requests merged in 2021-01, with the labels that each got.

#1643 [7.11][ML] Avoid applying scale change points when the scale can't be accurately estimated
  include/maths/CTimeSeriesTestForChange.h
  lib/maths/CTimeSeriesDecompositionDetail.cc
  lib/maths/CTimeSeriesTestForChange.cc
  lib/maths/unittest/CTimeSeriesModelTest.cc
Labels: >non-issue, backport, v7.11.0

#1642 [7.12][ML] Avoid applying scale change points when the scale can't be accurately estimated
  include/maths/CTimeSeriesTestForChange.h
  lib/maths/CTimeSeriesDecompositionDetail.cc
  lib/maths/CTimeSeriesTestForChange.cc
  lib/maths/unittest/CTimeSeriesModelTest.cc
Labels: >non-issue, backport, v7.12.0

#1644 [ML] Remove CFieldConfig and related files
  bin/autodetect/CCmdLineParser.cc
  bin/autodetect/CCmdLineParser.h
  bin/autodetect/Main.cc
  include/api/CAnomalyJob.h
  include/api/CAnomalyJobConfig.h
  include/api/CFieldConfig.h
  include/api/CFieldDataCategorizer.h
  include/api/CForecastRunner.h
  include/maths/CModel.h
  include/model/CAnomalyDetectorModelConfig.h
  lib/api/CAnomalyJob.cc
  lib/api/CAnomalyJobConfig.cc
  lib/api/CFieldConfig.cc
  lib/api/CFieldDataCategorizer.cc
  lib/api/CForecastRunner.cc
  lib/api/CJsonOutputWriter.cc
  lib/api/Makefile.first
  lib/api/dump_state/Main.cc
  lib/api/unittest/CAnomalyJobConfigTest.cc
  lib/api/unittest/CConfigUpdaterTest.cc
  lib/api/unittest/CFieldConfigTest.cc
  lib/api/unittest/Makefile
  lib/api/unittest/testfiles/new_mlfields.conf
  lib/api/unittest/testfiles/new_mlfields_over.conf
  lib/api/unittest/testfiles/new_mlfields_partition.conf
  lib/api/unittest/testfiles/new_persist_categorization.conf
  lib/api/unittest/testfiles/new_persist_count.conf
  lib/api/unittest/testfiles/new_persist_dc.conf
  lib/api/unittest/testfiles/new_persist_per_partition_categorization.conf
  lib/core/CPatternSet.cc
  lib/core/unittest/CPatternSetTest.cc
  lib/maths/CModel.cc
  lib/maths/unittest/CForecastTest.cc
  lib/model/CAnomalyDetectorModelConfig.cc
  lib/model/unittest/CAnomalyDetectorModelConfigTest.cc
Labels: :ml, >non-issue, review, v7.12.0, v8.0.0

#1645 [7.x][ML] Remove CFieldConfig and related files (#1644)
  bin/autodetect/CCmdLineParser.cc
  bin/autodetect/CCmdLineParser.h
  bin/autodetect/Main.cc
  include/api/CAnomalyJob.h
  include/api/CAnomalyJobConfig.h
  include/api/CFieldConfig.h
  include/api/CFieldDataCategorizer.h
  include/api/CForecastRunner.h
  include/maths/CModel.h
  include/model/CAnomalyDetectorModelConfig.h
  lib/api/CAnomalyJob.cc
  lib/api/CAnomalyJobConfig.cc
  lib/api/CFieldConfig.cc
  lib/api/CFieldDataCategorizer.cc
  lib/api/CForecastRunner.cc
  lib/api/CJsonOutputWriter.cc
  lib/api/Makefile.first
  lib/api/dump_state/Main.cc
  lib/api/unittest/CAnomalyJobConfigTest.cc
  lib/api/unittest/CConfigUpdaterTest.cc
  lib/api/unittest/CFieldConfigTest.cc
  lib/api/unittest/Makefile
  lib/api/unittest/testfiles/new_mlfields.conf
  lib/api/unittest/testfiles/new_mlfields_over.conf
  lib/api/unittest/testfiles/new_mlfields_partition.conf
  lib/api/unittest/testfiles/new_persist_categorization.conf
  lib/api/unittest/testfiles/new_persist_count.conf
  lib/api/unittest/testfiles/new_persist_dc.conf
  lib/api/unittest/testfiles/new_persist_per_partition_categorization.conf
  lib/core/CPatternSet.cc
  lib/core/unittest/CPatternSetTest.cc
  lib/maths/CModel.cc
  lib/maths/unittest/CForecastTest.cc
  lib/model/CAnomalyDetectorModelConfig.cc
  lib/model/unittest/CAnomalyDetectorModelConfigTest.cc
Labels: :ml, >non-issue, backport, v7.12.0

#1627 [ML] Hyperparameter importance
  docs/CHANGELOG.asciidoc
  include/api/CDataFrameTrainBoostedTreeRunner.h
  include/api/CInferenceModelMetadata.h
  include/maths/CBayesianOptimisation.h
  include/maths/CBoostedTree.h
  include/maths/CBoostedTreeImpl.h
  include/maths/CBoostedTreeUtils.h
  include/maths/CSampling.h
  lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
  lib/api/CDataFrameTrainBoostedTreeRegressionRunner.cc
  lib/api/CDataFrameTrainBoostedTreeRunner.cc
  lib/api/CInferenceModelMetadata.cc
  lib/api/unittest/CInferenceModelMetadataTest.cc
  lib/api/unittest/Makefile
  lib/api/unittest/testfiles/model_meta_data/model_meta_data.schema.json
  lib/maths/CBayesianOptimisation.cc
  lib/maths/CBoostedTree.cc
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/CSampling.cc
  lib/maths/unittest/CBayesianOptimisationTest.cc
  lib/maths/unittest/CSamplingTest.cc
Labels: :ml/DataFrameAnalysis, >enhancement, review, v7.12.0, v8.0.0

#1647 [ML] Always use Boost unordered maps/sets
  include/api/CBoostedTreeInferenceModelBuilder.h
  include/api/CDataFrameAnalysisInstrumentation.h
  include/api/CInferenceModelDefinition.h
  include/api/CInferenceModelMetadata.h
  lib/api/CInferenceModelDefinition.cc
  lib/model/unittest/CEventRatePopulationModelTest.cc
Labels: :ml, >refactoring, v7.12.0, v8.0.0

#1649 [7.x][ML] Hyperparameter importance
  docs/CHANGELOG.asciidoc
  include/api/CDataFrameTrainBoostedTreeRunner.h
  include/api/CInferenceModelMetadata.h
  include/maths/CBayesianOptimisation.h
  include/maths/CBoostedTree.h
  include/maths/CBoostedTreeImpl.h
  include/maths/CBoostedTreeUtils.h
  include/maths/CSampling.h
  lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
  lib/api/CDataFrameTrainBoostedTreeRegressionRunner.cc
  lib/api/CDataFrameTrainBoostedTreeRunner.cc
  lib/api/CInferenceModelMetadata.cc
  lib/api/unittest/CInferenceModelMetadataTest.cc
  lib/api/unittest/Makefile
  lib/api/unittest/testfiles/model_meta_data/model_meta_data.schema.json
  lib/maths/CBayesianOptimisation.cc
  lib/maths/CBoostedTree.cc
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/CSampling.cc
  lib/maths/unittest/CBayesianOptimisationTest.cc
  lib/maths/unittest/CSamplingTest.cc
Labels: :ml, >enhancement, backport, v7.12.0

#1650 [ML] Fix scale initialization
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/CBoostedTreeImpl.cc
Labels: :ml/DataFrameAnalysis, >non-issue, v7.12.0, v8.0.0

#1652 [7.x][ML] Always use Boost unordered maps/sets
  include/api/CBoostedTreeInferenceModelBuilder.h
  include/api/CDataFrameAnalysisInstrumentation.h
  include/api/CInferenceModelDefinition.h
  include/api/CInferenceModelMetadata.h
  lib/api/CInferenceModelDefinition.cc
  lib/model/unittest/CEventRatePopulationModelTest.cc
Labels: >refactoring, backport, v7.12.0

#1646 [ML] Improve time series model stability
  docs/CHANGELOG.asciidoc
  lib/maths/CSeasonalComponent.cc
  lib/maths/CSeasonalComponentAdaptiveBucketing.cc
  lib/maths/CTimeSeriesDecompositionDetail.cc
  lib/maths/unittest/CSeasonalComponentTest.cc
  lib/maths/unittest/CTimeSeriesDecompositionTest.cc
  lib/model/unittest/CEventRateModelTest.cc
  lib/model/unittest/CMetricModelTest.cc
Labels: :ml, >bug, affects-results, review, v7.12.0, v8.0.0

#1653 [7.x] [ML] Fix scale initialization
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/CBoostedTreeImpl.cc
Labels: :ml, >non-issue, backport, v7.12.0

#1651 [ML] Changes to allow native compilation on ARM Macs
  3rd_party/3rd_party.sh
  build-setup/macos.md
  build.gradle
  include/api/CInferenceModelMetadata.h
  lib/core/CUname.cc
  lib/maths/unittest/CBoostedTreeTest.cc
  lib/maths/unittest/CLinearAlgebraTest.cc
  mk/macosx.mk
  set_env.sh
Labels: :ml, >non-issue, v7.12.0, v8.0.0

#1648 [ML] Prepare for removal of unneeded arguments
  bin/autodetect/CCmdLineParser.cc
  bin/autodetect/CCmdLineParser.h
  bin/autodetect/Main.cc
  include/api/CAnomalyJobConfig.h
  lib/api/CAnomalyJobConfig.cc
  lib/api/unittest/CAnomalyJobConfigTest.cc
  lib/model/CAnomalyDetectorModelConfig.cc
Labels: :ml, >non-issue, review, v7.12.0, v8.0.0

#1657 [7.x][ML] Prepare for removal of unneeded arguments (#1648)
  bin/autodetect/CCmdLineParser.cc
  bin/autodetect/CCmdLineParser.h
  bin/autodetect/Main.cc
  include/api/CAnomalyJobConfig.h
  lib/api/CAnomalyJobConfig.cc
  lib/api/unittest/CAnomalyJobConfigTest.cc
  lib/model/CAnomalyDetectorModelConfig.cc
Labels: :ml, >non-issue, backport, v7.12.0

#1656 [ML] Improve program counter resets between unit tests
  include/core/CProgramCounters.h
  include/test/CProgramCounterClearingFixture.h
  lib/api/unittest/CDataFrameAnalysisInstrumentationTest.cc
  lib/api/unittest/CInferenceModelMetadataTest.cc
  lib/api/unittest/CRestorePreviousStateTest.cc
  lib/core/unittest/CProgramCountersTest.cc
  lib/test/CProgramCounterClearingFixture.cc
  lib/test/Makefile
Labels: :ml, >test, v7.11.0, v7.12.0, v8.0.0

#1655 [ML] Fix wrong model metadata label
  lib/api/CInferenceModelMetadata.cc
Labels: :ml/DataFrameAnalysis, >non-issue, v7.12.0, v8.0.0

#1658 [7.x][ML] Improve program counter resets between unit tests
  include/core/CProgramCounters.h
  include/test/CProgramCounterClearingFixture.h
  lib/api/unittest/CDataFrameAnalysisInstrumentationTest.cc
  lib/api/unittest/CInferenceModelMetadataTest.cc
  lib/api/unittest/CRestorePreviousStateTest.cc
  lib/core/unittest/CProgramCountersTest.cc
  lib/test/CProgramCounterClearingFixture.cc
  lib/test/Makefile
Labels: >test, backport, v7.12.0

#1659 [7.11][ML] Improve program counter resets between unit tests
  include/core/CProgramCounters.h
  include/test/CProgramCounterClearingFixture.h
  lib/api/unittest/CDataFrameAnalysisInstrumentationTest.cc
  lib/api/unittest/CRestorePreviousStateTest.cc
  lib/core/unittest/CProgramCountersTest.cc
  lib/test/CProgramCounterClearingFixture.cc
  lib/test/Makefile
Labels: >test, backport, v7.11.0

#1638 [ML] PyTorch Inference
  3rd_party/3rd_party.sh
  bin/pytorch_inference/.objs/.gitignore
  bin/pytorch_inference/CBufferedIStreamAdapter.cc
  bin/pytorch_inference/CBufferedIStreamAdapter.h
  bin/pytorch_inference/CCmdLineParser.cc
  bin/pytorch_inference/CCmdLineParser.h
  bin/pytorch_inference/Main.cc
  bin/pytorch_inference/Makefile
  bin/pytorch_inference/evaluate.py
  bin/pytorch_inference/examples/ner/expected_response.json
  bin/pytorch_inference/examples/ner/input.json
  build-setup/pytorch/setup_pytorch.md
  include/seccomp/CSystemCallFilter.h
  lib/seccomp/CSystemCallFilter_MacOSX.cc
  mk/linux.mk
  mk/linux_crosscompile_linux.mk
  mk/linux_crosscompile_macosx.mk
  mk/macosx.mk
  mk/rules.mk
  mk/windows.mk
Labels: >non-issue

#1660 [7.x][ML] Fix wrong model metadata label
  lib/api/CInferenceModelMetadata.cc
Labels: :ml, >non-issue, backport, v7.12.0

#1661 [ML] Revert "Improve time series model stability"
  docs/CHANGELOG.asciidoc
  lib/maths/CSeasonalComponent.cc
  lib/maths/CSeasonalComponentAdaptiveBucketing.cc
  lib/maths/CTimeSeriesDecompositionDetail.cc
  lib/maths/unittest/CSeasonalComponentTest.cc
  lib/maths/unittest/CTimeSeriesDecompositionTest.cc
  lib/model/unittest/CEventRateModelTest.cc
  lib/model/unittest/CMetricModelTest.cc
Labels: :ml, >non-issue, v8.0.0

#1664 [7.x][ML] Changes to allow native compilation on ARM Macs
  3rd_party/3rd_party.sh
  build-setup/macos.md
  build.gradle
  include/api/CInferenceModelMetadata.h
  lib/core/CUname.cc
  lib/maths/unittest/CBoostedTreeTest.cc
  lib/maths/unittest/CLinearAlgebraTest.cc
  mk/macosx.mk
  set_env.sh
Labels: >non-issue, backport, v7.12.0

#1662 [ML] Leniency parsing background_persist_interval
  lib/api/CAnomalyJobConfig.cc
Labels: :ml, >non-issue, review, v7.12.0, v8.0.0

#1663 [ML] Remove redundant autodetect options
  bin/autodetect/CCmdLineParser.cc
  bin/autodetect/CCmdLineParser.h
  bin/autodetect/Main.cc
  include/api/CAnomalyJobConfig.h
  lib/api/unittest/CAnomalyJobConfigTest.cc
Labels: :ml, >non-issue, review, v7.12.0, v8.0.0

#1665 [ML] Leniency parsing background_persist_interval (#1662)
  lib/api/CAnomalyJobConfig.cc
Labels: :ml, >non-issue, backport, v7.12.0

#1666 [7.x][ML] Remove redundant autodetect options (#1663)
  bin/autodetect/CCmdLineParser.cc
  bin/autodetect/CCmdLineParser.h
  bin/autodetect/Main.cc
  include/api/CAnomalyJobConfig.h
  lib/api/unittest/CAnomalyJobConfigTest.cc
Labels: :ml, >non-issue, backport, v7.12.0

#1667 [ML] Fix declaration shadows a local variable issue
  lib/maths/CBoostedTreeLeafNodeStatistics.cc
Labels: :ml/DataFrameAnalysis, >non-issue, >refactoring, v7.12.0, v8.0.0

#1670 [ML] Fix rapidjson assertion failures
  lib/api/CAnomalyJobConfig.cc
Labels: :ml, >non-issue, review, v7.12.0, v8.0.0

#1668 [ML] Fix bug persisting and restoring time series model decay rate controller
  docs/CHANGELOG.asciidoc
  include/maths/CDecayRateController.h
  include/maths/CPRNG.h
  lib/maths/CDecayRateController.cc
  lib/maths/CPRNG.cc
  lib/maths/CTimeSeriesModel.cc
  lib/maths/unittest/CDecayRateControllerTest.cc
Labels: :ml, >bug, review, v6.8.14, v7.11.0, v7.12.0, v8.0.0

#1671 [7.x][ML] Fix rapidjson assertion failures (#1670)
  lib/api/CAnomalyJobConfig.cc
Labels: :ml, >non-issue, backport, v7.12.0

#1672 [7.12][ML] Fix bug persisting and restoring time series model decay rate controller
  docs/CHANGELOG.asciidoc
  include/maths/CDecayRateController.h
  include/maths/CPRNG.h
  lib/maths/CDecayRateController.cc
  lib/maths/CPRNG.cc
  lib/maths/CTimeSeriesModel.cc
  lib/maths/unittest/CDecayRateControllerTest.cc
Labels: backport, v7.12.0

#1673 [7.11][ML] Fix bug persisting and restoring time series model decay rate controller
  docs/CHANGELOG.asciidoc
  include/maths/CDecayRateController.h
  include/maths/CPRNG.h
  lib/maths/CDecayRateController.cc
  lib/maths/CPRNG.cc
  lib/maths/CTimeSeriesModel.cc
  lib/maths/unittest/CDecayRateControllerTest.cc
Labels: backport, v7.11.0

#1674 [6.8][ML] Fix bug persisting and restoring time series model decay rate controller
  docs/CHANGELOG.asciidoc
  include/maths/CDecayRateController.h
  include/maths/CPRNG.h
  lib/maths/CDecayRateController.cc
  lib/maths/CPRNG.cc
  lib/maths/CTimeSeriesModel.cc
  lib/maths/unittest/CDecayRateControllerTest.cc
  lib/maths/unittest/CDecayRateControllerTest.h
Labels: backport, review, v6.8.14

#1680 [6.8][ML] Fix bug persisting and restoring time series model decay rate controller (part 2)
  lib/maths/CTimeSeriesModel.cc
Labels: :ml, >non-issue, review, v6.8.14

#1681 [ML] Correct a bug in upgrade from pre 6.3 state for the lat_long function
  docs/CHANGELOG.asciidoc
  include/maths/CTimeSeriesModel.h
  lib/maths/CTimeSeriesModel.cc
  lib/maths/unittest/CTimeSeriesModelTest.cc
Labels: :ml, >bug, review, v7.12.0, v8.0.0

#1684 [7.12][ML] Fix a bug in upgrade from pre 6.3 state for the lat_long function
  docs/CHANGELOG.asciidoc
  include/maths/CTimeSeriesModel.h
  lib/maths/CTimeSeriesModel.cc
  lib/maths/unittest/CTimeSeriesModelTest.cc
Labels: backport, v7.12.0

#1682 [ML] Parse JSON format config updates
  include/api/CAnomalyJobConfig.h
  include/api/CConfigUpdater.h
  include/model/CAnomalyDetectorModelConfig.h
  lib/api/CAnomalyJobConfig.cc
  lib/api/CConfigUpdater.cc
  lib/api/unittest/CConfigUpdaterTest.cc
  lib/model/CAnomalyDetectorModelConfig.cc
Labels: :ml, >non-issue, review, v7.12.0, v8.0.0

#1685 [ML] Adjusting macOS build instructions for PyTorch
  build-setup/macos.md
  build-setup/pytorch/setup_pytorch.md
Labels: :ml, >docs

#1677 [ML] Build setup instructions and tweaks for Torch on Windows
  3rd_party/3rd_party.sh
  bin/pytorch_inference/CCmdLineParser.cc
  bin/pytorch_inference/Main.cc
  bin/pytorch_inference/Makefile
  build-setup/windows.md
  mk/windows.mk
Labels: :ml, >build

#1686 [7.x][ML] Parse JSON format config updates (#1682)
  include/api/CAnomalyJobConfig.h
  include/api/CConfigUpdater.h
  include/model/CAnomalyDetectorModelConfig.h
  lib/api/CAnomalyJobConfig.cc
  lib/api/CConfigUpdater.cc
  lib/api/unittest/CConfigUpdaterTest.cc
  lib/model/CAnomalyDetectorModelConfig.cc
Labels: :ml, >non-issue, backport, v7.12.0

#1687 [ML] Tidy up data frame analysis progress monitoring
  lib/api/CDataFrameAnalysisInstrumentation.cc
Labels: :ml/DataFrameAnalysis, >non-issue, >refactoring, v7.12.0, v8.0.0

#1688 [ML] Add PyTorch setup instructions for Linux
  build-setup/linux.md
Labels: :ml, >docs

#1676 [ML] Early stopping for hyperparameter optimization procedure
  docs/CHANGELOG.asciidoc
  include/api/CDataFrameTrainBoostedTreeRunner.h
  include/maths/CBoostedTreeFactory.h
  include/maths/CBoostedTreeImpl.h
  include/test/CDataFrameAnalysisSpecificationFactory.h
  lib/api/CDataFrameTrainBoostedTreeRunner.cc
  lib/api/unittest/CDataFrameAnalyzerFeatureImportanceTest.cc
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/unittest/CBoostedTreeTest.cc
  lib/test/CDataFrameAnalysisSpecificationFactory.cc
Labels: :ml/DataFrameAnalysis, >enhancement, v7.12.0, v8.0.0

#1683 [ML] Provide the ability to override eta growth rate hyperparameter
  include/maths/CBoostedTreeFactory.h
  include/maths/CBoostedTreeImpl.h
  lib/api/CDataFrameTrainBoostedTreeRunner.cc
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/unittest/CBoostedTreeTest.cc
Labels: :ml/DataFrameAnalysis, >enhancement, >non-issue, review, v7.12.0, v8.0.0

#1689 [7.12][ML] Tidy up data frame analysis progress monitoring
  lib/api/CDataFrameAnalysisInstrumentation.cc
Labels: >non-issue, backport, v7.12.0

#1690 [7.12][ML] Provide the ability to override eta growth rate hyperparameter
  include/maths/CBoostedTreeFactory.h
  include/maths/CBoostedTreeImpl.h
  lib/api/CDataFrameTrainBoostedTreeRunner.cc
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/unittest/CBoostedTreeTest.cc
Labels: >non-issue, backport pending, v7.12.0

#1691 [7.x][ML] Early stopping for hyperparameter optimization procedure
  docs/CHANGELOG.asciidoc
  include/api/CDataFrameTrainBoostedTreeRunner.h
  include/maths/CBoostedTreeFactory.h
  include/maths/CBoostedTreeImpl.h
  include/test/CDataFrameAnalysisSpecificationFactory.h
  lib/api/CDataFrameTrainBoostedTreeRunner.cc
  lib/api/unittest/CDataFrameAnalyzerFeatureImportanceTest.cc
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/unittest/CBoostedTreeTest.cc
  lib/test/CDataFrameAnalysisSpecificationFactory.cc
Labels: :ml, >enhancement, backport, v7.12.0

#1678 [ML] Add libtorch Linux DockerFile
  bin/pytorch_inference/evaluate.py
  build-setup/pytorch/setup_pytorch.md
  dev-tools/docker/build_linux_build_image.sh
  dev-tools/docker/linux_image/Dockerfile
Labels: >build

#1692 [ML] Improving PyTorch build on Windows
  build-setup/windows.md
Labels: :ml, >docs

#1694 [ML] Additional logging for the feature importance test failure
  include/api/CDataFrameTrainBoostedTreeRegressionRunner.h
  lib/api/CDataFrameTrainBoostedTreeRegressionRunner.cc
Labels: :ml/DataFrameAnalysis, >non-issue, v7.12.0, v8.0.0

#1696 [ML] Use Eigen BLAS library when building PyTorch for Linux
  build-setup/linux.md
  dev-tools/docker/linux_image/Dockerfile
Labels: >build, >docs

#1697 [ML] Windows adjustments for PyTorch
  bin/pytorch_inference/evaluate.py
  build-setup/pytorch/setup_pytorch.md
  dev-tools/download_windows_deps.ps1
  lib/api/CIoManager.cc
Labels: :ml, >enhancement

#1675 [ML] Assorted time series modelling stability fixes
  docs/CHANGELOG.asciidoc
  include/maths/CCalendarComponent.h
  include/maths/CCalendarFeature.h
  include/maths/CSeasonalComponent.h
  include/maths/CSeasonalComponentAdaptiveBucketing.h
  include/maths/CSeasonalTime.h
  include/maths/CTimeSeriesDecompositionDetail.h
  include/maths/CTimeSeriesModel.h
  lib/maths/CCalendarComponent.cc
  lib/maths/CCalendarComponentAdaptiveBucketing.cc
  lib/maths/CCalendarFeature.cc
  lib/maths/CDecayRateController.cc
  lib/maths/CSeasonalComponent.cc
  lib/maths/CSeasonalComponentAdaptiveBucketing.cc
  lib/maths/CSeasonalTime.cc
  lib/maths/CTimeSeriesDecomposition.cc
  lib/maths/CTimeSeriesDecompositionDetail.cc
  lib/maths/CTimeSeriesModel.cc
  lib/maths/CTimeSeriesTestForSeasonality.cc
  lib/maths/unittest/CDecayRateControllerTest.cc
  lib/maths/unittest/CForecastTest.cc
  lib/maths/unittest/CSeasonalComponentTest.cc
  lib/maths/unittest/CTimeSeriesDecompositionTest.cc
  lib/maths/unittest/CTimeSeriesModelTest.cc
  lib/maths/unittest/CTimeSeriesTestForSeasonalityTest.cc
  lib/model/unittest/CEventRateModelTest.cc
  lib/model/unittest/CMetricModelTest.cc
Labels: :ml, >bug, review, v7.12.0, v8.0.0

#1695 [ML] Unify CBoostedTreeTest in 7.x and master
  lib/maths/unittest/CBoostedTreeTest.cc
Labels: :ml, >test, v7.12.0, v8.0.0

#1699 [ML] Rename the early stopping configuration parameter
  include/api/CDataFrameTrainBoostedTreeRunner.h
  include/maths/CBoostedTreeFactory.h
  include/test/CDataFrameAnalysisSpecificationFactory.h
  lib/api/CDataFrameTrainBoostedTreeRunner.cc
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/unittest/CBoostedTreeTest.cc
  lib/test/CDataFrameAnalysisSpecificationFactory.cc
Labels: :ml, >non-issue, v7.12.0, v8.0.0

#1706 [ML] Read eta_growth_rate_per_tree param
  lib/api/CDataFrameTrainBoostedTreeRunner.cc
Labels: :ml, :ml/DataFrameAnalysis, >non-issue, v7.12.0, v8.0.0

#1707 [ML] Fix seasonal model update immediately after initialisation
  lib/maths/CSeasonalComponent.cc
  lib/maths/CTimeSeriesDecompositionDetail.cc
  lib/maths/unittest/CForecastTest.cc
  lib/maths/unittest/CSeasonalComponentTest.cc
  lib/model/unittest/CEventRateModelTest.cc
  lib/model/unittest/CMetricModelTest.cc
Labels: :ml, >non-issue, review, v7.12.0, v8.0.0

#1708 [7.x][ML] Read eta_growth_rate_per_tree param (#1706)
  lib/api/CDataFrameTrainBoostedTreeRunner.cc
Labels: :ml, :ml/DataFrameAnalysis, >non-issue, backport

#1705 [7.x][ML] Rename the early stopping configuration parameter
  include/api/CDataFrameTrainBoostedTreeRunner.h
  include/maths/CBoostedTreeFactory.h
  include/test/CDataFrameAnalysisSpecificationFactory.h
  lib/api/CDataFrameTrainBoostedTreeRunner.cc
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/unittest/CBoostedTreeTest.cc
  lib/test/CDataFrameAnalysisSpecificationFactory.cc
Labels: :ml/DataFrameAnalysis, >non-issue, backport, v7.12.0

#1710 [ML] Disable early stopping for the feature importance API tests
  lib/api/unittest/CDataFrameAnalyzerFeatureImportanceTest.cc
Labels: :ml/DataFrameAnalysis, >non-issue, v7.12.0, v8.0.0

#1709 [ML] Revert "[ML] Additional logging for the feature importance test failure"
  include/api/CDataFrameTrainBoostedTreeRegressionRunner.h
  lib/api/CDataFrameTrainBoostedTreeRegressionRunner.cc
Labels: :ml/DataFrameAnalysis, >non-issue, v8.0.0

#1711 [7.x][ML] Disable early stopping for the feature importance API tests
  lib/api/unittest/CDataFrameAnalyzerFeatureImportanceTest.cc
Labels: :ml/DataFrameAnalysis, >non-issue, backport, v7.12.0

#1712 [ML] Remove mkl dependency and improve docker cleanup
  build-setup/linux.md
  build-setup/macos.md
  dev-tools/docker/linux_image/Dockerfile
Labels: 3rd party models
