Repository elastic/ml-cpp, pull requests merged in 2021-03, with the labels that each got.

#1778 [7.x][ML] Ensure program counters cache always cleared (#1774)
  include/api/CAnomalyJob.h
  include/core/CProgramCounters.h
  lib/api/CAnomalyJob.cc
  lib/api/CFieldDataCategorizer.cc
  lib/api/unittest/CPersistenceManagerTest.cc
  lib/core/CProgramCounters.cc
Labels: :ml, >non-issue, backport, v7.13.0

#1777 [ML] Fixes to get CI working on CentOS on AArch64
  dev-tools/run_es_tests.sh
  set_env.sh
Labels: :ml, >build, >non-issue, v7.11.2, v7.12.0, v7.13.0, v8.0.0

#1779 [ML] Ensure model_extractor compiles
  devbin/model_extractor/CCmdLineParser.cc
  devbin/model_extractor/CCmdLineParser.h
  devbin/model_extractor/Main.cc
Labels: :ml, >non-issue, review, v7.13.0, v8.0.0

#1773 [ML] Add makefile dependency on static objects for tests
  bin/controller/unittest/Makefile
  mk/stdboosttest.mk
Labels: >build, >non-issue, v7.12.0, v7.13.0, v8.0.0

#1781 [7.12][ML] Fixes to get CI working on CentOS on AArch64
  dev-tools/run_es_tests.sh
  set_env.sh
Labels: >non-issue, backport, v7.12.0

#1780 [7.x][ML] Fixes to get CI working on CentOS on AArch64
  dev-tools/run_es_tests.sh
  set_env.sh
Labels: >non-issue, backport, v7.13.0

#1783 [7.x][ML] Ensure model_extractor compiles (#1779)
  devbin/model_extractor/CCmdLineParser.cc
  devbin/model_extractor/CCmdLineParser.h
  devbin/model_extractor/Main.cc
  devbin/model_extractor/Makefile
Labels: :ml, >non-issue, backport, v7.13.0

#1782 [7.11][ML] Fixes to get CI working on CentOS on AArch64
  dev-tools/run_es_tests.sh
  set_env.sh
Labels: >non-issue, backport, v7.11.2

#1785 [7.x] [ML] Add makefile dependency on static objects for tests (#1773)
  bin/controller/unittest/Makefile
  mk/stdboosttest.mk
Labels: >build, >non-issue, backport, v7.13.0

#1771 [ML] Add clang-tidy configuration
  .clang-tidy
Labels: :ml, >non-issue

#1788 [7.x][ML] Add clang-tidy configuration
  .clang-tidy
Labels: :ml, >non-issue, backport, v7.12.0

#1753 [ML] Initial evaluation workbench setup
  .dockerignore
  .gitignore
  jupyter/README.md
  jupyter/docker/Dockerfile
  jupyter/docker/gcsfuse.repo
  jupyter/docker/init.sh
  jupyter/docker/jupyter_notebook_config.py
  jupyter/notebooks/configs/ember_malware_bytes.json
  jupyter/notebooks/configs/facebook_6000.json
  jupyter/notebooks/datasets/facebook_6000.csv
  jupyter/notebooks/scenario-1.ipynb
  jupyter/requirements.txt
  lib/maths/CBoostedTreeImpl.cc
  set_env.sh
Labels: :ml, >non-issue

#1787 [ML] VSCode setup instructions
  build-setup/vscode/using_vscode.md
Labels: >docs, v7.13.0, v8.0.0

#1791 [7.x] [ML] VSCode setup instructions (#1787)
  build-setup/vscode/using_vscode.md
Labels: >non-issue, backport, v7.13.0

#1772 [ML] Incremental train (part 1)
  include/maths/CBoostedTree.h
  include/maths/CBoostedTreeFactory.h
  include/maths/CBoostedTreeImpl.h
  include/maths/CBoostedTreeLeafNodeStatistics.h
  include/maths/CBoostedTreeLeafNodeStatisticsIncremental.h
  include/maths/CBoostedTreeLeafNodeStatisticsScratch.h
  include/maths/CDataFramePredictiveModel.h
  lib/api/CDataFrameTrainBoostedTreeRunner.cc
  lib/api/unittest/CBoostedTreeInferenceModelBuilderTest.cc
  lib/maths/CBoostedTree.cc
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/CBoostedTreeLeafNodeStatistics.cc
  lib/maths/CBoostedTreeLeafNodeStatisticsScratch.cc
  lib/maths/Makefile
  lib/maths/unittest/CBoostedTreeLeafNodeStatisticsTest.cc
  lib/maths/unittest/CBoostedTreeTest.cc
Labels: :ml/DataFrameAnalysis, >non-issue, >refactoring, review

#1786 [ML] Use TESTED_OBJS dependency in PyTorch unittest makefile
  bin/pytorch_inference/unittest/Makefile
Labels: 3rd party models, >non-issue

#1793 [ML] MSE loss function for incremental training
  include/maths/CBoostedTree.h
  include/maths/CBoostedTreeFactory.h
  include/maths/CBoostedTreeImpl.h
  include/maths/CBoostedTreeLoss.h
  include/maths/CBoostedTreeUtils.h
  include/maths/CDataFrameCategoryEncoder.h
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/CBoostedTreeLoss.cc
  lib/maths/CBoostedTreeUtils.cc
  lib/maths/unittest/CBoostedTreeLossTest.cc
  lib/maths/unittest/CBoostedTreeTest.cc
Labels: :ml/DataFrameAnalysis, >non-issue, review

#1795 [ML] Upgrading to PyTorch 1.8.0 on macOS
  build-setup/macos.md
  dev-tools/docker/build_macosx_build_image.sh
  dev-tools/docker/macosx_builder/Dockerfile
  dev-tools/docker/macosx_image/Dockerfile
  dev-tools/download_macos_deps.sh
Labels: 3rd party models

#1798 [ML] Improve bounds checks in state restore code
  include/core/CPersistUtils.h
  include/maths/CBasicStatisticsPersist.h
  lib/core/CProgramCounters.cc
  lib/core/unittest/CProgramCountersTest.cc
  lib/maths/CDataFrameUtils.cc
Labels: :ml, >non-issue, v6.8.15, v7.12.0, v7.13.0, v8.0.0

#1803 [ML] Make too many array values on restore fatal
  include/core/CPersistUtils.h
Labels: :ml, >non-issue, v8.0.0

#1801 [7.12][ML] Improve bounds checks in state restore code
  include/core/CPersistUtils.h
  include/maths/CBasicStatisticsPersist.h
  lib/core/CProgramCounters.cc
  lib/core/unittest/CProgramCountersTest.cc
  lib/maths/CDataFrameUtils.cc
Labels: >non-issue, backport, v7.12.0

#1802 [6.8][ML] Improve bounds checks in state restore code
  include/core/CPersistUtils.h
  include/maths/CBasicStatisticsPersist.h
  lib/core/CStatistics.cc
Labels: >non-issue, backport, v6.8.15

#1800 [7.x][ML] Improve bounds checks in state restore code
  include/core/CPersistUtils.h
  include/maths/CBasicStatisticsPersist.h
  lib/core/CProgramCounters.cc
  lib/core/unittest/CProgramCountersTest.cc
  lib/maths/CDataFrameUtils.cc
Labels: >non-issue, backport, v7.13.0

#1796 [ML] Upgrading to PyTorch 1.8.0 on Windows
  build-setup/windows.md
  dev-tools/download_windows_deps.ps1
Labels: 3rd party models

#1807 [ML] Some command line improvements
  bin/autodetect/CCmdLineParser.cc
  devbin/state_search_splitter/Main.cc
Labels: :ml, >non-issue, review, v7.12.1, v7.13.0, v8.0.0

#1799 [ML] Rename pytorch log pipe arg
  bin/pytorch_inference/CCmdLineParser.cc
  bin/pytorch_inference/CCmdLineParser.h
  bin/pytorch_inference/Main.cc
Labels: 3rd party models, :ml, >non-issue

#1809 [7.12][ML] Some command line improvements
  bin/autodetect/CCmdLineParser.cc
  devbin/state_search_splitter/Main.cc
Labels: >non-issue, backport, v7.12.0

#1808 [7.13][ML] Some command line improvements
  bin/autodetect/CCmdLineParser.cc
  devbin/state_search_splitter/Main.cc
Labels: >non-issue, backport, v7.13.0

#1806 [ML] Document the reason for allowing some syscalls
  lib/seccomp/CSystemCallFilter_Linux.cc
Labels: :ml, >non-issue, v7.13.0, v8.0.0

#1797 [ML] Upgrading to PyTorch 1.8.0 on Linux
  3rd_party/3rd_party.sh
  build-setup/linux.md
  dev-tools/docker/build_linux_aarch64_cross_build_image.sh
  dev-tools/docker/build_linux_aarch64_native_build_image.sh
  dev-tools/docker/build_linux_build_image.sh
  dev-tools/docker/linux_aarch64_cross_builder/Dockerfile
  dev-tools/docker/linux_aarch64_cross_image/Dockerfile
  dev-tools/docker/linux_aarch64_native_builder/Dockerfile
  dev-tools/docker/linux_aarch64_native_image/Dockerfile
  dev-tools/docker/linux_aarch64_native_tester/Dockerfile
  dev-tools/docker/linux_builder/Dockerfile
  dev-tools/docker/linux_image/Dockerfile
  dev-tools/docker/linux_tester/Dockerfile
Labels: 3rd party models

#1812 [ML] A couple of improvements to setting RPATH
  3rd_party/3rd_party.sh
  mk/linux.mk
  mk/linux_crosscompile_linux.mk
Labels: :ml, >build, >non-issue, v7.13.0, v8.0.0

#1813 [7.x][ML] Document the reason for allowing some syscalls
  lib/seccomp/CSystemCallFilter_Linux.cc
Labels: >non-issue, backport, v7.13.0

#1814 [7.x][ML] A couple of improvements to setting RPATH
  3rd_party/3rd_party.sh
  mk/linux.mk
  mk/linux_crosscompile_linux.mk
Labels: >non-issue, backport, v7.13.0

#1816 [ML] Add PyTorch license to repo
  3rd_party/licenses/pytorch-INFO.csv
  3rd_party/licenses/pytorch-LICENSE.txt
  3rd_party/licenses/pytorch-NOTICE.txt
Labels: 3rd party models

#1810 [ML] Supplementary files for data summarization investigation
  jupyter/.gitignore
  jupyter/notebooks/__init__.py
  jupyter/notebooks/configs/ccpp.json
  jupyter/notebooks/configs/electrical-grid-stability.json
  jupyter/notebooks/configs/regression_2175_kin8nm.json
  jupyter/notebooks/configs/regression_2202_elevators.json
  jupyter/notebooks/configs/regression_house_16h.json
  jupyter/notebooks/configs/regression_wind.json
  jupyter/notebooks/configs/wine_quality_white.json
  jupyter/notebooks/data_summarization_investigation/get dataset with eland.ipynb
  jupyter/notebooks/data_summarization_investigation/sampling_driver.py
  jupyter/notebooks/data_summarization_investigation/stratified-random-sampling.ipynb
  jupyter/notebooks/data_summarization_investigation/tree-guided-sampling.ipynb
  jupyter/notebooks/evaluation_scenarios/scenario-1.ipynb
  jupyter/notebooks/sampling-investigation-stable-neighbourhoods.ipynb
  jupyter/notebooks/utils/__init__.py
  jupyter/notebooks/utils/misc.py
  jupyter/notebooks/utils/trees.py
  lib/maths/CBoostedTreeImpl.cc
Labels: :ml/DataFrameAnalysis, >feature, >non-issue

#1819 [ML] Adding mremap to syscall filter
  docs/CHANGELOG.asciidoc
  lib/seccomp/CSystemCallFilter_Linux.cc
Labels: :ml, >enhancement, v7.13.0, v8.0.0

#1822 [7.x][ML] Adding mremap to syscall filter
  docs/CHANGELOG.asciidoc
  lib/seccomp/CSystemCallFilter_Linux.cc
Labels: backport, v7.13.0

#1821 [ML] Abort more explicitly
  include/core/CLogger.h
  lib/core/CLogger.cc
  lib/core/unittest/CLoggerTest.cc
Labels: :ml, >non-issue, v6.8.16, v7.12.1, v7.13.0, v8.0.0

#1823 [ML] Make state traversal unwind more quickly on errors
  include/core/CJsonStateRestoreTraverser.h
  include/core/CRapidXmlStateRestoreTraverser.h
  include/core/CStateRestoreTraverser.h
  include/maths/CMultimodalPriorMode.h
  include/model/CSearchKey.h
  lib/api/CAnomalyJob.cc
  lib/api/CFieldDataCategorizer.cc
  lib/core/CJsonStateRestoreTraverser.cc
  lib/core/CRapidXmlStateRestoreTraverser.cc
  lib/core/CStateRestoreTraverser.cc
  lib/maths/CBjkstUniqueValues.cc
  lib/maths/CConstantPrior.cc
  lib/maths/CCountMinSketch.cc
  lib/maths/CGammaRateConjugate.cc
  lib/maths/CLogNormalMeanPrecConjugate.cc
  lib/maths/CMultimodalPrior.cc
  lib/maths/CMultinomialConjugate.cc
  lib/maths/CNormalMeanPrecConjugate.cc
  lib/maths/COneOfNPrior.cc
  lib/maths/CPoissonMeanConjugate.cc
  lib/maths/CSeasonalComponent.cc
  lib/maths/CSeasonalComponentAdaptiveBucketing.cc
  lib/maths/CStatisticalTests.cc
  lib/model/CAnomalyDetector.cc
  lib/model/CCategoryExamplesCollector.cc
  lib/model/CCountingModel.cc
  lib/model/CDataGatherer.cc
  lib/model/CEventRateBucketGatherer.cc
  lib/model/CEventRateModel.cc
  lib/model/CEventRatePopulationModel.cc
  lib/model/CIndividualModel.cc
  lib/model/CMetricBucketGatherer.cc
  lib/model/CMetricModel.cc
  lib/model/CMetricPopulationModel.cc
  lib/model/CSearchKey.cc
  lib/model/CTokenListCategory.cc
Labels: :ml, >non-issue, v7.13.0, v8.0.0

#1824 [7.x][ML] Abort more explicitly
  include/core/CLogger.h
  lib/core/CLogger.cc
  lib/core/unittest/CLoggerTest.cc
Labels: >non-issue, backport, v7.13.0

#1827 [7.x][ML] Make state traversal unwind more quickly on errors
  include/core/CJsonStateRestoreTraverser.h
  include/core/CRapidXmlStateRestoreTraverser.h
  include/core/CStateRestoreTraverser.h
  include/maths/CMultimodalPriorMode.h
  include/model/CSearchKey.h
  lib/api/CAnomalyJob.cc
  lib/api/CFieldDataCategorizer.cc
  lib/core/CJsonStateRestoreTraverser.cc
  lib/core/CRapidXmlStateRestoreTraverser.cc
  lib/core/CStateRestoreTraverser.cc
  lib/maths/CBjkstUniqueValues.cc
  lib/maths/CConstantPrior.cc
  lib/maths/CCountMinSketch.cc
  lib/maths/CGammaRateConjugate.cc
  lib/maths/CLogNormalMeanPrecConjugate.cc
  lib/maths/CMultimodalPrior.cc
  lib/maths/CMultinomialConjugate.cc
  lib/maths/CNormalMeanPrecConjugate.cc
  lib/maths/COneOfNPrior.cc
  lib/maths/CPoissonMeanConjugate.cc
  lib/maths/CSeasonalComponent.cc
  lib/maths/CSeasonalComponentAdaptiveBucketing.cc
  lib/maths/CStatisticalTests.cc
  lib/model/CAnomalyDetector.cc
  lib/model/CCategoryExamplesCollector.cc
  lib/model/CCountingModel.cc
  lib/model/CDataGatherer.cc
  lib/model/CEventRateBucketGatherer.cc
  lib/model/CEventRateModel.cc
  lib/model/CEventRatePopulationModel.cc
  lib/model/CIndividualModel.cc
  lib/model/CMetricBucketGatherer.cc
  lib/model/CMetricModel.cc
  lib/model/CMetricPopulationModel.cc
  lib/model/CSearchKey.cc
  lib/model/CTokenListCategory.cc
Labels: >non-issue, backport, v7.13.0

#1818 [ML] Handle validation errors in PyTorch requests
  bin/pytorch_inference/CCommandParser.cc
  bin/pytorch_inference/CCommandParser.h
  bin/pytorch_inference/Main.cc
  bin/pytorch_inference/unittest/CCommandParserTest.cc
Labels: 3rd party models, >feature

#1826 [6.8][ML] Abort more explicitly
  include/core/CLogger.h
  lib/core/CLogger.cc
  lib/core/unittest/CLoggerTest.cc
Labels: >non-issue, backport, v6.8.16

#1817 [ML] Add ability to evaluate a simple PyTorch model
  bin/pytorch_inference/CCommandParser.cc
  bin/pytorch_inference/CCommandParser.h
  bin/pytorch_inference/Main.cc
  bin/pytorch_inference/evaluate.py
  bin/pytorch_inference/examples/simplest/test_run.json
  bin/pytorch_inference/unittest/CCommandParserTest.cc
Labels: 3rd party models, >feature

#1825 [7.12][ML] Abort more explicitly
  include/core/CLogger.h
  lib/core/CLogger.cc
  lib/core/unittest/CLoggerTest.cc
Labels: >non-issue, backport, v7.12.1

#1828 [ML] Make ML native processes work with glibc 2.33 on x86_64
  docs/CHANGELOG.asciidoc
  lib/seccomp/CSystemCallFilter_Linux.cc
Labels: :ml, >enhancement, v7.12.1, v7.13.0, v8.0.0

#1830 [7.x][ML] Make ML native processes work with glibc 2.33 on x86_64
  docs/CHANGELOG.asciidoc
  lib/seccomp/CSystemCallFilter_Linux.cc
Labels: backport, v7.13.0

#1831 [7.12][ML] Make ML native processes work with glibc 2.33 on x86_64
  docs/CHANGELOG.asciidoc
  lib/seccomp/CSystemCallFilter_Linux.cc
Labels: backport, v7.12.1

#1820 [ML] Tree to retrain selection
  include/maths/CBoostedTreeLoss.h
  include/maths/CBoostedTreeUtils.h
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/CBoostedTreeLoss.cc
  lib/maths/CBoostedTreeUtils.cc
  lib/maths/CDataFrameUtils.cc
  lib/maths/unittest/BoostedTreeTestData.cc
  lib/maths/unittest/BoostedTreeTestData.h
  lib/maths/unittest/CBoostedTreeLossTest.cc
  lib/maths/unittest/CBoostedTreeUtilsTest.cc
  lib/maths/unittest/Makefile
Labels: :ml/DataFrameAnalysis, >non-issue, review

#1833 [ML] Output data summarization
  include/api/CDataFrameAnalysisRunner.h
  include/api/CDataFrameAnalyzer.h
  include/api/CDataFrameTrainBoostedTreeClassifierRunner.h
  include/api/CDataFrameTrainBoostedTreeRegressionRunner.h
  include/api/CDataFrameTrainBoostedTreeRunner.h
  include/api/CDataSummarizationJsonSerializer.h
  include/api/CInferenceModelDefinition.h
  include/api/CSerializableToJson.h
  include/maths/CBoostedTree.h
  include/maths/CBoostedTreeImpl.h
  include/maths/CDataFramePredictiveModel.h
  lib/api/CDataFrameAnalysisRunner.cc
  lib/api/CDataFrameAnalyzer.cc
  lib/api/CDataFrameTrainBoostedTreeRegressionRunner.cc
  lib/api/CDataFrameTrainBoostedTreeRunner.cc
  lib/api/CDataSummarizationJsonSerializer.cc
  lib/api/CInferenceModelDefinition.cc
  lib/api/CSerializableToJson.cc
  lib/api/Makefile.first
  lib/api/unittest/CDataSummarizationJsonSerializerTest.cc
  lib/api/unittest/Makefile
  lib/api/unittest/testfiles/data_summarization_schema/data_summarization.schema.json
  lib/maths/CBoostedTree.cc
  lib/maths/CBoostedTreeImpl.cc
Labels: >feature, >non-issue, review, v8.0.0

#1835 [ML] Restructure Jenkins scripts
  build.gradle
  dev-tools/aws_creds_from_vault.sh
  dev-tools/docker/linux_aarch64_cross_builder/Dockerfile
  dev-tools/docker/linux_aarch64_native_builder/Dockerfile
  dev-tools/docker/linux_aarch64_native_tester/Dockerfile
  dev-tools/docker/linux_builder/Dockerfile
  dev-tools/docker/linux_tester/Dockerfile
  dev-tools/docker/macosx_builder/Dockerfile
  dev-tools/docker_build.sh
  dev-tools/docker_test.sh
  dev-tools/jenkins_ci.ps1
  dev-tools/jenkins_ci.sh
  dev-tools/jenkins_cross_compile.sh
  mk/toplevel.mk
  set_env.sh
Labels: :ml, >build, >non-issue, v6.8.16, v7.12.1, v7.13.0, v8.0.0

#1836 [ML] Make CI scripts independent of initial working directory
  dev-tools/jenkins_ci.sh
  dev-tools/jenkins_cross_compile.sh
Labels: :ml, >non-issue, v8.0.0

#1838 [7.x][ML] Restructure Jenkins scripts
  build.gradle
  dev-tools/aws_creds_from_vault.sh
  dev-tools/docker/linux_aarch64_cross_builder/Dockerfile
  dev-tools/docker/linux_aarch64_native_builder/Dockerfile
  dev-tools/docker/linux_aarch64_native_tester/Dockerfile
  dev-tools/docker/linux_builder/Dockerfile
  dev-tools/docker/linux_tester/Dockerfile
  dev-tools/docker/macosx_builder/Dockerfile
  dev-tools/docker_build.sh
  dev-tools/docker_test.sh
  dev-tools/jenkins_ci.ps1
  dev-tools/jenkins_ci.sh
  dev-tools/jenkins_cross_compile.sh
  mk/toplevel.mk
  set_env.sh
Labels: >non-issue, backport, v7.13.0

#1839 [7.12][ML] Restructure Jenkins scripts
  build.gradle
  dev-tools/aws_creds_from_vault.sh
  dev-tools/docker/linux_aarch64_cross_builder/Dockerfile
  dev-tools/docker/linux_aarch64_native_builder/Dockerfile
  dev-tools/docker/linux_aarch64_native_tester/Dockerfile
  dev-tools/docker/linux_builder/Dockerfile
  dev-tools/docker/linux_tester/Dockerfile
  dev-tools/docker/macosx_builder/Dockerfile
  dev-tools/docker_build.sh
  dev-tools/docker_test.sh
  dev-tools/jenkins_ci.ps1
  dev-tools/jenkins_ci.sh
  dev-tools/jenkins_cross_compile.sh
  mk/toplevel.mk
  set_env.sh
Labels: >non-issue, backport, v7.12.1
