Repository elastic/ml-cpp, pull requests merged in 2021-05, with the labels that each got.

#1888 [ML] Sync writing atomic more strongly in CStringStore
  docs/CHANGELOG.asciidoc
  lib/model/CStringStore.cc
  lib/model/unittest/CStringStoreTest.cc
Labels: :ml, >bug, v7.13.0, v7.14.0, v8.0.0

#1890 [7.13][ML] Fix CStringStore unit test
  include/core/CStoredStringPtr.h
  lib/core/CStoredStringPtr.cc
  lib/model/unittest/CStringStoreTest.cc
Labels: >non-issue, backport, v7.13.0

#1889 [7.x][ML] Fix CStringStore unit test
  include/core/CStoredStringPtr.h
  lib/core/CStoredStringPtr.cc
  lib/model/unittest/CStringStoreTest.cc
Labels: >non-issue, backport, v7.14.0

#1891 [7.x][ML] Sync writing atomic more strongly in CStringStore
  docs/CHANGELOG.asciidoc
  lib/model/CStringStore.cc
  lib/model/unittest/CStringStoreTest.cc
Labels: backport, v7.14.0

#1892 [7.13][ML] Sync writing atomic more strongly in CStringStore
  docs/CHANGELOG.asciidoc
  lib/model/CStringStore.cc
  lib/model/unittest/CStringStoreTest.cc
Labels: backport, v7.13.0

#1879 [ML] Restore blob for incremental training in place
  bin/data_frame_analyzer/Main.cc
  include/api/CDataFrameAnalysisRunner.h
  include/api/CDataFrameAnalysisSpecification.h
  include/api/CDataFrameAnalyzer.h
  include/api/CDataFrameOutliersRunner.h
  include/api/CDataFrameTrainBoostedTreeClassifierRunner.h
  include/api/CDataFrameTrainBoostedTreeRegressionRunner.h
  include/api/CDataFrameTrainBoostedTreeRunner.h
  include/api/CDataSummarizationJsonSerializer.h
  include/api/CSerializableToJson.h
  include/core/CDataFrame.h
  include/maths/CBoostedTree.h
  include/maths/CBoostedTreeFactory.h
  include/maths/CBoostedTreeImpl.h
  include/test/CDataFrameAnalysisSpecificationFactory.h
  lib/api/CDataFrameAnalysisRunner.cc
  lib/api/CDataFrameAnalysisSpecification.cc
  lib/api/CDataFrameAnalyzer.cc
  lib/api/CDataFrameOutliersRunner.cc
  lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
  lib/api/CDataFrameTrainBoostedTreeRegressionRunner.cc
  lib/api/CDataFrameTrainBoostedTreeRunner.cc
  lib/api/CDataSummarizationJsonSerializer.cc
  lib/api/CSerializableToJson.cc
  lib/api/unittest/CBoostedTreeInferenceModelBuilderTest.cc
  lib/api/unittest/CDataFrameAnalysisInstrumentationTest.cc
  lib/api/unittest/CDataFrameAnalyzerFeatureImportanceTest.cc
  lib/api/unittest/CDataFrameAnalyzerOutlierTest.cc
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
  lib/api/unittest/CDataFrameMockAnalysisRunner.cc
  lib/api/unittest/CDataFrameMockAnalysisRunner.h
  lib/api/unittest/CDataFrameTrainBoostedTreeClassifierRunnerTest.cc
  lib/api/unittest/CDataFrameTrainBoostedTreeRegressionRunnerTest.cc
  lib/api/unittest/CDataSummarizationJsonSerializerTest.cc
  lib/api/unittest/CInferenceModelMetadataTest.cc
  lib/api/unittest/testfiles/restore_incremental_model.json
  lib/core/CDataFrame.cc
  lib/maths/CBoostedTree.cc
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/CDataFrameUtils.cc
  lib/maths/unittest/CBoostedTreeTest.cc
  lib/test/CDataFrameAnalysisSpecificationFactory.cc
Labels: :ml/DataFrameAnalysis, >non-issue, review

#1893 [ML] Make atomic operations safer for aarch64
  docs/CHANGELOG.asciidoc
  include/maths/CIntegration.h
  lib/model/CStringStore.cc
Labels: :ml, >bug, v7.14.0, v8.0.0

#1894 [ML] Improve error checking when reading trainable model
  include/api/CDataFrameAnalysisRunner.h
  include/api/CDataFrameTrainBoostedTreeRunner.h
  include/api/CDataSummarizationJsonSerializer.h
  lib/api/CDataFrameAnalysisRunner.cc
  lib/api/CDataFrameTrainBoostedTreeRunner.cc
  lib/api/CDataSummarizationJsonSerializer.cc
  lib/api/unittest/CDataSummarizationJsonSerializerTest.cc
Labels: :ml/DataFrameAnalysis, >non-issue, review

#1896 [ML] Fix inference model feature encoder index mismatch
  include/api/CBoostedTreeInferenceModelBuilder.h
  include/api/CDataFrameAnalysisRunner.h
  include/api/CDataFrameAnalyzer.h
  include/api/CDataFrameTrainBoostedTreeRunner.h
  include/api/CDataSummarizationJsonSerializer.h
  include/api/CInferenceModelDefinition.h
  include/api/CSerializableToJson.h
  include/maths/CBoostedTree.h
  include/maths/CBoostedTreeFactory.h
  include/maths/CBoostedTreeImpl.h
  include/maths/CDataFramePredictiveModel.h
  lib/api/CBoostedTreeInferenceModelBuilder.cc
  lib/api/CDataFrameAnalysisRunner.cc
  lib/api/CDataFrameAnalyzer.cc
  lib/api/CDataFrameTrainBoostedTreeRunner.cc
  lib/api/CDataSummarizationJsonSerializer.cc
  lib/api/CInferenceModelDefinition.cc
  lib/api/unittest/CDataSummarizationJsonSerializerTest.cc
  lib/api/unittest/testfiles/data_summarization_schema/data_summarization.schema.json
  lib/api/unittest/testfiles/restore_incremental_model.json
  lib/maths/CBoostedTree.cc
  lib/maths/CBoostedTreeFactory.cc
  lib/maths/CBoostedTreeImpl.cc
  lib/maths/CDataFrameCategoryEncoder.cc
  lib/maths/CDataFramePredictiveModel.cc
Labels: :ml/DataFrameAnalysis, >non-issue, review

#1897 [ML] Read summarisation and model from chunked state
  include/api/CDataSummarizationJsonSerializer.h
  include/api/CInferenceModelDefinition.h
  include/api/CSerializableToJson.h
  lib/api/CDataFrameAnalyzer.cc
  lib/api/CDataSummarizationJsonSerializer.cc
  lib/api/CInferenceModelDefinition.cc
  lib/api/CSerializableToJson.cc
  lib/api/unittest/CSerializableToJsonTest.cc
  lib/api/unittest/Makefile
Labels: :ml/DataFrameAnalysis, >non-issue, review

#1903 [ML] Boost weighting for multiple adjacent words.
  docs/CHANGELOG.asciidoc
  include/api/CFieldDataCategorizer.h
  include/core/CWordDictionary.h
  include/model/CTokenListDataCategorizer.h
  include/model/CTokenListDataCategorizerBase.h
  lib/api/unittest/CAnomalyJobConfigTest.cc
  lib/core/unittest/CStringSimilarityTesterTest.cc
  lib/model/CTokenListCategory.cc
  lib/model/CTokenListDataCategorizerBase.cc
  lib/model/unittest/CTokenListDataCategorizerTest.cc
Labels: :ml, >enhancement, review, v7.14.0, v8.0.0

#1904 [7.x][ML] Boost weighting for multiple adjacent words. (#1903)
  docs/CHANGELOG.asciidoc
  include/api/CFieldDataCategorizer.h
  include/core/CWordDictionary.h
  include/model/CTokenListDataCategorizer.h
  include/model/CTokenListDataCategorizerBase.h
  lib/api/unittest/CAnomalyJobConfigTest.cc
  lib/core/unittest/CStringSimilarityTesterTest.cc
  lib/model/CTokenListCategory.cc
  lib/model/CTokenListDataCategorizerBase.cc
  lib/model/unittest/CTokenListDataCategorizerTest.cc
Labels: :ml, >enhancement, backport, v7.14.0
