Repository elastic/ml-cpp, pull requests merged in 2021-12, with the labels that each got.

#2137 [ML] Upgrade to Eigen 3.4.0
  3rd_party/licenses/eigen-INFO.csv
  3rd_party/licenses/eigen-NOTICE.txt
  3rd_party/pull-eigen.sh
  docs/CHANGELOG.asciidoc
  include/maths/common/CLeastSquaresOnlineRegressionDetail.h
  lib/maths/analytics/unittest/CBoostedTreeTest.cc
  lib/maths/common/unittest/CLinearAlgebraTest.cc
Labels: review, >build, :ml, v8.1.0

#2144 [ML] Improve training stability for regression and classification models
  docs/CHANGELOG.asciidoc
  include/maths/common/CLbfgs.h
  lib/maths/analytics/unittest/CBoostedTreeTest.cc
  lib/maths/common/CBayesianOptimisation.cc
Labels: >bug, review, :ml/DataFrameAnalysis, v8.1.0

#2147 [ML] Some improvements to Bayesian Optimisation implementation
  docs/CHANGELOG.asciidoc
  include/maths/common/CBayesianOptimisation.h
  include/maths/common/CLbfgs.h
  lib/maths/analytics/unittest/CBoostedTreeTest.cc
  lib/maths/common/CBayesianOptimisation.cc
  lib/maths/common/unittest/CBayesianOptimisationTest.cc
Labels: >enhancement, review, :ml/DataFrameAnalysis, v8.1.0

#2150 [ML] Improve regression and classification training stability
  docs/CHANGELOG.asciidoc
  lib/maths/analytics/CBoostedTreeImpl.cc
  lib/maths/analytics/unittest/CBoostedTreeTest.cc
Labels: >enhancement, review, :ml/DataFrameAnalysis, v8.1.0

#2149 [ML] Fix deprecation warning for macOS build
  include/api/CHierarchicalResultsWriter.h
  include/core/CBase64Filter.h
  include/core/CFastMutex.h
  include/core/CVectorRange.h
  include/core/CXmlNode.h
  include/maths/common/CClusterer.h
  include/maths/common/CMultivariateNormalConjugate.h
  include/model/CHierarchicalResults.h
  include/model/CHierarchicalResultsAggregator.h
  include/model/CHierarchicalResultsLevelSet.h
  include/model/CHierarchicalResultsNormalizer.h
  include/model/CHierarchicalResultsPopulator.h
  include/model/CHierarchicalResultsProbabilityFinalizer.h
  lib/api/CInferenceModelMetadata.cc
  lib/core/CBase64Filter.cc
  lib/core/CFastMutex_MacOSX.cc
  lib/core/CXmlNode.cc
  lib/maths/common/unittest/COrderingsTest.cc
  lib/model/CHierarchicalResults.cc
Labels: review, >non-issue, :ml, v8.1.0

#2143 [ML] Fix sources of cross platform variation in incremental training
  include/maths/analytics/CBoostedTreeHyperparameters.h
  lib/maths/analytics/CBoostedTreeImpl.cc
  lib/maths/analytics/unittest/CBoostedTreeTest.cc
Labels: review, >non-issue, :ml/DataFrameAnalysis

#2151 [ML] Relax test threshold
  lib/maths/analytics/unittest/CBoostedTreeTest.cc
Labels: :ml, >test, v8.1.0

#2145 [ML] Experiment multistep learning with hyperparameters ranges
  jupyter/data/jobs/.gitignore
  jupyter/notebooks/prototypes/multi-step learning/Compare to the baseline.ipynb
  jupyter/notebooks/prototypes/push2elasticsearch.ipynb
  jupyter/scripts/multi_step_learning/origin/experiment_driver.py
  jupyter/scripts/multi_step_learning/origin/generate_experiment_matrix.py
  jupyter/scripts/multi_step_learning/origin/job.tpl
  jupyter/scripts/multi_step_learning/origin/job_submitter.py
  jupyter/scripts/multi_step_learning/parameter_ranges/experiment_driver.py
  jupyter/scripts/multi_step_learning/parameter_ranges/generate_experiment_matrix.py
  jupyter/scripts/multi_step_learning/parameter_ranges/job.tpl
  jupyter/scripts/multi_step_learning/parameter_ranges/job_submitter.py
  jupyter/src/incremental_learning/job.py
  jupyter/src/incremental_learning/job_submitter.py
  jupyter/src/incremental_learning/misc.py
  jupyter/src/incremental_learning/storage.py
Labels: :ml/DataFrameAnalysis

#2152 [ML] Silence warnings stemming from PyTorch headers
  bin/pytorch_inference/Makefile
Labels: review, >non-issue, :ml, v8.1.0

#2153 [ML] Add the ability to optionally disable hyperparameter scaling
  include/api/CDataFrameTrainBoostedTreeRunner.h
  include/maths/analytics/CBoostedTreeFactory.h
  include/maths/analytics/CBoostedTreeHyperparameters.h
  include/maths/analytics/CBoostedTreeImpl.h
  lib/api/CDataFrameTrainBoostedTreeRunner.cc
  lib/maths/analytics/CBoostedTreeFactory.cc
  lib/maths/analytics/CBoostedTreeHyperparameters.cc
  lib/maths/analytics/CBoostedTreeImpl.cc
Labels: review, >non-issue, :ml/DataFrameAnalysis

#2159 [ML] Write actual thread settings after pytorch process starts
  bin/pytorch_inference/Main.cc
Labels: >non-issue, :ml, 3rd party models, v8.1.0

#2160 [ML] Fixing the way we set up the ES JVM on linux-aarch64
  dev-tools/run_es_tests.sh
Labels: :ml, >test, v8.0.0, v8.1.0

#2161 [8.0] [ML] Fixing the way we set up the ES JVM on linux-aarch64
  dev-tools/run_es_tests.sh
Labels: >test, backport, v8.0.0

#2164 [ML] Tighten up the pattern used to copy Torch dependencies
  3rd_party/3rd_party.sh
Labels: >build, >non-issue, :ml, v8.0.0, v8.1.0

#2165 [8.0] [ML] Tighten up the pattern used to copy Torch dependencies
  3rd_party/3rd_party.sh
Labels: >non-issue, backport, v8.0.0
