Repository elastic/ml-cpp, pull requests merged in 2021-10, with the labels that each got.

#2053 [ML] Improve aspects of skip_model_update rule
  docs/CHANGELOG.asciidoc
  include/maths/CModel.h
  include/model/CAnomalyDetectorModel.h
  lib/maths/CModel.cc
  lib/maths/CTimeSeriesModel.cc
  lib/maths/unittest/CTimeSeriesModelTest.cc
  lib/model/CAnomalyDetectorModel.cc
  lib/model/CEventRateModel.cc
  lib/model/CEventRatePopulationModel.cc
  lib/model/CMetricModel.cc
  lib/model/CMetricPopulationModel.cc
  lib/model/unittest/CEventRateModelTest.cc
  lib/model/unittest/CEventRatePopulationModelTest.cc
  lib/model/unittest/CMetricModelTest.cc
  lib/model/unittest/CMetricPopulationModelTest.cc
Labels: >enhancement, review, :ml, v8.0.0, v7.16.0

#2055 [7.x][ML] Improve aspects of skip_model_update rule (#2053)
  docs/CHANGELOG.asciidoc
  include/maths/CModel.h
  include/model/CAnomalyDetectorModel.h
  lib/maths/CModel.cc
  lib/maths/CTimeSeriesModel.cc
  lib/maths/unittest/CTimeSeriesModelTest.cc
  lib/model/CAnomalyDetectorModel.cc
  lib/model/CEventRateModel.cc
  lib/model/CEventRatePopulationModel.cc
  lib/model/CMetricModel.cc
  lib/model/CMetricPopulationModel.cc
  lib/model/unittest/CEventRateModelTest.cc
  lib/model/unittest/CEventRatePopulationModelTest.cc
  lib/model/unittest/CMetricModelTest.cc
  lib/model/unittest/CMetricPopulationModelTest.cc
Labels: >enhancement, :ml, backport, v7.16.0

#2051 [ML] Handle chunked state in Python Job object
  jupyter/src/incremental_learning/job.py
Labels: review, >non-issue, :ml/DataFrameAnalysis

#2057 [ML] Capture best hyperparameters after restoring for final train
  docs/CHANGELOG.asciidoc
  lib/maths/CBoostedTreeImpl.cc
Labels: >bug, review, v8.0.0, :ml/DataFrameAnalysis, v7.16.0

#2062 [7.x][ML] Capture best hyperparameters after restoring for final train
  docs/CHANGELOG.asciidoc
  lib/maths/CBoostedTreeImpl.cc
Labels: backport, v7.16.0

#2056 [ML] Add a notebook incrementally training DGA with sunburst domains
  jupyter/notebooks/incremental_learning/03-demo-dga-sunburst-update.ipynb
  lib/maths/CBoostedTreeFactory.cc
Labels: review, >non-issue, >test, :ml/DataFrameAnalysis

#2082 [ML] Avoid possible referencing out-of-scope temporary in lambda return types
  include/maths/common/CLbfgs.h
  include/maths/common/CLowessDetail.h
  lib/maths/analytics/CBoostedTreeLoss.cc
  lib/maths/analytics/CDataFrameUtils.cc
  lib/maths/analytics/unittest/CBoostedTreeLossTest.cc
  lib/maths/common/CBayesianOptimisation.cc
  lib/maths/common/CXMeansOnline1d.cc
  lib/maths/common/unittest/CLbfgsTest.cc
Labels: >bug, review, >non-issue, v8.0.0, v7.16.0
