Repository elastic/ml-cpp, pull requests merged in 2022-06, with the labels that each got.

#2275 [ML] Restructure docker image layers
  jupyter/docker/Dockerfile
  jupyter/src/incremental_learning/job.py
Labels: >non-issue, :ml/DataFrameAnalysis

#2291 [ML] Apply consistent size penalty selecting best classification and regression model
  docs/CHANGELOG.asciidoc
  include/maths/analytics/CBoostedTreeHyperparameters.h
  lib/maths/analytics/CBoostedTreeHyperparameters.cc
  lib/maths/analytics/CBoostedTreeImpl.cc
  lib/maths/analytics/unittest/testfiles/error_bayesian_optimisation_state.json
  lib/maths/analytics/unittest/testfiles/error_boosted_tree_impl_state.json
Labels: >enhancement, review, :ml/DataFrameAnalysis, v8.4.0

#2260 [ML] Coarse parameter tuning early stopping
  .clang-tidy
  include/core/CContainerPrinter.h
  include/maths/analytics/CBoostedTreeFactory.h
  include/maths/analytics/CBoostedTreeHyperparameters.h
  include/maths/common/CBayesianOptimisation.h
  include/maths/common/CLinearAlgebraEigen.h
  lib/core/unittest/CContainerPrinterTest.cc
  lib/maths/analytics/CBoostedTreeFactory.cc
  lib/maths/analytics/CBoostedTreeHyperparameters.cc
  lib/maths/analytics/CBoostedTreeImpl.cc
  lib/maths/analytics/unittest/CBoostedTreeHyperparametersTest.cc
  lib/maths/analytics/unittest/CBoostedTreeTest.cc
  lib/maths/common/CBayesianOptimisation.cc
  lib/maths/common/unittest/CBayesianOptimisationTest.cc
Labels: >non-issue, :ml/DataFrameAnalysis

#2301 [ML] Correct change version in documentation
  docs/CHANGELOG.asciidoc
Labels: :ml, v8.4.0

#2300 [8.3][ML] Improve normalisation of anomaly detection results for short bucket lengths
  docs/CHANGELOG.asciidoc
  include/model/CAnomalyScore.h
  lib/api/unittest/CResultNormalizerTest.cc
  lib/model/CAnomalyScore.cc
  lib/model/unittest/CAnomalyScoreTest.cc
  lib/model/unittest/CHierarchicalResultsTest.cc
Labels: backport, v8.3.0

#2303 [7.17] [ML] Fixing the way we set up the ES JVM on linux-aarch64
  dev-tools/run_es_tests.sh
Labels: >test, backport, v7.17.5

#2298 [ML] Early stopping for coarse parameter tuning
  .clang-tidy
  docs/CHANGELOG.asciidoc
  include/core/CContainerPrinter.h
  include/maths/analytics/CBoostedTreeFactory.h
  include/maths/analytics/CBoostedTreeHyperparameters.h
  include/maths/common/CBayesianOptimisation.h
  include/maths/common/CLinearAlgebraEigen.h
  lib/core/unittest/CContainerPrinterTest.cc
  lib/maths/analytics/CBoostedTreeFactory.cc
  lib/maths/analytics/CBoostedTreeHyperparameters.cc
  lib/maths/analytics/CBoostedTreeImpl.cc
  lib/maths/analytics/unittest/CBoostedTreeHyperparametersTest.cc
  lib/maths/analytics/unittest/CBoostedTreeTest.cc
  lib/maths/common/CBayesianOptimisation.cc
  lib/maths/common/unittest/CBayesianOptimisationTest.cc
Labels: >feature, :ml/DataFrameAnalysis, v8.4.0

#2297 [ML] Memory management for incremental training
  include/api/CDataFrameTrainBoostedTreeRunner.h
  include/api/CInferenceModelMetadata.h
  include/core/CDataFrame.h
  include/maths/analytics/CBoostedTreeFactory.h
  include/maths/analytics/CBoostedTreeImpl.h
  include/maths/analytics/CBoostedTreeUtils.h
  include/maths/analytics/CDataFrameCategoryEncoder.h
  include/maths/common/CNaturalBreaksClassifier.h
  lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
  lib/api/CDataFrameTrainBoostedTreeRunner.cc
  lib/api/CInferenceModelMetadata.cc
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
  lib/api/unittest/testfiles/model_meta_data/model_meta_data.schema.json
  lib/core/CDataFrame.cc
  lib/maths/analytics/CBoostedTreeFactory.cc
  lib/maths/analytics/CBoostedTreeImpl.cc
  lib/maths/analytics/CDataFrameCategoryEncoder.cc
  lib/maths/analytics/unittest/CBoostedTreeTest.cc
  lib/maths/analytics/unittest/CDataFrameCategoryEncoderTest.cc
  lib/maths/analytics/unittest/COutliersTest.cc
Labels: review, >non-issue, :ml/DataFrameAnalysis

#2294 [ML] Reactivate Java integration tests
  dev-tools/run_es_tests.sh
  include/api/ApiTypes.h
  include/api/CDataFrameAnalysisInstrumentation.h
  include/api/CDataFrameTrainBoostedTreeRunner.h
  include/api/CInferenceModelMetadata.h
  include/maths/analytics/CBoostedTreeImpl.h
  include/test/CDataFrameAnalysisSpecificationFactory.h
  lib/api/CDataFrameAnalysisInstrumentation.cc
  lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
  lib/api/CDataFrameTrainBoostedTreeRegressionRunner.cc
  lib/api/CDataFrameTrainBoostedTreeRunner.cc
  lib/api/CInferenceModelMetadata.cc
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
  lib/api/unittest/CDataSummarizationJsonSerializerTest.cc
  lib/maths/analytics/CBoostedTreeHyperparameters.cc
  lib/maths/analytics/CBoostedTreeImpl.cc
  lib/maths/analytics/CDataFrameUtils.cc
Labels: >non-issue, :ml/DataFrameAnalysis

#2306 [ML] Fix flaky test
  include/core/CStaticThreadPool.h
  lib/core/CStaticThreadPool.cc
  lib/core/unittest/CStaticThreadPoolTest.cc
Labels: review, >non-issue, >test, v8.4.0

#2310 [ML] Determine default value for cmake toolchain file
  CMakeLists.txt
  lib/ver/CMakeLists.txt
Labels: review, >non-issue, :ml

#2307 [ML] Updating CMake Docker config to build new official images
  .dockerignore
  .gitignore
  CONTRIBUTING.md
  build-setup/linux.md
  build-setup/linux_aarch64_cross_compiled.md
  build-setup/macos.md
  build-setup/macos_cross_compiled.md
  build-setup/windows.md
  build-setup/windows_simple.md
  build.gradle
  dev-tools/docker/build_linux_aarch64_cross_build_image.sh
  dev-tools/docker/build_linux_aarch64_native_build_image.sh
  dev-tools/docker/build_linux_build_image.sh
  dev-tools/docker/build_macosx_build_image.sh
  dev-tools/docker/linux_aarch64_cross_builder/Dockerfile
  dev-tools/docker/linux_aarch64_cross_image/Dockerfile
  dev-tools/docker/linux_aarch64_native_builder/Dockerfile
  dev-tools/docker/linux_aarch64_native_image/Dockerfile
  dev-tools/docker/linux_aarch64_native_tester/Dockerfile
  dev-tools/docker/linux_builder/Dockerfile
  dev-tools/docker/linux_image/Dockerfile
  dev-tools/docker/linux_tester/Dockerfile
  dev-tools/docker/macosx_builder/Dockerfile
  dev-tools/docker/macosx_image/Dockerfile
Labels: >build, >non-issue, :ml

#2309 [ML] Address outstanding TODOs on incremental training branch
  lib/maths/analytics/unittest/CBoostedTreeLossTest.cc
Labels: >non-issue, :ml/DataFrameAnalysis

#2313 [ML] Portability improvements
  3rd_party/CMakeLists.txt
  3rd_party/pull-eigen.cmake
  build.gradle
  cmake/compiler/vs2019.cmake
  cmake/variables.cmake
  lib/api/CMakeLists.txt
  lib/core/CMakeLists.txt
  lib/maths/analytics/CMakeLists.txt
  lib/maths/common/CMakeLists.txt
  lib/maths/time_series/CMakeLists.txt
  lib/model/CMakeLists.txt
  lib/test/CMakeLists.txt
  lib/ver/CMakeLists.txt
  test/CMakeLists.txt
Labels: review, >build, >non-issue, :ml

#2314 [ML] Fix edge cases for early stopping for training classification and regression models
  include/maths/analytics/CBoostedTreeHyperparameters.h
  include/maths/common/CLinearAlgebraEigen.h
  lib/maths/analytics/CBoostedTreeFactory.cc
  lib/maths/analytics/CBoostedTreeHyperparameters.cc
Labels: review, >non-issue, :ml/DataFrameAnalysis, v8.4.0

#2318 [ML] External master -> main renames
  dev-tools/mlcpp-release-notes.pl
  dev-tools/run_es_tests.sh
Labels: >build, >non-issue, :ml, v8.4.0

#2312 [ML] Write test output to files
  cmake/functions.cmake
  cmake/test-check-success.cmake
  cmake/test-clean-results.cmake
  cmake/test-runner.cmake
  lib/ver/CMakeLists.txt
  test/CMakeLists.txt
Labels: review, >build, >non-issue, :ml

#2320 [ML] Add additional incremental_training files
  jupyter/docker/Dockerfile
  lib/api/CMakeLists.txt
  lib/api/unittest/CMakeLists.txt
  lib/maths/analytics/CMakeLists.txt
  lib/maths/analytics/unittest/CMakeLists.txt
Labels: review, >build, >non-issue, :ml

#2323 [ML] Dynamically determine VCVER in 3rd_party.cmake
  3rd_party/3rd_party.cmake
Labels: review, >build, >non-issue, :ml

#2326 [ML] Fix JSON writer assertion
  lib/api/unittest/CSerializableToJsonTest.cc
Labels: >non-issue, >test, :ml/DataFrameAnalysis, v8.4.0

#2325 [ML] Fix edge case early stopping when parameters are fixed during coarse tuning
  include/maths/analytics/CBoostedTreeFactory.h
  include/maths/analytics/CBoostedTreeHyperparameters.h
  include/maths/common/CBayesianOptimisation.h
  lib/api/CDataFrameTrainBoostedTreeRunner.cc
  lib/maths/analytics/CBoostedTreeFactory.cc
  lib/maths/analytics/CBoostedTreeHyperparameters.cc
  lib/maths/analytics/CBoostedTreeImpl.cc
  lib/maths/analytics/unittest/CBoostedTreeTest.cc
  lib/maths/common/CBayesianOptimisation.cc
Labels: review, >non-issue, :ml/DataFrameAnalysis, v8.4.0

#2327 [ML] Fix cross compilation for Linux aarch64 using CMake
  3rd_party/3rd_party.cmake
  cmake/functions.cmake
  cmake/linux-aarch64.cmake
Labels: >build, >non-issue, :ml, v8.4.0

#2331 [ML] Add CMake targets for "dev only" binaries
  CMakeLists.txt
  cmake/functions.cmake
  devbin/CMakeLists.txt
  devbin/analyze_test/CMakeLists.txt
  devbin/model_extractor/CMakeLists.txt
  devbin/move_copy_swap/CMakeLists.txt
  devbin/state_search_splitter/CMakeLists.txt
  devbin/unixtime_to_string/CMakeLists.txt
  devbin/vfprog/CMakeLists.txt
  devbin/vsbug/CMakeLists.txt
  devlib/CMakeLists.txt
  devlib/vflib/CMakeLists.txt
Labels: review, >build, >non-issue, :ml

#2329 [ML] Alter build.gradle to allow for native windows builds
  build.gradle
  cmake/clang-format.cmake
  set_env.bat
Labels: review, >build, >non-issue, :ml

#2336 [ML] Manually set RPATH linker flags for MacOS cross compilation builds
  3rd_party/3rd_party.cmake
  cmake/functions.cmake
  lib/ver/CMakeLists.txt
Labels: review, >build, >non-issue, :ml

#2332 [ML] Address some bottlenecks training classification and regression models on large data sets
  docs/CHANGELOG.asciidoc
  include/maths/analytics/CDataFrameUtils.h
  include/maths/common/CBasicStatistics.h
  include/maths/common/CQuantileSketch.h
  jupyter/scripts/incremental_learning/origin/experiment_driver.py
  jupyter/src/incremental_learning/job.py
  lib/api/unittest/CDataFrameAnalyzerFeatureImportanceTest.cc
  lib/maths/analytics/CBoostedTreeFactory.cc
  lib/maths/analytics/CBoostedTreeImpl.cc
  lib/maths/analytics/CDataFrameUtils.cc
  lib/maths/analytics/unittest/CBoostedTreeTest.cc
  lib/maths/analytics/unittest/CDataFrameUtilsTest.cc
  lib/maths/common/CBasicStatistics.cc
  lib/maths/common/CQuantileSketch.cc
  lib/maths/common/unittest/CBasicStatisticsTest.cc
  lib/maths/common/unittest/CQuantileSketchTest.cc
  lib/maths/time_series/CCalendarCyclicTest.cc
  lib/maths/time_series/unittest/CCalendarCyclicTestTest.cc
Labels: >enhancement, review, :ml/DataFrameAnalysis, v8.4.0

#2338 [ML] Only set CMAKE_SYSTEM_NAME when cross compiling
  cmake/darwin-aarch64.cmake
  cmake/darwin-x86_64.cmake
  cmake/functions.cmake
  cmake/linux-aarch64.cmake
  cmake/linux-x86_64.cmake
Labels: review, >build, >non-issue, :ml

#2339 [ML] Bootstrap estimate sample error in the test loss for training classification and regression models
  include/core/CPersistUtils.h
  include/maths/analytics/CBoostedTreeHyperparameters.h
  include/maths/analytics/CBoostedTreeImpl.h
  include/maths/common/CBayesianOptimisation.h
  include/maths/common/CChecksum.h
  include/maths/common/CSampling.h
  lib/core/unittest/CPersistUtilsTest.cc
  lib/maths/analytics/CBoostedTreeFactory.cc
  lib/maths/analytics/CBoostedTreeHyperparameters.cc
  lib/maths/analytics/CBoostedTreeImpl.cc
  lib/maths/analytics/unittest/CBoostedTreeHyperparametersTest.cc
  lib/maths/analytics/unittest/CBoostedTreeTest.cc
  lib/maths/common/CBayesianOptimisation.cc
  lib/maths/common/CSampling.cc
  lib/maths/common/unittest/CBayesianOptimisationTest.cc
Labels: >enhancement, review, >non-issue, :ml/DataFrameAnalysis, v8.4.0
