Repository elastic/ml-cpp, pull requests merged in 2022-09, with the labels that each got.

#2398 [ML] Don't keep categorization tokens when existing category matches
  docs/CHANGELOG.asciidoc
  include/model/CTokenListDataCategorizerBase.h
  lib/model/CTokenListDataCategorizerBase.cc
  lib/model/unittest/CTokenListDataCategorizerTest.cc
Labels: >bug, :ml, v8.5.0, v7.17.7, v8.4.2

#2256 [ML] Improvements to the outlier influence calculation
  docs/CHANGELOG.asciidoc
  include/maths/analytics/COutliers.h
  include/maths/common/CLinearAlgebra.h
  include/maths/common/CLinearAlgebraEigen.h
  include/maths/common/CLinearAlgebraFwd.h
  include/maths/common/CLinearAlgebraShims.h
  lib/api/unittest/CDataFrameAnalyzerOutlierTest.cc
  lib/maths/analytics/COutliers.cc
  lib/maths/analytics/unittest/COutliersTest.cc
Labels: >enhancement, review, :ml/DataFrameAnalysis, v8.5.0

#2399 [8.4] [ML] Don't keep categorization tokens when existing category matches
  docs/CHANGELOG.asciidoc
  include/model/CTokenListDataCategorizerBase.h
  lib/model/CTokenListDataCategorizerBase.cc
  lib/model/unittest/CTokenListDataCategorizerTest.cc
Labels: backport, v8.4.2

#2397 [ML] Tidy up utility functions using parameter packs
  include/maths/analytics/CBoostedTreeLeafNodeStatistics.h
  include/maths/common/CBootstrapClusterer.h
  include/maths/common/CLowessDetail.h
  include/maths/common/COrderings.h
  include/maths/common/COrderingsSimultaneousSort.h
  include/maths/common/CSetTools.h
  include/maths/common/CSphericalCluster.h
  include/maths/common/CXMeans.h
  include/maths/common/CXMeansOnline.h
  include/maths/time_series/CSignal.h
  include/model/CHierarchicalResults.h
  include/model/CSampleQueue.h
  lib/maths/analytics/CBoostedTreeImpl.cc
  lib/maths/analytics/CBoostedTreeLeafNodeStatistics.cc
  lib/maths/analytics/CDataFrameUtils.cc
  lib/maths/analytics/CTreeShapFeatureImportance.cc
  lib/maths/analytics/unittest/CBoostedTreeTest.cc
  lib/maths/analytics/unittest/CDataFrameUtilsTest.cc
  lib/maths/common/CAgglomerativeClusterer.cc
  lib/maths/common/CBayesianOptimisation.cc
  lib/maths/common/CKMostCorrelated.cc
  lib/maths/common/COrderings.cc
  lib/maths/common/CQuantileSketch.cc
  lib/maths/common/CSampling.cc
  lib/maths/common/unittest/CBootstrapClustererTest.cc
  lib/maths/common/unittest/COrderingsTest.cc
  lib/maths/common/unittest/CPriorTest.cc
  lib/maths/common/unittest/CSetToolsTest.cc
  lib/maths/common/unittest/CXMeansOnlineTest.cc
  lib/maths/time_series/CCalendarFeature.cc
  lib/maths/time_series/CTimeSeriesDecompositionDetail.cc
  lib/maths/time_series/CTimeSeriesModel.cc
  lib/maths/time_series/CTimeSeriesSegmentation.cc
  lib/maths/time_series/CTimeSeriesTestForSeasonality.cc
  lib/model/CAnnotatedProbability.cc
  lib/model/CBucketGatherer.cc
  lib/model/CHierarchicalResults.cc
  lib/model/CMetricBucketGatherer.cc
  lib/model/CProbabilityAndInfluenceCalculator.cc
  lib/model/unittest/CHierarchicalResultsTest.cc
  lib/model/unittest/CModelTestFixtureBase.h
Labels: review, >non-issue, :ml, >refactoring, v8.5.0

#2400 [7.17] [ML] Don't keep categorization tokens when existing category matches
  docs/CHANGELOG.asciidoc
  include/model/CTokenListDataCategorizerBase.h
  lib/model/CTokenListDataCategorizerBase.cc
  lib/model/unittest/CTokenListDataCategorizerTest.cc
Labels: backport, v7.17.7

#2402 [ML] Add missing Windows export
  include/maths/common/COrderings.h
Labels: >non-issue, :ml, v8.5.0

#2401 [ML] Improve efficiency of categorical sample without replacement
  docs/CHANGELOG.asciidoc
  lib/maths/analytics/CBoostedTreeImpl.cc
  lib/maths/analytics/unittest/CBoostedTreeTest.cc
  lib/maths/common/CSampling.cc
  lib/maths/common/unittest/CKMostCorrelatedTest.cc
  lib/maths/common/unittest/CSamplingTest.cc
Labels: >enhancement, review, :ml/DataFrameAnalysis, v8.5.0

#2404 [ML] Fix seed parameter name
  lib/api/CDataFrameTrainBoostedTreeRunner.cc
Labels: >non-issue, :ml, v8.6.0

#2406 [ML] Fix failure computing leaf values with multithreading for multi-class classification
  include/maths/common/CSampling.h
  include/maths/time_series/CTimeSeriesDecompositionDetail.h
  lib/maths/analytics/CBoostedTreeFactory.cc
  lib/maths/analytics/CBoostedTreeLoss.cc
  lib/maths/analytics/unittest/CBoostedTreeTest.cc
  lib/maths/common/unittest/CSamplingTest.cc
Labels: >non-issue, :ml/DataFrameAnalysis, v8.5.0, v8.6.0

#2408 [ML] Fix failure computing leaf values with multithreading for multi-class classification
  include/maths/common/CSampling.h
  include/maths/time_series/CTimeSeriesDecompositionDetail.h
  lib/maths/analytics/CBoostedTreeFactory.cc
  lib/maths/analytics/CBoostedTreeLoss.cc
  lib/maths/analytics/unittest/CBoostedTreeTest.cc
  lib/maths/common/unittest/CSamplingTest.cc
Labels: >non-issue, backport, v8.5.0

#2407 [ML] Change randomize_seed parameter type
  lib/api/CDataFrameTrainBoostedTreeRunner.cc
Labels: >non-issue, :ml, v8.6.0

#2410 [ML] Fix for 'No statistics' error message
  devbin/model_extractor/Main.cc
  docs/CHANGELOG.asciidoc
  lib/model/CIndividualModel.cc
  lib/model/CMetricModel.cc
Labels: >bug, review, :ml, v8.6.0
