Repository elastic/ml-cpp, pull requests merged in 2022-11, with the labels that each got.

#2414 [ML] Fix for "No counts available" error message
  docs/CHANGELOG.asciidoc
  include/api/CAnomalyJob.h
  lib/api/CAnomalyJob.cc
  lib/api/unittest/CAnomalyJobTest.cc
  lib/api/unittest/testfiles/incomplete_initial_bucket.txt
  lib/api/unittest/testfiles/pop_sum_bytes_by_status_over_clientip.json
Labels: >bug, review, :ml, v8.6.0

#2415 [ML] Fix anomaly length computation
  lib/maths/time_series/CTimeSeriesModel.cc
Labels: >non-issue, :ml/DataFrameAnalysis, v8.6.0

#2417 [ML] Fix license info file extension
  3rd_party/licenses/MKL-INFO.csv
Labels: >non-issue, :ml, 3rd party models, v8.6.0, v8.5.1

#2418 [8.5] [ML] Fix license info file extension
  3rd_party/licenses/MKL-INFO.csv
Labels: >non-issue, backport, v8.5.1

#2419 [ML] Reanable confidence bounds computation
  lib/maths/time_series/CTimeSeriesModel.cc
Labels: >non-issue, :ml, v8.6.0

#2420 [ML] Fix 3rd party license sort order and make MKL more searchable
  3rd_party/licenses/MKL-INFO.csv
  3rd_party/licenses/intel-mkl-INFO.csv
  3rd_party/licenses/intel-mkl-LICENSE.txt
  3rd_party/licenses/intel-mkl-NOTICE.txt
Labels: >non-issue, :ml, 3rd party models, v8.6.0, v8.5.1

#2421 [8.5] [ML] Fix 3rd party license sort order and make MKL more searchable
  3rd_party/licenses/MKL-INFO.csv
  3rd_party/licenses/intel-mkl-INFO.csv
  3rd_party/licenses/intel-mkl-LICENSE.txt
  3rd_party/licenses/intel-mkl-NOTICE.txt
Labels: >non-issue, backport, v8.5.1
