Repository elastic/ml-cpp, pull requests merged in 2022-03, with the labels that each got.

#1584 [ML] Correct the test to select the trend model to use to forecast
  include/maths/common/CStatisticalTests.h
  lib/maths/common/CStatisticalTests.cc
  lib/maths/time_series/CTimeSeriesDecompositionDetail.cc
  lib/maths/time_series/CTrendComponent.cc
Labels: review, >non-issue, :ml, affects-results, v8.2.0

#2224 Use deps and nodeps archives for project artifacts
  build.gradle
  dev-tools/docker/docker_entrypoint.sh
  dev-tools/jenkins_ci.sh
Labels: >build, >non-issue, v8.2.0

#2222 [ML] Support example weights in classification and regression model training
  docs/CHANGELOG.asciidoc
  include/api/CDataFrameTrainBoostedTreeRunner.h
  include/maths/analytics/CBoostedTreeFactory.h
  include/maths/analytics/CBoostedTreeImpl.h
  include/maths/analytics/CBoostedTreeUtils.h
  lib/api/CDataFrameTrainBoostedTreeRunner.cc
  lib/maths/analytics/CBoostedTreeFactory.cc
  lib/maths/analytics/CBoostedTreeImpl.cc
  lib/maths/analytics/unittest/CBoostedTreeTest.cc
Labels: >enhancement, review, :ml/DataFrameAnalysis, v8.2.0

#2225 [ML] Speedup finding change points in the time series trend
  docs/CHANGELOG.asciidoc
  include/maths/common/CBasicStatistics.h
  include/maths/common/CLeastSquaresOnlineRegression.h
  include/maths/common/CLeastSquaresOnlineRegressionDetail.h
  include/maths/time_series/CTimeSeriesSegmentation.h
  lib/maths/common/unittest/CLeastSquaresOnlineRegressionTest.cc
  lib/maths/time_series/CTimeSeriesSegmentation.cc
Labels: >enhancement, review, :ml, v8.2.0

#2229 [ML] Better handling of low cardinality features for training classification and regression models
  docs/CHANGELOG.asciidoc
  include/maths/analytics/CBoostedTreeImpl.h
  lib/maths/analytics/CBoostedTreeFactory.cc
  lib/maths/analytics/CBoostedTreeImpl.cc
  lib/maths/analytics/unittest/CBoostedTreeTest.cc
Labels: >enhancement, :ml/DataFrameAnalysis, v8.2.0

#2230 [ML] Better handling of extreme outliers in time series modelling
  docs/CHANGELOG.asciidoc
  include/maths/time_series/CSignal.h
  include/maths/time_series/CTimeSeriesTestForSeasonality.h
  lib/maths/time_series/CSignal.cc
  lib/maths/time_series/CTimeSeriesDecompositionDetail.cc
  lib/maths/time_series/CTimeSeriesTestForChange.cc
  lib/maths/time_series/CTimeSeriesTestForSeasonality.cc
  lib/maths/time_series/unittest/CSignalTest.cc
Labels: >enhancement, review, :ml, affects-results, v8.2.0

#2232 [ML] Allow on-the-fly adjustment of the number of threads in use
  include/core/CStaticThreadPool.h
  lib/core/CStaticThreadPool.cc
  lib/core/unittest/CStaticThreadPoolTest.cc
Labels: review, >non-issue, v8.2.0

#2236 [ML] Improve calendar component test
  docs/CHANGELOG.asciidoc
  include/maths/time_series/CCalendarComponent.h
  include/maths/time_series/CCalendarComponentAdaptiveBucketing.h
  include/maths/time_series/CCalendarCyclicTest.h
  include/maths/time_series/CCalendarFeature.h
  include/maths/time_series/CTimeSeriesDecompositionDetail.h
  lib/maths/time_series/CCalendarComponent.cc
  lib/maths/time_series/CCalendarComponentAdaptiveBucketing.cc
  lib/maths/time_series/CCalendarCyclicTest.cc
  lib/maths/time_series/CCalendarFeature.cc
  lib/maths/time_series/CTimeSeriesDecompositionDetail.cc
  lib/maths/time_series/unittest/CCalendarComponentAdaptiveBucketingTest.cc
  lib/maths/time_series/unittest/CCalendarComponentTest.cc
  lib/maths/time_series/unittest/CCalendarCyclicTestTest.cc
  lib/maths/time_series/unittest/CSeasonalComponentTest.cc
  lib/maths/time_series/unittest/Makefile
Labels: review, :ml, affects-results, v8.2.0

#2242 [ML] Fix cause of log error
  lib/maths/time_series/CCalendarCyclicTest.cc
Labels: review, >non-issue, :ml, v8.2.0

#2243 [ML] Speedup detection of calendar components
  docs/CHANGELOG.asciidoc
  include/maths/time_series/CCalendarCyclicTest.h
  lib/maths/time_series/CCalendarCyclicTest.cc
  lib/maths/time_series/CTimeSeriesDecompositionDetail.cc
Labels: >enhancement, review, :ml, affects-results, v8.2.0

#2233 [ML] Upgrade to PyTorch 1.11 on Windows
  build-setup/windows.md
  dev-tools/download_windows_deps.ps1
Labels: >build, >non-issue, :ml, 3rd party models, v8.3.0

#2235 [ML] Upgrade to PyTorch 1.11 on macOS
  build-setup/macos.md
  dev-tools/docker/build_macosx_build_image.sh
  dev-tools/docker/macosx_builder/Dockerfile
  dev-tools/docker/macosx_image/Dockerfile
  dev-tools/download_macos_deps.sh
Labels: >build, >non-issue, :ml, 3rd party models, v8.3.0

#2238 [ML] Upgrade to PyTorch 1.11 on Linux
  3rd_party/3rd_party.sh
  3rd_party/licenses/pytorch-INFO.csv
  build-setup/linux.md
  dev-tools/docker/build_linux_aarch64_cross_build_image.sh
  dev-tools/docker/build_linux_aarch64_native_build_image.sh
  dev-tools/docker/build_linux_build_image.sh
  dev-tools/docker/linux_aarch64_cross_builder/Dockerfile
  dev-tools/docker/linux_aarch64_cross_image/Dockerfile
  dev-tools/docker/linux_aarch64_native_builder/Dockerfile
  dev-tools/docker/linux_aarch64_native_image/Dockerfile
  dev-tools/docker/linux_aarch64_native_tester/Dockerfile
  dev-tools/docker/linux_builder/Dockerfile
  dev-tools/docker/linux_image/Dockerfile
  dev-tools/docker/linux_tester/Dockerfile
  docs/CHANGELOG.asciidoc
Labels: >build, :ml, 3rd party models, v8.3.0

#2234 [ML] Generate encoding without training
  include/api/CDataFrameTrainBoostedTreeRunner.h
  include/maths/analytics/CBoostedTreeFactory.h
  include/maths/analytics/CBoostedTreeImpl.h
  jupyter/src/.bumpversion.cfg
  jupyter/src/incremental_learning/__init__.py
  jupyter/src/incremental_learning/job.py
  jupyter/src/setup.py
  jupyter/tests/incremental_learning/test_regression.py
  lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
  lib/api/CDataFrameTrainBoostedTreeRegressionRunner.cc
  lib/api/CDataFrameTrainBoostedTreeRunner.cc
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
  lib/maths/analytics/CBoostedTreeFactory.cc
  lib/maths/analytics/unittest/CBoostedTreeTest.cc
  lib/test/CDataFrameAnalysisSpecificationFactory.cc
Labels: >non-issue, :ml/DataFrameAnalysis

#2248 [ML] Don't use moved from variable
  lib/maths/analytics/CBoostedTreeHyperparameters.cc
  lib/maths/analytics/unittest/CBoostedTreeTest.cc
Labels: >bug, review, >non-issue, :ml/DataFrameAnalysis, v8.3.0

#2250 [ML] Fix test
  build-setup/clion/using_clion.md
  lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
Labels: >bug, review, >non-issue, >test, :ml/DataFrameAnalysis, v8.3.0

#2251 [ML] Correct restart from failure when fine tuning classification and regression models
  docs/CHANGELOG.asciidoc
  include/maths/analytics/CBoostedTreeHyperparameters.h
  lib/maths/analytics/CBoostedTreeHyperparameters.cc
  lib/maths/analytics/CBoostedTreeImpl.cc
Labels: >bug, review, :ml/DataFrameAnalysis, v8.3.0
