Repository elastic/ml-cpp, pull requests merged in 2022-10, with the labels that each got.

#2396 [ML] Explain anomalies
  include/api/CHierarchicalResultsWriter.h
  include/api/CJsonOutputWriter.h
  include/maths/common/CModel.h
  include/model/CAnnotatedProbability.h
  include/model/CAnnotatedProbabilityBuilder.h
  include/model/CProbabilityAndInfluenceCalculator.h
  lib/api/CHierarchicalResultsWriter.cc
  lib/api/CJsonOutputWriter.cc
  lib/api/unittest/CJsonOutputWriterTest.cc
  lib/maths/time_series/CTimeSeriesModel.cc
  lib/model/CAnnotatedProbability.cc
  lib/model/CAnnotatedProbabilityBuilder.cc
  lib/model/CEventRateModel.cc
  lib/model/CEventRatePopulationModel.cc
  lib/model/CMetricModel.cc
  lib/model/CProbabilityAndInfluenceCalculator.cc
Labels: review, >non-issue, :ml, v8.6.0

#2412 [ML] Add option to run pytorch_inference in low priority
  bin/pytorch_inference/CCmdLineParser.cc
  bin/pytorch_inference/CCmdLineParser.h
  bin/pytorch_inference/Main.cc
  bin/pytorch_inference/evaluate.py
Labels: >non-issue, :ml, 3rd party models, v8.6.0

#2413 [ML] Deactivate confidence bounds computation
  lib/maths/time_series/CTimeSeriesModel.cc
Labels: >non-issue, v8.6.0
