Repository elastic/ml-cpp, pull requests merged in 2022-12, with the labels that each got.

#2424 [ML] Improve performance of closing files before spawning
  docs/CHANGELOG.asciidoc
  include/core/CDetachedProcessSpawner.h
  lib/core/CDetachedProcessSpawner.cc
Labels: >bug, :ml, v8.6.0, v7.17.9, v8.7.0

#2426 [8.6] [ML] Improve performance of closing files before spawning
  docs/CHANGELOG.asciidoc
  include/core/CDetachedProcessSpawner.h
  lib/core/CDetachedProcessSpawner.cc
Labels: backport, v8.6.0

#2428 [ML] Use rapidjson's key function where possible
  lib/api/CJsonOutputWriter.cc
  lib/api/CModelSnapshotJsonWriter.cc
  lib/core/CJsonLogLayout.cc
  lib/core/CMemoryUsageJsonWriter.cc
  lib/core/CProgramCounters.cc
Labels: :ml, >refactoring, v8.7.0
