Repository elastic/ml-cpp, pull requests merged in 2022-04, with the labels that each got.

#2252 [ML] Compress quantiles for persistence
  docs/CHANGELOG.asciidoc
  include/model/CAnomalyScore.h
  lib/model/CAnomalyScore.cc
  lib/model/CHierarchicalResultsNormalizer.cc
  lib/model/Makefile
  lib/model/unittest/CAnomalyScoreTest.cc
  lib/model/unittest/CHierarchicalResultsTest.cc
  lib/model/unittest/Makefile
Labels: >enhancement, :ml, v8.2.0, v8.3.0

#2253 [ML] Upgrade to zlib 1.2.12 on Windows
  3rd_party/licenses/zlib-INFO.csv
  build-setup/windows.md
  dev-tools/download_windows_deps.ps1
  docs/CHANGELOG.asciidoc
Labels: >enhancement, :ml, v8.3.0

#2254 [8.2] [ML] Compress quantiles for persistence
  docs/CHANGELOG.asciidoc
  include/model/CAnomalyScore.h
  lib/model/CAnomalyScore.cc
  lib/model/CHierarchicalResultsNormalizer.cc
  lib/model/Makefile
  lib/model/unittest/CAnomalyScoreTest.cc
  lib/model/unittest/CHierarchicalResultsTest.cc
  lib/model/unittest/Makefile
Labels: backport, v8.2.0

#2249 [ML] Numerical robustness improvements for Bayesian Optimisation
  docs/CHANGELOG.asciidoc
  lib/maths/analytics/unittest/CDataFrameUtilsTest.cc
  lib/maths/common/CBayesianOptimisation.cc
Labels: >bug, review, :ml/DataFrameAnalysis, v8.3.0

#2259 [ML] Some corrections to ANOVA for Bayesian Optimisation
  docs/CHANGELOG.asciidoc
  include/maths/common/CBayesianOptimisation.h
  lib/maths/analytics/unittest/CBoostedTreeTest.cc
  lib/maths/common/CBayesianOptimisation.cc
  lib/maths/common/unittest/CBayesianOptimisationTest.cc
Labels: >bug, review, :ml/DataFrameAnalysis, v8.3.0
