Repository elastic/ml-cpp, pull requests merged in 2023-08, with the labels that each got.

#2554 [ML] Download Windows build dependencies from GCS
  dev-tools/download_windows_deps.ps1
Labels: >build, >non-issue, :ml, v8.10.0, v7.17.13, v8.9.2

#2552 [NLP] Respond to the server when an unknown command is received
  bin/pytorch_inference/Main.cc
Labels: >non-issue, 3rd party models, v8.10.0

#2556 [7.17][ML] Download Windows build dependencies from GCS (#2554)
  dev-tools/download_windows_deps.ps1
Labels: >build, >non-issue, :ml, backport, v7.17.13

#2557 [ML] Preparing for 8.10 feature freeze
  catalog-info.yaml
  gradle.properties
Labels: >build, >non-issue, :ml, v8.11.0

#2559 [Snyk] Security upgrade tornado from 6.2 to 6.3.3
  jupyter/requirements.txt
Labels: >non-issue, :ml, v8.11.0
