Repository elastic/ml-cpp, pull requests merged in 2023-09, with the labels that each got.

#2561 [Snyk] Security upgrade jupyter-server from 1.24.0 to 2.7.2
  jupyter/requirements.txt
Labels: >non-issue, :ml, v8.11.0

#2563 [ML] Include an extra header in CDataFrameRowSlice
  lib/core/CDataFrameRowSlice.cc
Labels: >non-issue, :ml, v8.11.0, v7.17.15, v8.10.1

#2565 [7.17] [ML] Include an extra header in CDataFrameRowSlice
  include/model/CStringStore.h
  lib/core/CDataFrameRowSlice.cc
Labels: >non-issue, :ml, backport

#2566 [ML] Treat Boost version as exact required, not minimum
  cmake/variables.cmake
Labels: >non-issue, :ml, v8.11.0, v8.10.1, v8.9.3

#2568 [8.9] [ML] Treat Boost version as exact required, not minimum
  cmake/variables.cmake
Labels: >non-issue, backport, v8.9.3

#2564 [8.10] [ML] Include an extra header in CDataFrameRowSlice
  include/model/CStringStore.h
  lib/core/CDataFrameRowSlice.cc
Labels: >non-issue, backport, v8.10.1

#2560 Upgrade to boost 1 83
  .buildkite/pipelines/build_linux.json.py
  .buildkite/pipelines/build_macos.json.py
  3rd_party/3rd_party.cmake
  3rd_party/licenses/boost-INFO.csv
  build-setup/linux.md
  build-setup/macos.md
  build-setup/windows.md
  cmake/functions.cmake
  cmake/variables.cmake
  dev-tools/docker/build_linux_aarch64_cross_build_image.sh
  dev-tools/docker/build_linux_aarch64_native_build_image.sh
  dev-tools/docker/build_linux_build_image.sh
  dev-tools/docker/build_macosx_build_image.sh
  dev-tools/docker/linux_aarch64_cross_builder/Dockerfile
  dev-tools/docker/linux_aarch64_cross_image/Dockerfile
  dev-tools/docker/linux_aarch64_native_builder/Dockerfile
  dev-tools/docker/linux_aarch64_native_image/Dockerfile
  dev-tools/docker/linux_aarch64_native_tester/Dockerfile
  dev-tools/docker/linux_builder/Dockerfile
  dev-tools/docker/linux_image/Dockerfile
  dev-tools/docker/linux_tester/Dockerfile
  dev-tools/docker/macosx_builder/Dockerfile
  dev-tools/docker/macosx_image/Dockerfile
  dev-tools/download_macos_deps.sh
  dev-tools/download_windows_deps.ps1
  include/api/CAnomalyJobConfig.h
  include/core/CCompressedLfuCache.h
  include/core/CMemoryDec.h
  include/core/CMemoryDef.h
  include/maths/common/CLbfgs.h
  include/model/CStringStore.h
  lib/api/CAnomalyJob.cc
  lib/api/CAnomalyJobConfig.cc
  lib/api/unittest/CAnomalyJobLimitTest.cc
  lib/api/unittest/CDataFrameAnalysisRunnerTest.cc
  lib/core/CDataFrame.cc
  lib/core/CNamedPipeFactory.cc
  lib/core/unittest/CCompressedLfuCacheTest.cc
  lib/core/unittest/CHashingTest.cc
  lib/maths/analytics/unittest/CDataFrameCategoryEncoderTest.cc
  lib/model/unittest/CEventRateModelTest.cc
  lib/model/unittest/CMetricAnomalyDetectorTest.cc
  lib/seccomp/CSystemCallFilter_Linux.cc
Labels: >build, >non-issue, :ml, dependencies, v8.11.0

#2570 [ML] Increase testMurmurHash slack factor to 8%
  lib/core/unittest/CHashingTest.cc
Labels: >non-issue, :ml, >test, v8.11.0

#2572 [ML] Add extra debug handling for the seccomp test.
  .buildkite/pipelines/build_linux.json.py
  .buildkite/pipelines/build_macos.json.py
  .buildkite/pipelines/build_windows.json.py
  cmake/test-runner.cmake
Labels: >non-issue, :ml, >test-failure, v8.11.0

#2576 [ML] Call readvalue even if cache write fails
  docs/CHANGELOG.asciidoc
  include/core/CCompressedLfuCache.h
Labels: >bug, :ml, v8.11.0, v8.10.3
