Repository elastic/ml-cpp, pull requests merged in 2023-05, with the labels that each got.

#2470 [ML] Add native MacOS aarch64 build support in BuildKite
  .buildkite/hooks/post-checkout
  .buildkite/pipelines/build_linux.json.py
  .buildkite/pipelines/build_macos.json.py
  .buildkite/pipelines/build_windows.json.py
  .buildkite/scripts/steps/build_and_test.sh
Labels: review, >build, >non-issue, :ml, v8.8.0, v7.17.11, v8.9.0

#2476 [8.8][ML] Add native MacOS aarch64 build support in BuildKite (#2470)
  .buildkite/hooks/post-checkout
  .buildkite/pipelines/build_linux.json.py
  .buildkite/pipelines/build_macos.json.py
  .buildkite/pipelines/build_windows.json.py
  .buildkite/scripts/steps/build_and_test.sh
Labels: >non-issue, :ml, backport, v8.8.0

#2477 [8.7][ML] Add native MacOS aarch64 build support in BuildKite (#2470)
  .buildkite/hooks/post-checkout
  .buildkite/pipelines/build_linux.json.py
  .buildkite/pipelines/build_macos.json.py
  .buildkite/pipelines/build_windows.json.py
  .buildkite/scripts/steps/build_and_test.sh
Labels: >non-issue, :ml, backport, v8.7.0

#2478 [7.17][ML] Add native MacOS aarch64 build support in BuildKite (#2470)
  .buildkite/hooks/post-checkout
  .buildkite/pipelines/build_linux.json.py
  .buildkite/pipelines/build_macos.json.py
  .buildkite/scripts/steps/build_and_test.sh
Labels: >non-issue, :ml, backport, v7.17.11

#2480 [ML] Fix Linux PATH in environment file
  set_env.sh
Labels: >build, >non-issue, :ml, v8.9.0

#2482 [8.8][ML] Make use of CI Vault's AWS secrets engine (#2474)
  .buildkite/scripts/common/aws_creds_from_vault.sh
  buildSrc/src/main/groovy/org/elastic/gradle/UploadS3Task.groovy
Labels: >build, >non-issue, :ml, backport, v8.8.0

#2483 [8.7][ML] Make use of CI Vault's AWS secrets engine (#2474)
  .buildkite/scripts/common/aws_creds_from_vault.sh
  buildSrc/src/main/groovy/org/elastic/gradle/UploadS3Task.groovy
Labels: >build, >non-issue, :ml, backport, v8.7.0

#2484 [7.17][ML] Make use of CI Vault's AWS secrets engine (#2474)
  .buildkite/scripts/common/aws_creds_from_vault.sh
  buildSrc/src/main/groovy/org/elastic/gradle/UploadS3Task.groovy
Labels: >build, >non-issue, :ml, backport, v7.17.11

#2486 [Snyk] Security upgrade tornado from 6.2 to 6.3.2
  jupyter/requirements.txt
Labels: >non-issue, :ml, v8.9.0

#2489 [ML] Upgrade to latest AWS SDK version
  buildSrc/build.gradle
  dev-tools/docker_build.sh
  dev-tools/docker_test.sh
Labels: >build, >non-issue, :ml, v7.17.11, v8.9.0, v8.8.1

#2490 [8.8] [ML] Upgrade to latest AWS SDK version
  buildSrc/build.gradle
  dev-tools/docker_build.sh
  dev-tools/docker_test.sh
Labels: >non-issue, backport, v8.8.1

#2491 [7.17] [ML] Upgrade to latest AWS SDK version
  buildSrc/build.gradle
  dev-tools/docker_build.sh
  dev-tools/docker_test.sh
Labels: >non-issue, backport, v7.17.11

#2487 [ML] retrieve real memory usage of pytorch inference
  bin/pytorch_inference/CCommandParser.cc
  bin/pytorch_inference/CCommandParser.h
  bin/pytorch_inference/CResultWriter.cc
  bin/pytorch_inference/CResultWriter.h
  bin/pytorch_inference/Main.cc
  bin/pytorch_inference/unittest/CCommandParserTest.cc
  bin/pytorch_inference/unittest/CResultWriterTest.cc
  include/core/CProcessStats.h
  lib/core/CMakeLists.txt
  lib/core/CProcessStats_Linux.cc
  lib/core/CProcessStats_MacOSX.cc
  lib/core/CProcessStats_Windows.cc
  lib/core/unittest/CMakeLists.txt
  lib/core/unittest/CProcessStatsTest_Linux.cc
  lib/core/unittest/CProcessStatsTest_MacOSX.cc
  lib/core/unittest/CProcessStatsTest_Windows.cc
Labels: >non-issue, :ml, v8.9.0

#2469 [ML] Prevent adding new seasonal and calendar components to comply with hard limit
  docs/CHANGELOG.asciidoc
  include/core/CMemoryCircuitBreaker.h
  include/maths/common/CModel.h
  include/maths/time_series/CTimeSeriesDecomposition.h
  include/maths/time_series/CTimeSeriesDecompositionDetail.h
  include/maths/time_series/CTimeSeriesDecompositionInterface.h
  include/maths/time_series/CTimeSeriesDecompositionStub.h
  include/maths/time_series/CTimeSeriesTestForSeasonality.h
  include/model/CAnomalyDetectorModel.h
  lib/core/CMakeLists.txt
  lib/core/CMemoryCircuitBreaker.cc
  lib/maths/common/CModel.cc
  lib/maths/time_series/CTimeSeriesDecomposition.cc
  lib/maths/time_series/CTimeSeriesDecompositionDetail.cc
  lib/maths/time_series/CTimeSeriesDecompositionStub.cc
  lib/maths/time_series/CTimeSeriesModel.cc
  lib/maths/time_series/CTimeSeriesTestForSeasonality.cc
  lib/maths/time_series/unittest/CMathsMemoryTest.cc
  lib/maths/time_series/unittest/CTimeSeriesDecompositionTest.cc
  lib/maths/time_series/unittest/CTimeSeriesModelTest.cc
  lib/model/CAnomalyDetectorModel.cc
  lib/model/CEventRateModel.cc
  lib/model/CEventRatePopulationModel.cc
  lib/model/CMetricModel.cc
  lib/model/CMetricPopulationModel.cc
Labels: >enhancement, :ml, affects-results, v8.9.0

#2497 [ML] Migrate to Backstage for BuildKite pipeline definitions
  .buildkite/dra.yml
  .buildkite/job-build-test-all-debug.yml
  .buildkite/pipeline.yml
  .buildkite/snapshot.yml
  .buildkite/staging.yml
  catalog-info.yaml
Labels: >build, >non-issue, :ml, v8.9.0
