Repository elastic/ml-cpp, pull requests merged in 2023-11, with the labels that each got.

#2591 [ML] Improve forecasting for time series with step changes
  docs/CHANGELOG.asciidoc
  include/maths/common/CNaiveBayes.h
  lib/core/CStateRestoreTraverser.cc
  lib/maths/common/CNaiveBayes.cc
  lib/maths/common/unittest/CLbfgsTest.cc
  lib/maths/common/unittest/CNaiveBayesTest.cc
  lib/maths/time_series/CTrendComponent.cc
  lib/maths/time_series/unittest/CTrendComponentTest.cc
  lib/model/unittest/CMetricDataGathererTest.cc
  lib/model/unittest/CMetricPopulationDataGathererTest.cc
  lib/model/unittest/CResourceMonitorTest.cc
Labels: >enhancement, :ml, v8.12.0

#2594 [ML] Python module version updates
  jupyter/requirements.txt
Labels: >non-issue, :ml, v8.12.0

#2593 [7.17][ML] Improve forecasting for time series with step changes (#2591)
  docs/CHANGELOG.asciidoc
  include/maths/common/CNaiveBayes.h
  lib/core/CStateRestoreTraverser.cc
  lib/maths/common/CNaiveBayes.cc
  lib/maths/common/unittest/CLbfgsTest.cc
  lib/maths/common/unittest/CNaiveBayesTest.cc
  lib/maths/time_series/CTrendComponent.cc
  lib/maths/time_series/unittest/CTrendComponentTest.cc
  lib/model/unittest/CMetricDataGathererTest.cc
  lib/model/unittest/CMetricPopulationDataGathererTest.cc
  lib/model/unittest/CResourceMonitorTest.cc
Labels: backport, v7.17.16

#2596 [ML] Set QAF_TESTS_TO_RUN to ml_cpp_pr
  .buildkite/pipelines/run_qa_tests.yml.sh
Labels: >build, >non-issue, :ml, v8.12.0

#2597 [8.11][ML] Improve forecasting for time series with step changes
  docs/CHANGELOG.asciidoc
  include/maths/common/CNaiveBayes.h
  lib/core/CStateRestoreTraverser.cc
  lib/maths/common/CNaiveBayes.cc
  lib/maths/common/unittest/CLbfgsTest.cc
  lib/maths/common/unittest/CNaiveBayesTest.cc
  lib/maths/time_series/CTrendComponent.cc
  lib/maths/time_series/unittest/CTrendComponentTest.cc
  lib/model/unittest/CMetricDataGathererTest.cc
  lib/model/unittest/CMetricPopulationDataGathererTest.cc
  lib/model/unittest/CResourceMonitorTest.cc
Labels: backport, v8.11.2

#2598 [ML] Update release notes following extra backport of #2597
  docs/CHANGELOG.asciidoc
Labels: :ml, >docs, v8.12.0
