Repository elastic/ml-cpp, pull requests merged in 2023-10, with the labels that each got.

#2577 [ML] Call readvalue even if cache write fails
  docs/CHANGELOG.asciidoc
  include/core/CCompressedLfuCache.h
Labels: >bug, :ml, backport, v8.10.3

#2581 [ML] Add a release note for Boost 1.83 upgrade
  docs/CHANGELOG.asciidoc
Labels: >enhancement, :ml, v8.12.0

#2575 [ML] Removing assertion on murmur hash lookup performance
  lib/core/unittest/CHashingTest.cc
Labels: >non-issue, :ml, v8.12.0

#2580 [ML] Revert Boost 1.83 upgrade for 8.11
  .buildkite/pipelines/build_linux.json.py
  .buildkite/pipelines/build_macos.json.py
  3rd_party/3rd_party.cmake
  3rd_party/licenses/boost-INFO.csv
  build-setup/linux.md
  build-setup/macos.md
  build-setup/windows.md
  cmake/functions.cmake
  cmake/variables.cmake
  dev-tools/docker/build_linux_aarch64_cross_build_image.sh
  dev-tools/docker/build_linux_aarch64_native_build_image.sh
  dev-tools/docker/build_linux_build_image.sh
  dev-tools/docker/build_macosx_build_image.sh
  dev-tools/docker/linux_aarch64_cross_builder/Dockerfile
  dev-tools/docker/linux_aarch64_cross_image/Dockerfile
  dev-tools/docker/linux_aarch64_native_builder/Dockerfile
  dev-tools/docker/linux_aarch64_native_image/Dockerfile
  dev-tools/docker/linux_aarch64_native_tester/Dockerfile
  dev-tools/docker/linux_builder/Dockerfile
  dev-tools/docker/linux_image/Dockerfile
  dev-tools/docker/linux_tester/Dockerfile
  dev-tools/docker/macosx_builder/Dockerfile
  dev-tools/docker/macosx_image/Dockerfile
  dev-tools/download_macos_deps.sh
  dev-tools/download_windows_deps.ps1
  include/api/CAnomalyJobConfig.h
  include/core/CCompressedLfuCache.h
  include/core/CMemoryDec.h
  include/core/CMemoryDef.h
  include/maths/common/CLbfgs.h
  include/model/CStringStore.h
  lib/api/CAnomalyJob.cc
  lib/api/CAnomalyJobConfig.cc
  lib/api/unittest/CAnomalyJobLimitTest.cc
  lib/api/unittest/CDataFrameAnalysisRunnerTest.cc
  lib/core/CDataFrame.cc
  lib/core/CNamedPipeFactory.cc
  lib/core/unittest/CCompressedLfuCacheTest.cc
  lib/core/unittest/CHashingTest.cc
  lib/maths/analytics/unittest/CDataFrameCategoryEncoderTest.cc
  lib/model/unittest/CEventRateModelTest.cc
  lib/model/unittest/CMetricAnomalyDetectorTest.cc
  lib/seccomp/CSystemCallFilter_Linux.cc
Labels: >non-issue, :ml, v8.11.0

#2579 [ML] Preparing for 8.11 feature freeze
  catalog-info.yaml
  gradle.properties
Labels: >build, >non-issue, :ml, v8.12.0

#2582 [ML] Remove inaccurate log message
  include/core/CCompressedLfuCache.h
Labels: >non-issue, :ml, v8.11.0, v8.12.0, v8.10.4

#2583 [ML] Remove inaccurate log message (#2582)
  include/core/CCompressedLfuCache.h
Labels: >non-issue, :ml, backport, v8.11.0

#2584 [ML] Remove inaccurate log message (#2582)
  include/core/CCompressedLfuCache.h
Labels: >non-issue, :ml, backport, v8.10.4

#2585 [ML] Adjust memory calculations for unordered containers
  include/core/CMemoryDec.h
  include/core/CMemoryDef.h
  lib/api/unittest/CAnomalyJobLimitTest.cc
  lib/core/unittest/CCompressedLfuCacheTest.cc
Labels: >non-issue, :ml, v8.12.0

#2586 [ML] Ensure estimated latitude is within the allowed range
  docs/CHANGELOG.asciidoc
  include/model/CIndividualModel.h
  lib/model/ModelTypes.cc
  lib/model/unittest/CMetricModelTest.cc
Labels: >bug, :ml, v8.12.0
