Repository elastic/ml-cpp, pull requests merged in 2024-11, with the labels that each got.

#2782 Update build configurations for version 8.17 and SNAPSHOT messages
  catalog-info.yaml
Labels: >build, >non-issue, v9.0.0

#2781 [ML] Bump version to 8.18.0
  gradle.properties
Labels: >build, >non-issue, :ml, v8.18.0

#2784 [ML] Fix typos in catalog-info.yaml
  catalog-info.yaml
Labels: >build, >non-issue, :ml, v9.0.0

#2780 [ML] Upgrade to Boost 1.86.0 on Windows 2022 builds
  .buildkite/pipelines/build_windows.json.py
  3rd_party/3rd_party.cmake
  build-setup/windows.md
  cmake/variables.cmake
  dev-tools/build_windows_third_party_deps.ps1
  docs/CHANGELOG.asciidoc
  lib/core/unittest/CMemoryUsageTest.cc
  lib/model/CBucketGatherer.cc
Labels: >enhancement, :ml, v9.0.0, v8.18.0

#2783 [ML] Upgrade to PyTorch 2.5.0 on Windows 2022 builds
  .buildkite/pipelines/build_windows.json.py
  build-setup/windows.md
  dev-tools/build_windows_third_party_deps.ps1
  docs/CHANGELOG.asciidoc
Labels: >enhancement, :ml, v9.0.0, v8.18.0

#2786 [ML] Fix merge error in windows pipeline
  .buildkite/pipelines/build_windows.json.py
Labels: >non-issue, :ml, v9.0.0

#2774 [ML] Build solely on macos 13 (Ventura) aarch64
  .buildkite/pipeline.json.py
  .buildkite/pipelines/build_macos.json.py
  .buildkite/scripts/steps/build_and_test.sh
  .ci/orka/README.md
  .ci/orka/install.sh
  .ci/orka/orka-macos-13-arm.pkr.hcl
  .ci/orka/third_party_deps.sh
  build-setup/macos.md
  build-setup/macos_cross_compiled.md
  cmake/compiler/clang.cmake
  dev-tools/build_macos_third_party_deps.sh
  dev-tools/docker/README.md
  dev-tools/docker/build_macosx_build_image.sh
  dev-tools/docker/macosx_builder/Dockerfile
  dev-tools/docker/macosx_image/Dockerfile
  dev-tools/docker_build.sh
  dev-tools/download_macos_deps.sh
  dev-tools/strip_binaries.sh
Labels: >build, >non-issue, :ml, v9.0.0, v8.18.0

#2787 [ML] Remove macOS x86_64 builds from _all_ pipelines
  .buildkite/branch.json.py
  .buildkite/job-build-test-all-debug.json.py
Labels: >non-issue, :ml, v9.0.0, v8.18.0

#2788 [ML] Remove dependency on macos_x86_64 build step
  .buildkite/pipelines/create_dra.yml.sh
Labels: >non-issue, :ml, v9.0.0, v8.18.0
