Repository elastic/ml-cpp, pull requests merged in 2024-06, with the labels that each got.

#2672 [ML] Add CMake config for Address Sanitizer builds
  cmake/variables.cmake
Labels: >build, >non-issue, :ml, v8.15.0

#2673 [ML] Fix stack-use-after-scope error
  docs/CHANGELOG.asciidoc
  lib/model/CHierarchicalResultsNormalizer.cc
Labels: >bug, :ml, v8.15.0

#2680 [ML] Catch any exception thrown by inference
  bin/pytorch_inference/Main.cc
  docs/CHANGELOG.asciidoc
Labels: >bug, 3rd party models, Feature:NLP, v8.15.0, v8.14.1

#2678 [Backport] [ML] Remove allocators from cache after usage
  docs/CHANGELOG.asciidoc
  include/api/CJsonOutputWriter.h
  include/core/CRapidJsonWriterBase.h
  include/core/CScopedRapidJsonPoolAllocator.h
  lib/api/CJsonOutputWriter.cc
Labels: >enhancement, backport, ci:run-qa-tests, v7.17.23

#2679 [ML] Remove allocators from cache after usage
  docs/CHANGELOG.asciidoc
  include/api/CJsonOutputWriter.h
  include/core/CBoostJsonWriterBase.h
  include/core/CScopedBoostJsonPoolAllocator.h
  lib/api/CJsonOutputWriter.cc
Labels: >enhancement, :ml, ci:run-qa-tests, v8.15.0, v8.14.1

#2681 [Backport][ML] Remove allocators from cache after usage (#2679)
  docs/CHANGELOG.asciidoc
  include/api/CJsonOutputWriter.h
  include/core/CBoostJsonWriterBase.h
  include/core/CScopedBoostJsonPoolAllocator.h
  lib/api/CJsonOutputWriter.cc
Labels: >enhancement, backport, ci:run-qa-tests, v8.14.1

#2674 [ML] Use custom Boost::JSON allocator
  bin/autodetect/Main.cc
  dev-tools/run_es_tests.sh
  docs/CHANGELOG.asciidoc
  include/api/CJsonOutputWriter.h
  include/core/CBoostJsonPoolAllocator.h
  include/core/CBoostJsonWriterBase.h
  include/core/CProgramCounters.h
  include/model/CResourceMonitor.h
  lib/api/CAnomalyJob.cc
  lib/api/CJsonOutputWriter.cc
  lib/api/CModelSizeStatsJsonWriter.cc
  lib/api/unittest/CAnomalyJobLimitTest.cc
  lib/api/unittest/CModelSnapshotJsonWriterTest.cc
  lib/model/CForecastDataSink.cc
  lib/model/CResourceMonitor.cc
Labels: >bug, :ml, ci:run-qa-tests, v8.14.0, v8.15.0

#2682 [8.14][ML] Use custom Boost::JSON allocator (#2674)
  bin/autodetect/Main.cc
  dev-tools/run_es_tests.sh
  docs/CHANGELOG.asciidoc
  include/api/CJsonOutputWriter.h
  include/core/CBoostJsonPoolAllocator.h
  include/core/CBoostJsonWriterBase.h
  include/core/CProgramCounters.h
  include/model/CResourceMonitor.h
  lib/api/CAnomalyJob.cc
  lib/api/CJsonOutputWriter.cc
  lib/api/CModelSizeStatsJsonWriter.cc
  lib/api/unittest/CAnomalyJobLimitTest.cc
  lib/api/unittest/CModelSnapshotJsonWriterTest.cc
  lib/model/CForecastDataSink.cc
  lib/model/CResourceMonitor.cc
Labels: >enhancement, :ml, backport, v8.14.2
