Repository elastic/ml-cpp, pull requests merged in 2024-12, with the labels that each got.

#2778 [ML] Upgrade to PyTorch 2.5.0 on ARM macOS
  .ci/orka/orka-macos-13-arm.pkr.hcl
  .ci/orka/third_party_deps.sh
  build-setup/macos.md
  docs/CHANGELOG.asciidoc
Labels: >enhancement, :ml, v9.0.0, v8.18.0

#2779 [ML] Upgrade to Boost 1.86.0 on ARM macOS
  .buildkite/pipelines/build_macos.json.py
  .ci/orka/orka-macos-13-arm.pkr.hcl
  .ci/orka/third_party_deps.sh
  3rd_party/3rd_party.cmake
  3rd_party/licenses/boost-INFO.csv
  build-setup/macos.md
  cmake/variables.cmake
  docs/CHANGELOG.asciidoc
  lib/core/unittest/CMemoryUsageTest.cc
Labels: >enhancement, :ml, v9.0.0, v8.18.0

#2785 [ML] Update Linux builder Docker container for 9.0
  .buildkite/pipelines/build_linux.json.py
  .buildkite/pipelines/run_es_tests_aarch64.yml.sh
  .buildkite/pipelines/run_es_tests_x86_64.yml.sh
  .buildkite/pipelines/sonarqube.yml.sh
  3rd_party/3rd_party.cmake
  3rd_party/licenses/gcc-runtime-INFO.csv
  3rd_party/licenses/libxml2-INFO.csv
  build-setup/linux.md
  build-setup/linux_aarch64_cross_compiled.md
  cmake/architecture/aarch64.cmake
  cmake/compiler/gcc.cmake
  cmake/variables.cmake
  dev-tools/docker/README.md
  dev-tools/docker/build_linux_aarch64_cross_build_image.sh
  dev-tools/docker/build_linux_aarch64_native_build_image.sh
  dev-tools/docker/build_linux_build_image.sh
  dev-tools/docker/build_linux_dependency_builder_image.sh
  dev-tools/docker/linux_aarch64_cross_builder/Dockerfile
  dev-tools/docker/linux_aarch64_cross_image/Dockerfile
  dev-tools/docker/linux_aarch64_native_builder/Dockerfile
  dev-tools/docker/linux_aarch64_native_image/Dockerfile
  dev-tools/docker/linux_aarch64_native_tester/Dockerfile
  dev-tools/docker/linux_builder/Dockerfile
  dev-tools/docker/linux_dependency_builder_image/Dockerfile
  dev-tools/docker/linux_image/Dockerfile
  dev-tools/docker/linux_tester/Dockerfile
  dev-tools/docker/pytorch_linux_image/Dockerfile
  dev-tools/docker/ubuntu_devbox/Dockerfile
  dev-tools/docker/ubuntu_devbox/Dockerfile.8.16
  docs/CHANGELOG.asciidoc
  include/core/CContainerPrinter.h
  include/core/CStateMachine.h
  include/maths/time_series/CSeasonalTime.h
  set_env.sh
Labels: >enhancement, >build, v9.0.0

#2790 [8.18][ML] Upgrade to PyTorch 2.5.0 on Windows 2016 builds (#2783)
  3rd_party/licenses/pytorch-INFO.csv
  build-setup/windows.md
  dev-tools/download_windows_deps.ps1
  docs/CHANGELOG.asciidoc
Labels: >enhancement, :ml, backport, v8.18.0

#2791 [8.18][ML] Windows 2016 boost 1.86 (#2780)
  3rd_party/3rd_party.cmake
  3rd_party/licenses/boost-INFO.csv
  build-setup/windows.md
  cmake/variables.cmake
  docs/CHANGELOG.asciidoc
  lib/core/unittest/CMemoryUsageTest.cc
  lib/model/CBucketGatherer.cc
Labels: >enhancement, :ml, backport, v8.18.0

#2794 [8.18][ML] Upgrade to PyTorch 2.5 and Boost 1.86 for macOS ARM builds
  3rd_party/3rd_party.cmake
  build-setup/macos.md
  cmake/variables.cmake
  dev-tools/download_macos_deps.sh
  docs/CHANGELOG.asciidoc
  lib/core/unittest/CMemoryUsageTest.cc
Labels: >enhancement, :ml, backport, v8.18.0

#2795 [8.18][ML] Drop support for macOS Intel builds
  .buildkite/branch.json.py
  .buildkite/job-build-test-all-debug.json.py
  .buildkite/pipeline.json.py
  .buildkite/pipelines/build_macos.json.py
  .buildkite/pipelines/create_dra.yml.sh
  .buildkite/scripts/steps/build_and_test.sh
  .ci/orka/README.md
  build-setup/macos.md
  build-setup/macos_cross_compiled.md
  cmake/compiler/clang.cmake
  dev-tools/docker/README.md
  dev-tools/docker/build_macosx_build_image.sh
  dev-tools/docker/macosx_builder/Dockerfile
  dev-tools/docker/macosx_image/Dockerfile
  dev-tools/docker_build.sh
  dev-tools/strip_binaries.sh
  docs/CHANGELOG.asciidoc
Labels: >enhancement, :ml, backport, v8.18.0

#2799 [ML] Windows 2022: Upgrade PyTorch to version 2.5.1
  .buildkite/pipelines/build_windows.json.py
  build-setup/windows.md
  dev-tools/build_windows_third_party_deps.ps1
  docs/CHANGELOG.asciidoc
Labels: >enhancement, :ml, v9.0.0, v8.18.0

#2801 [8.18][ML] Windows 2022: Upgrade PyTorch to version 2.5.1 (#2799)
  build-setup/windows.md
  dev-tools/download_windows_deps.ps1
  docs/CHANGELOG.asciidoc
Labels: >enhancement, :ml, backport, v8.18.0

#2789 [8.x][ML] Update Boost and PyTorch versions for Linux
  .buildkite/pipelines/build_linux.json.py
  3rd_party/3rd_party.cmake
  build-setup/linux.md
  cmake/variables.cmake
  dev-tools/docker/README.md
  dev-tools/docker/build_linux_aarch64_cross_build_image.sh
  dev-tools/docker/linux_aarch64_cross_builder/Dockerfile
  dev-tools/docker/linux_aarch64_cross_image/Dockerfile
  dev-tools/docker/linux_aarch64_native_builder/Dockerfile
  dev-tools/docker/linux_aarch64_native_image/Dockerfile
  dev-tools/docker/linux_aarch64_native_tester/Dockerfile
  dev-tools/docker/linux_builder/Dockerfile
  dev-tools/docker/linux_dependency_builder_image/Dockerfile
  dev-tools/docker/linux_image/Dockerfile
  dev-tools/docker/linux_tester/Dockerfile
Labels: >build, >non-issue, v8.18.0

#2797 [ML] Update model snapshot version and remove deprecated tags
  lib/api/CAnomalyJob.cc
  lib/api/unittest/CMakeLists.txt
  lib/api/unittest/CRestorePreviousStateTest.cc
  lib/api/unittest/testfiles/state/6.5.0/by_detector_state.json
  lib/api/unittest/testfiles/state/6.5.0/categorizer_state.json
  lib/api/unittest/testfiles/state/6.5.0/count_detector_state.json
  lib/api/unittest/testfiles/state/6.5.0/dc_detector_state.json
  lib/api/unittest/testfiles/state/6.5.0/normalizer_state.json
  lib/api/unittest/testfiles/state/6.5.0/over_detector_state.json
  lib/api/unittest/testfiles/state/6.5.0/partition_detector_state.json
  lib/api/unittest/testfiles/state/7.1.0/by_detector_state.json
  lib/api/unittest/testfiles/state/7.1.0/categorizer_state.json
  lib/api/unittest/testfiles/state/7.1.0/count_detector_state.json
  lib/api/unittest/testfiles/state/7.1.0/dc_detector_state.json
  lib/api/unittest/testfiles/state/7.1.0/normalizer_state.json
  lib/api/unittest/testfiles/state/7.1.0/over_detector_state.json
  lib/api/unittest/testfiles/state/7.1.0/partition_detector_state.json
  lib/api/unittest/testfiles/state/7.3.0/by_detector_state.json
  lib/api/unittest/testfiles/state/7.3.0/categorizer_state.json
  lib/api/unittest/testfiles/state/7.3.0/count_detector_state.json
  lib/api/unittest/testfiles/state/7.3.0/dc_detector_state.json
  lib/api/unittest/testfiles/state/7.3.0/normalizer_state.json
  lib/api/unittest/testfiles/state/7.3.0/over_detector_state.json
  lib/api/unittest/testfiles/state/7.3.0/partition_detector_state.json
  lib/api/unittest/testfiles/state/7.9.0/by_detector_state.json
  lib/api/unittest/testfiles/state/7.9.0/categorizer_state.json
  lib/api/unittest/testfiles/state/7.9.0/count_detector_state.json
  lib/api/unittest/testfiles/state/7.9.0/dc_detector_state.json
  lib/api/unittest/testfiles/state/7.9.0/normalizer_state.json
  lib/api/unittest/testfiles/state/7.9.0/over_detector_state.json
  lib/api/unittest/testfiles/state/7.9.0/partition_detector_state.json
  lib/core/CPackedBitVector.cc
  lib/core/unittest/CPackedBitVectorTest.cc
  lib/maths/common/unittest/testfiles/poorly_conditioned_multimodal.txt
  lib/maths/time_series/CCalendarCyclicTest.cc
  lib/maths/time_series/CTimeSeriesDecomposition.cc
  lib/maths/time_series/CTimeSeriesDecompositionDetail.cc
  lib/maths/time_series/CTimeSeriesModel.cc
  lib/maths/time_series/CTrendComponent.cc
  lib/maths/time_series/unittest/CTrendComponentTest.cc
  lib/maths/time_series/unittest/testfiles/CTrendComponent.7.0.expected_values.txt
  lib/maths/time_series/unittest/testfiles/CTrendComponent.7.0.xml
Labels: :ml, >refactoring, v9.0.0

#2798 [ML] macOS ARM: Upgrade PyTorch to version 2.5.1
  .buildkite/pipelines/build_macos.json.py
  .ci/orka/README.md
  .ci/orka/orka-macos-13-arm.pkr.hcl
  .ci/orka/third_party_deps.sh
  3rd_party/licenses/pytorch-INFO.csv
  build-setup/macos.md
  docs/CHANGELOG.asciidoc
Labels: >enhancement, :ml, v9.0.0, v8.18.0

#2802 [8.18][ML] macOS ARM: Upgrade PyTorch to version 2.5.1 (#2798)
  3rd_party/licenses/pytorch-INFO.csv
  build-setup/macos.md
  dev-tools/download_macos_deps.sh
  docs/CHANGELOG.asciidoc
Labels: >enhancement, :ml, backport, v8.18.0

#2803 [ML] Rebuild Docker image for nightly pytorch latest builds
  dev-tools/docker/README.md
  dev-tools/docker/build_linux_dependency_builder_image.sh
  dev-tools/docker/pytorch_linux_image/Dockerfile
Labels: >non-issue, :ml, v9.0.0

#2777 [ML] Update C++ standard to 20 and refine clang-tidy checks
  .buildkite/pipelines/sonarqube.yml.sh
  .clang-tidy
  cmake/variables.cmake
  include/api/CAnomalyJob.h
  lib/api/CAnomalyJob.cc
  lib/maths/common/unittest/CKMeansOnlineTest.cc
  lib/maths/time_series/unittest/CTimeSeriesDecompositionTest.cc
Labels: >non-issue, :ml, v9.1.0
