Repository elastic/ml-cpp, pull requests merged in 2024-08, with the labels that each got.

#2701 [ML] Fixing force time shift logic
  include/api/CDetectionRulesJsonParser.h
  include/model/CDetectionRule.h
  lib/model/CCountingModel.cc
  lib/model/CDetectionRule.cc
  lib/model/CEventRatePopulationModel.cc
  lib/model/CIndividualModel.cc
  lib/model/CMetricPopulationModel.cc
Labels: >non-issue, :ml, v8.16.0

#2705 [8.15][ML] Upgrade to PyTorch 2.3.1 (#2688)
  .buildkite/pipelines/build_linux.json.py
  .buildkite/pipelines/build_macos.json.py
  .buildkite/scripts/steps/build_and_test.sh
  .ci/orka/README.md
  .ci/orka/orka-macos-12-x86_64.pkr.hcl
  3rd_party/licenses/pytorch-INFO.csv
  build-setup/linux.md
  build-setup/macos.md
  build-setup/windows.md
  dev-tools/docker/build_linux_aarch64_cross_build_image.sh
  dev-tools/docker/build_linux_aarch64_native_build_image.sh
  dev-tools/docker/build_linux_build_image.sh
  dev-tools/docker/build_macosx_build_image.sh
  dev-tools/docker/linux_aarch64_cross_builder/Dockerfile
  dev-tools/docker/linux_aarch64_cross_image/Dockerfile
  dev-tools/docker/linux_aarch64_native_builder/Dockerfile
  dev-tools/docker/linux_aarch64_native_image/Dockerfile
  dev-tools/docker/linux_aarch64_native_tester/Dockerfile
  dev-tools/docker/linux_builder/Dockerfile
  dev-tools/docker/linux_image/Dockerfile
  dev-tools/docker/linux_tester/Dockerfile
  dev-tools/docker/macosx_builder/Dockerfile
  dev-tools/docker/macosx_image/Dockerfile
  dev-tools/download_macos_deps.sh
  dev-tools/download_windows_deps.ps1
  docs/CHANGELOG.asciidoc
Labels: >build, :ml, backport, ci:run-qa-tests, v8.15.1

#2706 [ML] Update release notes following backport of #2688 (#2705)
  docs/CHANGELOG.asciidoc
Labels: :ml, >docs, v8.16.0

#2707 [ML] Correct the reference to a Buildkite step name
  .buildkite/pipelines/create_dra.yml.sh
Labels: >build, >non-issue, :ml, v8.15.1

#2703 [ML] Migrate to S3 bucket in elastic-dev AWS account for 3rd party dependencies
  dev-tools/docker/linux_aarch64_cross_image/Dockerfile
  dev-tools/docker/macosx_image/Dockerfile
  dev-tools/download_macos_deps.sh
Labels: >build, >non-issue, :ml, v7.17.23, v8.14.2, v8.16.0, v8.15.1

#2708 [8.15][ML] Migrate to S3 bucket in elastic-dev AWS account for 3rd party dependencies (#2703)
  dev-tools/docker/linux_aarch64_cross_image/Dockerfile
  dev-tools/docker/macosx_image/Dockerfile
  dev-tools/download_macos_deps.sh
Labels: >non-issue, :ml, backport, v8.15.1

#2710 [8.14][ML] Migrate to S3 bucket in elastic-dev AWS account for 3rd party dependencies (#2703)
  dev-tools/docker/linux_aarch64_cross_image/Dockerfile
  dev-tools/docker/macosx_image/Dockerfile
  dev-tools/download_macos_deps.sh
Labels: >non-issue, :ml, backport, v8.14.4

#2711 [ML] Tidy the PyTorch tests Buildkite pipeline
  .buildkite/pipelines/run_pytorch_tests.yml.sh
Labels: >build, >non-issue, :ml, v8.16.0

#2709 [7.17][ML] Migrate to S3 bucket in elastic-dev AWS account for 3rd party dependencies (#2703)
  dev-tools/docker/linux_aarch64_cross_image/Dockerfile
  dev-tools/docker/macosx_image/Dockerfile
  dev-tools/download_macos_deps.sh
Labels: >non-issue, :ml, backport, v7.17.24
