Repository elastic/ml-cpp, pull requests merged in 2024-10, with the labels that each got.

#2760 Revert "[ML] Change time shift sign for intuitive configuration (#2737)"
  lib/model/CDetectionRule.cc
  lib/model/unittest/CDetectionRuleTest.cc
Labels: >non-issue, :ml, v8.16.0, v9.0.0

#2761 Revert-2743
  lib/model/CDetectionRule.cc
  lib/model/unittest/CDetectionRuleTest.cc
Labels: >non-issue, :ml, v8.16.0

#2759 [ML] Fix forecasting parameters initialization for large models
  docs/CHANGELOG.asciidoc
  lib/model/CForecastModelPersist.cc
  lib/model/unittest/CForecastModelPersistTest.cc
Labels: >bug, :ml, v8.16.0, v9.0.0, v8.15.4

#2762 [ML] Fix forecasting parameters initialization for large models (#2759)
  docs/CHANGELOG.asciidoc
  lib/model/CForecastModelPersist.cc
  lib/model/unittest/CForecastModelPersistTest.cc
Labels: >bug, :ml, backport, v8.16.0

#2765 [ML] Fix source of multiple unit test failures on macos
  include/maths/time_series/CTimeSeriesMultibucketFeatures.h
Labels: >build, >non-issue, >test, v9.0.0

#2766 Feature freeze 8.16
  catalog-info.yaml
  gradle.properties
Labels: >non-issue

#2767 [ML] Add daily snapshot for 8.15 to catalog-info.yaml
  catalog-info.yaml
Labels: >build, >non-issue, :ml

#2768 [ML] Permit 8.15 builds to be triggered by GH activity
  catalog-info.yaml
Labels: >build, >non-issue, :ml, v9.0.0

#2764 [ML] Add Dockerfile for Ubuntu devbox
  dev-tools/docker/ubuntu_devbox/Dockerfile
  dev-tools/docker/ubuntu_devbox/Dockerfile.8.11
Labels: review, >non-issue, v9.0.0

#2689 [ML] Add SonarQube Scanning for Pull Requests
  .buildkite/pipeline.json.py
  .buildkite/pipelines/sonarqube.yml.sh
  .buildkite/scripts/steps/run_sonar-scanner.sh
  sonar-project.properties
Labels: >build, >non-issue, :ml, v9.0.0
