Repository elastic/ml-cpp, pull requests merged in 2025-01, with the labels that each got.

#2805 [ML] Fix for CKMeansOnlineTest compilation errors
  lib/maths/common/unittest/CKMeansOnlineTest.cc
Labels: >non-issue, :ml, v9.0.0

#2809 [ML] Increase the upper limits for the Boost.JSON SAX parser
  docs/CHANGELOG.asciidoc
  include/core/BoostJsonConstants.h
Labels: >bug, :ml, v9.0.0, v8.18.0, v8.16.4, v8.17.2

#2812 [8.17][ML] Increase the upper limits for the Boost.JSON SAX parser (#2809)
  docs/CHANGELOG.asciidoc
  include/core/BoostJsonConstants.h
Labels: >bug, :ml, backport, v8.17.2

#2811 [8.16][ML] Increase the upper limits for the Boost.JSON SAX parser (#2809)
  docs/CHANGELOG.asciidoc
  include/core/BoostJsonConstants.h
Labels: >bug, :ml, backport, v8.16.4

#2810 [ML] Include value of VERSION_QUALIFIER in DRA artifact names
  .buildkite/scripts/steps/create_dra.sh
  lib/ver/CMakeLists.txt
Labels: >build, >non-issue, :ml, v9.0.0

#2814 [ML] Fix for VERSION_QUALIFIER use in product version
  lib/ver/CMakeLists.txt
Labels: >non-issue, :ml, v9.0.0

#2815 [ML] Fix compilation issue in debug build
  lib/maths/time_series/unittest/CTimeSeriesMultibucketFeaturesTest.cc
Labels: >non-issue, :ml, v9.0.0

#2816 [ML] Bump version to 8.19.0
  gradle.properties
Labels: >build, >non-issue, :ml, v8.19.0

#2817 Update build configurations for version 8.18
  catalog-info.yaml
Labels: >build, >non-issue, v9.0.0
